objects/Account.object
<CustomObject>
    <fields>
        <fullName>Sharing_Group__c</fullName>
        <description>Each Master Account has a Public Group consisting of the Exec and Mgr Roles. Sub-Agent Opportunities and Leads will be shared to this Group.</description>
        <label>Sharing Group</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer Accounts</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/CameleonCPQ__QxQuote__c.object
<CustomObject>
    <description>PROS Smart CPQx Quote</description>
    <fields>
        <fullName>CameleonCPQ__Status__c</fullName>
        <description>Quote Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Review Internally</fullName>
                </value>
                <value>
                    <fullName>Approved Internally</fullName>
                </value>
                <value>
                    <fullName>Presented to Customer</fullName>
                </value>
                <value>
                    <fullName>Accepted by Customer</fullName>
                </value>
                <value>
                    <fullName>In Review Internally (Post-Customer)</fullName>
                </value>
                <value>
                    <fullName>Fully Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected Internally</fullName>
                </value>
                <value>
                    <fullName>Rejected by Customer</fullName>
                </value>
                <value>
                    <fullName>Awaiting Account ID</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OpportunityId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Orion Quotes</relationshipLabel>
        <relationshipName>PROS_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PROS Quote</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PROS Quotes</pluralLabel>
    <recordTypes>
        <fullName>New_Written_Agreement</fullName>
        <active>false</active>
        <label>New Written Agreement</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CameleonCPQ__QxQuoteLine__c.object
<CustomObject>
    <description>PROS Smart CPQx Quote Line</description>
    <fields>
        <fullName>CameleonCPQ__QuoteId__c</fullName>
        <label>Quote</label>
        <referenceTo>CameleonCPQ__QxQuote__c</referenceTo>
        <relationshipLabel>PROS Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Violation_Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Violation_Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>PROS Quote Line</label>
    <nameField>
        <label>Item Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PROS Quote Lines</pluralLabel>
    <recordTypes>
        <fullName>CPT</fullName>
        <active>true</active>
        <label>CPT</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CameleonCPQ__QxSetup__c.object
<CustomObject>
    <description>PROS Smart CPQx Settings per PROS Quote record type</description>
    <fields>
        <fullName>CameleonCPQ__LinesManagementPolicy__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>0 = [No Synchronization],  1 = [Create/Update/Delete]</inlineHelpText>
        <label>Lines Management Policy</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CameleonCPQ__MappingSetName__c</fullName>
        <label>Mapping Set Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CameleonCPQ__QuoteModelName__c</fullName>
        <label>Quote Model Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>PROS Setup</label>
    <nameField>
        <label>PROS Quote Record Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PROS Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Primary_Competitor1_DonotInUse__c</fullName>
        <label>Do Not Use Primary Competitor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>All Supplies</fullName>
                </value>
                <value>
                    <fullName>Asset Management</fullName>
                </value>
                <value>
                    <fullName>CBFS</fullName>
                </value>
                <value>
                    <fullName>CBS/Facilities</fullName>
                </value>
                <value>
                    <fullName>Contract Furniture</fullName>
                </value>
                <value>
                    <fullName>Email Marketing</fullName>
                </value>
                <value>
                    <fullName>Ergonomics</fullName>
                </value>
                <value>
                    <fullName>Facilities- Coffee</fullName>
                </value>
                <value>
                    <fullName>Filing &amp; Binding</fullName>
                </value>
                <value>
                    <fullName>Furniture - Catalog</fullName>
                </value>
                <value>
                    <fullName>Furniture - Interiors</fullName>
                </value>
                <value>
                    <fullName>General Consultation</fullName>
                </value>
                <value>
                    <fullName>Ink &amp; Toner</fullName>
                </value>
                <value>
                    <fullName>Instructional Solutions</fullName>
                </value>
                <value>
                    <fullName>K-12 Growth</fullName>
                </value>
                <value>
                    <fullName>Labels &amp; Forms</fullName>
                </value>
                <value>
                    <fullName>Legal Services</fullName>
                </value>
                <value>
                    <fullName>Logo Design</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>MPS</fullName>
                </value>
                <value>
                    <fullName>Multi-Category</fullName>
                </value>
                <value>
                    <fullName>Office Essentials</fullName>
                </value>
                <value>
                    <fullName>Office Products</fullName>
                </value>
                <value>
                    <fullName>Office Supplies</fullName>
                </value>
                <value>
                    <fullName>Paper</fullName>
                </value>
                <value>
                    <fullName>Print and Promo</fullName>
                </value>
                <value>
                    <fullName>Print Services</fullName>
                </value>
                <value>
                    <fullName>School Supplies</fullName>
                </value>
                <value>
                    <fullName>Search Marketing</fullName>
                </value>
                <value>
                    <fullName>SEO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PROS_Access_Custom_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of restricted profiles</description>
    <fields>
        <fullName>Profiles__c</fullName>
        <label>Profiles</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>PROS Access Custom Setting</label>
</CustomObject>

classes/QuoteAppRequestEmail_TC.cls
@isTest
public class QuoteAppRequestEmail_TC {
    @isTest
    public static void testmethod1(){
        Account masterAccount = new Account(Name='master account'); 
        masterAccount.Sharing_Group__c = 'Master Account Share'; 
        insert masterAccount; 
        
        Recordtype custAccRT = [Select id, Sobjecttype from recordtype where name = 'Customer' and Sobjecttype = 'Account']; 
        Account account1 = new Account(Name='Test Account');
        account1.RecordTypeId = custAccRT.Id; 
        account1.ParentId = masterAccount.Id; 
        insert account1; 
        
        Contact con = new Contact(LastName='userName', AccountId = account1.Id);
        insert con; 
        
        Contact con2 = new Contact(LastName='userName2', AccountId = account1.Id);
        insert con2; 
        

        Opportunity opp1 = new Opportunity(); 
        opp1.Name = 'Test';   
        opp1.Product__c = 'Furniture - Catalog';
        opp1.StageName = 'Prospecting'; 
        opp1.CloseDate = Date.today().addDays(1);
        opp1.AccountId = account1.Id;
        opp1.Amount=10000000;
        opp1.Primary_Competitor1_DonotInUse__c = 'comp1';
        //system.debug('opp '+ opp1);
        insert opp1;
        
        CameleonCPQ__QxSetup__c  c = new CameleonCPQ__QxSetup__c(Name='Master',CameleonCPQ__QuoteModelName__c='OfficeDepot',CameleonCPQ__MappingSetName__c='New_Written_Agreement',CameleonCPQ__LinesManagementPolicy__c=1);
        insert c;

        PROS_Access_Custom_Setting__c pacs1 = new PROS_Access_Custom_Setting__c(Name='In Review_VIEW', Profiles__c='Field Sales');
        PROS_Access_Custom_Setting__c pacs2 = new PROS_Access_Custom_Setting__c(Name='Draft_VIEW', Profiles__c='Field Sales');
        insert new List<PROS_Access_Custom_Setting__c> { pacs1, pacs2 };

         Id cptRTId = Schema.SObjectType.CameleonCPQ__QxQuoteLine__c.getRecordTypeInfosByName().get('CPT').getRecordTypeId();
        
         CameleonCPQ__QxQuote__c testQuote1 = new CameleonCPQ__QxQuote__c(Name='TEST 1',CameleonCPQ__Status__c='Accepted',OpportunityId__c=opp1.id);
        insert testQuote1; 
        List<CameleonCPQ__QxQuoteLine__c> qlineList=new List<CameleonCPQ__QxQuoteLine__c>();
        CameleonCPQ__QxQuoteLine__c qline1=new CameleonCPQ__QxQuoteLine__c();
        qline1.Violation_Type__c='Compliance';
        qline1.Violation_Message__c='test';
        qline1.recordtypeId = cptRTId;
        qline1.CameleonCPQ__QuoteId__c=testQuote1.id;
        qlineList.add(qline1);
        CameleonCPQ__QxQuoteLine__c qline2=new CameleonCPQ__QxQuoteLine__c();
        qline2.Violation_Type__c='Maintenance';
        qline2.Violation_Message__c='test';
        qline2.recordtypeId = cptRTId;
        qline2.CameleonCPQ__QuoteId__c=testQuote1.id;
        qlineList.add(qline2);
        CameleonCPQ__QxQuoteLine__c qline3=new CameleonCPQ__QxQuoteLine__c();
        qline3.Violation_Type__c='Business';
        qline3.Violation_Message__c='test';
        qline3.CameleonCPQ__QuoteId__c=testQuote1.id;
        qline3.recordtypeId = cptRTId;
        qlineList.add(qline3);
            insert qlineList;
        QuoteAppRequestEmail.quoteapp(testQuote1.Id);
    }
}