objects/Account.object
<CustomObject>
    <fields>
        <fullName>AOPS_Cust_Id__c</fullName>
        <description>AOPS Customer Account Number</description>
        <externalId>true</externalId>
        <label>AOPS Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>AOPS_Seq_ID__c</fullName>
        <externalId>true</externalId>
        <label>AOPS Seq ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Related_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>(Tech-Zone)</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <description>OMX Primary Key</description>
        <externalId>true</externalId>
        <inlineHelpText>OMX Primary Key</inlineHelpText>
        <label>OMX Primary Key</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>InActive</fullName>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Legacy_Delta__c.object
<CustomObject>
    <description>This Object  is designed to Process the Legacy data to OD SFDC Instance entities like Notes, Events,Task.</description>
    <fields>
        <fullName>CreatedByName__c</fullName>
        <description>This hold the CreatedBy Name of the Legacy record</description>
        <label>CreatedByName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>E_Description__c</fullName>
        <description>This hold the Description of the Event Record</description>
        <label>T_Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LastModifiedByName__c</fullName>
        <description>This hold the LastModifiedBy Name of the Legacy record</description>
        <label>LastModifiedByName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastModifiedDate__c</fullName>
        <description>This hold the LastModifiedDate of the Legacy record</description>
        <label>LastModifiedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>N_Body__c</fullName>
        <description>This hold the Body of the Notes</description>
        <label>N_Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>N_ISPRIVATE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This hold the ISPRIVATE for Notes and Events</description>
        <label>N_ISPRIVATE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>N_Legacy_Created_Date__c</fullName>
        <description>This is Notes Legacy Created Date</description>
        <label>N_Legacy_Created_Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>N_ParentId_Type__c</fullName>
        <description>This hold the Type(Sobject) to which Notes Has to be Linked to</description>
        <label>N_ParentId_Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>N_ParentId__c</fullName>
        <description>This hold the Raw Parent ID for Notes</description>
        <label>N_ParentId</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>N_Title__c</fullName>
        <description>This hold the Title for Notes</description>
        <label>N_Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OMX_primary_key__c</fullName>
        <description>This holds the Legacy ID of the record</description>
        <label>OMX_primary_key</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnerRepNumber__c</fullName>
        <description>This hold the Owner&apos;s Rep Number of the Legacy record</description>
        <label>OwnerRepNumber</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFDC_ID__c</fullName>
        <description>This is the Created SFDC ID</description>
        <label>SFDC_ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Determines the status of the record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>T_ActivityDate__c</fullName>
        <description>This hold the ActivityDate of the Task and Event Record</description>
        <label>T_ActivityDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>T_CallDisposition__c</fullName>
        <description>This hold the CallDisposition of the Task Record</description>
        <label>T_CallDisposition</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>T_CallDurationInSeconds__c</fullName>
        <description>This hold the CallDurationInSeconds of the Task Record</description>
        <label>T_CallDurationInSeconds</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>T_CallObject__c</fullName>
        <description>This hold the CallObject of the Task Record</description>
        <label>T_CallObject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>T_CallType__c</fullName>
        <description>This hold the CallType of the Task Record</description>
        <label>T_CallType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>T_ISRECURRENCE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This hold the ISRECURRENCE of the Task Record</description>
        <label>T_ISRECURRENCE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>T_IsReminderSet__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This hold the IsReminderSet of the Task and Event Record</description>
        <label>T_IsReminderSet</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>T_Priority__c</fullName>
        <description>This hold the Priority of the Task Record</description>
        <label>T_Priority</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>T_RecurrenceDayOfMonth__c</fullName>
        <description>This hold the RecurrenceDayOfMonth of the Task Record</description>
        <label>T_RecurrenceDayOfMonth</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>T_RecurrenceDayOfWeekMask__c</fullName>
        <description>This hold the RecurrenceDayOfWeekMask of the Task and Event Record</description>
        <label>T_RecurrenceDayOfWeekMask</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>T_RecurrenceEndDateOnly__c</fullName>
        <description>This hold the RecurrenceEndDateOnly of the Task and Event Record</description>
        <label>T_RecurrenceEndDateOnly</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>T_RecurrenceInstance__c</fullName>
        <description>This hold the RecurrenceInstance of the Task and Event Record</description>
        <label>T_RecurrenceInstance</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>T_RecurrenceInterval__c</fullName>
        <description>This hold the RecurrenceInterval of the Task and Event Record</description>
        <label>T_RecurrenceInterval</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>T_RecurrenceMonthOfYear__c</fullName>
        <description>This hold the RecurrenceMonthOfYear of the Task and Event Record</description>
        <label>T_RecurrenceMonthOfYear</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>T_RecurrenceStartDateOnly__c</fullName>
        <description>This hold the RecurrenceStartDateOnly of the Task Record</description>
        <label>T_RecurrenceStartDateOnly</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>T_RecurrenceTimeZoneSidKey__c</fullName>
        <description>This hold the RecurrenceTimeZoneSidKey of the Task and Event Record</description>
        <label>T_RecurrenceTimeZoneSidKey</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>T_RecurrenceType__c</fullName>
        <description>This hold the RecurrenceType of the Task and Event Record</description>
        <label>T_RecurrenceType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>T_ReminderDateTime__c</fullName>
        <description>This hold the ReminderDateTime of the Task and Events Record</description>
        <label>T_ReminderDateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>T_Status__c</fullName>
        <description>This hold the Status of the Task Record</description>
        <label>T_Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>T_Subject__c</fullName>
        <description>This hold the Subject of the Task and Event Record</description>
        <label>T_Subject</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>T_WhatId_Type__c</fullName>
        <description>The field is created to capture the type of Object the Task/Event belongs to</description>
        <inlineHelpText>Determines whether the Task belongs to Accounts or Opportunities</inlineHelpText>
        <label>T WhatId Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>T_WhatId__c</fullName>
        <description>This hold the WhatId of the Task Record</description>
        <label>T_WhatId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>T_WhoId_Type__c</fullName>
        <description>The field is created to capture the type of Object the Task/Event belongs to</description>
        <inlineHelpText>Determines whether the Task belongs to Leads or Contacts</inlineHelpText>
        <label>T WhoId Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>T_WhoId__c</fullName>
        <description>This hold the WhoId of the Task Record</description>
        <label>T_WhoId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>createdDate__c</fullName>
        <description>This hold the createdDate of the Legacy record</description>
        <label>createdDate</label>
        <type>DateTime</type>
    </fields>
    <label>Legacy_Delta</label>
    <nameField>
        <label>OMX_Delta Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legacy_Delta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ProcessLegacyData_Batch_TC.cls
@Istest
private class ProcessLegacyData_Batch_TC
{
static testMethod void ProcessLegacyData_Batch_TC()
{


Account acc = new Account();
acc.AOPS_Cust_Id__c ='6583';
acc.OMX_primary_key__c='271991';
acc.Name='Test';
insert acc;

contact c1 = new Contact();
c1.LastName='LastNametest';
c1.email='testemail@test.com';
c1.AccountId = acc.id;
insert c1;
Account acc1 = new Account();
acc1.AOPS_Seq_ID__c = '6583-0087';
acc1.Related_Account__c = acc.id;
acc1.Name='Test';
insert acc1;


Legacy_Delta__c LD= new Legacy_Delta__c();
LD.N_Body__c='ASDFGH';
LD.N_Legacy_Created_Date__c='';
LD.N_ISPRIVATE__c=False;
LD.N_ParentId__c='271991';
LD.N_ParentId_Type__c='Account';
LD.N_Title__c='';
LD.T_CallType__c='';
LD.T_RecurrenceDayOfMonth__c=5;
LD.T_Subject__c='aseryttr';
LD.T_CallDurationInSeconds__c=15;
LD.T_RecurrenceTimeZoneSidKey__c='';
LD.T_CallObject__c ='';
LD.LastModifiedByName__c='Niraj';
LD.status__c='open';  
LD.SFDC_ID__c='';
LD.T_WhoId__c=acc.id; 
LD.T_WhoId_Type__c='Account';
LD.T_WhatId__c=acc.id;
LD.T_WhatId_Type__c='Account';
LD.OMX_primary_key__c='271991';
LD.OwnerRepNumber__c='6351';


insert LD;

Legacy_Delta__c LD1= new Legacy_Delta__c();
LD1.N_Body__c='ASDFGH';
LD1.N_Legacy_Created_Date__c='';
LD1.N_ISPRIVATE__c=False;
LD1.N_ParentId__c='271991';
LD1.N_ParentId_Type__c='Account';
LD1.N_Title__c='';
LD1.T_CallType__c='';
LD1.T_RecurrenceDayOfMonth__c=5;
LD1.T_Subject__c='aseryttr';
LD1.T_CallDurationInSeconds__c=15;
LD1.T_RecurrenceTimeZoneSidKey__c='';
LD1.T_CallObject__c ='';
LD1.LastModifiedByName__c='Niraj';
LD1.status__c='open';  
LD1.SFDC_ID__c='';
LD1.T_WhoId__c=acc.id; 
LD1.T_WhoId_Type__c='Account';
LD1.T_WhatId__c='';
LD1.T_WhatId_Type__c='';
//LD.OMX_primary_key__c='271991';
LD1.OwnerRepNumber__c='6351';


insert LD1;
test.starttest();
ProcessLegacyData_Batch cab = new ProcessLegacyData_Batch();
String qry='Select id,N_Body__c,OMX_primary_key__c,N_Legacy_Created_Date__c,N_ISPRIVATE__c,N_ParentId__c,N_ParentId_Type__c,N_Title__c,T_CallType__c ,T_ReminderDateTime__c ,T_RecurrenceDayOfMonth__c ,T_Subject__c ,T_CallDurationInSeconds__c ,T_RecurrenceTimeZoneSidKey__c ,T_CallObject__c ,LastModifiedByName__c ,LastModifiedDate__c ,T_CallDisposition__c ,T_IsRecurrence__c ,T_RecurrenceDayOfWeekMask__c ,T_IsReminderSet__c ,createdDate__c ,T_Status__c ,T_RecurrenceInterval__c ,T_RecurrenceInstance__c ,T_ActivityDate__c ,T_RecurrenceType__c ,T_RecurrenceEndDateOnly__c ,T_RecurrenceMonthOfYear__c ,T_RecurrenceStartDateOnly__c ,CreatedByName__c ,T_Priority__c ,E_Description__c , T_WhoId_Type__c,T_WhoId__c,T_WhatId__c,T_WhatId_Type__c,OwnerRepNumber__c,SFDC_ID__c  from Legacy_Delta__c where status__c =\'Open\' and SFDC_ID__c=null';

ProcessLegacyData_Batch cab1 = new ProcessLegacyData_Batch(qry);
database.executebatch(cab1);

String CRON_EXP = '0 0 0 3 9 ? 2022';    
System.schedule('Assignment Batch',CRON_EXP , cab1 );

test.stoptest();
}
}