objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Extension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Extension</label>
        <referenceTo>Account_Extension__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Account_Dormant__c.object
<CustomObject>
    <fields>
        <fullName>AccountExtension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Extension</label>
        <referenceTo>Account_Extension__c</referenceTo>
        <relationshipName>Account_Dormant</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Original_Account_ID__c</fullName>
        <externalId>true</externalId>
        <label>Original Account ID</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Dormant Account Duplicate</label>
    <nameField>
        <label>Account Dormant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dormant Account Duplicates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account_Extension__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Original_Account_ID__c</fullName>
        <externalId>true</externalId>
        <label>Original Account ID</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Account Extension</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Extensions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>OD_Employee_ID__c</fullName>
        <externalId>true</externalId>
        <label>OD Employee ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/beforeomxtrigTest.cls
@isTest
private class beforeomxtrigTest {
    static User testUser;
	private static testMethod void restoreAPItest() {
          User stdTestUser = new User();
     stdTestUser.firstName = 'stdTestUser';
     stdTestUser.LastName = 'test';
     stdTestUser.Alias = '12';
     stdTestUser.Email = 'stdTestUser@officedepot.com';
     stdTestUser.UserName= 'zzdataloadernorth@officedepot.com';
     stdTestUser.ProfileId = [Select id from profile where name = 'System Administrator' limit 1].Id;
     stdTestUser.CommunityNickname = stdTestUser.firstname+'_'+stdTestUser.lastName;
     stdTestUser.EmailEncodingKey ='ISO-8859-1';
     stdTestUser.LanguageLocaleKey = 'en_US';
     //stdTestUser.TimeZoneSidKey ='America/Indianapolis';
     stdTestUser.TimeZoneSidKey ='America/New_York';
     stdTestUser.LocaleSidKey = 'en_US';
     stdTestUser.Country = 'USA';
     stdTestUser.OD_Employee_ID__c ='odEmpId';
     insert stdTestUser;
         System.RunAs(stdTestUser){
             Account account = new Account(Name = 'acct1',omx_primary_key__C='123456');
             insert account;
             Account_Extension__c ae=[select id from account_extension__c where Original_Account_ID__c=:account.id];
             Account_Dormant__C ad = new Account_Dormant__c(AccountExtension__c = ae.id);
             insert ad;
             delete account;
             Account account2 = new Account(Name = 'acct1',omx_primary_key__C='123457');
             insert account2;
         }
	}
}