objects/Account.object
<CustomObject>
    <fields>
        <fullName>AOPS_Cust_Id__c</fullName>
        <description>AOPS Customer Account Number</description>
        <externalId>true</externalId>
        <label>AOPS Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Oracle_Party_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Party ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Customer_Transition__c.object
<CustomObject>
    <description>Object to Track Customer Conversion and Review Project</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Transition Relationship</relationshipLabel>
        <relationshipName>Customer_Transition_Relationship</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Error_Message_Level__c</fullName>
        <label>Error Message Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Account Setup Failure</fullName>
                </value>
                <value>
                    <fullName>Address Failure</fullName>
                </value>
                <value>
                    <fullName>Purchase Order Failure</fullName>
                </value>
                <value>
                    <fullName>Cost Center Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Error_Message_Type__c</fullName>
        <label>Error Message Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>System Failure</fullName>
                </value>
                <value>
                    <fullName>Data Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field will update dynamically per your selections.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>UnScheduled</fullName>
                    <color>#0B6FCE</color>
                    <default>true</default>
                    <label>UnScheduled</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                    <color>#78C953</color>
                    <label>Scheduled</label>
                </value>
                <value>
                    <fullName>ReScheduled</fullName>
                    <color>#E27001</color>
                    <label>ReScheduled</label>
                </value>
                <value>
                    <fullName>On Deck</fullName>
                    <color>#F3D904</color>
                    <label>On Deck</label>
                </value>
                <value>
                    <fullName>Launched</fullName>
                    <color>#009900</color>
                    <label>Launched</label>
                </value>
                <value>
                    <fullName>Transition Complete</fullName>
                    <color>#A53711</color>
                    <label>Transition Complete</label>
                </value>
                <value>
                    <fullName>Audit 2</fullName>
                    <color>#66E9BD</color>
                    <label>Audit 2</label>
                </value>
                <value>
                    <fullName>Loss of Customer</fullName>
                    <color>#0B24BE</color>
                    <label>Loss of Customer</label>
                </value>
                <value>
                    <fullName>OMX Extension in Development</fullName>
                    <color>#419249</color>
                    <label>OMX Extension in Development</label>
                </value>
                <value>
                    <fullName>Ready to Order</fullName>
                    <color>#B6E32E</color>
                    <label>Ready to Order</label>
                </value>
                <value>
                    <fullName>Ready for eCom Mod</fullName>
                    <color>#641CCF</color>
                    <label>Ready for eCom Mod</label>
                </value>
                <value>
                    <fullName>Redirect Stopped</fullName>
                    <color>#F96FB7</color>
                    <label>Redirect Stopped</label>
                </value>
                <value>
                    <fullName>Auto Redirected</fullName>
                    <color>#2F5D85</color>
                    <label>Auto Redirected</label>
                </value>
                <value>
                    <fullName>Awaiting Disposition</fullName>
                    <color>#AFCADF</color>
                    <label>Awaiting Disposition</label>
                </value>
                <value>
                    <fullName>Awaiting RFP</fullName>
                    <color>#8F6429</color>
                    <label>Awaiting RFP</label>
                </value>
                <value>
                    <fullName>Administrative Close</fullName>
                    <color>#EFAE73</color>
                    <label>Administrative Close</label>
                </value>
                <value>
                    <fullName>TOOP</fullName>
                    <color>#F96FB7</color>
                    <label>TOOP</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Transition</label>
    <nameField>
        <label>Customer Transition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Transition</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Customer_Transition_Dtls__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Transition_ID__c</fullName>
        <label>Customer Transition ID</label>
        <referenceTo>Customer_Transition__c</referenceTo>
        <relationshipLabel>Customer Transition Details</relationshipLabel>
        <relationshipName>Customer_Transition_Dtls</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Error_Message_Level__c</fullName>
        <label>Error Message Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Account Setup Failure</fullName>
                </value>
                <value>
                    <fullName>Address Failure</fullName>
                </value>
                <value>
                    <fullName>Purchase Order Failure</fullName>
                </value>
                <value>
                    <fullName>Cost Center Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Error_Message_Type__c</fullName>
        <label>Error Message Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>System Failure</fullName>
                </value>
                <value>
                    <fullName>Data Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <description>OMX Primary Key for Consignee, Cost Center and PO</description>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Transition Details</label>
    <nameField>
        <displayFormat>CTD-{000000000}</displayFormat>
        <label>CTD Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Transition Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TransitionCustomerOMX_ctrl_TC.cls
@isTest
Public class TransitionCustomerOMX_ctrl_TC
{
    static testmethod void method1()
    {
    
        
        Account pacc = new Account ();
        pacc.name = 'SUN Test Account1';
        pacc.BillingStreet = '1040 N 326 W';
        pacc.billingcity = 'Orem';
        pacc.BillingState = 'UT';
        pacc.Billingcountry = 'USA';
        pacc.Oracle_Party_Id__c = '543456';
        pacc.AOPS_Cust_Id__c = '003456';
        insert pacc;
        
        Account acc = new Account ();
        acc.name = 'SUN Test Account';
        acc.BillingStreet = '1040 N 326 W';
        acc.billingcity = 'Orem';
        acc.BillingState = 'UT';
        acc.Billingcountry = 'USA';
        acc.Oracle_Party_Id__c = '123456';
        acc.AOPS_Cust_Id__c = '123456';
        acc.parentid=pacc.id;
        insert acc;   
        
        Customer_Transition__c CT = new Customer_Transition__c(name='test',Status__c='Scheduled',Error_Message_Level__c='Cost Center Failure',Error_Message_Type__c='Data Failure',Error_Message__c='Error',Account__c=acc.id,OMX_Primary_Key__c='omxTest1');
        insert CT;
        
        Customer_Transition_Dtls__c CTD = new Customer_Transition_Dtls__c(Error_Message_Level__c='Cost Center Failure',Error_Message_Type__c='Data Failure',Customer_Transition_ID__c=CT.id,Error_Message__c='Error',OMX_Primary_Key__c=CT.OMX_Primary_Key__c);
        insert CTD;
        
        ApexPages.currentPage().getParameters().put('id',CT.id);
        
        Test.startTest(); // added for the story #S-418600 (00715635)

        TransitionCustomerOMX_ctrl con = new TransitionCustomerOMX_ctrl();
        
        // added for the story #S-418600 (00715635) #START
        
        TransitionCustomerOMX_ctrl.sortingField = 'name'; 
        TransitionCustomerOMX_ctrl.sortDir = 'limit 12'; 
        con.accountName = 'testAccount';
        con.custAccountName = 'testCusAccName';
        con.recordTypeValue = 'testValue';
        
        // added for the story #S-418600 (00715635) #END
        
        con.ErrorMessageLevelValue = 'Cost Center Failure';
        con.ErrorMessageTypeValue = 'Data Failure';
        
        con.Search();
        con.populateOMX();
        con.first();
        con.last();
        con.previous();
        con.next();
        
        // added for the story #S-418600 (00715635) #START
        
        Boolean result = con.hasNext;
        result = con.hasPrevious;
        Integer pageNumber = con.pageNumber; 
        
        Test.stopTest(); 
        
        // added for the story #S-418600 (00715635) #END 
        
    }
}