objects/Account.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Duns_Number__c</fullName>
        <description>Duns Number from Data Warehousing</description>
        <label>Duns Number</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Org/Company</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Accounts/Sites</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_DML__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related DML</label>
        <referenceTo>DML__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip/Postal Code</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <description>Prospect Accounts</description>
        <label>Prospect</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/DML__c.object
<CustomObject>
    <fields>
        <fullName>DECISION_MAKER_ID__c</fullName>
        <externalId>true</externalId>
        <label>Decision Maker Id</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DECISION_MAKER_NM__c</fullName>
        <externalId>true</externalId>
        <label>DML Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DUNS_Number__c</fullName>
        <label>DUNS Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effective_End_Date__c</fullName>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Start_Date__c</fullName>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Org</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>DML</relationshipLabel>
        <relationshipName>DML</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_for_Creation__c</fullName>
        <label>Reason for Creation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Picklist1</fullName>
                </value>
                <value>
                    <fullName>Picklist2</fullName>
                </value>
                <value>
                    <fullName>Picklist3</fullName>
                </value>
                <value>
                    <fullName>Picklist4</fullName>
                </value>
                <value>
                    <fullName>Picklist5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DML</label>
    <nameField>
        <displayFormat>DML-{0000000}</displayFormat>
        <label>DML ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DML</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DML_Relation__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Account Setup Requested, Customer, Prospect, Customer (OfficeMax)</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>DML Relationship</relationshipLabel>
        <relationshipName>DML_Relations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CUSTOMERID__c</fullName>
        <externalId>true</externalId>
        <label>CUSTOMER ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DECISIONMAKERID__c</fullName>
        <externalId>true</externalId>
        <label>DECISIONMAKERID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DML__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DML ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>DML__c.Status__c</field>
                <operation>notContain</operation>
                <value>Rejected,Draft</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>DML__c</referenceTo>
        <relationshipLabel>DML Relationship</relationshipLabel>
        <relationshipName>DML_Relations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DUNS_Number__c</fullName>
        <formula>DML__r.DUNS_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DUNS Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effective_End_Date__c</fullName>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Start_Date__c</fullName>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Org</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipName>DML_Relations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DML Relationship</label>
    <nameField>
        <displayFormat>DR-{0000}</displayFormat>
        <label>DML Relation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DML Relationship</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DML_Relation_History__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Account Setup Requested,Customer, Prospect, Parent, GrandParent, Great Grandparent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>DML Relation History</relationshipLabel>
        <relationshipName>DML_Relation_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CUSTOMERID__c</fullName>
        <externalId>true</externalId>
        <label>CUSTOMER ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DML__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DML ID</label>
        <referenceTo>DML__c</referenceTo>
        <relationshipName>DML_Relation_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_End_Date__c</fullName>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Start_Date__c</fullName>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <label>Relation History</label>
    <nameField>
        <displayFormat>DH-{0000}</displayFormat>
        <label>DML Relation History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DML Relation History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <description>Representation of Customer Relationship Hierarchy Node</description>
    <fields>
        <fullName>Address_1__c</fullName>
        <label>Address 1</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Name__c</fullName>
        <label>Business Name</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <externalId>true</externalId>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DML__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DML</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DUNS_Number__c</fullName>
        <externalId>true</externalId>
        <label>DUNS Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <externalId>true</externalId>
        <label>State</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Org</label>
    <nameField>
        <displayFormat>Org-{0000}</displayFormat>
        <label>Org Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Person__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Person_IDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Person ID</label>
    <nameField>
        <label>Sales Person ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Person IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DMLRelationController_TC.cls
@isTest
public class DMLRelationController_TC {
    public static Integer pageNumber = 1;
    public static Integer recordToDisply = 50;
    static testMethod void getDMLApprovalDataTest() {
        Recordtype rt = [SELECT Id FROM RecordType WHERE Name = 'Deployment Request'];
		list<DML__c> lstDML = new list<DML__c>();
        DML__c dmlrec = new DML__c();
        dmlrec.Status__c = 'Approved';
        //dmlrec.DECISION_MAKER_ID__c = '123456600';
        dmlrec.Effective_Start_Date__c = system.today();

        lstDML.add(dmlrec);

        DML__c dmlrec1 = new DML__c();
        dmlrec1.Status__c = 'Approved';
        //dmlrec1.DECISION_MAKER_ID__c = '123446799';
        dmlrec1.Effective_Start_Date__c=system.today();
        lstDML.add(dmlrec1);
		insert lstDML;
        
        Account prospectAccount = Test_Utils.CreateAccount('Prospect');
        prospectAccount.Related_DML__c = dmlrec.id;
        insert prospectAccount;
        
        Account prospectAccount1 = Test_Utils.CreateAccount('Prospect');
        prospectAccount1.Related_DML__c = dmlrec1.id;
        insert prospectAccount1;

        Org__c org = new Org__c();
        org.Business_Name__c = 'Test org';
        org.DUNS_Number__c = '123123456';
        org.Address_1__c = 'Melino Park';
        org.City__c = 'Bocca';
        org.State__c  ='FL';
        org.Zip__c = '12345';
        insert org;

        DML_Relation__c dmlr = new DML_Relation__c();
        dmlr.Org__c = org.Id;
        //dmlr.CUSTOMERID__c = '123456422';
        dmlr.Account__c = prospectAccount.id;
        dmlr.DML__c = dmlrec.Id;
        //dmlr.DECISIONMAKERID__c = '013834953';
        dmlr.Effective_End_Date__c = system.today();
        dmlr.Effective_Start_Date__c = system.today();
        insert dmlr;
        list<Case> lstCase = new list<Case>();
        Case newCase = new Case();
        newCase.accountId = prospectAccount.id;
        newCase.Support_Type__c = 'New DML Exception';
        newCase.Support_Sub_Type__c = dmlrec.Reason_for_Creation__c;
        newCase.subject = prospectAccount.Name;
        newCase.RecordTypeId = rt.Id;
        newCase.Description = 'Account Name :' + ' ' + prospectAccount.Name + '\n' + 'Request Type: New DML Exception' + '\n' + 'Reason For DML Creation:' + ' ' + dmlrec.Reason_for_Creation__c + '\n' + 'Please check the DML by clicking this link:' + '  ' + 'https://officedepot--oduat.cs78.my.salesforce.com/' + dmlrec.id;
        lstCase.add(newCase);

        Case newCase1 = new Case();
        newCase1.accountId = prospectAccount1.id;
        newCase1.Support_Type__c = 'New DML Exception';
        newCase1.Support_Sub_Type__c = dmlrec1.Reason_for_Creation__c;
        newCase1.subject = prospectAccount1.Name;
        newCase1.RecordTypeId = rt.Id;
        newCase1.Description = 'Account Name :' + ' ' + prospectAccount1.Name + '\n' + 'Request Type: New DML Exception' + '\n' + 'Reason For DML Creation:' + ' ' + dmlrec1.Reason_for_Creation__c + '\n' + 'Please check the DML by clicking this link:' + '  ' + 'https://officedepot--oduat.cs78.my.salesforce.com/' + dmlrec1.id;
        lstCase.add(newCase1);
        
        insert lstCase;

        DMLRelationController.CasePagerWrapper objWrapper =  new DMLRelationController.CasePagerWrapper();
        objWrapper = DMLRelationController.getDMLApprovalData(pageNumber, recordToDisply);
        System.debug('objWrapper=>'+objWrapper);
        String caseid = '["' + newCase.Id + '"]';
        String caseid1 = '["' + newCase1.Id + '"]';
        system.debug('caseid' + caseid);
        string notes = 'Rejected';
        DMLRelationController.CasePagerWrapper objWrapper2 =  new DMLRelationController.CasePagerWrapper();
        DMLRelationController.CasePagerWrapper objWrapper3 =  new DMLRelationController.CasePagerWrapper();
        objWrapper2 = DMLRelationController.processDMLApproval(caseid1, pageNumber, recordToDisply);
        System.debug('objWrapper2=>'+objWrapper2);
        //objWrapper3 = DMLRelationController.processDMLRejection(caseid, notes, pageNumber, recordToDisply);
        System.debug('objWrapper3=>'+objWrapper3);
        

        
        System.AssertEquals(true, objWrapper.total == 0);
        
    }
    static testMethod void processDMLRejectionTest() {
        Recordtype rt = [SELECT Id FROM RecordType WHERE Name = 'Deployment Request'];
		list<DML__c> lstDML = new list<DML__c>();
        DML__c dmlrec = new DML__c();
        dmlrec.Status__c = 'Approved';
        dmlrec.DECISION_MAKER_ID__c = '111456600';
        dmlrec.Effective_End_Date__c = system.today();

        lstDML.add(dmlrec);

        DML__c dmlrec1 = new DML__c();
        dmlrec1.Status__c = 'Approved';
        dmlrec1.DECISION_MAKER_ID__c = '111446799';
        dmlrec1.Effective_Start_Date__c=system.today();
        lstDML.add(dmlrec1);
        
        insert lstDML;

        Account prospectAccount = Test_Utils.CreateAccount('Prospect');
        prospectAccount.Related_DML__c = dmlrec.id;
        insert prospectAccount;
        
        Account prospectAccount1 = Test_Utils.CreateAccount('Prospect');
        prospectAccount1.Related_DML__c = dmlrec1.id;
        insert prospectAccount1;
        

        Org__c org = new Org__c();
        org.Business_Name__c = 'Test org';
        org.DUNS_Number__c = '111123456';
        org.Address_1__c = 'Melino Park';
        org.City__c = 'Bocca';
        org.State__c  ='FL';
        org.Zip__c = '12345';
        insert org;

        DML_Relation__c dmlr = new DML_Relation__c();
        dmlr.Org__c = org.Id;
        dmlr.CUSTOMERID__c = '123456111';
        dmlr.Account__c = prospectAccount.id;
        dmlr.DML__c = dmlrec.Id;
        //dmlr.DECISIONMAKERID__c = '013834953';
        dmlr.Effective_End_Date__c = system.today();
        dmlr.Effective_Start_Date__c = system.today();
        insert dmlr;
        
        Case newCase1 = new Case();
        newCase1.accountId = prospectAccount1.id;
        newCase1.Support_Type__c = 'New DML Exception';
        newCase1.Support_Sub_Type__c = dmlrec1.Reason_for_Creation__c;
        newCase1.subject = prospectAccount1.Name;
        newCase1.RecordTypeId = rt.Id;
        newCase1.Description = 'Account Name :' + ' ' + prospectAccount1.Name + '\n' + 'Request Type: New DML Exception' + '\n' + 'Reason For DML Creation:' + ' ' + dmlrec1.Reason_for_Creation__c + '\n' + 'Please check the DML by clicking this link:' + '  ' + 'https://officedepot--oduat.cs78.my.salesforce.com/' + dmlrec1.id;
        insert newCase1;
      
        String caseid1 = '["' + newCase1.Id + '"]';                
        //system.debug('caseid' + caseid);                        
        DMLRelationController.CasePagerWrapper objWrapper3 =  new DMLRelationController.CasePagerWrapper();
        string notes = 'Rejected';
        Test.startTest();
        try{
        objWrapper3 = DMLRelationController.processDMLRejection(caseid1, notes, pageNumber, recordToDisply);
        }catch(Exception e){
        
        }
        Test.StopTest();
        System.debug('objWrapper3=>'+objWrapper3);
        
        
    }
     static testMethod void processDMLRelationDataTest() {
         list<DML__c> lstDML = new list<DML__c>();
       DML__c dmlrec = new DML__c();
        dmlrec.Status__c = 'Approved';
        dmlrec.DECISION_MAKER_ID__c = '123556600';
        dmlrec.Effective_End_Date__c = system.today();

        lstDML.add(dmlrec);

        DML__c dmlrec1 = new DML__c();
        dmlrec1.Status__c = 'Approved';
        dmlrec1.DECISION_MAKER_ID__c = '123556799';
        dmlrec1.Effective_Start_Date__c=system.today();
         lstDML.add(dmlrec1);
        insert lstDML;

        Account prospectAccount = Test_Utils.CreateAccount('Prospect');
        prospectAccount.Related_DML__c = dmlrec.id;
        insert prospectAccount;
        
        Account prospectAccount1 = Test_Utils.CreateAccount('Prospect');
        prospectAccount1.Related_DML__c = dmlrec1.id;
        insert prospectAccount1;

        Org__c org = new Org__c();
        org.Business_Name__c = 'Test org';
        org.DUNS_Number__c = '123553456';
        org.Address_1__c = 'Melino Park';
        org.City__c = 'Bocca';
        org.State__c  ='FL';
        org.Zip__c = '12345';
        insert org;

        DML_Relation__c dmlr = new DML_Relation__c();
        dmlr.Org__c = org.Id;
        dmlr.CUSTOMERID__c = '123456422';
        dmlr.Account__c = prospectAccount.id;
        dmlr.DML__c = dmlrec.Id;
        //dmlr.DECISIONMAKERID__c = '013834953';
        dmlr.Effective_End_Date__c = system.today();
        dmlr.Effective_Start_Date__c = system.today();
        insert dmlr;
        
        String newDMLId = '' + dmlrec1.id;
        String input = '["' + dmlr.Id + '"]';
        String dataVal = String.valueOf(Date.today());
        Map <String, List<Object>> mapData = new Map <String, List<Object>>();
        system.debug('input=>'+input);
        system.debug('newDMLId=>'+newDMLId);
        system.debug('dataVal=>'+dataVal);
        mapData = DMLRelationController.processDMLRelationData(input, newDMLId,dataVal);
        System.debug('mapData=>'+mapData);
     }
    static testMethod void getDMLRelationDataTest() {
       
        DML__c dmlrec = new DML__c();
        //dmlrec.Status__c = 'Draft';
        dmlrec.DECISION_MAKER_ID__c = '123456755';
        dmlrec.DECISION_MAKER_NM__c = 'DML name';
        dmlrec.Effective_Start_Date__c=system.today();
        insert dmlrec;


        Org__c org = new Org__c();
        org.Business_Name__c = 'Test org';
        org.DUNS_Number__c = '123423477';
        org.Address_1__c = 'Melino Park';
        org.City__c = 'Bocca';
        org.State__c  ='FL';
        org.Zip__c = '12345';
        insert org;

        Account prospectAccount = Test_Utils.CreateAccount('Prospect');
        prospectAccount.Related_DML__c = dmlrec.id;
        prospectAccount.Org__c = org.id;
        insert prospectAccount;


        DML_Relation__c dmlr = new DML_Relation__c();
        dmlr.Org__c = org.Id;
        dmlr.CUSTOMERID__c = '123456666';
        dmlr.Account__c = prospectAccount.id;
        dmlr.DML__c = dmlrec.Id;
        //dmlr.DECISIONMAKERID__c = '013834950'; 
        dmlr.Effective_End_Date__c = system.today();
        dmlr.Effective_Start_Date__c = system.today();
        insert dmlr;

        List<String> CustId = new List<String>{'123456678','123456676'};
        List<String> ParentId = new List<String> {'1234'};
        List<String> DMLId = new List<String>();
        DMLId.add(dmlrec.Name);
        String DMLName='test';
        List<String> RepId = new List<String>{'123456678','123456676'};
        List<String> GPId = new List<String>{'123456678','123456676'};
        List<String> DunsId = new List<String>{'123456678','123456676'};
        
        DMLRelationController.DMLRelatedData objData = DMLRelationController.getDMLRelationData(CustId, ParentId, DMLId, DMLName,RepId, GPId, DunsId,1,50);     
        System.debug('objData=>'+objData);
        System.AssertEquals(true, objData.countDml == 0);
        
    }
    
    static testMethod void processDMLRelationDataSalesRepTest() {
  		list<DML__c> lstDML = new list<DML__c>();
        DML__c dmlrec = new DML__c();
        //dmlrec.Status__c = 'Draft';
        dmlrec.DECISION_MAKER_ID__c = '123456733';
        dmlrec.DECISION_MAKER_NM__c = 'DML name';
        dmlrec.Effective_Start_Date__c=system.today();
        lstDML.add(dmlrec);
        
        DML__c dmlrec2 = new DML__c();
        //dmlrec.Status__c = 'Draft';
        dmlrec2.DECISION_MAKER_ID__c = '123456722';
        dmlrec2.DECISION_MAKER_NM__c = 'new DML name';
        dmlrec2.Effective_Start_Date__c=system.today();
        lstDML.add(dmlrec2);
        insert lstDML;
        
        DML_Relation__c dmlr = new DML_Relation__c();
       // dmlr.Org__c = org.Id;
        dmlr.CUSTOMERID__c = '123456633';
        //dmlr.Account__c = prospectAccount.id;
        dmlr.DML__c = dmlrec.Id;
        //dmlr.DECISIONMAKERID__c = '013834952';
        dmlr.Effective_End_Date__c = system.today()+10;
        dmlr.Effective_Start_Date__c = system.today();
        insert dmlr;
        
        User oUser = [select id,Name,TimeZoneSidKey,Username,Alias,Country,Email,FirstName,LastName,IsActive,IsPortalEnabled 
                      FROM User Where id =: userInfo.getUserId()];
        Sales_Person__c salesPerson=new Sales_Person__c();
        salesPerson.user__c=oUser.id;
        insert salesPerson;
        
        String InputData = '["' + dmlr.Id + '"]';
        string newDMLId= salesPerson.id;
        String Segment='Major $500K-$1M';
        String newDMLIdVal=salesPerson.id;
        String ProposedDate='2018-10-10';
        List < DML_Relation__c > lstDMLR = DMLRelationController.processDMLRelationDataSalesRep(InputData, newDMLId, Segment, newDMLIdVal, ProposedDate,'','');
        System.debug('lstDMLR=>'+lstDMLR);
        newDMLId=dmlrec2.id; 
        String DateVal='2018-10-10';
        
        
        
        Map <String, List < Object >> mapObj = DMLRelationController.processDMLRelationDate(InputData, newDMLId, DateVal);
        String status = DMLRelationController.processDMLData(newDMLId);
        System.debug('status=>'+status);
        List < DML_Relation_History__c > lstDRH = DMLRelationController.getDMLRelationHistory(dmlr.Id);
        System.debug('lstDRH=>'+lstDRH);
        System.AssertEquals(true, lstDMLR.size()>0);
        System.AssertEquals('SUCCESS', status);
        //System.AssertEquals(true, lstDRH.size()>0);
        
    }
     
}