objects/Account.object
<CustomObject>
    <fields>
        <fullName>Address1__c</fullName>
        <label>Address1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>USA</fullName>
                    <default>true</default>
                    <label>USA</label>
                </value>
                <value>
                    <fullName>CAN</fullName>
                </value>
                <value>
                    <fullName>MEX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <inlineHelpText>Small is less than 30 Employees</inlineHelpText>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Sector__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Small &lt; $10K</fullName>
                </value>
                <value>
                    <fullName>Small $10K-$75K</fullName>
                </value>
                <value>
                    <fullName>Medium $75K-$150K</fullName>
                </value>
                <value>
                    <fullName>Standard $150K-$250K</fullName>
                </value>
                <value>
                    <fullName>Key $250K-$500K</fullName>
                </value>
                <value>
                    <fullName>Major $500K-$1M</fullName>
                </value>
                <value>
                    <fullName>K-12</fullName>
                </value>
                <value>
                    <fullName>Higher-Ed</fullName>
                </value>
                <value>
                    <fullName>Federal</fullName>
                </value>
                <value>
                    <fullName>State</fullName>
                </value>
                <value>
                    <fullName>Local</fullName>
                </value>
                <value>
                    <fullName>Non-Profit</fullName>
                </value>
                <value>
                    <fullName>Enterprise $1M+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip/Postal Code</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>GrandParent</fullName>
        <active>true</active>
        <description>Used for GP Maintenance</description>
        <label>GrandParent</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/createDMLRelationshipRecord_Test.cls
@isTest
public class createDMLRelationshipRecord_Test {
    static testMethod void UnitTest1() {
        Id Parent_RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('GrandParent').getRecordTypeId();
    	Account Acc = new Account();
        Acc.Name='Test';
        Acc.Address1__c='New Testing';
        Acc.City__c='City Test';
        Acc.State__c='TMO';
        Acc.Country__c='USA';
        Acc.Zip__c='12321';
        Acc.Segment__c='State';
        Acc.RecordtypeId=Parent_RecordTypeId;
        Insert Acc;
    }
}