objects/Account.object
<CustomObject>
    <fields>
        <fullName>Address1__c</fullName>
        <label>Address1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OMX_Mainframe_Account_Level__c</fullName>
        <description>the legacy officemax account hierarchy: CS,CU,NA</description>
        <label>OMX Mainframe Account Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Site/Consignee</fullName>
                </value>
                <value>
                    <fullName>Main Account</fullName>
                </value>
                <value>
                    <fullName>National</fullName>
                </value>
                <value>
                    <fullName>Super National</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OMX_Mainframe_Account_Number__c</fullName>
        <description>Account # for main accounts from OfficeMax Mainframe. Field: n_cust</description>
        <label>OMX Mainframe Account #</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Oracle_Party_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Party ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sales_PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is used for Primary Owner Sales ID.</description>
        <label>Sales Person ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sales_Person__c.Primary__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Person__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <inlineHelpText>Small is less than 30 Employees</inlineHelpText>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Sector__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Small &lt; $10K</fullName>
                </value>
                <value>
                    <fullName>Small $10K-$75K</fullName>
                </value>
                <value>
                    <fullName>Medium $75K-$150K</fullName>
                </value>
                <value>
                    <fullName>Standard $150K-$250K</fullName>
                </value>
                <value>
                    <fullName>Key $250K-$500K</fullName>
                </value>
                <value>
                    <fullName>Major $500K-$1M</fullName>
                </value>
                <value>
                    <fullName>K-12</fullName>
                </value>
                <value>
                    <fullName>Higher-Ed</fullName>
                </value>
                <value>
                    <fullName>Federal</fullName>
                </value>
                <value>
                    <fullName>State</fullName>
                </value>
                <value>
                    <fullName>Local</fullName>
                </value>
                <value>
                    <fullName>Non-Profit</fullName>
                </value>
                <value>
                    <fullName>Enterprise $1M+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Split_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Split Record</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer Accounts</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Customer_Transition__c.object
<CustomObject>
    <description>Object to Track Customer Conversion and Review Project</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Transition Relationship</relationshipLabel>
        <relationshipName>Customer_Transition_Relationship</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OMX_Mainframe_Account_Level__c</fullName>
        <formula>text(Account__r.OMX_Mainframe_Account_Level__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>OMX Mainframe Account Level</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field will update dynamically per your selections.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>UnScheduled</fullName>
                    <color>#0B6FCE</color>
                    <default>true</default>
                    <label>UnScheduled</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                    <color>#78C953</color>
                    <label>Scheduled</label>
                </value>
                <value>
                    <fullName>ReScheduled</fullName>
                    <color>#E27001</color>
                    <label>ReScheduled</label>
                </value>
                <value>
                    <fullName>On Deck</fullName>
                    <color>#F3D904</color>
                    <label>On Deck</label>
                </value>
                <value>
                    <fullName>Launched</fullName>
                    <color>#009900</color>
                    <label>Launched</label>
                </value>
                <value>
                    <fullName>Transition Complete</fullName>
                    <color>#A53711</color>
                    <label>Transition Complete</label>
                </value>
                <value>
                    <fullName>Audit 2</fullName>
                    <color>#66E9BD</color>
                    <label>Audit 2</label>
                </value>
                <value>
                    <fullName>Loss of Customer</fullName>
                    <color>#0B24BE</color>
                    <label>Loss of Customer</label>
                </value>
                <value>
                    <fullName>OMX Extension in Development</fullName>
                    <color>#419249</color>
                    <label>OMX Extension in Development</label>
                </value>
                <value>
                    <fullName>Ready to Order</fullName>
                    <color>#B6E32E</color>
                    <label>Ready to Order</label>
                </value>
                <value>
                    <fullName>Ready for eCom Mod</fullName>
                    <color>#641CCF</color>
                    <label>Ready for eCom Mod</label>
                </value>
                <value>
                    <fullName>Redirect Stopped</fullName>
                    <color>#F96FB7</color>
                    <label>Redirect Stopped</label>
                </value>
                <value>
                    <fullName>Auto Redirected</fullName>
                    <color>#2F5D85</color>
                    <label>Auto Redirected</label>
                </value>
                <value>
                    <fullName>Awaiting Disposition</fullName>
                    <color>#AFCADF</color>
                    <label>Awaiting Disposition</label>
                </value>
                <value>
                    <fullName>Awaiting RFP</fullName>
                    <color>#8F6429</color>
                    <label>Awaiting RFP</label>
                </value>
                <value>
                    <fullName>Administrative Close</fullName>
                    <color>#EFAE73</color>
                    <label>Administrative Close</label>
                </value>
                <value>
                    <fullName>TOOP</fullName>
                    <color>#F96FB7</color>
                    <label>TOOP</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transition_Status__c</fullName>
        <label>Transition Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Transition</label>
    <nameField>
        <label>Customer Transition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Transition</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Sales_Person__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role_Relate_Id__c</fullName>
        <externalId>true</externalId>
        <label>Role Relate Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Person_IDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Person ID</label>
    <nameField>
        <label>Sales Person ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Person IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Short_Title__c</fullName>
        <label>Short Title</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/AccountStructure_CT_TC.cls
@isTest
private class AccountStructure_CT_TC 
{
    static testMethod void TestAccountStructure_CT(){
        
        executeoncetest.bypassAccountExtension = true;

        Schema.DescribeSObjectResult d1 = Schema.SObjectType.Account; 
        Map<String,Schema.RecordTypeInfo> rtMapByName = d1.getRecordTypeInfosByName(); 
        
        Profile profileObj = [select id from profile where name='System Administrator'];

        String profId = profileObj.id;
        user usrObj = new user(Username='abc@officedepot.com.uat',FirstName ='Fname', LastName='Lname', Alias='abc', CommunityNickname='abc', LocaleSidKey='en_US', EmailEncodingKey='UTF-8', Profileid = profId, LanguageLocaleKey='en_US', email='abc@officedepot.com.uat',TimeZoneSidKey='America/New_York');
        usrObj.Short_Title__c='';
        Insert usrObj;
        
        Account pacc = new Account ();
        pacc.name = 'SUN Test Account1';
        pacc.recordtypeid=rtMapByName.get('Customer (OfficeMax)').getRecordTypeId(); 
        pacc.BillingStreet = '1040 N 326 W';
        pacc.billingcity = 'Orem';
        pacc.BillingState = 'UT';
        pacc.Billingcountry = 'USA';
        pacc.Oracle_Party_Id__c = '543456';
        pacc.omx_primary_key__C = '003456';
        pacc.Split_Record__c = false;
        pacc.status__c='Inactive';
        pacc.address1__C='test';
        pacc.OMX_Mainframe_Account_Number__c = '003456';
        system.runas(usrObj){
            insert pacc;
        }
        
        Test.startTest();
        Account acc = new Account ();
        acc.name = 'SUN Test Account';
        acc.BillingStreet = '1040 N 326 W';
        acc.billingcity = 'Orem';
        acc.BillingState = 'UT';
        acc.Billingcountry = 'USA';
        acc.Oracle_Party_Id__c = '123456';
        acc.Split_Record__c = false;
        acc.omx_primary_key__C = '123456';
        acc.parentid=pacc.id;
        acc.recordtypeid=rtMapByName.get('Customer (OfficeMax)').getRecordTypeId();
        acc.address1__C='testing records address 25';
        acc.OMX_Mainframe_Account_Number__c = '123456';
        system.runas(usrObj){
        insert acc;   
        }
        pacc.status__c='Active';
        system.runas(usrObj){
        update pacc;
        }
        Customer_Transition__c parentCT = new Customer_Transition__c(name='parenttest',account__c = pacc.id,Status__c='Scheduled');
       system.runas(usrObj){
        insert parentCT;
       }
        
        Customer_Transition__c CT = new Customer_Transition__c(name='test',account__c = acc.id,Status__c='Scheduled');
        system.runas(usrObj){
        insert CT;
        }
        
        Test.setCurrentPage(Page.Account_Hierarchy_Page_CT);
        ApexPages.CurrentPage().getParameters().put('EL','Y');
        ApexPages.CurrentPage().getParameters().put('id',acc.id);
        ApexPages.StandardController controller1 = new ApexPages.StandardController(acc);
        
        AccountStructure_CT asct = new AccountStructure_CT();
        AccountStructure_CT asct1 = new AccountStructure_CT(controller1);
        
        asct.userEmailCc='xyz@officedepot.com.uat';
        asct1.userEmailCc='xyz@officedepot.com.uat;abc@officedepot.com.uat';
        asct1.getObjectStructure();
        asct1.setcurrentId(String.valueOf(acc.id));
        asct1.IdTreeNodeForAction='0';
        asct1.NodeStatus='';
        asct1.updateTree();
        List<String> cn1 = new List<String>();
        List<String> nn1 = new List<String>();
        cn1.add('0');
        cn1.add('1');
        nn1.add('0');
        nn1.add('1');
        
        String nodeType ='child';
        asct1.setlevelFlag( nn1,nodeType);
        asct1.setcloseFlag(cn1,nn1,nodeType);
        asct1.isLastNode( nn1);
        asct1.ExclusionList=false;
        asct1.GetTopElement(String.valueOf(acc.id));
        asct1.ExclusionList=true;
        asct1.getEmailList(0,1);
        asct1.createNewBody();
        
        asct1.accountMap.put(pacc.id,pacc);
        PageReference pf = asct1.sendEmail();
        asct1.CreateActivity();
        PageReference pf1 = asct1.selectedAccounts();
        PageReference pf2 = asct1.LaunchSelected();
        PageReference pf3 = asct1.BackToAccountHierarchy();
        List<SelectOption> ops =  asct1.getUsers();
        String str = asct1.getSelectedUsers();
        asct1.setSelectedUsers(str);
        
        List<Boolean> bn= new List<Boolean>();
        bn.add(true);
        AccountStructure_CT.ObjectStructureMap wrap = new AccountStructure_CT.ObjectStructureMap( '0', bn,bn ,'child', true, true, CT );
        wrap.getnodeId();
        wrap.getlevelFlag();
        wrap.getcloseFlag();
        wrap.getnodeType();
        wrap.getcurrentNode();
        Customer_Transition__c ctt = wrap.getaccount();
        wrap.setnodeId('test');
        wrap.setlevelFlag(true);
        wrap.setlcloseFlag(true);
        wrap.setnodeType('test');
        wrap.setcurrentNode(true);
        wrap.setaccount(ctt);
        
        AccountStructure_CT.WrapErrors wrapError = new AccountStructure_CT.WrapErrors('123456@@:@@SUN Test Account@@:@@Account Owner is not Active');
        wrapError.getomxPrimaryKey();
        wrapError.getaccName();
        wrapError.getreason();

		//Test.startTest() ; // Added for the story #S-355233
		
        Test.setCurrentPage(Page.Account_Hierarchy_Page_CT);
        ApexPages.CurrentPage().getParameters().put('EL','Y');
        ApexPages.CurrentPage().getParameters().put(pacc.id,'1');
        asct1.accountMap.put(pacc.id,pacc);
        PageReference pf5 = asct1.LaunchSelected();
        
        Test.stopTest(); // Added for the story #S-355233
        
    }
    
    // Added for the story #S-355233 #START
     static testMethod void TestAccountStructure_CT1(){
        
        executeoncetest.bypassAccountExtension = true;
        
        Schema.DescribeSObjectResult d1 = Schema.SObjectType.Account; 
        Map<String,Schema.RecordTypeInfo> rtMapByName = d1.getRecordTypeInfosByName(); 
        
        Profile profileObj = [select id from profile where name='System Administrator'];
        

        String profId = profileObj.id;
        user usrObj = new user(Username='abc@officedepot.com.uat',FirstName ='Fname', LastName='Lname', Alias='abc', CommunityNickname='abc', LocaleSidKey='en_US', EmailEncodingKey='UTF-8', Profileid = profId, LanguageLocaleKey='en_US', email='abc@officedepot.com.uat',TimeZoneSidKey='America/New_York');
        usrObj.Short_Title__c='';
        Insert usrObj;
        
        Sales_Person__c s= new Sales_Person__c();
        s.name = 'Awaiting SalesID';
        s.IsActive__c=true;
        s.Role_Relate_Id__c ='333333';
        s.Primary__c =true;
        s.user__c=usrObj.id;
          system.runas(usrObj){
        insert s;
          }
        
        Account pacc = new Account ();
        pacc.name = 'SUN Test Account1';
        pacc.recordtypeid=rtMapByName.get('Customer (OfficeMax)').getRecordTypeId(); 
        pacc.BillingStreet = '1040 N 326 W';
        pacc.billingcity = 'Orem';
        pacc.BillingState = 'UT';
        pacc.Billingcountry = 'USA';
        pacc.Oracle_Party_Id__c = '543456';
        pacc.omx_primary_key__C = '003456';
        pacc.Split_Record__c = false;
        pacc.status__c='Inactive';
        pacc.address1__C='test';
        pacc.OMX_Mainframe_Account_Number__c = '003456';
        pacc.Segment__c = 'Other';
        pacc.Sales_PersonID__c = s.id;
          system.runas(usrObj){
        insert pacc;
          }
        Test.startTest();
        Account acc = new Account ();
        acc.name = 'SUN Test Account';
        acc.BillingStreet = '1040 N 326 W';
        acc.billingcity = 'Orem';
        acc.BillingState = 'UT';
        acc.Billingcountry = 'USA';
        acc.Oracle_Party_Id__c = '123456';
        acc.Split_Record__c = false;
        acc.omx_primary_key__C = '123456';
        acc.parentid=pacc.id;
        acc.recordtypeid=rtMapByName.get('Customer (OfficeMax)').getRecordTypeId();
        acc.address1__C='testing records address 25';
        acc.OMX_Mainframe_Account_Number__c = '123456';
          system.runas(usrObj){
        insert acc;
          }
        
        pacc.status__c='Active';
          system.runas(usrObj){
        update pacc;
          }
        
        Customer_Transition__c parentCT = new Customer_Transition__c(name='parenttest',account__c = pacc.id,Status__c='Scheduled');
          system.runas(usrObj){
        insert parentCT;
          }
        
        Customer_Transition__c CT = new Customer_Transition__c(name='test',account__c = acc.id,Status__c='Scheduled');
          system.runas(usrObj){
        insert CT;
          }
        
        //Test.startTest();
        
        Test.setCurrentPage(Page.Account_Hierarchy_Page_CT);
        ApexPages.CurrentPage().getParameters().put('EL','N');
        ApexPages.CurrentPage().getParameters().put('id',acc.id);
        ApexPages.StandardController controller1 = new ApexPages.StandardController(acc);
        
        AccountStructure_CT asct = new AccountStructure_CT();
        AccountStructure_CT asct1 = new AccountStructure_CT(controller1);
        AccountStructure_CT asct2 = new AccountStructure_CT('test'); 
        
        system.assertEquals(asct.ExclusionList, false);
        
        asct.userEmailCc='xyz@officedepot.com.uat';
        asct1.userEmailCc='xyz@officedepot.com.uat;abc@officedepot.com.uat';
        
        asct1.asm = null;
        asct1.getObjectStructure();
        
        system.assertnotEquals(asct1.asm, null);
        
        asct1.setcurrentId(String.valueOf(acc.id));
        asct1.IdTreeNodeForAction='0';
        asct1.NodeStatus='';
        asct1.updateTree();
        List<String> cn1 = new List<String>();
        List<String> nn1 = new List<String>();
        cn1.add('0');
        cn1.add('1');
        nn1.add('0');
        nn1.add('1');
        
        String nodeType ='child';
        asct1.setlevelFlag( nn1,nodeType);
        asct1.setcloseFlag(cn1,nn1,nodeType);
        asct1.isLastNode( nn1);
        asct1.ExclusionList=false;
        asct1.GetTopElement(String.valueOf(acc.id));
        asct1.ExclusionList=true;
        asct1.getEmailList(0,1);
        asct1.createNewBody();
        
        asct1.accountMap.put(pacc.id,pacc);
        PageReference pf = asct1.sendEmail();
        asct1.CreateActivity();
        PageReference pf1 = asct1.selectedAccounts();
        PageReference pf2 = asct1.LaunchSelected();
        
        system.assertEquals(pf2, null);
        
        PageReference pf3 = asct1.BackToAccountHierarchy();
        List<SelectOption> ops =  asct1.getUsers();
        String str = asct1.getSelectedUsers();
        asct1.setSelectedUsers(str);
        
        List<Boolean> bn= new List<Boolean>();
        bn.add(true);
        AccountStructure_CT.ObjectStructureMap wrap = new AccountStructure_CT.ObjectStructureMap( '0', bn,bn ,'child', true, true, CT );
        wrap.getnodeId();
        wrap.getlevelFlag();
        wrap.getcloseFlag();
        wrap.getnodeType();
        wrap.getcurrentNode();
        Customer_Transition__c ctt = wrap.getaccount();
        wrap.setnodeId('test');
        wrap.setlevelFlag(true);
        wrap.setlcloseFlag(true);
        wrap.setnodeType('test');
        wrap.setcurrentNode(true);
        wrap.setaccount(ctt);
        
        AccountStructure_CT.WrapErrors wrapError = new AccountStructure_CT.WrapErrors('123456@@:@@SUN Test Account@@:@@Account Owner is not Active');
        wrapError.getomxPrimaryKey();
        wrapError.getaccName();
        wrapError.getreason();

        Test.setCurrentPage(Page.Account_Hierarchy_Page_CT);
        ApexPages.CurrentPage().getParameters().put('EL','Y');
        ApexPages.CurrentPage().getParameters().put(pacc.id,'1');
        asct1.accountMap.put(pacc.id,pacc);
        PageReference pf5 = asct1.LaunchSelected();
        
        system.assertNotEquals(pf5, null);
        
        Test.stopTest();
        
    }
    
   /*static testMethod void TestAccountStructure_CT2(){
       
        executeoncetest.bypassAccountExtension = true;

        Schema.DescribeSObjectResult d1 = Schema.SObjectType.Account; 
        Map<String,Schema.RecordTypeInfo> rtMapByName = d1.getRecordTypeInfosByName(); 
        
        Profile profileObj = [select id from profile where name='System Administrator'];
		
        String profId = profileObj.id;
        user usrObj = new user(Username='abc@officedepot.com.uat',FirstName ='Fname', LastName='Lname', Alias='abc', CommunityNickname='abc', LocaleSidKey='en_US', EmailEncodingKey='UTF-8', Profileid = profId, LanguageLocaleKey='en_US', email='abc@officedepot.com.uat',TimeZoneSidKey='America/New_York');
        usrObj.Short_Title__c='';
        Insert usrObj;
        Test.startTest();
        Sales_Person__c s= new Sales_Person__c();
        s.name = 'D7873';
        s.IsActive__c=true;
        s.Role_Relate_Id__c ='333333';
        s.Primary__c =true;
        s.user__c=usrObj.id;
        insert s;
        
        Account pacc = new Account ();
        pacc.name = 'SUN Test Account1';
        pacc.recordtypeid=rtMapByName.get('Customer (OfficeMax)').getRecordTypeId(); 
        pacc.BillingStreet = '1040 N 326 W';
        pacc.billingcity = 'Orem';
        pacc.BillingState = 'UT';
        pacc.Billingcountry = 'USA';
        pacc.Oracle_Party_Id__c = '543456';
        pacc.omx_primary_key__C = '003456';
        pacc.Split_Record__c = false;
        pacc.status__c='Inactive';
        pacc.address1__C='test';
        pacc.OMX_Mainframe_Account_Number__c = '003456';
        pacc.Segment__c = 'Other';
        pacc.Sales_PersonID__c = s.id;
        pacc.ownerId = usrObj.id;
        pacc.OMX_Mainframe_Account_Level__c = 'Main Account';
        insert pacc;
       Test.stopTest();
        Account acc = new Account ();
        acc.name = 'SUN Test Account';
        acc.BillingStreet = '1040 N 326 W';
        acc.billingcity = 'Orem';
        acc.BillingState = 'UT';
        acc.Billingcountry = 'USA';
        acc.Oracle_Party_Id__c = '123456';
        acc.Split_Record__c = false;
        acc.omx_primary_key__C = '123456';
        acc.parentid=pacc.id;
        acc.recordtypeid=rtMapByName.get('Customer (OfficeMax)').getRecordTypeId();
        acc.address1__C='testing records address 25';
        acc.OMX_Mainframe_Account_Number__c = '123456';
        acc.ownerId = usrObj.id;
        insert acc;
       
        
        Customer_Transition__c parentCT = new Customer_Transition__c(name='parenttest',account__c = pacc.id,Status__c='Scheduled', Transition_Status__c = 'Inactive');
        insert parentCT;
        
        Customer_Transition__c CT = new Customer_Transition__c(name='test',account__c = acc.id,Status__c='Scheduled');
        insert CT;
        
        //Test.startTest();
        
        Test.setCurrentPage(Page.Account_Hierarchy_Page_CT);
        ApexPages.CurrentPage().getParameters().put('EL','N');
        ApexPages.CurrentPage().getParameters().put('id',acc.id);
        ApexPages.StandardController controller1 = new ApexPages.StandardController(acc);
        
        AccountStructure_CT asct = new AccountStructure_CT();
        AccountStructure_CT asct1 = new AccountStructure_CT(controller1);
        AccountStructure_CT asct2 = new AccountStructure_CT('test'); 
        
        system.assertEquals(asct.ExclusionList, false);
        
        asct.userEmailCc='xyz@officedepot.com.uat';
        asct1.userEmailCc='xyz@officedepot.com.uat;abc@officedepot.com.uat';
        
        asct1.asm = null;
        asct1.getObjectStructure();
        
        system.assertnotEquals(asct1.asm, null);
        
        asct1.setcurrentId(String.valueOf(acc.id));
        asct1.IdTreeNodeForAction='0';
        asct1.NodeStatus='';
        asct1.updateTree();
        List<String> cn1 = new List<String>();
        List<String> nn1 = new List<String>();
        cn1.add('0');
        cn1.add('1');
        nn1.add('0');
        nn1.add('1');
        
        String nodeType ='child';
        asct1.setlevelFlag( nn1,nodeType);
        asct1.setcloseFlag(cn1,nn1,nodeType);
        asct1.isLastNode( nn1);
        asct1.ExclusionList=false;
        asct1.GetTopElement(String.valueOf(acc.id));
        asct1.ExclusionList=true;
        asct1.getEmailList(0,1);
        asct1.createNewBody();
        
        asct1.accountMap.put(pacc.id,pacc);
        PageReference pf = asct1.sendEmail();
        asct1.CreateActivity();
        
        ApexPages.currentPage().getParameters().put(pacc.id, '1');
        asct1.accountMap.put(pacc.id,pacc);
        PageReference pf0 = asct1.selectedAccounts();
        asct1.CreateActivity();
        asct1.getEmailList(0,1);
        
        Account accountInfo = new Account();
        accountInfo = (new List<Account>([select id, owner.email,name, recordtypeid, BillingStreet, billingcity, BillingState, Billingcountry, Oracle_Party_Id__c, omx_primary_key__C, Split_Record__c, status__c, address1__C, OMX_Mainframe_Account_Number__c, Segment__c, Sales_PersonID__c  from Account where id =:pacc.id]))[0];
        
        ApexPages.currentPage().getParameters().put(pacc.id, '1');
        asct1.accountMap.put(pacc.id,accountInfo);
        PageReference pf1 = asct1.selectedAccounts();
        List<SelectOption> ops1 =  asct1.getUsers();
        asct1.CreateActivity();
        asct1.getEmailList(0,1);
        
        asct1.getEmailList(0,2);
        
        PageReference pf2 = asct1.LaunchSelected();
        
        system.assertNotEquals(pf2, null);
        
        PageReference pf3 = asct1.BackToAccountHierarchy();
        List<SelectOption> ops =  asct1.getUsers();
        String str = asct1.getSelectedUsers();
        asct1.setSelectedUsers(str);
        
        List<Boolean> bn= new List<Boolean>();
        bn.add(true);
        AccountStructure_CT.ObjectStructureMap wrap = new AccountStructure_CT.ObjectStructureMap( '0', bn,bn ,'child', true, true, CT );
        wrap.getnodeId();
        wrap.getlevelFlag();
        wrap.getcloseFlag();
        wrap.getnodeType();
        wrap.getcurrentNode();
        Customer_Transition__c ctt = wrap.getaccount();
        wrap.setnodeId('test');
        wrap.setlevelFlag(true);
        wrap.setlcloseFlag(true);
        wrap.setnodeType('test');
        wrap.setcurrentNode(true);
        wrap.setaccount(ctt);
        
        AccountStructure_CT.WrapErrors wrapError = new AccountStructure_CT.WrapErrors('123456@@:@@SUN Test Account@@:@@Account Owner is not Active');
        wrapError.getomxPrimaryKey();
        wrapError.getaccName();
        wrapError.getreason();

        Test.setCurrentPage(Page.Account_Hierarchy_Page_CT);
        ApexPages.CurrentPage().getParameters().put('EL','Y');
        ApexPages.CurrentPage().getParameters().put(pacc.id,'1');
        asct1.accountMap.put(pacc.id,pacc);
        PageReference pf5 = asct1.LaunchSelected();
        
        system.assertNotEquals(pf5, null);
        
        
        
    }*/
    // Added for the story #S-355233 #END
}