objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer Accounts</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>GrandParent</fullName>
        <active>true</active>
        <description>Used for GP Maintenance</description>
        <label>GrandParent</label>
    </recordTypes>
    <recordTypes>
        <fullName>Parent</fullName>
        <active>true</active>
        <label>Parent</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Customer_Transition__c.object
<CustomObject>
    <description>Object to Track Customer Conversion and Review Project</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Transition Relationship</relationshipLabel>
        <relationshipName>Customer_Transition_Relationship</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Transition_Type2__c</fullName>
        <formula>IF(LEFT(Name ,35) == &apos;Customer Transition Grandparent of &apos;,&apos;Grandparent&apos;,
IF(LEFT(Name ,30) == &apos;Customer Transition Parent of &apos;,&apos;Parent&apos;,
IF(LEFT(Name ,41) == &apos;Customer Transition Great Grandparent of &apos;,&apos;Great Grandparent&apos;,
IF(Parent__c !=NULL,&apos;Child&apos;,&apos;Standalone&apos;))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Transition Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enterprise_Account_Owner_Email__c</fullName>
        <label>Enterprise Account Owner Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Enterprise_Account_Owner__c</fullName>
        <label>Enterprise Account Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enterprise_Managing_Director_Email__c</fullName>
        <label>Enterprise Managing Director Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Enterprise_Managing_Director__c</fullName>
        <label>Enterprise Managing Director</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enterprise_RVP_Emai__c</fullName>
        <label>Enterprise RVP Emai</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Enterprise_RVP__c</fullName>
        <label>Enterprise RVP</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Customer Transition</label>
    <nameField>
        <label>Customer Transition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Transition</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/BatchUpdateCustomerTransition.cls
// (c) 2016 Appirio, Inc.
//
// Batch class to update three fields on the Customer Transition Object each day
//
// 6 Oct 2016     Luke Slevin       Original S-440213/S-440215

global class BatchUpdateCustomerTransition implements Database.Batchable<sObject> {

    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query =  'SELECT Id, Enterprise_Account_Owner_Email__c,Enterprise_Managing_Director_Email__c,Enterprise_RVP_Emai__c,'+
                        'Enterprise_Account_Owner__c,Enterprise_Managing_Director__c,Enterprise_RVP__c,'+
                        'Customer_Transition_Type2__c,Account__r.Owner.Email, Account__r.Parent.Owner.Email,'+
                        'Account__r.Parent.Parent.Owner.Email, Account__r.Owner.Manager.Email,Account__r.Parent.Owner.Manager.Email,'+
                        'Account__r.Parent.Parent.Owner.Manager.Email,Account__r.Owner.Manager.Manager.Email,Account__r.Parent.Owner.Manager.Manager.Email,'+
                        'Account__r.Parent.Parent.Owner.Manager.Manager.Email,Account__r.Owner.Name,Account__r.Owner.Manager.Name,Account__r.Owner.Manager.Manager.Name '+
                        'FROM Customer_Transition__c';
        return Database.getQueryLocator(query);

    }

    global void execute(Database.BatchableContext BC, List<Customer_Transition__c> scope) {

        for(Customer_Transition__c ct : scope)  {
            if(ct.Customer_Transition_Type2__c == 'Grandparent')    {
                ct.Enterprise_Account_Owner_Email__c = ct.Account__r.Owner.Email;
                ct.Enterprise_Account_Owner__c = ct.Account__r.Owner.Name;
            }
            else if(ct.Customer_Transition_Type2__c == 'Parent')    {
                ct.Enterprise_Account_Owner_Email__c = ct.Account__r.Parent.Owner.Email;
                ct.Enterprise_Account_Owner__c = ct.Account__r.Owner.Name;
            }
            else if(ct.Customer_Transition_Type2__c == 'Child') {
                ct.Enterprise_Account_Owner_Email__c = ct.Account__r.Parent.Parent.Owner.Email;
                ct.Enterprise_Account_Owner__c = ct.Account__r.Owner.Name;
            }
            else    {
                ct.Enterprise_Account_Owner_Email__c = '';
                ct.Enterprise_Account_Owner__c = '';
            }

            if (ct.Customer_Transition_Type2__c == 'Grandparent')   {
                ct.Enterprise_Managing_Director_Email__c = ct.Account__r.Owner.Manager.Email;
                ct.Enterprise_Managing_Director__c = ct.Account__r.Owner.Manager.Name;
            }
            else if (ct.Customer_Transition_Type2__c == 'Parent')   {
                ct.Enterprise_Managing_Director_Email__c = ct.Account__r.Parent.Owner.Manager.Email;
                ct.Enterprise_Managing_Director__c = ct.Account__r.Owner.Manager.Name;
            }
            else if (ct.Customer_Transition_Type2__c == 'Child')    {
                ct.Enterprise_Managing_Director_Email__c = ct.Account__r.Parent.Parent.Owner.Manager.Email;
                ct.Enterprise_Managing_Director__c = ct.Account__r.Owner.Manager.Name;
            }
            else    {
                ct.Enterprise_Managing_Director_Email__c = '';
                ct.Enterprise_Managing_Director__c = '';
            }

            if (ct.Customer_Transition_Type2__c == 'Grandparent')   {
                ct.Enterprise_RVP_Emai__c = ct.Account__r.Owner.Manager.Manager.Email;
                ct.Enterprise_RVP__c = ct.Account__r.Owner.Manager.Manager.Name;
            }
            else if (ct.Customer_Transition_Type2__c == 'Parent')   {
                ct.Enterprise_RVP_Emai__c = ct.Account__r.Parent.Owner.Manager.Manager.Email;
                ct.Enterprise_RVP__c = ct.Account__r.Owner.Manager.Manager.Name;
            }
            else if (ct.Customer_Transition_Type2__c == 'Child')    {
                ct.Enterprise_RVP_Emai__c = ct.Account__r.Parent.Parent.Owner.Manager.Manager.Email;
                ct.Enterprise_RVP__c = ct.Account__r.Owner.Manager.Manager.Name;
            }
            else    {
                ct.Enterprise_RVP_Emai__c  = '';
                ct.Enterprise_RVP__c = '';
            }
        }
        update scope;
    }

    global void finish(Database.BatchableContext BC) {

    }

}