objects/Account.object
<CustomObject>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sales_PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is used for Primary Owner Sales ID.</description>
        <label>Sales Person ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sales_Person__c.Primary__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Person__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <inlineHelpText>Small is less than 30 Employees</inlineHelpText>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Sector__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Small &lt; $10K</fullName>
                </value>
                <value>
                    <fullName>Small $10K-$75K</fullName>
                </value>
                <value>
                    <fullName>Medium $75K-$150K</fullName>
                </value>
                <value>
                    <fullName>Standard $150K-$250K</fullName>
                </value>
                <value>
                    <fullName>Key $250K-$500K</fullName>
                </value>
                <value>
                    <fullName>Major $500K-$1M</fullName>
                </value>
                <value>
                    <fullName>K-12</fullName>
                </value>
                <value>
                    <fullName>Higher-Ed</fullName>
                </value>
                <value>
                    <fullName>Federal</fullName>
                </value>
                <value>
                    <fullName>State</fullName>
                </value>
                <value>
                    <fullName>Local</fullName>
                </value>
                <value>
                    <fullName>Non-Profit</fullName>
                </value>
                <value>
                    <fullName>Enterprise $1M+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer Accounts</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Parent</fullName>
        <active>true</active>
        <label>Parent</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Customer_Transition__c.object
<CustomObject>
    <description>Object to Track Customer Conversion and Review Project</description>
    <fields>
        <fullName>Account_Splitting_Required_frmla__c</fullName>
        <formula>IF(
OR(Billing_Frequency_Excptn__c,Billing_Document_Type_Excptn__c,Payment_Terms_Excptn__c,AB_Flag_Disparate__c,Billing_Method_Exception__c  ,Billing_Method_Not_PE__c ,Consignees_have_disparate_credit_limits__c)  &amp;&amp; AOPS_Flag__c==&apos;Y&apos; &amp;&amp; No_of_Active_Sites__c &gt;1  &amp;&amp;  text(Final_Split_Decision__c) ==&apos;&apos;, 
&apos;Yes&apos;,

IF(
OR(Billing_Frequency_Excptn__c,Billing_Document_Type_Excptn__c,Payment_Terms_Excptn__c,AB_Flag_Disparate__c,Billing_Method_Exception__c  ,Billing_Method_Not_PE__c ,Consignees_have_disparate_credit_limits__c)  &amp;&amp; AOPS_Flag__c==&apos;Y&apos;   &amp;&amp; No_of_Active_Sites__c &gt;1 &amp;&amp; text(Final_Split_Decision__c) ==&apos;No&apos;, 
&apos;Yes&apos;,


IF(
OR(Billing_Frequency_Excptn__c,Billing_Document_Type_Excptn__c,Payment_Terms_Excptn__c,AB_Flag_Disparate__c,Billing_Method_Exception__c  ,Billing_Method_Not_PE__c ,Consignees_have_disparate_credit_limits__c)  &amp;&amp; AOPS_Flag__c==&apos;Y&apos;   &amp;&amp;   text(Final_Split_Decision__c) ==&apos;Yes&apos;, 
&apos;Yes&apos;,

&apos;No&apos;
)
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Splitting Required?</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Transition Relationship</relationshipLabel>
        <relationshipName>Customer_Transition_Relationship</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Transition_Type__c</fullName>
        <formula>IF(LEFT(Name ,35) == &apos;Customer Transition Grandparent of &apos;,&apos;Grandparent&apos;,
IF(LEFT(Name ,30) == &apos;Customer Transition Parent of &apos;,&apos;Parent&apos;,
IF(LEFT(Name ,41) == &apos;Customer Transition Great Grandparent of &apos;,&apos;Great Grandparent&apos;,&apos;Child&apos;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Transition Type Internal</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Final_Split_Decision__c</fullName>
        <description>If the “final split decision” box is set to “yes” – Mod 5 will run and then Mod 1 will run 
If the “final split decision” box is set to “no” – Mod 5 will be bypassed and Mod 1 will run as normal</description>
        <inlineHelpText>“Blank” – Mod 5 and Mod 1 cannot run 
&quot;Yes” – Mod 5 will run and then Mod 1 will run 
&quot;No” – Mod 5 will be bypassed and Mod 1 will run as normal</inlineHelpText>
        <label>Final Split Decision</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Parent_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Parent Name on the Account object</description>
        <label>Parent Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Transition (Account)</relationshipLabel>
        <relationshipName>Customer_Transition</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Transition_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Transition</label>
        <referenceTo>Customer_Transition__c</referenceTo>
        <relationshipLabel>Child Account Transitions</relationshipLabel>
        <relationshipName>Parent_Transition</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ready_for_Mod1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ready for Account Setup/Mod 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field will update dynamically per your selections.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>UnScheduled</fullName>
                    <color>#0B6FCE</color>
                    <default>true</default>
                    <label>UnScheduled</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                    <color>#78C953</color>
                    <label>Scheduled</label>
                </value>
                <value>
                    <fullName>ReScheduled</fullName>
                    <color>#E27001</color>
                    <label>ReScheduled</label>
                </value>
                <value>
                    <fullName>On Deck</fullName>
                    <color>#F3D904</color>
                    <label>On Deck</label>
                </value>
                <value>
                    <fullName>Launched</fullName>
                    <color>#009900</color>
                    <label>Launched</label>
                </value>
                <value>
                    <fullName>Transition Complete</fullName>
                    <color>#A53711</color>
                    <label>Transition Complete</label>
                </value>
                <value>
                    <fullName>Audit 2</fullName>
                    <color>#66E9BD</color>
                    <label>Audit 2</label>
                </value>
                <value>
                    <fullName>Loss of Customer</fullName>
                    <color>#0B24BE</color>
                    <label>Loss of Customer</label>
                </value>
                <value>
                    <fullName>OMX Extension in Development</fullName>
                    <color>#419249</color>
                    <label>OMX Extension in Development</label>
                </value>
                <value>
                    <fullName>Ready to Order</fullName>
                    <color>#B6E32E</color>
                    <label>Ready to Order</label>
                </value>
                <value>
                    <fullName>Ready for eCom Mod</fullName>
                    <color>#641CCF</color>
                    <label>Ready for eCom Mod</label>
                </value>
                <value>
                    <fullName>Redirect Stopped</fullName>
                    <color>#F96FB7</color>
                    <label>Redirect Stopped</label>
                </value>
                <value>
                    <fullName>Auto Redirected</fullName>
                    <color>#2F5D85</color>
                    <label>Auto Redirected</label>
                </value>
                <value>
                    <fullName>Awaiting Disposition</fullName>
                    <color>#AFCADF</color>
                    <label>Awaiting Disposition</label>
                </value>
                <value>
                    <fullName>Awaiting RFP</fullName>
                    <color>#8F6429</color>
                    <label>Awaiting RFP</label>
                </value>
                <value>
                    <fullName>Administrative Close</fullName>
                    <color>#EFAE73</color>
                    <label>Administrative Close</label>
                </value>
                <value>
                    <fullName>TOOP</fullName>
                    <color>#F96FB7</color>
                    <label>TOOP</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Written_Agreement_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Written Agreement Customer Level ID</label>
        <referenceTo>Customer_Transition__c</referenceTo>
        <relationshipLabel>Customer Transition (Written Agreement Customer Level)</relationshipLabel>
        <relationshipName>Customer_Transition</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Transition</label>
    <nameField>
        <label>Customer Transition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Transition</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Transition_Launch__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Transition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Transition</label>
        <referenceTo>Customer_Transition__c</referenceTo>
        <relationshipLabel>Transition Launch</relationshipLabel>
        <relationshipName>Transition_Launch</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OMX_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Key</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Mod 1 Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Fail</fullName>
                </value>
                <value>
                    <fullName>ReSubmit</fullName>
                </value>
                <value>
                    <fullName>Submit</fullName>
                    <default>true</default>
                    <label>Submit</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TYpe__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Parent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transition Launch</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Transition Launch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transition Launch</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TransLaunchBatchClass.cls
// This class is to Auto Launch the list of Records Loaded in the Transition Launch Object
Global class TransLaunchBatchClass   implements database.Batchable<Sobject>,Database.Stateful,Schedulable
{

    global String strQuery; //this variable used to set query from test class or from shceduler if required

      public Integer countParent=0;
      public String DEFAULT_QUERY;

    /* Default Constructor*/
    global TransLaunchBatchClass   ()
    {
    // Parents are Launched first and then the child
    countParent=  [select count() from Transition_Launch__c where TYpe__c = 'Parent' and
    (Status__c = 'Submit' or Status__c = 'ReSubmit')];

    System.debug('&&&&&&&&&&&&&&countParent'+countParent);
    if(countParent>0){

     DEFAULT_QUERY ='Select OMX_Key__c'
                                   +' FROM Transition_Launch__c'
                                   +' WHERE TYpe__c = \'Parent\'  and   (Status__c = \'Submit\' or Status__c = \'ReSubmit\' ) Limit 500';
    }

    else{
         DEFAULT_QUERY ='Select OMX_Key__c'
                                   +' FROM Transition_Launch__c'
                                   +' WHERE TYpe__c = null  and   (Status__c = \'Submit\' or Status__c = \'ReSubmit\' ) Limit 500';

    }


        this.strQuery = DEFAULT_QUERY;
    }
    /*This costructor is called from the Batch Schedule method*/
    global TransLaunchBatchClass   (String query)
    {
        System.debug('QUERY IS---->'+query);
        if(query != null && query != '')
        {
            this.strQuery = query;
        }
        else
        {
            this.strQuery = DEFAULT_QUERY;
        }
    system.debug('strQuery@@@'+strQuery);
    }
    /* This method prepares the scope of the batch program based on the query result */
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        system.debug('strQuery@@@'+strQuery);
        return Database.getQueryLocator(strQuery);
    }
     /* This method processes query result in batches */
    global void execute(Database.BatchableContext BC, SObject[] scope)
    {
        List<Transition_Launch__c> splitrecs = scope;
        List<String> accomxid= new List<String>();
         Set<String> accomxidChild= new Set<String>();
          System.debug('&&&&&&&&&&'+splitrecs);
          if(splitrecs.size()>0){
                  for(Transition_Launch__c sad : splitrecs){
                    accomxid.add(sad.OMX_Key__c);
                  }
           }

                  String ParentError=' ';
                  String OriginalAccountError=' ';

               List<Customer_transition__C > custList= new   List<Customer_transition__C >();
               List<Transition_Launch__c  > transList = new List<Transition_Launch__c  >();
 // Processing the errors
                         for(Transition_Launch__c  sadtls : [Select Id,
                                                Customer_Transition__r.Parent_Transition_ID__c,
                                                Customer_Transition__r.Parent_Transition_ID__r.Customer_Transition_Type__c,
                                                Customer_Transition__r.Parent_Transition_ID__r.omx_primary_key__C,
                                                Customer_Transition__r.Parent_Transition_ID__r.Ready_for_Mod1__c,
                                                Customer_Transition__r.Parent_Transition_ID__r.Final_Split_Decision__c,
                                                Customer_Transition__r.Parent_Transition_ID__r.account__r.ownerId,
                                                Customer_Transition__r.Parent_Transition_ID__r.account__r.owner.IsActive,
                                                Customer_Transition__r.Parent_Transition_ID__r.Account_Splitting_Required_frmla__c,
                                                Customer_Transition__r.Parent_Transition_ID__r.account__r.status__c,
                                                Customer_Transition__r.Parent_Transition_ID__r.account__r.Sales_PersonID__c,
                                                Customer_Transition__r.Parent_Transition_ID__r.Account__r.Segment__c,
                                                Customer_Transition__r.Parent_Transition_ID__r.account__r.Sales_PersonID__r.name,
                                                Customer_Transition__r.Parent_Transition_ID__r.account__r.OMX_Mainframe_Account_Level__c,
                                                Customer_Transition__r.Parent_Transition_ID__r.AOPS_Flag__c,
                                                Customer_Transition__r.Parent_Transition_ID__r.status__C,
                                                Customer_Transition__r.Parent_Transition_ID__r.transition_status__C,
                                                Customer_Transition__r.Parent_Transition_ID__r.Written_Agreement_Customer_No__c,
                                                Customer_Transition__r.Parent_Transition_ID__r.account__R.split_record__C,
                                                Customer_Transition__r.Parent_Transition_ID__r.Override_Loss_of_Customer__c ,               // case number 00658908
                                                Customer_Transition__r.Parent_Transition_ID__r.Customer_Transition_Type2__c,                //Added for Case# 00674130
                                                Customer_Transition__r.Parent_Transition_ID__r.Written_Agreement__c,                        //Added for Case# 00674130
                                                Customer_Transition__r.Parent_Transition_ID__r.Local_Core__c,                               //Added for Case# 00674130
                                                Customer_Transition__r.Parent_Transition_ID__r.Written_Agreement_Custom_Core_Request__c,    //Added for Case# 00674130
                                                Customer_Transition__r.Parent_Transition_ID__r.Override_Administrative_close__c,
                                                Customer_Transition__r.Override_Administrative_close__c,
                                              
                                                Customer_Transition__c,Customer_Transition__r.omx_primary_key__C,
                                                Customer_Transition__r.Ready_for_Mod1__c, Customer_Transition__r.Final_Split_Decision__c,
                                                Customer_Transition__r.account__r.ownerId,
                                                Customer_Transition__r.account__r.owner.IsActive,
                                                Customer_Transition__r.Account_Splitting_Required_frmla__c,Customer_Transition__r.account__r.status__c,
                                                Customer_Transition__r.account__r.Sales_PersonID__c,
                                                Customer_Transition__r.Account__r.Segment__c,
                                                Customer_Transition__r.account__r.Sales_PersonID__r.name,
                                                Customer_Transition__r.account__r.OMX_Mainframe_Account_Level__c,
                                                Customer_Transition__r.AOPS_Flag__c,
                                                Customer_Transition__r.status__C,
                                                Customer_Transition__r.transition_status__C,
                                                Customer_Transition__r.Written_Agreement_Customer_No__c,
                                                Customer_Transition__r.account__R.split_record__C,
                                                Customer_Transition__r.Override_Loss_of_Customer__c ,                   // case number 00658908
                                                Customer_Transition__r.Customer_Transition_Type2__c,                     //Added for Case# 00674130
                                                Customer_Transition__r.Written_Agreement__c,                            //Added for Case# 00674130
                                                Customer_Transition__r.Local_Core__c,                                   //Added for Case# 00674130
                                                Customer_Transition__r.Written_Agreement_Custom_Core_Request__c,       //Added for Case# 00674130
                                               OMX_Key__c,status__c
                                               FROM Transition_Launch__c
                                               WHERE OMX_Key__c in  :accomxid]){


                          ParentError=' ';
                          OriginalAccountError=' ';


                                  // For Checking Parent
                                                if(sadtls.Customer_Transition__r.Parent_Transition_ID__c !=null && sadtls.Customer_Transition__r.Parent_Transition_ID__r.Ready_for_Mod1__c==false && ParentError  ==' '  &&  sadtls.Customer_Transition__r.Parent_Transition_ID__r.Customer_Transition_Type__c=='Parent'){


                                                        if(  (sadtls.Customer_Transition__r.Parent_Transition_ID__r.Status__c !='On Deck'   &&  sadtls.Customer_Transition__r.Parent_Transition_ID__r.Written_Agreement_Customer_No__c==null)
                                                             ||
                                                          (sadtls.Customer_Transition__r.Parent_Transition_ID__r.Written_Agreement_Customer_No__c!=null &&

                                                                  sadtls.Customer_Transition__r.Parent_Transition_ID__r.status__c != 'ODP Agreement in Development'
                                                                  && sadtls.Customer_Transition__r.Parent_Transition_ID__r.status__c != 'OMX Extension in Development'
                                                                  && sadtls.Customer_Transition__r.Parent_Transition_ID__r.status__c != 'ODP Agreement Complete'
                                                                   && sadtls.Customer_Transition__r.Parent_Transition_ID__r.status__c != 'On Deck'
                                                                  ) &&
                                                                  (!(sadtls.Customer_Transition__r.Parent_Transition_ID__r.Status__c =='Administrative Close'  && sadtls.Customer_Transition__r.Parent_Transition_ID__r.Override_Administrative_close__c == true))
                                                                   //Start Changes for Case No 00658908
                                                                  &&(!(sadtls.Customer_Transition__r.Parent_Transition_ID__r.status__c == 'Loss of Customer' && sadtls.Customer_Transition__r.Parent_Transition_ID__r.Override_Loss_of_Customer__c == true))
                                                                  //End Changes for Case No 00658908

                                                         )
                                                        ParentError  =ParentError  +sadtls.Customer_Transition__r.Parent_Transition_ID__r.omx_primary_key__C+ ' Not in Valid status for Launching' + ' , ' ;


                                                        if(sadtls.Customer_Transition__r.Parent_Transition_ID__r.account__r.Sales_PersonID__c==null)
                                                        ParentError  =ParentError  +sadtls.Customer_Transition__r.Parent_Transition_ID__r.omx_primary_key__C+ ' Sales Person ID is \'NULL\'' + ' , ' ;


                                                        if(sadtls.Customer_Transition__r.Parent_Transition_ID__r.account__r.Sales_PersonID__r.name=='Awaiting SalesID' || sadtls.Customer_Transition__r.Parent_Transition_ID__r.account__r.Sales_PersonID__r.name=='D7873'   )
                                                        ParentError  =ParentError  +sadtls.Customer_Transition__r.Parent_Transition_ID__r.omx_primary_key__C+ ' Sales Person ID is \'INVALID\'' + ' , ' ;


                                                        if(sadtls.Customer_Transition__r.Parent_Transition_ID__r.account__r.status__c !='Active')
                                                        ParentError  =ParentError  +sadtls.Customer_Transition__r.Parent_Transition_ID__r.omx_primary_key__C+' Account is not Active' + ' , ' ;

                                                        if(sadtls.Customer_Transition__r.Parent_Transition_ID__r.account__r.owner.IsActive !=true)
                                                        ParentError  =ParentError  +sadtls.Customer_Transition__r.Parent_Transition_ID__r.omx_primary_key__C+ ' Account Owner is not Active' + ' , ' ;


                                                        if((sadtls.Customer_Transition__r.Parent_Transition_ID__r.account__r.OMX_Mainframe_Account_Level__c == 'Main Account')
                                                        &&(sadtls.Customer_Transition__r.Parent_Transition_ID__r.Transition_Status__c !='Active'))
                                                        ParentError  =ParentError  +sadtls.Customer_Transition__r.Parent_Transition_ID__r.omx_primary_key__C+ ' Transition Status is not Active' + ' , ' ;


                                                        if ((sadtls.Customer_Transition__r.Parent_Transition_ID__r.Final_Split_Decision__c ==''  || sadtls.Customer_Transition__r.Parent_Transition_ID__r.Final_Split_Decision__c ==null ) &&   sadtls.Customer_Transition__r.Parent_Transition_ID__r.Account_Splitting_Required_frmla__c=='Yes')
                                                        ParentError  =ParentError  +sadtls.Customer_Transition__r.Parent_Transition_ID__r.omx_primary_key__C+' Final Split Decision is \'Blank\''+' , ' ;


                                                         if ((sadtls.Customer_Transition__r.Parent_Transition_ID__r.Final_Split_Decision__c =='Yes'   ||  sadtls.Customer_Transition__r.Parent_Transition_ID__r.account__R.split_record__C==true) )
                                                        ParentError  =ParentError  +sadtls.Customer_Transition__r.Parent_Transition_ID__r.omx_primary_key__C+'Split Record can be Launched only through Mod 5 process'+' , ' ;


                                                        if((sadtls.Customer_Transition__r.Parent_Transition_ID__r.account__r.OMX_Mainframe_Account_Level__c == 'Main Account')
                                                        &&(sadtls.Customer_Transition__r.Parent_Transition_ID__r.AOPS_Flag__c!='Y'))
                                                        ParentError  =ParentError  +sadtls.Customer_Transition__r.Parent_Transition_ID__r.omx_primary_key__C+ ' AOPS Flag is not \'Y\'' + ' , ' ;


                                                        if(sadtls.Customer_Transition__r.Parent_Transition_ID__r.Account__r.Segment__c==null)
                                                        ParentError  =ParentError  +sadtls.Customer_Transition__r.Parent_Transition_ID__r.omx_primary_key__C+' Segment is \'NULL\'' + ' , ' ;


                                                        if(sadtls.Customer_Transition__r.Parent_Transition_ID__r.Account__r.Segment__c=='Other')
                                                        ParentError  =ParentError  +sadtls.Customer_Transition__r.Parent_Transition_ID__r.omx_primary_key__C+' Segment is \'Other\'' + ' , ' ;


                                                        if(string.valueof(sadtls.Customer_Transition__r.Parent_Transition_ID__r.Account__r.ownerid).substring(0,15)==System.Label.salesforce)
                                                        ParentError  =ParentError  +sadtls.Customer_Transition__r.Parent_Transition_ID__r.omx_primary_key__C+' Owner is \'Salesforce\'' + ' , ' ;

                                                        if(string.valueof(sadtls.Customer_Transition__r.Parent_Transition_ID__r.Account__r.ownerid).substring(0,15)==System.Label.SalesforceDataloaderNorth)
                                                        ParentError  =ParentError  +sadtls.Customer_Transition__r.Parent_Transition_ID__r.omx_primary_key__C+' Owner is \'Salesforce DataLoader North\'' + ' , ' ;

                                                        //Added for Case# 00674130
                                                        if((sadtls.Customer_Transition__r.Parent_Transition_ID__r.Customer_Transition_Type2__c == 'Standalone' || sadtls.Customer_Transition__r.Parent_Transition_ID__r.Customer_Transition_Type2__c == 'Child') && sadtls.Customer_Transition__r.Parent_Transition_ID__r.Written_Agreement__c == true && sadtls.Customer_Transition__r.Parent_Transition_ID__r.Local_Core__c == true && (sadtls.Customer_Transition__r.Parent_Transition_ID__r.Written_Agreement_Custom_Core_Request__c == '' || sadtls.Customer_Transition__r.Parent_Transition_ID__r.Written_Agreement_Custom_Core_Request__c == null) )
                                                        ParentError=ParentError+'Written Agreement Custom Core Request is required' + ' , ' ;


                                                  }


                                             System.debug('&&&&&&&&ParentError  '+ParentError  );

                                               // for Original Account

                                               if(sadtls.Customer_Transition__c !=null && sadtls.Customer_Transition__r.Ready_for_Mod1__c==false && OriginalAccountError  ==' '){




                                                                        if( (sadtls.Customer_Transition__r.Status__c !='On Deck'   &&  sadtls.Customer_Transition__r.Written_Agreement_Customer_No__c==null)
                                                                             ||
                                                                          (sadtls.Customer_Transition__r.Written_Agreement_Customer_No__c!=null &&

                                                                                  sadtls.Customer_Transition__r.status__c != 'ODP Agreement in Development'
                                                                                  && sadtls.Customer_Transition__r.status__c != 'OMX Extension in Development'
                                                                                  && sadtls.Customer_Transition__r.status__c != 'ODP Agreement Complete'
                                                                                  && sadtls.Customer_Transition__r.status__c != 'On Deck'
                                                                                  ) &&

                                                                                 (!(sadtls.Customer_Transition__r.Status__c =='Administrative Close'  && sadtls.Customer_Transition__r.Override_Administrative_close__c == true))
                                                                                 //Start Changes for Case No 00658908
                                                                               &&
                                                                                (!(sadtls.Customer_Transition__r.status__c == 'Loss of Customer' && sadtls.Customer_Transition__r.Override_Loss_of_Customer__c == true))
                                                                                //End Changes for Case No 00658908


                                                                         )
                                                                        OriginalAccountError  =OriginalAccountError  +sadtls.Customer_Transition__r.omx_primary_key__C+ ' Not in Valid status for Launching' + ' , ' ;


                                                                        if(sadtls.Customer_Transition__r.account__r.Sales_PersonID__c==null)
                                                                        OriginalAccountError  =OriginalAccountError  +sadtls.Customer_Transition__r.omx_primary_key__C+ ' Sales Person ID is \'NULL\'' + ' , ' ;


                                                                        if(sadtls.Customer_Transition__r.account__r.Sales_PersonID__r.name=='Awaiting SalesID' || sadtls.Customer_Transition__r.account__r.Sales_PersonID__r.name=='D7873'   )
                                                                        OriginalAccountError  =OriginalAccountError  +sadtls.Customer_Transition__r.omx_primary_key__C+ ' Sales Person ID is \'INVALID\'' + ' , ' ;


                                                                        if(sadtls.Customer_Transition__r.account__r.status__c !='Active')
                                                                        OriginalAccountError  =OriginalAccountError  +sadtls.Customer_Transition__r.omx_primary_key__C+' Account is not Active' + ' , ' ;

                                                                         System.debug('&&&&&&&&&&&sadtls.Customer_Transition__r.account__r.owner.IsActive'+sadtls.Customer_Transition__r.account__r.owner.IsActive);

                                                                        if(sadtls.Customer_Transition__r.account__r.owner.IsActive !=true)
                                                                        OriginalAccountError  =OriginalAccountError  +sadtls.Customer_Transition__r.omx_primary_key__C+ ' Account Owner is not Active' + ' , ' ;


                                                                        if((sadtls.Customer_Transition__r.account__r.OMX_Mainframe_Account_Level__c == 'Main Account')
                                                                        &&(sadtls.Customer_Transition__r.Transition_Status__c !='Active'))
                                                                        OriginalAccountError  =OriginalAccountError  +sadtls.Customer_Transition__r.omx_primary_key__C+ ' Transition Status is not Active' + ' , ' ;


                                                                        if ((sadtls.Customer_Transition__r.Final_Split_Decision__c ==''  || sadtls.Customer_Transition__r.Final_Split_Decision__c ==null ) &&   sadtls.Customer_Transition__r.Account_Splitting_Required_frmla__c=='Yes')
                                                                        OriginalAccountError  =OriginalAccountError  +sadtls.Customer_Transition__r.omx_primary_key__C+' Final Split Decision is \'Blank\''+' , ' ;


                                                                         if ((sadtls.Customer_Transition__r.Final_Split_Decision__c =='Yes'   ||  sadtls.Customer_Transition__r.account__R.split_record__C==true) )
                                                                         ParentError  =ParentError  +sadtls.Customer_Transition__r.omx_primary_key__C+'Split Record can be Launched only through Mod 5 process'+' , ' ;



                                                                        if((sadtls.Customer_Transition__r.account__r.OMX_Mainframe_Account_Level__c == 'Main Account')
                                                                        &&(sadtls.Customer_Transition__r.AOPS_Flag__c!='Y'))
                                                                        OriginalAccountError  =OriginalAccountError  +sadtls.Customer_Transition__r.omx_primary_key__C+ ' AOPS Flag is not \'Y\'' + ' , ' ;


                                                                        if(sadtls.Customer_Transition__r.Account__r.Segment__c==null)
                                                                        OriginalAccountError  =OriginalAccountError  +sadtls.Customer_Transition__r.omx_primary_key__C+' Segment is \'NULL\'' + ' , ' ;


                                                                        if(sadtls.Customer_Transition__r.Account__r.Segment__c=='Other')
                                                                        OriginalAccountError  =OriginalAccountError  +sadtls.Customer_Transition__r.omx_primary_key__C+' Segment is \'Other\'' + ' , ' ;


                                                                        if(string.valueof(sadtls.Customer_Transition__r.Account__r.ownerid).substring(0,15)==System.Label.salesforce)
                                                                        OriginalAccountError  =OriginalAccountError  +sadtls.Customer_Transition__r.omx_primary_key__C+' Owner is \'Salesforce\'' + ' , ' ;

                                                                        if(string.valueof(sadtls.Customer_Transition__r.Account__r.ownerid).substring(0,15)==System.Label.SalesforceDataloaderNorth)
                                                                        OriginalAccountError  =OriginalAccountError  +sadtls.Customer_Transition__r.omx_primary_key__C+' Owner is \'Salesforce DataLoader North\'' + ' , ' ;

                                                                         //Added for Case# 00674130
                                                                        if((sadtls.Customer_Transition__r.Customer_Transition_Type2__c == 'Standalone' || sadtls.Customer_Transition__r.Customer_Transition_Type2__c == 'Child') && sadtls.Customer_Transition__r.Written_Agreement__c == true && sadtls.Customer_Transition__r.Local_Core__c == true && (sadtls.Customer_Transition__r.Written_Agreement_Custom_Core_Request__c == '' || sadtls.Customer_Transition__r.Written_Agreement_Custom_Core_Request__c == null) )
                                                                        OriginalAccountError=OriginalAccountError+'Written Agreement Custom Core Request is required' + ' , ' ;


                                                  }



                                if(  ParentError==' ' &&  OriginalAccountError==' '){
                                       Customer_transition__C custNew= new Customer_transition__C ();
                                       custNew.Id=sadtls.Customer_Transition__c;
                                       custNew.Ready_for_Mod1__c=true;
                                       //custNew.EBS_Populated_Date__c=System.Today();
                                       custList.add(custNew);
                                       Transition_Launch__c  trans = new Transition_Launch__c ();
                                       trans.Id= sadtls.Id;
                                       trans.Status__c='Success';
                                       trans.Error_Message__c=null;
                                       transList.add(trans );
                               }
                               else{

                               System.debug('&&&&&&&&&&&ParentError'+ParentError);
                                System.debug('&&&&&&&&&&&OriginalAccountError'+OriginalAccountError);
                                       Transition_Launch__c  trans = new Transition_Launch__c ();
                                       trans.Id= sadtls.Id;
                                       trans.Status__c='Fail';
                                       trans.Error_Message__c=ParentError+OriginalAccountError;
                                       transList.add(trans );
                               }




                     }
                                      // end of loop



                   if(custList.size()>0)
                   update custList;
                   if(transList.size()>0)
                   update transList;


        }


      /* This method is to execute to relase some resources if any*/
    global void finish(Database.BatchableContext BC)
    {
    }

    global void execute(SchedulableContext sc)
    {
        String strQuery = '';
        TransLaunchBatchClass  Mod5LaunchBatchObj = new TransLaunchBatchClass   ();
        database.executebatch(Mod5LaunchBatchObj, 1);

    }

}