objects/Account.object
<CustomObject>
    <fields>
        <fullName>AOPS_Cust_Id__c</fullName>
        <description>AOPS Customer Account Number</description>
        <externalId>true</externalId>
        <label>AOPS Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>AOPS_Seq_ID__c</fullName>
        <externalId>true</externalId>
        <label>AOPS Seq ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Oracle_Party_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Party ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Ace_Customer_Core_Changes__c.object
<CustomObject>
    <description>Price Change Process UI</description>
    <fields>
        <fullName>ACE_Customer_Price_Changes__c</fullName>
        <label>Batch</label>
        <referenceTo>ACE_Customer_Price_Changes__c</referenceTo>
        <relationshipLabel>Customer Core Changes</relationshipLabel>
        <relationshipName>Ace_Customer_Core_Changes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Approved_Proposed_Price__c</fullName>
        <description>Rollup of price to be used in IGM % calculations</description>
        <label>New Price</label>
        <summarizedField>Ace_Customer_SKU_Changes__c.Approved_Proposed_Price__c</summarizedField>
        <summaryFilterItems>
            <field>Ace_Customer_SKU_Changes__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </summaryFilterItems>
        <summaryForeignKey>Ace_Customer_SKU_Changes__c.Ace_Customer_Core_Changes__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>CoreID__c</fullName>
        <externalId>true</externalId>
        <label>CoreID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Sell_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Aggregate of the Current Sell Price</description>
        <label>Current Sell Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Item_12_Month_Qty__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Accumulated SKU Sold Qty for this Core, Last 12 calendar months from current date
Same Time Period as of Sales</description>
        <label>Item 12 Month Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Item_12_Month_Sales__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Vendavo PA</description>
        <label>Item 12 Month Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SRM_Differential__c</fullName>
        <defaultValue>0</defaultValue>
        <label>SRM Differential $</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Spend_Impact_12_Month__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Spend Impact 12 Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Customer Core Changes</label>
    <nameField>
        <label>Core</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Core Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ACE_Customer_MailOut__c.object
<CustomObject>
    <description>This object will hold external email communications, this data will feed into cheetah</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>ACE Customer MailOuts</relationshipLabel>
        <relationshipName>ACE_Customer_MailOuts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>ACE Customer MailOuts</relationshipLabel>
        <relationshipName>ACE_Customer_MailOuts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email_Key__c</fullName>
        <description>Email Key to Track Response</description>
        <label>Email Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>ACE Customer MailOut</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ACE Customer MailOuts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ACE_Customer_Price_Changes__c.object
<CustomObject>
    <description>Price Change Process UI</description>
    <fields>
        <fullName>Approved_Proposed_Price__c</fullName>
        <description>This price is used for IGM calculations</description>
        <label>New Price</label>
        <summarizedField>Ace_Customer_Core_Changes__c.Approved_Proposed_Price__c</summarizedField>
        <summaryForeignKey>Ace_Customer_Core_Changes__c.ACE_Customer_Price_Changes__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Current_Sell_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Aggregate of the Current Sell Price</description>
        <label>Current Sell Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Customer_Response__c</fullName>
        <label>Customer Response</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Call Me</fullName>
                </value>
                <value>
                    <fullName>Reject</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>ACE_Customer_Price_Changes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Exception_Date_Lock__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exception Date Lock</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Item_12_Month_Qty__c</fullName>
        <description>Accumulated SKU Sold Qty for this Core, Last 12 calendar months from current date
Same Time Period as of Sales</description>
        <label>Item 12 Month Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Item_12_Month_Sales__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Vendavo PA</description>
        <label>Item 12 Month Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Owning_Customer_ID__c</fullName>
        <externalId>true</externalId>
        <label>Cust ID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Page_Key__c</fullName>
        <description>This key is used in sites to validate incoming customer</description>
        <label>Page Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Unlock__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Record_Unlock</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SFDC_Notification_Flag__c</fullName>
        <label>SFDC Notification Flag</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SKU_Approval_Pending__c</fullName>
        <defaultValue>false</defaultValue>
        <description>to track the related sku&apos;s approval status</description>
        <label>SKU Approval Pending</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SRM_Differential__c</fullName>
        <defaultValue>0</defaultValue>
        <label>SRM Differential $</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Spend_Impact_12_Month__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Estimated Total Annual Spend Change</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Customer Core Price Changes</label>
    <nameField>
        <label>Batch</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Core Price Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ACE_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is For ACE Custom Settings</description>
    <fields>
        <fullName>BatchName__c</fullName>
        <label>BatchName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ACE_Settings</label>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <description>Contact Role</description>
        <inlineHelpText>eBilling &amp; Account Payable contacts need to be added to iReceivables.</inlineHelpText>
        <label>Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounts Payable</fullName>
                </value>
                <value>
                    <fullName>CIO</fullName>
                </value>
                <value>
                    <fullName>eBilling</fullName>
                </value>
                <value>
                    <fullName>End User</fullName>
                </value>
                <value>
                    <fullName>Executive Level</fullName>
                </value>
                <value>
                    <fullName>IT Buyer</fullName>
                </value>
                <value>
                    <fullName>IT Decision Maker</fullName>
                </value>
                <value>
                    <fullName>IT Director</fullName>
                </value>
                <value>
                    <fullName>IT influencer</fullName>
                </value>
                <value>
                    <fullName>Price Change Approver</fullName>
                </value>
                <value>
                    <fullName>Price Change Notification/Viewer</fullName>
                </value>
                <value>
                    <fullName>Super User</fullName>
                </value>
                <value>
                    <fullName>Purchasing Manager</fullName>
                </value>
                <value>
                    <fullName>O/S Order Placer</fullName>
                </value>
                <value>
                    <fullName>Tech Order Placer</fullName>
                </value>
                <value>
                    <fullName>Frn Order Placer</fullName>
                </value>
                <value>
                    <fullName>Product Selector</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>Payment/Credit</fullName>
                </value>
                <value>
                    <fullName>Applicant</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Dotcom user</fullName>
                </value>
                <value>
                    <fullName>Receiver</fullName>
                </value>
                <value>
                    <fullName>Catalog</fullName>
                </value>
                <value>
                    <fullName>Certification</fullName>
                </value>
                <value>
                    <fullName>Partner Sales Rep</fullName>
                </value>
                <value>
                    <fullName>Tax Exemption</fullName>
                </value>
                <value>
                    <fullName>PO Report Recipient</fullName>
                </value>
                <value>
                    <fullName>Alibaba Buyer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ACEMyPriceChanges_TC.cls
@isTest
private class ACEMyPriceChanges_TC 
{

static testMethod void ACEMyPriceChanges_method(){
  
 Account acc = new Account (name = 'SUN Test Account',AOPS_Seq_ID__c = '123456',AOPS_Cust_Id__c = '123456',Oracle_Party_Id__c = '123456',Billingcountry = 'USA',BillingState = 'UT',BillingStreet = '1040 N 326 W',billingcity = 'Orem');
 insert acc;
 
 ACE_Settings__c desettings = new ACE_Settings__c(BatchName__c='Q4-2014');
 insert desettings; 

 Contact con = new contact(firstname='test',
                         lastname='lastname',
                         role__c = 'Price Change Approver',
                         email='test@test.com',
                         Accountid=acc.id);
                         
 insert con;
 
 ACE_Customer_Price_Changes__c ace1 = new ACE_Customer_Price_Changes__c(name='1234ddd',
                                     SRM_Differential__c=5,
                                     Customer_Response__c='Approved',
                                     Item_12_Month_Qty__c = 50,
                                     Total_Spend_Impact_12_Month__c=5,
                                     Customer__c = acc.id, 
                                     Owning_Customer_ID__c ='123456', 
                                     SFDC_Notification_Flag__c = '3',
                                     Record_Unlock__c = true,
                                     SKU_Approval_Pending__c = true,
                                     Exception_Date_Lock__c = true,
                                     page_Key__c='pagekey1234');
 system.debug('@@@@'+ace1);
 insert ace1;
  
 Ace_Customer_Core_Changes__c CCCC = new Ace_Customer_Core_Changes__c();
 CCCC.ACE_Customer_Price_Changes__c=ace1.id;
 CCCC.CoreID__c='alpha';
 insert CCCC;

   ACE_Customer_MailOut__c mailout = new ACE_Customer_MailOut__c(name = '1234ddd',
                                     Email__c='test@testemail.com',
                                     contact__c = con.id,
                                     Email_Key__c='1234ddd');
   insert mailout;
   update mailout;   
 
 ApexPages.currentPage().getParameters().Put('pkey','pagekey1234');
 ApexPages.currentPage().getParameters().Put('ekey','1234ddd');
 ACEMyPriceChanges AMPC = new ACEMyPriceChanges ();
   AMPC.sortCust();
   AMPC.Refresh_rec();
   AMPC.skuDownload();
   AMPC.getDisablePrevious();
   AMPC.getDisableNext();
   AMPC.nextPage();
   AMPC.prevPage();
   AMPC.displayHighlighted = true;
   AMPC.searchText  = '1234';
   AMPC.getSKURecords();
   AMPC.AppRec();
   AMPC.RejRec();
   AMPC.searchText  = '';
   AMPC.getSKURecords();   
   AMPC.getFieldName = 'Approved_Proposed_Price__c';
   AMPC.sortCust();
   AMPC.getFieldName = 'Alt_Sell_Price__c';
   AMPC.sortCust();
   AMPC.getFieldName = 'Current_Sell_Price__c';
   AMPC.sortCust();
   AMPC.getFieldName = 'Item_12_Month_Sales__c';
   AMPC.sortCust();
   AMPC.getFieldName = 'Item_12_Month_Qty__c';
   AMPC.sortCust();
   AMPC.getFieldName = 'Alt_UOM__c';
   AMPC.sortCust();
   AMPC.getFieldName = 'UOM__c';
   AMPC.sortCust();
   AMPC.getFieldName = 'Alt_SKU_Description__c';
   AMPC.sortCust();
   AMPC.getFieldName = 'SKU_Description__c';
   AMPC.sortCust();
   AMPC.getFieldName = 'Alt_SKU__c';
   AMPC.sortCust();
   AMPC.getFieldName = 'SKU__c';
   AMPC.sortCust();
 }
}