objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer Accounts</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/et4ae5__IndividualEmailResult__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <formula>et4ae5__Contact__r.Account.Account_ID_Case_Safe__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AccountId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sample_Email_Link__c</fullName>
        <formula>SUBSTITUTE(et4ae5__TriggeredSendDefinition__r.Sample_Email_Link__c, &apos;http://&apos;, &apos;https://&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sample Email Link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VIWB__c</fullName>
        <description>See the Email in web browser</description>
        <inlineHelpText>This URL will expire after 2 years from record creation date</inlineHelpText>
        <label>VIWB</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>et4ae5__Clicked__c</fullName>
        <formula>et4ae5__NumberOfUniqueClicks__c &gt; 0</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Clicked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>et4ae5__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Individual Email Results</relationshipLabel>
        <relationshipName>IndividualEmailResults</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>et4ae5__HardBounce__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>The email sent to this subscriber  was rejected due to permanent conditions (this typically results when &quot;user unknown&quot; or &quot;domain not found&quot; errors occur)</inlineHelpText>
        <label>Hard Bounce</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>et4ae5__NumberOfTotalClicks__c</fullName>
        <inlineHelpText>The total number of times this subscriber clicked on the links on this email</inlineHelpText>
        <label>Number of Total Clicks</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>et4ae5__Opened__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates whether the subscriber opened the email or not</inlineHelpText>
        <label>Opened</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>et4ae5__SoftBounce__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>The email sent was rejected due to a seemingly temporary condition, such as a full inbox, after the system retries unsuccessfully to send the email every 15 minutes for 72 hours. A subscriber will be set to Held status after three soft bounces</inlineHelpText>
        <label>Soft Bounce</label>
        <type>Checkbox</type>
    </fields>
    <label>Individual Email Result</label>
    <nameField>
        <label>Email Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individual Email Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/marketing360GMILController.cls
/**
* @author Rajendra Shahane, rajendra.shahane@officedepot.com
* @date 09/16/2020
*
* 
* @description This class methods are used by marketing360gmiltab LWC component to display and search Indivisual Email Result related to current account contacts
*              
*               test class => marketing360GMILController_Test class
* Created for JIRA: NAIT-148002 03049086 - Display Marketing Data in Customer 360/GMIL
*/
public class marketing360GMILController {
@AuraEnabled(cacheable=true)
    //public static Map <String,list<et4ae5__IndividualEmailResult__c>> getContactDetails(string accountId,string aopsCustId) {
    public static Map <String,list<et4ae5__IndividualEmailResult__c>> getContactDetails(string accountId) {
        Map <String,list<et4ae5__IndividualEmailResult__c>> mapContactEmailRes;
        datetime dtToday = datetime.now().adddays(-14);
        if(label.Marketing360_Past_Contact_Activity_Days != null)
        {
            if(label.Marketing360_Past_Contact_Activity_Days.isNumeric())
            {
                
                dtToday = datetime.now().adddays(integer.valueOf(label.Marketing360_Past_Contact_Activity_Days) * -1);
            }
        }
        datetime dtmodified = datetime.newInstance(dtToday.year(), dtToday.month(), dtToday.day());        
		for(et4ae5__IndividualEmailResult__c emailResult: [select Id,Sample_Email_Link__c, Name,et4ae5__Contact__r.Name,et4ae5__Opened__c,et4ae5__HardBounce__c,et4ae5__SoftBounce__c,et4ae5__Clicked__c,et4ae5__NumberOfTotalClicks__c,VIWB__c  
                                                           from et4ae5__IndividualEmailResult__c where AccountId__c =:accountId 
                                                           and lastmodifieddate >= :dtmodified order by lastmodifieddate desc])
        {
            if(mapContactEmailRes == null )	mapContactEmailRes = new Map <String,list<et4ae5__IndividualEmailResult__c>>();
            if(!mapContactEmailRes.containsKey(emailResult.et4ae5__Contact__r.Name))
            {
                if(mapContactEmailRes.size() < 10) 
                {
                    
                    mapContactEmailRes.put(emailResult.et4ae5__Contact__r.Name, new list<et4ae5__IndividualEmailResult__c>{emailResult});
                }
            }
            else	mapContactEmailRes.get(emailResult.et4ae5__Contact__r.Name).add(emailResult);                
        }
        
        system.debug('accountId ' + accountId);
        //system.debug('aopsCustId ' + aopsCustId);
        system.debug('mapContactEmailRes ' + mapContactEmailRes);	
        return mapContactEmailRes;
    }
    
    @AuraEnabled
    public static Map <String,list<et4ae5__IndividualEmailResult__c>> searchContactDetails(string accountId, string strContactName) {
        //strContactName += '%';
        Map <String,list<et4ae5__IndividualEmailResult__c>> mapContactEmailRes;
        datetime dtToday = datetime.now().adddays(-14);
        if(label.Marketing360_Past_Contact_Activity_Days != null)
        {
            if(label.Marketing360_Past_Contact_Activity_Days.isNumeric())
            {
                
                dtToday = datetime.now().adddays(integer.valueOf(label.Marketing360_Past_Contact_Activity_Days) * -1);
            }
        }
        datetime dtmodified = datetime.newInstance(dtToday.year(), dtToday.month(), dtToday.day());
        /*for(et4ae5__IndividualEmailResult__c emailResult : [select Id, Name,et4ae5__Contact__r.Name,et4ae5__Opened__c,et4ae5__HardBounce__c,et4ae5__SoftBounce__c,et4ae5__Clicked__c,et4ae5__NumberOfTotalClicks__c,VIWB__c  
                                                           from et4ae5__IndividualEmailResult__c where AccountId__c =:accountId and  
                                                            et4ae5__Contact__r.name like :strContactName 
                                                            and lastmodifieddate >= :dtmodified order by lastmodifieddate desc])*/
        for(et4ae5__IndividualEmailResult__c emailResult : [select Id,Sample_Email_Link__c, Name,et4ae5__Contact__r.Name,et4ae5__Opened__c,et4ae5__HardBounce__c,et4ae5__SoftBounce__c,et4ae5__Clicked__c,et4ae5__NumberOfTotalClicks__c,VIWB__c  
                                                           from et4ae5__IndividualEmailResult__c where AccountId__c =:accountId and  
                                                            lastmodifieddate >= :dtmodified order by lastmodifieddate desc])
        {
            if(mapContactEmailRes == null )	mapContactEmailRes = new Map <String,list<et4ae5__IndividualEmailResult__c>>();
            string strName = emailResult.et4ae5__Contact__r.Name.toUpperCase();
            if(strName.startsWith(strContactName.toUpperCase()))
            {
                if(!mapContactEmailRes.containsKey(emailResult.et4ae5__Contact__r.Name))
                {
                    if(mapContactEmailRes.size() < 10) 
                    {
                        
                        mapContactEmailRes.put(emailResult.et4ae5__Contact__r.Name, new list<et4ae5__IndividualEmailResult__c>{emailResult});
                    }
                }
                else	mapContactEmailRes.get(emailResult.et4ae5__Contact__r.Name).add(emailResult);
            }            
        }
        system.debug('accountId ' + accountId);
        //system.debug('aopsCustId ' + aopsCustId);
        system.debug('strContactName ' + strContactName);
        system.debug('mapContactEmailRes ' + mapContactEmailRes);	
        return mapContactEmailRes;
    }
}