objects/Account.object
<CustomObject>
    <fields>
        <fullName>Grandparent__c</fullName>
        <formula>IF($RecordType.Name = &quot;GrandParent&quot;, &quot;Yes&quot;, &quot;No&quot; )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Grandparent?</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Product__c</fullName>
        <description>This field is used to identify the difference between the MPS Prospect and Others</description>
        <label>Primary Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All Supplies</fullName>
                </value>
                <value>
                    <fullName>CBS</fullName>
                </value>
                <value>
                    <fullName>CPD-Print</fullName>
                </value>
                <value>
                    <fullName>CPD-Promo</fullName>
                </value>
                <value>
                    <fullName>Furniture</fullName>
                </value>
                <value>
                    <fullName>Ink &amp; Toner</fullName>
                </value>
                <value>
                    <fullName>Paper</fullName>
                </value>
                <value>
                    <fullName>MPS</fullName>
                </value>
                <value>
                    <fullName>Tech</fullName>
                </value>
                <value>
                    <fullName>Filing &amp; Binding</fullName>
                </value>
                <value>
                    <fullName>Labels &amp; Forms</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>Office Essentials</fullName>
                </value>
                <value>
                    <fullName>Writing &amp; Drafting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Remediation_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This flag would be populated and used for the BSD price increases</description>
        <label>Remediation Support For Price Increases</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Parent</fullName>
        <active>true</active>
        <label>Parent</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ACE_Batches__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Batch__c</fullName>
        <label>Batch</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>ACE_Batches</label>
</CustomObject>

objects/ACE_Customer_Price_Changes__c.object
<CustomObject>
    <description>Price Change Process UI</description>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>ACE_Customer_Price_Changes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Hosted_Catalog__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Hosted Catalog flag for Hosted Catalog bucket</description>
        <label>Hosted Catalog</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Owning_Customer_Legal__c</fullName>
        <label>Governed By Written Agreement (T/F)</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PRICE_NOT_CALCULATED__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PRICE_NOT_CALCULATED</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Update_Timing_Action__c</fullName>
        <label>Update Timing Action</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Customer Core Price Changes</label>
    <nameField>
        <label>Batch</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Core Price Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ACEWRFCreation_Batch.cls
global class ACEWRFCreation_Batch implements database.Batchable<Sobject>
{
    public String acequery ;
    global String batchId = '1';

    global ACEWRFCreation_Batch(){

        list<ACE_Batches__c> BatchName =[SELECT Id,Batch__c from ACE_Batches__c order by CreatedDate desc limit 5];
        if(BatchName[0]!= null)
            this.batchId = BatchName[0].Batch__c;

        //this.acequery  = 'SELECT Id,customer__r.Remediation_Required__c,Hosted_Catalog__c,PRICE_NOT_CALCULATED__c from ACE_Customer_Price_Changes__c where Name= \''+batchId +'\' '+ ' and (Customer__r.Remediation_Required__c = true OR Hosted_Catalog__c = true OR PRICE_NOT_CALCULATED__c = true)';
        // Updated the query for Case-00152641 //
        this.acequery  = 'SELECT Id,customer__c,customer__r.ownerID,Customer__r.Grandparent__c,Customer__r.Parent.Grandparent__c,' ;
        this.acequery += 'Customer__r.Parent.parent.Grandparent__c,Customer__r.Parent.id,Customer__r.Parent.Parent.Id,' ;
        //this.acequery += 'Owning_Customer_Legal__c,Customer__r.Primary_Product__c,customer__r.Remediation_Required__c,Hosted_Catalog__c,PRICE_NOT_CALCULATED__c,Update_Timing_Action__c from ACE_Customer_Price_Changes__c where Name= \''+batchId +'\' '+ ' and (Customer__r.Remediation_Required__c = true OR PRICE_NOT_CALCULATED__c = true)';
        this.acequery += 'Owning_Customer_Legal__c,Customer__r.Primary_Product__c,customer__r.Remediation_Required__c,Hosted_Catalog__c,PRICE_NOT_CALCULATED__c,Update_Timing_Action__c from ACE_Customer_Price_Changes__c where Name= \''+batchId +'\' '+ ' and ((Customer__r.Remediation_Required__c = true and PRICE_NOT_CALCULATED__c = false) OR (Customer__r.Remediation_Required__c = false and PRICE_NOT_CALCULATED__c = true))'; 
        this.acequery += 'and Update_Timing_Action__c = \'T\'';//ROM-37 - to not create WRFs for Update_Timing_Action__c = 'F'
    }

    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        return Database.getQueryLocator(acequery);
    }
     // Start : Added by Mohit for Story S-353024 //
    global void execute(Database.BatchableContext BC, SObject[] scope) {
      List<ACE_Customer_Price_Changes__c> custRecords= scope;
      ACEWRFCreation wrf = new ACEWRFCreation();
      wrf.createWRFFromBatch(custRecords);
    }
    // End

    /* Comment by Mohit for Story S-353024 //
    global void execute(Database.BatchableContext BC, SObject[] scope)
    {
      List<ACE_Customer_Price_Changes__c> custRecords= scope;

      List<ID> custRemIDs = new List<ID>();
      List<ID> custHostIDs = new List<ID>();
      List<ID> custPriceIDs = new List<ID>();

      List<case> caseList = new List<case>();
      Set<ID> caseSet = new Set<ID>();
      caseList = [select Customer_Core_Price_Changes__r.id from case where Customer_Core_Price_Changes__c!=null and WRF_Request_Type__c = 'BSD Pricing'];
      for(case cs:caseList){
          caseSet.add(cs.Customer_Core_Price_Changes__r.id);
      }


      for(ACE_Customer_Price_Changes__c cus:custRecords){
          if(cus.PRICE_NOT_CALCULATED__c && cus.customer__r.Remediation_Required__c && cus.Hosted_Catalog__c)
              custPriceIDs.add(cus.id);
          else if(cus.PRICE_NOT_CALCULATED__c && !cus.Hosted_Catalog__c && !cus.customer__r.Remediation_Required__c)
              custPriceIDs.add(cus.id);
          else if(cus.PRICE_NOT_CALCULATED__c && cus.Hosted_Catalog__c && !cus.customer__r.Remediation_Required__c)
              custPriceIDs.add(cus.id);
          else if(cus.PRICE_NOT_CALCULATED__c && !cus.Hosted_Catalog__c && cus.customer__r.Remediation_Required__c)
              custPriceIDs.add(cus.id);
          else if(!cus.PRICE_NOT_CALCULATED__c && cus.Hosted_Catalog__c && cus.customer__r.Remediation_Required__c)
              custRemIDs.add(cus.id);
          else if(!cus.PRICE_NOT_CALCULATED__c && !cus.Hosted_Catalog__c && cus.customer__r.Remediation_Required__c)
              custRemIDs.add(cus.id);
          else if(!cus.PRICE_NOT_CALCULATED__c && cus.Hosted_Catalog__c && !cus.customer__r.Remediation_Required__c && !caseSet.contains(cus.id))
              custHostIDs.add(cus.id);
      }


      system.debug('$$$$$$$$$$$custRemIDs'+custRemIDs);
      system.debug('$$$$$$$$$$$custHostIDs'+custHostIDs);
      system.debug('$$$$$$$$$$$custPriceIDs'+custPriceIDs);
      ACEWRFCreation wrf = new ACEWRFCreation();

      if(custRemIDs.size()>0)
          wrf.createWRF(custRemIDs,'Remediation');

      if(custHostIDs.size()>0){
        wrf.createWRF(custHostIDs,'BSD Pricing');
      }

      if(custPriceIDs.size()>0)
          wrf.createWRF(custPriceIDs,'Compliance');

    }
    */
    global void finish(Database.BatchableContext BC)
    {
       System.debug('Completed Processing.... ACE WRF Case Batch for :'+batchId) ;
    }
}