objects/Account.object
<CustomObject>
    <fields>
        <fullName>AOPS_Cust_Id__c</fullName>
        <description>AOPS Customer Account Number</description>
        <externalId>true</externalId>
        <label>AOPS Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>AOPS_Seq_ID__c</fullName>
        <externalId>true</externalId>
        <label>AOPS Seq ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Address1__c</fullName>
        <label>Address1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address2__c</fullName>
        <label>Address2</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Key__c</fullName>
        <label>Address Key</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To__c</fullName>
        <label>Bill To</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Community_Postscript__c</fullName>
        <label>Community Postscript</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>USA</fullName>
                    <default>true</default>
                    <label>USA</label>
                </value>
                <value>
                    <fullName>CAN</fullName>
                </value>
                <value>
                    <fullName>MEX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DEPT_REQUIRED_CODE__c</fullName>
        <label>DEPT_REQUIRED_CODE</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Status_Modified__c</fullName>
        <label>Date Status Modified</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Opt_In__c</fullName>
        <inlineHelpText>Submit an Account Maintenance Request to update Opt In values</inlineHelpText>
        <label>Email Opt In</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Freight_Charge__c</fullName>
        <label>Freight Charge</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Future_Use_Reserved__c</fullName>
        <label>Future Use Reserved</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LOCATION_REQ_CODE_7__c</fullName>
        <label>LOCATION_REQ_CODE_7</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mail_Opt_In__c</fullName>
        <inlineHelpText>Submit an Account Maintenance Request to update Opt In values</inlineHelpText>
        <label>Mail Opt In</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mail_To__c</fullName>
        <label>Mail To</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile_Opt_In__c</fullName>
        <label>Mobile Opt In</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_REQUIRED_CODE__c</fullName>
        <label>PO_REQUIRED_CODE</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Opt_In__c</fullName>
        <inlineHelpText>Submit an Account Maintenance Request to update Opt In values</inlineHelpText>
        <label>Phone Opt In</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RELEASE_REQUIRED_CODE__c</fullName>
        <label>RELEASE_REQUIRED_CODE</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>(Tech-Zone)</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShipTo_Status__c</fullName>
        <label>ShipTo Status</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site</fullName>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip/Postal Code</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer Accounts</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Site</fullName>
        <active>true</active>
        <label>Site</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Account_Site_Final_Staging__c.object
<CustomObject>
    <description>This object is account site final staging for AOPS to SFDC sync to store AOPS account address sequences.</description>
    <fields>
        <fullName>AOPS_Cust_Id__c</fullName>
        <label>AOPS Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AOPS_Seq_ID__c</fullName>
        <externalId>true</externalId>
        <label>AOPS Seq ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address1__c</fullName>
        <label>Address1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address2__c</fullName>
        <label>Address2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Key__c</fullName>
        <label>Address Key</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To__c</fullName>
        <label>Bill To</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CXTF001P_SFDC_KEY1__c</fullName>
        <label>CXTF001P SFDC KEY1</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CXTF001P_SFDC_KEY2__c</fullName>
        <label>CXTF001P SFDC KEY2</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>USA</fullName>
                    <default>true</default>
                    <label>USA</label>
                </value>
                <value>
                    <fullName>CAN</fullName>
                </value>
                <value>
                    <fullName>MEX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Status_Modified__c</fullName>
        <label>Date Status Modified</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Address_Addendum_Changed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Address Addendum Changed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Address_Master_Changed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Address Master Changed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mail_To__c</fullName>
        <label>Mail To</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipTo_Status__c</fullName>
        <label>ShipTo Status</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sync_Failed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync Failed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Account Site Final Staging</label>
    <nameField>
        <label>Account Site Final Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Sites Final Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AOPSSyncToSiteProcessor.cls
public class AOPSSyncToSiteProcessor {

    List<Account_Site_Final_Staging__c> stagingRecordsToSync; // The staging records that have changed to be synced.
    Map<String, String> syncFailedMessageMap;
    Map<String, String> accountOwnerIdByAopsIdMap;

    public AOPSSyncToSiteProcessor(List<Account_Site_Final_Staging__c> finalStagingRecords) {
        stagingRecordsToSync = finalStagingRecords;
    }
    
    public static Boolean isFailedRecord(Account_Site_Final_Staging__c finalStagingRec) {
        return finalStagingRec.Sync_Failed__c;
    }
    
    /**
     * Syncs the staging records from the instance variable stagingRecordsToSync to corresponding
     * Site records.
     * Additionally, the staging records are marked as having been synced.
     */
    public void sync() {
     
		try {
            boolean isAddressMasterFlagChanged = true;
            boolean isDelete = false;
            Database.UpsertResult[] upsertSiteResultList = null;
            List<Account> siteSuccessList = null;
            List<Account> siteFailedList = null;

            getAccountOwnerList(stagingRecordsToSync);
            // 1. Handle staging records with master flag changed.
            List<Account_Site_Final_Staging__c> stagingRecList = getStagingRecList(stagingRecordsToSync, isAddressMasterFlagChanged, isDelete);
            System.debug('Total number of staging recs = '+ stagingRecList.size());
            // 1.1 Handle sites with SFDC id during account setup
            List<Account> accountSiteList = getStagingRecListWithSfdcId(stagingRecList);
            System.debug('Site list in getStagingRecListWithSfdcId=============================================='+ accountSiteList.size());
            System.debug(accountSiteList);
            if (accountSiteList.size() > 0) {
                upsertSiteResultList = Database.upsert(accountSiteList, Account.Id, false);
                siteSuccessList = getSuccessfulUpsertedSites(upsertSiteResultList, accountSiteList);
                siteFailedList = getFailedUpsertedSites(upsertSiteResultList, accountSiteList);
                markStagingRecordsWithSyncStatus(siteSuccessList, siteFailedList, stagingRecList);
                updateAccountsWithPrimarySiteAddress(siteSuccessList, stagingRecList);
            }
            
            System.debug('Before calling without sfdc id, size ==='+ stagingRecList.size());
            // 1.2 Handle sites without SFDC id
            accountSiteList = getStagingRecListWithoutSfdcId(stagingRecList);
            System.debug('Site list in getStagingRecListWithoutSfdcId=============================================='+ accountSiteList.size());
            if (accountSiteList.size() > 0) {
                upsertSiteResultList = Database.upsert(accountSiteList, Account.AOPS_Seq_ID__c, false);
                siteSuccessList = getSuccessfulUpsertedSites(upsertSiteResultList, accountSiteList);
                siteFailedList = getFailedUpsertedSites(upsertSiteResultList, accountSiteList);
                markStagingRecordsWithSyncStatus(siteSuccessList, siteFailedList, stagingRecList);
                updateAccountsWithPrimarySiteAddress(siteSuccessList, stagingRecList);
            }
            // Handle staging records where master flag is not changed but the secondary flags are changed.
            isAddressMasterFlagChanged = false;
            stagingRecList = getStagingRecList(stagingRecordsToSync, isAddressMasterFlagChanged, isDelete);
            accountSiteList = getExistingSiteList(stagingRecList);
            if (accountSiteList.size() > 0) {
                upsertSiteResultList = Database.upsert(accountSiteList, Account.AOPS_Seq_ID__c, false);
                siteSuccessList = getSuccessfulUpsertedSites(upsertSiteResultList, accountSiteList);
                siteFailedList = getFailedUpsertedSites(upsertSiteResultList, accountSiteList);
                markStagingRecordsWithSyncStatus(siteSuccessList, siteFailedList, stagingRecList);
            }
            // Handle staging records with a delete action.
            isDelete = true;
            stagingRecList = getStagingRecList(stagingRecordsToSync, isAddressMasterFlagChanged, isDelete);
            accountSiteList = getExistingSiteList(stagingRecList);
            if (accountSiteList.size() > 0) {
                Database.DeleteResult[] deleteSiteResultList = Database.delete(accountSiteList, false);
                siteSuccessList = getSuccessfulUpsertedSites(upsertSiteResultList, accountSiteList);
                siteFailedList = getFailedUpsertedSites(upsertSiteResultList, accountSiteList);
                markStagingRecordsWithSyncStatus(siteSuccessList, siteFailedList, stagingRecList);
            }
        } catch(Exception e) {
            handleSyncFailure(e);
        }        
        
    }

    private void getAccountOwnerList(List<Account_Site_Final_Staging__c> stagingRecordsToSync) {

        accountOwnerIdByAopsIdMap = new Map<String, String>();
        List<String> aopsCustIdList = new List<String>();
        for (Account_Site_Final_Staging__c finalStageRec : stagingRecordsToSync) {
            aopsCustIdList.add(finalStageRec.AOPS_Cust_Id__c);
        }

        if (aopsCustIdList.size() > 0) {
            List<Account>  accountList = [select AOPS_Cust_Id__c, ownerid from account where AOPS_Cust_Id__c IN :aopsCustIdList and type='Customer'];
            for (Account acct : accountList) {
                accountOwnerIdByAopsIdMap.put(acct.AOPS_Cust_Id__c, acct.ownerid);
            }
        }
    }
    
    private void updateAccountsWithPrimarySiteAddress(List<Account> siteList, List<Account_Site_Final_Staging__c> stagingRecList) {
        
        Map<String, Account_Site_Final_Staging__c> primarySiteStagingRecMap = new Map<String, Account_Site_Final_Staging__c>();
        List<String> aopsCustIdList = new List<String>();
        
        for (Account_Site_Final_Staging__c stageRec : stagingRecList) {
            if (stageRec.AOPS_Seq_ID__c.contains('-00001')) {
                primarySiteStagingRecMap.put(stageRec.AOPS_Cust_Id__c, stageRec);
                aopsCustIdList.add(stageRec.aops_cust_id__c);
            }
        }
                
        List<Account> acctList = [SELECT id, aops_cust_id__c FROM account where aops_cust_id__c in :primarySiteStagingRecMap.keySet()];
        
        Account_Site_Final_Staging__c stageRec;
        for (Account acct : acctList) {
            stageRec = primarySiteStagingRecMap.get(acct.AOPS_Cust_Id__c);
            copyAddress(stageRec, acct);
        }
        
    }
    
    private void copyAddress(Account_Site_Final_Staging__c source, Account target) {
        target.Address1__c = source.Address1__c;
        target.Address2__c = source.Address2__c;
        target.City__c = source.City__c;
        target.State__c = source.State__c;
        target.Zip__c = source.Zip__c;
        target.Country__c = source.Country__c;        
    }
    
    private Account getSiteFromStagingRec(Account_Site_Final_Staging__c stagingRec, Account custSite) {
            
        //custSite.AOPS_Cust_Id__c = stagingRec.AOPS_Cust_Id__c;
        custSite.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Site').getRecordTypeId();
        custSite.AOPS_Seq_Id__c = stagingRec.AOPS_Seq_ID__c;
        custSite.Address_Key__c = stagingRec.Address_Key__c;
        
        if (stagingRec.Is_Address_Master_Changed__c) {            
            custSite.Name = stagingRec.Account_Name__c;
            custSite.Address1__c = stagingRec.Address1__c;
            custSite.Address2__c = stagingRec.Address2__c;
            custSite.City__c = stagingRec.City__c;
            custSite.State__c = stagingRec.State__c;
            custSite.Zip__c = stagingRec.Zip__c;
            custSite.Country__c = stagingRec.Country__c;
            custSite.Date_Status_Modified__c = stagingRec.Date_Status_Modified__c;
            custSite.ShipTo_Status__c = stagingRec.ShipTo_Status__c;
            custSite.Bill_To__c = stagingRec.Bill_To__c;
            custSite.Mail_To__c = stagingRec.Mail_To__c;
            custSite.County__c = stagingRec.County__c;           
            String accountOwnerId = (String) accountOwnerIdByAopsIdMap.get(stagingRec.aops_cust_id__c);
            if (accountOwnerId != null)
                custSite.ownerId = accountOwnerId;
            else
                custSite.ownerId = Label.Dataloader_Id_Trigger;
            System.debug('Account owner id ========='+ custSite.ownerId);
        }
        if (stagingRec.Is_Address_Addendum_Changed__c) {
            
        }        
        
        return custSite;
    }
    
    private List<Account_Site_Final_Staging__c> getStagingRecList(List<Account_Site_Final_Staging__c> stagingRecordsToSync, boolean isAddressMasterFlagChanged, boolean isDelete) {
        
		List<Account_Site_Final_Staging__c> stageRecList = new List<Account_Site_Final_Staging__c>();
        
        for (Account_Site_Final_Staging__c siteStaging : stagingRecordsToSync) {
            if (isDelete) {
                if(siteStaging.Action__c == 'D') {
                    stageRecList.add(siteStaging);
                }
            } else if (isAddressMasterFlagChanged) {
                if (siteStaging.Is_Address_Master_Changed__c) {
                	stageRecList.add(siteStaging);
            	}                
            } else {
                if (!siteStaging.Is_Address_Master_Changed__c && siteStaging.Is_Address_Addendum_Changed__c) {
                	stageRecList.add(siteStaging);
            	}
            }
        }
    	return stageRecList;
	}
    
    private List<Account> getStagingRecListWithoutSfdcId(List<Account_Site_Final_Staging__c> stagingRecList) {
        
        List<Account> accountList = new List<Account>();
        Account account;
        
        List<Account_Site_Final_Staging__c> stagingRecListWithoutSfdcId = new List<Account_Site_Final_Staging__c>();
        List<String> aopsCustIdList = new List<String>();
        
        for (Account_Site_Final_Staging__c stagingRec : stagingRecList) {
            if (!doesSfdcIdExist(stagingRec)) {
            	//stagingRecMap.put(stagingRec.AOPS_Cust_Id__c, stagingRec);    
            	aopsCustIdList.add(stagingRec.AOPS_Cust_Id__c);
                stagingRecListWithoutSfdcId.add(stagingRec);
            }
        }
        
        // Accounts have to exist to sync sites.
        List<Account> existingAcctList = [select Id, AOPS_Cust_Id__c from account where AOPS_Cust_Id__c in :aopsCustIdList];
        Map<String,String> existAcctIdMap = new Map<String,String>();
        for (Account acct : existingAcctList) {
            existAcctIdMap.put(acct.AOPS_Cust_Id__c, acct.Id);
        }
        
        List<Account_Site_Final_Staging__c> stagingRecListWithAccounts = new List<Account_Site_Final_Staging__c>();
        for (Account_Site_Final_Staging__c stagingRec : stagingRecListWithoutSfdcId) {
            if (existAcctIdMap.get(stagingRec.AOPS_Cust_Id__c) != null) {
            	stagingRecListWithAccounts.add(stagingRec);
            }
        }
                
        for (Account_Site_Final_Staging__c stagingRec : stagingRecListWithAccounts) {
            account = getSiteFromStagingRec(stagingRec, new Account());
            account.Related_Account__c = existAcctIdMap.get(stagingRec.AOPS_Cust_Id__c);
            accountList.add(account);
        }
        return accountList;
    }
    
    private boolean doesSfdcIdExist(Account_Site_Final_Staging__c stagingRec) {
    
        boolean exist = false;
        
        if (stagingRec != null) {
            if(String.isNotEmpty(stagingRec.CXTF001P_SFDC_KEY1__c) && String.isNotEmpty(stagingRec.CXTF001P_SFDC_KEY2__c)) {
                exist = true;
            }
        }
        return exist;
    }
        
    private List<Account> getStagingRecListWithSfdcId(List<Account_Site_Final_Staging__c> stagingRecList) {
        
        List<Account> accountList = new List<Account>();
        Account account;
        for (Account_Site_Final_Staging__c stagingRec : stagingRecList) {
            if(doesSfdcIdExist(stagingRec)) {
                account = getSiteFromStagingRec(stagingRec, new Account());
                account.Related_Account__c = stagingRec.CXTF001P_SFDC_KEY1__c;
                account.Id = stagingRec.CXTF001P_SFDC_KEY2__c;
                accountList.add(account);
            }
        }
        return accountList;
    }
    
    private List<Account> getExistingSiteList(List<Account_Site_Final_Staging__c> stagingRecList) {
        
        List<Account> siteList = new List<Account>();
        
        Map<String, Account_Site_Final_Staging__c> stagingRecMap = new Map<String, Account_Site_Final_Staging__c>();
        for (Account_Site_Final_Staging__c stagingRec : stagingRecList) {
            stagingRecMap.put(stagingRec.AOPS_Seq_Id__c, stagingRec);
        }               
        
        List<Account> existingSiteList = [SELECT id, AOPS_Cust_Id__c, Community_Postscript__c, Freight_Charge__c, DEPT_REQUIRED_CODE__c, 
                                  	LOCATION_REQ_CODE_7__c, PO_REQUIRED_CODE__c, RELEASE_REQUIRED_CODE__c, Future_Use_Reserved__c,
									Mobile_Opt_In__c, Phone_Opt_In__c, Mail_Opt_In__c, Email_Opt_In__c, Max_Order_Limit__c, AOPS_Seq_Id__c
                                  FROM account 
                                  WHERE aops_seq_id__c in :stagingRecMap.keySet()];
    	
        Account_Site_Final_Staging__c stageRec;
        for (Account acct : existingSiteList) {
            stageRec = stagingRecMap.get(acct.AOPS_Seq_Id__c);
            acct = getSiteFromStagingRec(stageRec, acct);
            siteList.add(acct);
        }
        
        return siteList;
    }
    
    private List<Account> getSuccessfulUpsertedSites(Database.UpsertResult[] upsertAcctList, List<Account> accountList) {
        
        List<Account> successAcctList = new List<Account>();
        for(Integer i=0; i < upsertAcctList.size(); i++) {
            if(upsertAcctList[i].isSuccess()) {
                successAcctList.add(accountList[i]);
            }
        }
        return successAcctList;
    }
    
    private List<Account> getFailedUpsertedSites(Database.UpsertResult[] upsertAcctList, List<Account> accountList) {
        
        List<Account> failedAcctList = new List<Account>();
        syncFailedMessageMap = new Map<String,String>();
        
        for(Integer i=0; i < upsertAcctList.size(); i++) {
            if(!upsertAcctList[i].isSuccess()) {
                failedAcctList.add(accountList[i]);
            }
            if(!upsertAcctList[i].isSuccess()) {
                Database.Error[] errors = upsertAcctList[i].getErrors();
                syncFailedMessageMap.put(accountList[i].AOPS_Seq_ID__c, getErrorMessage(errors));
            }
        }
        return failedAcctList;
    }

    private List<Account> getSuccessfulDeletedSites(Database.DeleteResult[] deleteAcctList, List<Account> accountList) {
        
        List<Account> successAcctList = new List<Account>();
        for(Integer i=0; i < deleteAcctList.size(); i++) {
            if(deleteAcctList[i].isSuccess()) {
                successAcctList.add(accountList[i]);
            }
        }
        return successAcctList;
    }
    
    private List<Account> getFailedDeletedSites(Database.DeleteResult[] deleteAcctList, List<Account> accountList) {
        
        List<Account> failedAcctList = new List<Account>();
        syncFailedMessageMap = new Map<String,String>();
        
        for(Integer i=0; i < deleteAcctList.size(); i++) {
            if(!deleteAcctList[i].isSuccess()) {
                failedAcctList.add(accountList[i]);
            }
            if(!deleteAcctList[i].isSuccess()) {
                Database.Error[] errors = deleteAcctList[i].getErrors();
                syncFailedMessageMap.put(accountList[i].AOPS_Seq_ID__c, getErrorMessage(errors));
            }
        }
        return failedAcctList;
    }

    private String getErrorMessage(Database.Error[] errors) {
        String message = '';
        for (Database.Error err : errors) {
            System.debug('Error message '+ err.getMessage());
            message = message + ':' + err.statuscode + ':' + err.message;
        }
        return message;
    }
    
    /**
     * Sets the "Is Changed" fields on the staging records to false, effectively
     * marking them as in sync with their corresponding Sites.
     */
    private void markStagingRecordsWithSyncStatus(List<Account> successList, List<Account> failedList, List<Account_Site_Final_Staging__c> syncedStagingRecList) {
        
        Map<String, Account_Site_Final_Staging__c> stagingRecMap = new Map<String, Account_Site_Final_Staging__c>();
        
        for (Account_Site_Final_Staging__c afs : syncedStagingRecList) {
            stagingRecMap.put(afs.AOPS_Seq_ID__c, afs);
        }
        
        List<Account_Site_Final_Staging__c> clonedRecords = new List<Account_Site_Final_Staging__c>();        
        Account_Site_Final_Staging__c stagingRec;
        
        for(Account acct : successList) {
            stagingRec = stagingRecMap.get(acct.AOPS_Seq_ID__c);
            Account_Site_Final_Staging__c clonedRecord = new Account_Site_Final_Staging__c(Id=stagingRec.Id);
            clonedRecord.Is_Address_Master_Changed__c = false;
            clonedRecord.Is_Address_Addendum_Changed__c = false;
            clonedRecord.Sync_Failed__c = false;
            clonedRecord.Sync_Failed_Reason__c = '';
            clonedRecord.Number_Of_Attempts__c = 0;
            clonedRecords.add(clonedRecord);
        }
        
        for(Account acct : failedList) {
            stagingRec = stagingRecMap.get(acct.AOPS_Seq_ID__c);
            Account_Site_Final_Staging__c clonedRecord = new Account_Site_Final_Staging__c(Id=stagingRec.Id);
            clonedRecord.Sync_Failed__c = true;
            clonedRecord.Sync_Failed_Reason__c = syncFailedMessageMap.get(acct.AOPS_Seq_ID__c);
            clonedRecords.add(clonedRecord);
        }
        
        update clonedRecords;
    }
    
    private void handleSyncFailure(Exception e) {
        System.debug('Exception in AOPSSyncToSiteProcessor = ' + e.getMessage());
        System.debug('Exception occurred: ' + e.getStackTraceString());        
    }   
}