objects/Account.object
<CustomObject>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Split_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Split Record</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer Accounts</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Parent</fullName>
        <active>true</active>
        <label>Parent</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <description>OMX Primary Key</description>
        <externalId>true</externalId>
        <inlineHelpText>OMX Primary Key</inlineHelpText>
        <label>OMX Primary Key</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>InActive</fullName>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Customer_Transition__c.object
<CustomObject>
    <description>Object to Track Customer Conversion and Review Project</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Transition Relationship</relationshipLabel>
        <relationshipName>Customer_Transition_Relationship</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BulkSplit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used in bulk launch batch class. set from customer transition trigger when sites&gt;6000</description>
        <label>BulkSplit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MOD5_Ready_To_Launch__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MOD5-Ready To Launch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mod5TriggerContact__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to Process Contact Batch in bulk for Split . set in class Mod5Bulk batch and used in class
Mod5InsertCntcBatchV3</description>
        <label>Mod5TriggerContact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Ready_for_Mod1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ready for Account Setup/Mod 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Split_Launching_Status__c</fullName>
        <label>Split Launching Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Fail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field will update dynamically per your selections.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>UnScheduled</fullName>
                    <color>#0B6FCE</color>
                    <default>true</default>
                    <label>UnScheduled</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                    <color>#78C953</color>
                    <label>Scheduled</label>
                </value>
                <value>
                    <fullName>ReScheduled</fullName>
                    <color>#E27001</color>
                    <label>ReScheduled</label>
                </value>
                <value>
                    <fullName>On Deck</fullName>
                    <color>#F3D904</color>
                    <label>On Deck</label>
                </value>
                <value>
                    <fullName>Launched</fullName>
                    <color>#009900</color>
                    <label>Launched</label>
                </value>
                <value>
                    <fullName>Transition Complete</fullName>
                    <color>#A53711</color>
                    <label>Transition Complete</label>
                </value>
                <value>
                    <fullName>Audit 2</fullName>
                    <color>#66E9BD</color>
                    <label>Audit 2</label>
                </value>
                <value>
                    <fullName>Loss of Customer</fullName>
                    <color>#0B24BE</color>
                    <label>Loss of Customer</label>
                </value>
                <value>
                    <fullName>OMX Extension in Development</fullName>
                    <color>#419249</color>
                    <label>OMX Extension in Development</label>
                </value>
                <value>
                    <fullName>Ready to Order</fullName>
                    <color>#B6E32E</color>
                    <label>Ready to Order</label>
                </value>
                <value>
                    <fullName>Ready for eCom Mod</fullName>
                    <color>#641CCF</color>
                    <label>Ready for eCom Mod</label>
                </value>
                <value>
                    <fullName>Redirect Stopped</fullName>
                    <color>#F96FB7</color>
                    <label>Redirect Stopped</label>
                </value>
                <value>
                    <fullName>Auto Redirected</fullName>
                    <color>#2F5D85</color>
                    <label>Auto Redirected</label>
                </value>
                <value>
                    <fullName>Awaiting Disposition</fullName>
                    <color>#AFCADF</color>
                    <label>Awaiting Disposition</label>
                </value>
                <value>
                    <fullName>Awaiting RFP</fullName>
                    <color>#8F6429</color>
                    <label>Awaiting RFP</label>
                </value>
                <value>
                    <fullName>Administrative Close</fullName>
                    <color>#EFAE73</color>
                    <label>Administrative Close</label>
                </value>
                <value>
                    <fullName>TOOP</fullName>
                    <color>#F96FB7</color>
                    <label>TOOP</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Transition</label>
    <nameField>
        <label>Customer Transition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Transition</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/CustTransParentChildLevel__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>SOA_EndPoint__c</fullName>
        <label>SOA EndPoint</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>soa_user__c</fullName>
        <label>soa user</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Cust Trans Parent Child Level</label>
</CustomObject>

objects/Split_Account_Detail__c.object
<CustomObject>
    <fields>
        <fullName>AP_CONTACT_FIRST_NAME__c</fullName>
        <label>AP CONTACT FIRST NAME</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AP_CONTACT_LAST_NAME__c</fullName>
        <label>AP CONTACT LAST NAME</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AP_CONTACT_TELEPHONE__c</fullName>
        <label>AP CONTACT TELEPHONE #</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ContactsAdded__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used in Bulk split contact Batch Mod5InsertCntcBatchV3</description>
        <label>Contacts Added</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Customer_Transition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Customer Transition</label>
        <referenceTo>Customer_Transition__c</referenceTo>
        <relationshipLabel>Split Account Details</relationshipLabel>
        <relationshipName>Split_Account_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Linked_Customer_Transition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Linked Customer Transition</label>
        <referenceTo>Customer_Transition__c</referenceTo>
        <relationshipLabel>Split Account Details (Linked Customer Transition)</relationshipLabel>
        <relationshipName>Split_Account_Details1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Main_Account_Name__c</fullName>
        <label>NEW ACCOUNT NAME</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_Account__c</fullName>
        <label>NEW OMX ACCOUNT #</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NEW_BILLING_TYPE_AT_HEADER_LEVEL__c</fullName>
        <label>NEW BILLING TYPE AT HEADER LEVEL</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NEW_BILL_TO_OMX_CONSIGNEE__c</fullName>
        <label>NEW BILL TO OMX CONSIGNEE #</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NEW_MAIN_ACCT_ADDRESS__c</fullName>
        <label>NEW MAIN ACCT ADDRESS</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Original_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Split Account Details</relationshipLabel>
        <relationshipName>Split_Account_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Split Account Detail</label>
    <nameField>
        <label>Split Account Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Split Account Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Mod5InsertCntcBatchV3_TC.cls
/******************************************************
* Name : Mod5InsertCntcBatchV3_TC
* Created By : Alka Taneja
* Created Date : 16 June, 2016
* Story : S-418600 (00715635)
/******************************************************/
@isTest(seeAllData=false)
public class Mod5InsertCntcBatchV3_TC{

    public static Split_Account_Detail__c eachCTdtls;
    public static Customer_Transition__c ct;
    public static Account acc;
    public static Contact c1;
    
    public static testMethod void TestActvityCreation() {
        
        Test.startTest();
        
        createTestData();
        
        Mod5InsertCntcBatchV3 ob = new Mod5InsertCntcBatchV3();
        Database.executeBatch(ob, 200);
        
        Test.stopTest();
    }
    
    public static void createTestData() {
    
      // Create sample data
      CustTransParentChildLevel__c custPCLevel = new CustTransParentChildLevel__c();
      custPCLevel.name = 'Parent_Child';
      custPCLevel.SOA_EndPoint__c = 'https://osbuat01.officedepot.com/';
      custPCLevel.soa_user__c = 'SVC-SFDCWS:SVC4sfd3';
      insert custPCLevel;
      
      acc = Test_Utils.createAccount('Customer (OfficeMax)');
      acc.Split_Record__c = true;
      insert acc;
      acc.OMX_Primary_Key__c = acc.Id;
      update acc;
      
      c1 = new Contact();
      c1.LastName='LastNametest1';
      c1.email='testemail1@test.com';
      c1.AccountId = acc.id;
      c1.firstname='first';
      c1.OMX_primary_key__c='1234';
      c1.title = 'Manager';
      c1.Primary_Contact__c = true;
      insert c1;
      
      ct = Test_Utils.createCustomerTransaction(false, acc);
      ct.MOD5_Ready_To_Launch__c = true;
      ct.Ready_for_Mod1__c = false;
      ct.Name = 'Customer Transition Parent of TestAccount';
      ct.BulkSplit__c = true;
      ct.OMX_Primary_Key__c = acc.Id + '-1';
      ct.Status__c = 'Scheduled';
      ct.Mod5TriggerContact__c = true;
      ct.Split_Launching_Status__c = 'Success';
      ct.account__c = acc.id;
      insert ct;
      
      eachCTdtls = new Split_Account_Detail__c();
      eachCTdtls.status__c='';
      eachCTdtls.Master_Account__c ='123458-01';
      eachCTdtls.Customer_Transition__c =ct.id;
      eachCTdtls.AP_CONTACT_FIRST_NAME__c ='First';
      eachCTdtls.AP_CONTACT_LAST_NAME__c ='Last';
      eachCTdtls.NEW_BILLING_TYPE_AT_HEADER_LEVEL__c ='Di';
      eachCTdtls.Original_Account__c = acc.id;
      eachCTdtls.AP_CONTACT_TELEPHONE__c ='12345698789';
      eachCTdtls.NEW_BILL_TO_OMX_CONSIGNEE__c = '123456';
      eachCTdtls.NEW_MAIN_ACCT_ADDRESS__c = '123456';
      eachCTdtls.Main_Account_Name__c ='New Name';  
      eachCTdtls.Linked_Customer_Transition__c = ct.id;
      eachCTdtls.ContactsAdded__c = false;
      insert eachCTdtls;
      
    }
}