objects/Account.object
<CustomObject>
    <fields>
        <fullName>AOPS_Cust_Id__c</fullName>
        <description>AOPS Customer Account Number</description>
        <externalId>true</externalId>
        <label>AOPS Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Account_Extension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Extension</label>
        <referenceTo>Account_Extension__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Owner__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; 
&amp; Sales_PersonID__r.User__r.Id, 
Sales_PersonID__r.User__r.FirstName+&apos; &apos;+Sales_PersonID__r.User__r.LastName 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address1__c</fullName>
        <label>Address1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <description>Prospect Accounts</description>
        <label>Prospect</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Account_Dormant__c.object
<CustomObject>
    <fields>
        <fullName>AOPS_Cust_Id__c</fullName>
        <externalId>true</externalId>
        <label>AOPS Cust Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountExtension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Extension</label>
        <referenceTo>Account_Extension__c</referenceTo>
        <relationshipName>Account_Dormant</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>AccountExtension__r.Account_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Owner__c</fullName>
        <formula>AccountExtension__r.Account_Owner__r.Alias</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Owner Alias</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address1__c</fullName>
        <externalId>true</externalId>
        <label>Address1</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Original_Account_ID__c</fullName>
        <externalId>true</externalId>
        <label>Original Account ID</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Dormant Account Duplicate</label>
    <nameField>
        <label>Account Dormant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dormant Account Duplicates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account_Extension__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>AOPS_Cust_Id__c</fullName>
        <description>AOPS Customer Account Number</description>
        <externalId>true</externalId>
        <label>AOPS Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Dormants1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Extensions (Account)</relationshipLabel>
        <relationshipName>Account_to_extension</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address1__c</fullName>
        <label>Address1</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Original_Account_ID__c</fullName>
        <externalId>true</externalId>
        <label>Original Account ID</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Account Extension</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Extensions</pluralLabel>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <label>[Prospect]</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Account_Owner__c</fullName>
        <label>Account Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Profile_Extension_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Profile Extension Account</label>
        <referenceTo>Account_Extension__c</referenceTo>
        <relationshipLabel>Account Profile</relationshipLabel>
        <relationshipName>Account_Profile</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Profile</relationshipLabel>
        <relationshipName>Account_Profile1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Profile_Unique_Name__c</fullName>
        <externalId>true</externalId>
        <label>Profile Unique Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Account Profile</label>
    <nameField>
        <label>Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Profile</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Data_Cleansing_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>SYSTEM_ACCOUNT__c</fullName>
        <label>SYSTEM ACCOUNT</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Data Cleansing Settings</label>
</CustomObject>

objects/DNBI_Credentials__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To provide the Credentials to connect to DNBI System</description>
    <fields>
        <fullName>DnB_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If Checked will enable the DNBI functionality in the Account Triggers</description>
        <label>DnB Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <label>UserName</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>DNBI Credentials</label>
</CustomObject>

classes/AccountRestore_TC.cls
@isTest
private class AccountRestore_TC {
    static User testUser;
    private static testMethod void restoreAPItest() {
         testUser = Test_Utils.createTestUser('tes46','9965445');
               Id SystemId= Schema.SObjectType.Account.getRecordTypeInfosByName().get('System').getRecordTypeId();
               Id ProspectId= Schema.SObjectType.Account.getRecordTypeInfosByName().get('Prospect').getRecordTypeId();

         
         System.RunAs(testUser){
         
         DNBI_Credentials__c cred = new DNBI_Credentials__c(name='Test',UserName__c='Test',DnB_Active__c=true);
         insert cred;
         
         
         List<Account> accInsert= new List<Account>();
             Data_Cleansing_Settings__c dc = new Data_Cleansing_Settings__c(system_account__c='SYSTEMCLEANSE');
             insert dc;
             String systemAccount = [SELECT id,system_account__c from Data_Cleansing_Settings__c].system_account__c;
             Account account = new Account(Name = 'acct1',AOPS_Cust_Id__c='123456');
             accInsert.add(account);
             
             
             Account accountSystem = new Account(Name = systemAccount,AOPS_Cust_Id__c='987654',recordtypeId=SystemId);
             accInsert.add(accountSystem);
             
             Account accountProspect = new Account(Name = 'TetProspect',recordtypeId=ProspectId,Address1__c ='Test');
             accInsert.add(accountProspect);


              insert accInsert;
             
             
             Account_Extension__c ae=[select id from account_extension__c where Original_Account_ID__c=:account.id]; 
             ae.Account_Owner__c=testUser.Id;
             ae.Account_Name__c='TestExt';
             update ae;                        
             
                       System.debug('&&&&&&&&&&&&&extensionTestClass'+ae.Id);

             
            Test.starttest();

             
             //Account_Extension__c aeSystem=[select id from account_extension__c where Original_Account_ID__c=:accountSystem.id];
             Account_Profile__c ap = new Account_Profile__C(account__c=accountSystem.id,
                                                            Account_Profile_Extension_Account__c=ae.id,
                                                            Profile_Unique_Name__c = 'XYZ'+accountSystem.name);
             insert ap;
             
             //***********logic is occuring for both insert and update 
            ap.Account_Profile_Extension_Account__c = ae.id;
            update ap;

                          
             Account_Dormant__C ad = new Account_Dormant__c(AccountExtension__c = ae.id);
             insert ad;
             delete account;
             
             //account_profile__c a = [select id from account_profile__C where Account_Profile_Extension_Account__c=:ae.id];
             
             Account_Extension__c  recId=[ select account__C from Account_Extension__c where Id =:ae.id];
             System.debug('&&&&&&&&&&&& extension Record'+recId.account__C );
            
             list<Account_Dormant__c> adList = new list<Account_Dormant__c>();
             adList.add(ad);
             AccountRestore ar = new AccountRestore();
             executeoncetest.bypassAccountExtension = false;
             ar.restoreAccount(adList,'Sales Exist','');
             
             update accountProspect;
             Test.stoptest();

             
         }
    }
    
    
}