objects/Account.object
<CustomObject>
    <fields>
        <fullName>Site</fullName>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer Accounts</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Site</fullName>
        <active>true</active>
        <label>Site</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Lattice_Play__c.object
<CustomObject>
    <fields>
        <fullName>Account_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Lattice_Plays1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Appirio Lattice Play</label>
    <nameField>
        <displayFormat>LP-{0000}</displayFormat>
        <label>Lattice Play Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lattice Plays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LatticePlaysTriggersTest.cls
// Appirio 2015
//
// Test class for LatticePlaysTriggers 
// LSLEVIN - Original - 2.18.2016 - S-376888
@isTest
private class LatticePlaysTriggersTest {
	
	@isTest static void test_LatticePlaysTriggerCustomer() {
		Schema.DescribeSObjectResult schemaA = Schema.SObjectType.Account; 
		Map<String,Schema.RecordTypeInfo> AccountRecordTypeInfo = schemaA.getRecordTypeInfosByName();


		Account acc = new Account();
		acc.Name = 'Testing LP Account';
		acc.recordTypeId = AccountRecordTypeInfo .get('Customer').getRecordTypeId();
		insert acc;

		Lattice_Play__c lp = new Lattice_Play__c();
		lp.Account_Id__c = acc.Id;
		insert lp;
	}

	@isTest static void test_LatticePlaysTriggerSite() {
		Schema.DescribeSObjectResult schemaA = Schema.SObjectType.Account; 
		Map<String,Schema.RecordTypeInfo> AccountRecordTypeInfo = schemaA.getRecordTypeInfosByName();


		Account acc = new Account();
		acc.Name = 'Testing LP Account';
		acc.recordTypeId = AccountRecordTypeInfo .get('Site').getRecordTypeId();
		insert acc;

		Lattice_Play__c lp = new Lattice_Play__c();
		lp.Account_Id__c = acc.Id;
		insert lp;
	}

	@isTest static void test_LatticePlaysTriggerNull() {
		Account acc = new Account();
		acc.Name = 'Testing LP Account';
		insert acc;

		Lattice_Play__c lp = new Lattice_Play__c();
		insert lp;
	}
	
}