objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip/Postal Code</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>InActive</fullName>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GPO_Lead__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>GPO_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Name__c</fullName>
        <label>Company name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WCW_Range__c</fullName>
        <label>WCW Range</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1-19</fullName>
                    <default>true</default>
                    <label>1-19</label>
                </value>
                <value>
                    <fullName>20-49</fullName>
                </value>
                <value>
                    <fullName>50-99</fullName>
                </value>
                <value>
                    <fullName>100-149</fullName>
                </value>
                <value>
                    <fullName>150-199</fullName>
                </value>
                <value>
                    <fullName>200-249</fullName>
                </value>
                <value>
                    <fullName>250-500</fullName>
                </value>
                <value>
                    <fullName>500+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>first_name__c</fullName>
        <label>First name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>User Registration</label>
    <nameField>
        <label>GPO  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>(Tech-Zone)</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>Site (OfficeMax)</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>Site (GT)</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>Site</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Qualifying Deals</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Used in PRM for deal registration</description>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Used in PRM for Deal Registration</description>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <inlineHelpText>This field is required in order to convert  (Unless lead is directly linked to an account)</inlineHelpText>
        <label>Zip/Postal Code</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/GPOLead.cls
public class GPOLead {

public gpo_lead__c glead {get;set;}
public boolean successMsg {get;set;}
public boolean errorMsg {get;set;}
public boolean showForm {get;set;}
public String errorText {get;set;}
public String parentAccid {get;set;}

public GPOLead() {
   system.debug('test2');
   glead = new GPO_Lead__c();
   successMsg = false;
   errorMsg = false;
   showForm=true;
   
}

public GPOLead(GPOCommunityLandingController controller) {
system.debug('No Code');
  
}

public void newLead() {
   system.debug('Inside Lead Create');
   glead = new GPO_Lead__c();
   successMsg = false;
   errorMsg = false;
   showForm=true;
}

public void saveLead() {

try
{
parentAccid = ApexPages.currentPage().getParameters().get('id');
if (glead.first_name__c == null || glead.last_name__c == null || glead.Phone__c == null || glead.Email__c == null || glead.Business_Name__c == null 
     || glead.Zip__c == null || glead.WCW_Range__c == null) {
  errorText = 'Error: Please Enter All the Required Fields';
  errorMsg = true;
  successMsg = false;
}
else {
system.debug('Successful');
 if (parentAccid != null) {
    list<account> acc = [select id from account where id = :parentAccid];
    if (acc.size() > 0)
     glead.Account__c = parentAccid;
 }
 glead.status__c = 'New';
 insert glead;
 successMsg = true;
 errorMsg=false;
 showForm=false;
}
 }
 catch(Exception e) {
  system.debug('Unexpected Error:' + e);
  errorText = 'Error: Lead Submission Failed, Please contact Administractor.';
  errorMsg = true;
  successMsg = false;
 }
}

}