objects/Account.object
<CustomObject>
    <fields>
        <fullName>Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Org/Company</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Accounts/Sites</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <description>Prospect Accounts</description>
        <label>Prospect</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/DML__c.object
<CustomObject>
    <fields>
        <fullName>DECISION_MAKER_NM__c</fullName>
        <externalId>true</externalId>
        <label>DML Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effective_Start_Date__c</fullName>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Org</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>DML</relationshipLabel>
        <relationshipName>DML</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DML</label>
    <nameField>
        <displayFormat>DML-{0000000}</displayFormat>
        <label>DML ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DML</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DML_Relation__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Account Setup Requested, Customer, Prospect, Customer (OfficeMax)</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>DML Relationship</relationshipLabel>
        <relationshipName>DML_Relations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DML__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DML ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>DML__c.Status__c</field>
                <operation>notContain</operation>
                <value>Rejected,Draft</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>DML__c</referenceTo>
        <relationshipLabel>DML Relationship</relationshipLabel>
        <relationshipName>DML_Relations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Start_Date__c</fullName>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Org</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipName>DML_Relations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DML Relationship</label>
    <nameField>
        <displayFormat>DR-{0000}</displayFormat>
        <label>DML Relation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DML Relationship</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <description>Representation of Customer Relationship Hierarchy Node</description>
    <fields>
        <fullName>DML__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DML</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Org</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipName>Orgs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Org</label>
    <nameField>
        <displayFormat>Org-{0000}</displayFormat>
        <label>Org Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountSummaryController_TC.cls
@isTest
public class AccountSummaryController_TC {
    @isTest
    private static void findAll() {    
     Org__C org = MyUtils_Org.GenerateOrg(123);
        insert org; 
        Org__C orgchild = MyUtils_Org.GenerateOrg(14);
        orgchild.Parent_Org__c=org.id;
        insert orgchild; 
        Org__C orgchild1 = MyUtils_Org.GenerateOrg(10);
        orgchild1.Parent_Org__c=orgchild.id;
        insert orgchild1; 
        Org__C orgchild2 = MyUtils_Org.GenerateOrg(13);
        orgchild2.Parent_Org__c=orgchild1.id;
        insert orgchild2; 
        Account prospectAccount = Test_Utils.CreateAccount('Prospect');
        prospectAccount.org__C = org.id;
        AccountSummaryController.findAll(Org.Id);
    }
  @isTest
    private static void getdml() {    
    Org__C org = MyUtils_Org.GenerateOrg(12);
        insert org;    
        Account prospectAccountnew = Test_Utils.CreateAccount('Prospect');
        prospectAccountnew.org__C = org.id;
        insert prospectAccountnew;      
        DML__C dml = new DML__C(DECISION_MAKER_NM__c='tst',Effective_Start_Date__c=system.today());
        //dml.Effective_Start_Date__c = system.today()-3;
        insert dml;
        DML_Relation__c dmlr = new DML_Relation__c(DML__C=dml.id,org__C=org.id,Account__C=prospectAccountnew.id,Effective_Start_Date__c=system.today());
        insert dmlr;
          AccountSummaryController.getdml(prospectAccountnew.Id);
        AccountSummaryController.getAccid(prospectAccountnew.Id);
        
    }
}