objects/Account.object
<CustomObject>
    <fields>
        <fullName>AOPS_Cust_Id__c</fullName>
        <description>AOPS Customer Account Number</description>
        <externalId>true</externalId>
        <label>AOPS Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>AOPS_Seq_ID__c</fullName>
        <externalId>true</externalId>
        <label>AOPS Seq ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Loyatly_Number__c</fullName>
        <description>Business Pro - Stores loyalty data</description>
        <externalId>true</externalId>
        <label>Loyalty Number</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Oracle_Party_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Party ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sales_PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is used for Primary Owner Sales ID.</description>
        <label>Sales Person ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sales_Person__c.Primary__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Person__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer Accounts</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Loyalty_Number__c</fullName>
        <description>Used by Business Pro for creating contacts from DW</description>
        <externalId>true</externalId>
        <label>Loyalty Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <description>OMX Primary Key</description>
        <externalId>true</externalId>
        <inlineHelpText>OMX Primary Key</inlineHelpText>
        <label>OMX Primary Key</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Person__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Person_IDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Person ID</label>
    <nameField>
        <label>Sales Person ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Person IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BusinessProTrigger_TC.cls
@IsTest
public class BusinessProTrigger_TC
{
    static testMethod void businessProTriggerTest() 
    {
        Recordtype rcrdTypeObj = [select id from recordtype where recordtype.name = 'Customer (Business Pro)' limit 1];

        //Profile prfleObj = [SELECT Id FROM Profile WHERE Name='Business Pro Rep'];

        User usrObj = [select id from user where name = 'Dataloader' limit 1];
        System.runAs (usrObj)
        { 
            Sales_Person__c slsPrsnObj = new Sales_Person__c();
            slsPrsnObj.IsActive__c = true;
            slsPrsnObj.Primary__c = true;
            slsPrsnObj.User__c = usrObj.id;
            insert slsPrsnObj;

            Account acc = new Account ();
            acc.recordtypeId=rcrdTypeObj.id;
            acc.name = 'SUN Test Account1';
            acc.BillingStreet = '1039 N 326 W';
            acc.billingcity = 'Orem';
            acc.BillingState = 'UT';
            acc.Billingcountry = 'USA';
            acc.Oracle_Party_Id__c = '09856';
            acc.AOPS_Cust_Id__c = '09856';
            acc.AOPS_Seq_ID__c = '09856';
            acc.OwnerID = usrObj.id;
            acc.Sales_PersonID__c = slsPrsnObj.id;
            acc.Loyatly_Number__c='11223';
            insert acc;

            Contact conObj = new Contact();
            conObj.LastName='LastName BusinessPro';
            conObj.email='testemail11@test.com';
            conObj.OMX_Primary_Key__c='123456';
            conObj.Loyalty_Number__c='11223';
            conObj.Primary_Contact__c=true;
            insert conObj;
        }
    }
    

}