objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <description>Prospect Accounts</description>
        <label>Prospect</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/DML__c.object
<CustomObject>
    <fields>
        <fullName>Decision_Maker_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DML Sales Rep ID</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Sales_Person__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Person__c</referenceTo>
        <relationshipLabel>DMLs</relationshipLabel>
        <relationshipName>DMLs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_End_Date__c</fullName>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Start_Date__c</fullName>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <label>DML</label>
    <nameField>
        <displayFormat>DML-{0000000}</displayFormat>
        <label>DML ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DML</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DML_Relation__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Account Setup Requested, Customer, Prospect, Customer (OfficeMax)</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>DML Relationship</relationshipLabel>
        <relationshipName>DML_Relations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DML__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DML ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>DML__c.Status__c</field>
                <operation>notContain</operation>
                <value>Rejected,Draft</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>DML__c</referenceTo>
        <relationshipLabel>DML Relationship</relationshipLabel>
        <relationshipName>DML_Relations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_End_Date__c</fullName>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Start_Date__c</fullName>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <formula>if((ISNULL(Effective_End_Date__c)  || Effective_End_Date__c &gt; today() ) &amp;&amp; ( BLANKVALUE(Effective_End_Date__c , today()+100 )&gt;    Effective_Start_Date__c) &amp;&amp; (Effective_Start_Date__c &lt;=today() ) ,TRUE,FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>DML Relationship</label>
    <nameField>
        <displayFormat>DR-{0000}</displayFormat>
        <label>DML Relation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DML Relationship</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Person__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Person_IDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Person ID</label>
    <nameField>
        <label>Sales Person ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Person IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DMLDisplay_Test.cls
@IsTest
public without sharing class DMLDisplay_Test {
    
    @TestSetup
    static void makeData(){

        Schema.RecordTypeInfo prospect_recordtype = MyUtils.getRecordTypeInfo('Account', 'Prospect');
        Account my_account = new Account(
            Name='Test_Account',
            RecordTypeId = prospect_recordtype.getRecordTypeId()
        );

        insert my_account;

        Sales_Person__c my_sales_person = new Sales_Person__c(
            IsActive__c = true,
            Primary__c = true,
            Name = 'TSP100',
            User__c = UserInfo.getUserId()
        );
        insert my_sales_person;

        DML__c my_dml = new DML__c(
            Effective_Start_Date__c = Date.today() - 1,
            Effective_End_Date__c = Date.today() + 10,
            Decision_Maker_Rep__c = my_sales_person.Id
        );
        insert my_dml;

        DML_Relation__c my_relation = new DML_Relation__c(
            DML__c = my_dml.Id,
            Account__c = my_account.Id,
            Effective_Start_Date__c = Date.today() - 1,
            Effective_End_Date__c = Date.today() + 10
        );

        insert my_relation;
    }

    @isTest
    public static void test_valid_run(){
        Test.startTest();
        Account my_account = [SELECT Id FROM Account LIMIT 1];
        System.debug(LoggingLevel.INFO, my_account);
        DML__c my_dml = [SELECT Id FROM DML__c LIMIT 1];
        System.debug(LoggingLevel.INFO, my_account);
        DML_Relation__c my_dml_relation = [SELECT Id FROM DML_Relation__c WHERE IsActive__c=true LIMIT 1];
        System.debug(LoggingLevel.INFO, my_account);
        
        System.assertEquals(my_dml.Id, DmlDisplay.getDmlIdFromAccount(my_account.Id)); 

        Test.stopTest();
    }

    @isTest
    public static void test_exception(){
        Test.startTest();
        Account my_account = [SELECT Id FROM Account LIMIT 1];
        DML__c my_dml = [SELECT Id FROM DML__c LIMIT 1];
        DML_Relation__c my_dml_relation = [SELECT Id FROM DML_Relation__c WHERE IsActive__c=true LIMIT 1];
        DELETE my_dml_relation;

        try{
            DmlDisplay.getDmlIdFromAccount(my_account.Id);
        } catch (Exception e){
            System.debug(LoggingLevel.INFO, 'We caught it.');
        }
        Test.stopTest();
    }
}