objects/Account.object
<CustomObject>
    <fields>
        <fullName>AOPS_Cust_Id__c</fullName>
        <description>AOPS Customer Account Number</description>
        <externalId>true</externalId>
        <label>AOPS Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>AOPS_Seq_ID__c</fullName>
        <externalId>true</externalId>
        <label>AOPS Seq ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Current_GPO__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Current GPO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Oracle_Party_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Party ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sales_PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is used for Primary Owner Sales ID.</description>
        <label>Sales Person ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sales_Person__c.Primary__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Person__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>GrandParent</fullName>
        <active>true</active>
        <description>Used for GP Maintenance</description>
        <label>GrandParent</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/GPOLookUpController_TC.cls
@isTest
public class GPOLookUpController_TC {
    static testmethod void InsertRec(){	    
        Id GrandParent_RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('GrandParent').getRecordTypeId();
        Account acc = new Account ();
        acc.name = 'SUN Test Account';
        acc.BillingStreet = '1040 N 326 W';
        acc.billingcity = 'Orem';
        acc.BillingState = 'UT';
        acc.Billingcountry = 'USA';
        acc.Oracle_Party_Id__c = '123456';
        acc.AOPS_Cust_Id__c = '123456';
        acc.AOPS_Seq_ID__c = '123456';
        acc.OwnerID = '005E0000000lNbV';// This is the salesforce User ID
        acc.Sales_PersonID__c = 'a0AE0000000GGMn'; //Sales person Id for the Salesforce USer
        acc.RecordtypeId=GrandParent_RecordTypeId;
        acc.Current_GPO__c=true;
        insert acc;
        GPOLookUpController.fetchLookUpValues('SUN Test Account');
    }
    
}