objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer Accounts</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Fact_Sheet__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Facts_Sheet</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Additional_Account_Handling_Comments__c</fullName>
        <label>Additional Account Handling Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Can_Customer_Care_Maintain_Account__c</fullName>
        <label>Can Customer Care Maintain Account?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Can_Restrictions_Be_Overridden_Without_A__c</fullName>
        <label>Can Restrictions Be Overridden W/O Appr</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Custmustclearcreditpriortorebill__c</fullName>
        <inlineHelpText>When rebilling orders to correct rejections, does the customer need to receive the credit to clear the rejected invoice from their system?</inlineHelpText>
        <label>Cust must clear credit prior to rebill</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Intelligent Document</label>
    <nameField>
        <displayFormat>FS-{00000000}</displayFormat>
        <label>Fact Sheet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Intelligent Document</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RelatedCIDCtrl_Test.cls
/**
* @author Sandesh Ganjare, sandesh.ganjare@officedepot.com
* @date 08/09/2020
*
* 
* @description This class fetch all the records of Customer Intelligent Document object related to Accounts in hierarchy.
*              
*               Test class => RelatedCustomerIntelligentDocumentCtrl class
* JIRA: NAIT-137444: 02944812 - Ability to Input/Maintain Fact Sheet Fields in SFDC
*/
@isTest
public class RelatedCIDCtrl_Test {
    @testSetup static void setup() {
        List<Account> TestAccountGP =  DataFactory.createAccountTestRecords('Account',1,'');
       
        List<Account> TestAccount =  DataFactory.createAccountTestRecords('Test Account',1,TestAccountGP[0].Id);
        //TestAccount[0].Parentid = TestAccountGP[0].Id;
        //UPDATE TestAccount;

        Fact_Sheet__c fs = new Fact_Sheet__c();
        fs.Can_Customer_Care_Maintain_Account__c='No';
        fs.Can_Restrictions_Be_Overridden_Without_A__c='No';
        fs.Custmustclearcreditpriortorebill__c='No';
        fs.Account__c= TestAccount[0].Id;
        fs.Additional_Account_Handling_Comments__c='Test Test';
        INSERT fs;
     }
 
     @IsTest
     static void getRelatedCIDTest(){
        List<Fact_Sheet__c> customerIntelligentDocumentList = new List<Fact_Sheet__c>();
        List<Account> accountList = [SELECT id,Parentid FROM Account Where Parentid!=null LIMIT 1 ];
        Test.StartTest();
            customerIntelligentDocumentList = RelatedCustomerIntelligentDocumentCtrl.getRelatedCID(String.valueOf(accountList[0].Id));
        Test.StopTest();
        System.assertEquals(true,customerIntelligentDocumentList.size()>0);
     }
}