objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Admin_Config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Administrative configurations such as endpoints, privileged users, etc.</description>
    <fields>
        <fullName>Ownership_Changes_Batch__c</fullName>
        <description>This is used by the batch programs - AccountHeaderAccess_Batch.cls and OpportunityOwnerChanges_Batch.cls</description>
        <label>Ownership Changes Batch</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Admin Config</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Related_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Is this opportunity related to site? If so please select.</inlineHelpText>
        <label>Related Site</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Related site must be a child site of the Opportunity&apos;s Account. You have picked a site that is not related to the account.  
Quick Tip: Create an opportunity from a Site Page and it will bring in Account &amp; Site info automatically.</errorMessage>
            <filterItems>
                <field>Account.Related_Account__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>(Tech-Zone)</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ActivatedbyBatch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is activated by batch to overcome the Account Assignment Failures</description>
        <label>ActivatedbyBatch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reassgin_Opportunity__c</fullName>
        <label>Reassgin Opportunity</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/OpportunityOwnerChanges_Batch.cls
global class OpportunityOwnerChanges_Batch implements database.Batchable<Sobject>, Schedulable
{
 public String opp_query= 'SELECT id,account.id,account.ownerid,ownerid,account.owner.isactive,related_site__r.ownerid,related_site__r.owner.isactive from opportunity'
                          + ' where owner.Reassgin_Opportunity__c IN (\'NP\',\'P\') and owner.ActivatedbyBatch__c != true';
 
    global OpportunityOwnerChanges_Batch ()
    {
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC)
    {            
        System.debug('Opportunity Query ===== = '+opp_query);
        return Database.getQueryLocator(opp_query);
    }
    
    global void execute(Database.BatchableContext BC, SObject[] scope)
    {
      list<opportunity> opp_list = scope;
      list<opportunity> opp_upd = new list<opportunity> ();
      list<ID> user_id = new list<ID> ();
      list<user> update_users = new list<user> ();
      Map<id,boolean> users_partial_update = new Map<id,boolean> ();
       
      For (opportunity o: opp_list) {
       if (o.related_site__r.owner.isactive) {
          user_id.add(o.ownerid);
          o.ownerid = o.related_site__r.ownerid;
          opp_upd.add(o);
       }
       else if (o.account.owner.isactive) {
         user_id.add(o.ownerid);
         o.ownerid = o.account.ownerid;
         opp_upd.add(o);
       }
       else
        users_partial_update.put(o.ownerid,true);  
        
      }
 
      for (user u: [SELECT ID FROM USER WHERE ID = :user_id]) {
       if (!users_partial_update.containskey(u.id)) {
         u.Reassgin_Opportunity__c = 'C';
         update_users.add(u);
        }
       else {
         u.Reassgin_Opportunity__c = 'P';
         update_users.add(u);
       }
      }
      try{
     Database.update(opp_upd,false);
      Database.update(update_users,false);
      }
      catch(Exception e)
      {
      system.debug('@@@@'+e);
      }
    }
    
    global void finish(Database.BatchableContext BC)
    {
        
    }
    
    global void execute(SchedulableContext sc)
    {
        integer batch_size = 100;
        OpportunityOwnerChanges_Batch oppBatch = new OpportunityOwnerChanges_Batch();
        Admin_Config__c ownerbatch = Admin_Config__c.getvalues('Default');
        if (ownerbatch.Ownership_Changes_Batch__c != null)
          batch_size = integer.valueof(ownerbatch.Ownership_Changes_Batch__c);
        database.executebatch(oppBatch, batch_size);      
         
    } 
    
}