objects/Account.object
<CustomObject>
    <fields>
        <fullName>Parent_ID__c</fullName>
        <formula>iF(CONTAINS(RecordType.Name, &apos;Site&apos;), Related_Account__r.Parent.Cust_ID__c, 
  IF(RecordType.Name ==&apos;Customer (GT)&apos;, Parent.OMX_Primary_Key__c, 
   IF(RecordType.Name ==&apos;Customer (OfficeMax)&apos;  &amp;&amp; Parent.OMX_Primary_Key__c!=&apos;&apos;, Parent.OMX_Primary_Key__c, Parent.AOPS_Cust_Id__c

   
  )
 )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent ID</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer Accounts</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Admin_Context__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Admin Context</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>(Tech-Zone)</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (Admin Context)</relationshipLabel>
        <relationshipName>Contacts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GPO_Community__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GPO Community</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>(Tech-Zone)</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (GPO Community)</relationshipLabel>
        <relationshipName>Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GPO_Community_Setup__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used for GPO Communities</description>
    <fields>
        <fullName>Admin_ProfileId__c</fullName>
        <description>This contains the ID for the super user admin profile and used to display admin header</description>
        <label>Admin ProfileId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Page__c</fullName>
        <label>Home Page</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Image_Path__c</fullName>
        <label>Image Path</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_Page__c</fullName>
        <label>Member Page</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>defaultRecordType__c</fullName>
        <label>defaultRecordType</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>enabled_group_recordtypeid__c</fullName>
        <label>enabled group recordtypeid</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>GPO Community Setup</label>
</CustomObject>

objects/GPO_Group__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>GPO Group</relationshipLabel>
        <relationshipName>GPO_Group</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Activated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>NOTE: Once activated, the Community can NOT be deactivated.</description>
        <inlineHelpText>NOTE: Once activated, the Community can NOT be deactivated.</inlineHelpText>
        <label>Activated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Community_Image__c</fullName>
        <label>Community Image</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>GPO_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GPO Template</label>
        <referenceTo>GPO_Template__c</referenceTo>
        <relationshipLabel>GPO Group</relationshipLabel>
        <relationshipName>GPO_Group</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <formula>IF(Account__r.ParentId != null, Account__r.ParentId,&apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ultimate_Parent2__c</fullName>
        <formula>IF(Account__r.ParentId != null,IF(Account__r.Parent.ParentId != null,  IF(Account__r.Parent.Parent.ParentId != null,Account__r.Parent.Parent.ParentId, Account__r.Parent.ParentId),Account__r.ParentId),Account__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Ultimate Parent2</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Welcome_Title__c</fullName>
        <label>Title</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>GPO Group</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>GPO Group</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GPO Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GPO_Lead__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>GPO_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GPO_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Community this user registered under, this field is used in email template.</description>
        <inlineHelpText>Community that this user registered under</inlineHelpText>
        <label>GPO Group</label>
        <referenceTo>GPO_Group__c</referenceTo>
        <relationshipLabel>User Registrations</relationshipLabel>
        <relationshipName>User_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Registration</label>
    <nameField>
        <label>GPO  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Registrations</pluralLabel>
    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <label>Default</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GPO_Template__c.object
<CustomObject>
    <fields>
        <fullName>Home_Page__c</fullName>
        <label>Home Page</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_Page__c</fullName>
        <label>Member Page</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>GPO Template</label>
    <nameField>
        <label>GPO Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GPO Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>(Tech-Zone)</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>Site (OfficeMax)</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>Site (GT)</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>Site</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Qualifying Deals</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>GT_Employee_ID__c</fullName>
        <description>This is the HR EMP Id from G&amp;T - Canada</description>
        <externalId>true</externalId>
        <label>GT Employee ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MB_Expiration_Date__c</fullName>
        <description>market Builder Exp date time for TOKEN</description>
        <label>MB Expiration Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OD_Employee_ID__c</fullName>
        <externalId>true</externalId>
        <label>OD Employee ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Token_Market_Builder__c</fullName>
        <description>The Token used for Market Builder App</description>
        <label>Token Market Builder</label>
        <length>100</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/GPOCommunityAdminLandingExt_TC.cls
/**
 Created by Najma Ateeq
 */
@isTest
private class GPOCommunityAdminLandingExt_TC {

    static testMethod void myUnitTest() {
        User user = getTestUser('System Administrator','aaab@officedepot.com','227112');
        //Account parentAcc = Test_Utils.getTestAccount(user,'123456');
        System.runAs(user){
        Account account = Test_Utils.getTestAccount(user,'123456');
        //system.debug('account--Najma'+account.Id);
         Account childAcc = Test_Utils.getTestAccount(user,'1234561');
        childAcc.ParentId = account.Id;
        update  childAcc;
        system.debug('childAcc--'+childAcc.Id);
       
        //account.Parent_ID__c =  parentAcc.Id;
        //update account;
        Contact contact =  CreateContact(account.Id);
        
        //User user = Test_Utils.getTestUser('System Administrator','aaa@officedepot.com','227112');
       
        GPO_Template__c gpoTemp = Test_Utils.createGPOTemplate('Sample Template',false);
        gpoTemp.Home_Page__c =  '/gpo/GPOHome';
        gpoTemp.Member_Page__c = '/gpo/GPOMember';
        insert gpoTemp;
        GPO_Community_Setup__c gpoCommunitySetup = Test_Utils.createGPOCommunitySetUp(gpoTemp,false);
        gpoCommunitySetup.member_page__C = '/gpo/GPOMember';
        gpoCommunitySetup.home_page__c = '/gpo/GPOHome';
        gpoCommunitySetup.image_path__c = '/gpo/servlet/servlet.FileDownload?file=';
        gpoCommunitySetup.enabled_group_recordtypeid__c = '012M00000000jDDIAY';
      //  Modified by Rahul Story S-371041
        gpoCommunitySetup.Admin_ProfileId__c = [select Id from Profile where Name ='Customer Community Login User - GPO Admin' limit 1].Id;
        gpoCommunitySetup.defaultRecordType__c = Schema.SObjectType.GPO_Group__c.getRecordTypeInfosByName().get('Template Default').getRecordTypeId(); 
        //End S-371041
        insert gpoCommunitySetup ;
         
        GPO_Group__c gpoGroup = Test_Utils.createGPOGroup(gpoTemp, account, false);
            gpoGroup.Welcome_Title__c = 'Test GPO Group Title';
            //gpoGroup.RecordTypeId = '012M00000000jDEIAY';
            gpoGroup.RecordTypeId = Schema.SObjectType.GPO_Group__c.getRecordTypeInfosByName().get('Template Default').getRecordTypeId(); //S-321807
           gpoGroup.Activated__c = true;
           gpoGroup.Account__c = account.Id;
          // gpoGroup.Ultimate_Parent2__c = account.Id;
            //gpoGroup.Community_Image__c = att.Id;
            //gpoGroup.Parent__c = account.Id;
        insert gpoGroup;
        //system.debug('-----Najma'+[select Id,Ultimate_Parent2__c from GPO_Group__c where id =: gpoGroup.Id limit 1]);
       Attachment att = new Attachment();
         att.Name = 'Test';
         att.body = Blob.valueOf('test');
         att.ParentId = gpoGroup.Id;
         insert att;
         gpoGroup.Community_Image__c = att.Id;
         update gpoGroup;
         
         //GPO_Lead__c lead = Test_Utils.createGPOLead(childAcc,true);
        //User portalUser = getCommunityUser('aaa@officedepot.com','227112',contact.Id);
        User portalUser = getCommunityUser('a_227198@officedepot.com','227198',contact.Id);
        System.runAs(portalUser){
            
            
            GPOCommunityAuthLandingController cntrl = new GPOCommunityAuthLandingController();
            //cntrl.selectedGroup = gpoGroup;
            
            GPOCommunityAdminLandingExt ex = new GPOCommunityAdminLandingExt(cntrl);
            ex.save();
            ex.getPagedAccounts();
            ex.getActiveNodes();
            
            
            
        }
        }
    }
    static User getCommunityUser(String userName,String empId,Id conId){
        Profile profileObj = [select id from profile where name= 'Customer Community Login User - GPO Admin'];
        String profId = profileObj.id;
        
        string email = userName;
        string[] name = userName.split('@');
        user u = new user(Username=userName,FirstName =name[1], LastName=name[0], Alias=name[0], CommunityNickname=userName, LocaleSidKey='en_US', EmailEncodingKey='UTF-8', Profileid = profId, LanguageLocaleKey='en_US');
        u.email=email;
        u.MB_Expiration_Date__c = System.now().addminutes(1);
        u.OD_Employee_ID__c =empId;
        u.GT_Employee_ID__c =empId;
        u.ContactId = conId;
        u.IsActive=true;
        u.TimeZoneSidKey='America/Los_Angeles';
        u.Token_Market_Builder__c ='xyz';
       // u.IsPortalEnabled = true;
        try{ 
            Insert u;
            system.debug('@@@User@@@ : '+u);
            return u;
        }
        catch(Exception e) {
            system.debug('Exception'+e);
        }
        return u;
    }
    public static Contact CreateContact(Id accountId) {
    Contact contact = new Contact(LastName = 'TEST',AccountId = accountId);
    contact.MailingCountry = 'MEX';
    contact.Admin_Context__c =  accountId;
    contact.GPO_Community__c =accountId;
    insert contact;
    
    return contact;
  }
  public static User getTestUser(String profileName,String userName,String empId){
        Profile profileObj = [select id from profile where name=: profileName];
        String profId = profileObj.id;
        UserRole ContractDivisionRoleId = [SELECT Id from UserRole WHERE Name = 'Contract Division' limit 1];
        string email = userName;
        string[] name = userName.split('@');
        user u = new user(Username=userName,FirstName =name[1], LastName=name[0], Alias=name[0], CommunityNickname=userName, LocaleSidKey='en_US', EmailEncodingKey='UTF-8', Profileid = profId, LanguageLocaleKey='en_US');
        u.email=email;
        u.MB_Expiration_Date__c = System.now().addminutes(1);
        u.OD_Employee_ID__c =empId;
        u.GT_Employee_ID__c =empId;
        u.IsActive=true;
        u.TimeZoneSidKey='America/Los_Angeles';
        u.Token_Market_Builder__c ='xyz';
        u.UserRoleId = ContractDivisionRoleId.Id;
        try{ 
            Insert u;
            system.debug('@@@User@@@ : '+u);
            return u;
        }
        catch(Exception e) {
            system.debug('Exception'+e);
        }
        return u;
    }
}