objects/Account.object
<CustomObject>
    <fields>
        <fullName>Partner_Sub_Agent_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Sub-Agent Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>End User Accounts</relationshipLabel>
        <relationshipName>Contact_End_User_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Agent</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Sub Agent)</relationshipLabel>
        <relationshipName>Sub_Agent</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <description>Partner Layout for Onboarding Partners</description>
        <label>Partner</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Used in PRM for deal registration</description>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Used in PRM for Deal Registration</description>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Sub_Agent_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Sub-Agent Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Contact must at the Partner Sub-Agent Account.</errorMessage>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Sub_Agent__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads_Partner_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Sub-Agent Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Account must be of type &quot;Partner&quot;.</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Sub Agent)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/LeaddealShareTest.cls
@isTest 
public class LeaddealShareTest {
    static testMethod void leaddealTest() { 
        //Create Partner User 
        Profile p = [select Id, name from Profile where UserType = 'PowerPartner' limit 1];
        String userName = 'xyz@officedepot.com';
        String email = userName;
        String [] name = userName.split('@');
        
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs(thisUser) {
            Recordtype rtPartner = [Select id, Sobjecttype from recordtype where name = 'Partner' and Sobjecttype = 'Account'];
            Account acc = new Account(Name='Test Account');
            acc.RecordTypeId = rtPartner.Id; 
            insert acc; 
                
            Contact con = new Contact(LastName='userName', AccountId = acc.Id);
            insert con; 
            
            Contact con2 = new Contact(LastName='userName2', AccountId = acc.Id);
            insert con2; 
            
            User partnerUser = 
                new User(Username = userName, FirstName = name[1], LastName = name[0], Alias = name[0], CommunityNickname = userName, LocaleSidKey = 'en_US', EmailEncodingKey = 'UTF-8', Profileid = p.id, LanguageLocaleKey = 'en_US');
            partnerUser.email = email;
            partnerUser.ContactId = con.id;
            partnerUser.IsActive = true;
            partnerUser.TimeZoneSidKey = 'America/Los_Angeles';
            insert partnerUser;
            
            Id RTId = Schema.SobjectType.Lead.getRecordTypeInfosByName().get('Lead (Deals)').getRecordTypeId();            
            Lead newld = new Lead();
            newld.last_name__c = 'Test';
            newld.lastname = 'Test';
            newld.firstName = 'Test';
            newld.first_name__c = 'Test';
            newld.company = 'Test Company';
            newld.Status = 'New';
            newld.RecordTypeId = RTId;
            newld.Email = 'abc@gmail.com';
            system.debug('account id is ' + acc.Id); 
            newld.Sub_Agent__c = acc.Id; 
            newld.Partner_Sub_Agent_Contact__c = con2.id;
            system.debug('newld'+newld);
            insert newld;
            system.debug('newld' + newld);
            newld.Partner_Sub_Agent_Contact__c = con.id;
            update newld;
        }        
    }
}