objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Single User</fullName>
                </value>
                <value>
                    <fullName>Multi-User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer Accounts</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Parent</fullName>
        <active>true</active>
        <label>Parent</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Fact_Sheet__c.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <formula>Account__r.Hierarchy__c</formula>
        <label>Account Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Facts_Sheet</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Additional_Account_Handling_Comments__c</fullName>
        <label>Additional Account Handling Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Can_Customer_Care_Maintain_Account__c</fullName>
        <label>Can Customer Care Maintain Account?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Can_Restrictions_Be_Overridden_Without_A__c</fullName>
        <label>Can Restrictions Be Overridden W/O Appr</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Custmustclearcreditpriortorebill__c</fullName>
        <inlineHelpText>When rebilling orders to correct rejections, does the customer need to receive the credit to clear the rejected invoice from their system?</inlineHelpText>
        <label>Cust must clear credit prior to rebill</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EDI_Customer_Email__c</fullName>
        <label>EDI Customer Email</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EDI_Customer_Name__c</fullName>
        <label>EDI Customer Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EDI_Customer_Phone__c</fullName>
        <label>EDI Customer Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>EDI_Exceptions_Email__c</fullName>
        <label>EDI Exceptions Email</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EDI_Exceptions_Name__c</fullName>
        <label>EDI Exceptions Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EDI_Exceptions_Phone__c</fullName>
        <label>EDI Exceptions Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Forms_of_Order_Entry__c</fullName>
        <label>Forms of Order Entry</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BSD Net</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                    <label>Email/Fax</label>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
                <value>
                    <fullName>EDI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Inherit_Hierarchy__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inherit Hierarchy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MISC__c</fullName>
        <label>Miscellaneous Credit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <formula>Account__r.Name &amp;&apos; &apos;&amp;&quot;-&quot;&amp;&apos; &apos;&amp; Account__r.AOPS_Cust_Id__c</formula>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ordering_Platform__c</fullName>
        <label>Ordering Platform</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Match__c</fullName>
        <label>Price Match</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Variance__c</fullName>
        <label>Price Variance</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Proprietary_Flag__c</fullName>
        <label>Proprietary Flag</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Special_Instructions__c</fullName>
        <label>Special Instructions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>What_Can_Be_Done_To_Maintain_Account__c</fullName>
        <inlineHelpText>Please Advise on what can be done to maintain the account.</inlineHelpText>
        <label>What Can Be Done To Maintain Account</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Customer Intelligent Document</label>
    <nameField>
        <displayFormat>FS-{00000000}</displayFormat>
        <label>Fact Sheet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Intelligent Document</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RelatedCustomerIntelligentDocumentCtrl.cls
/**
* @author Sandesh Ganjare, sandesh.ganjare@officedepot.com
* @date 06/09/2020
*
* 
* @description This class fetch all the records of Customer Intelligent Document object related to Accounts in hierarchy.
*              This class used for 'RelatedCustomerIntelligentDocument' LWC component.
*               Test class => RelatedCIDCtrl_Test
* JIRA: NAIT-137444: 02944812 - Ability to Input/Maintain Fact Sheet Fields in SFDC
*/

public class RelatedCustomerIntelligentDocumentCtrl {
    @AuraEnabled(cacheable=true)
    public static List<Fact_Sheet__c> getRelatedCID(String recId){
        system.debug('==>'+recId);
        List<Fact_Sheet__c> customerIntelligentDocumentList = new List<Fact_Sheet__c>();
        Set<Id> accountIdSet = new Set<Id>();
        List<Account> accountList = [SELECT id,Parentid,Parent.Parentid,Parent.Parent.Parentid FROM Account WHERE id=:recId LIMIT 1];
        if(!accountList.isEmpty()){
            if(accountList[0].id != null){
                accountIdSet.add(accountList[0].id);
            }
            if(accountList[0].Parentid != null){
                accountIdSet.add(accountList[0].Parentid);
            }
            if(accountList[0].Parent.Parentid != null){
                accountIdSet.add(accountList[0].Parent.Parentid);
            }
            if(accountList[0].Parent.Parent.Parentid != null){
                accountIdSet.add(accountList[0].Parent.Parent.Parentid);    
            }
            system.debug('accountIdSet==>'+accountIdSet);
        }
        customerIntelligentDocumentList = [SELECT Id,Name, Name__c,Account_Type__c,Additional_Account_Handling_Comments__c,Can_Customer_Care_Maintain_Account__c,
                                                Can_Restrictions_Be_Overridden_Without_A__c,Custmustclearcreditpriortorebill__c,EDI_Customer_Email__c,
                                                EDI_Customer_Name__c,EDI_Customer_Phone__c,EDI_Exceptions_Email__c,
                                                EDI_Exceptions_Name__c,EDI_Exceptions_Phone__c,Forms_of_Order_Entry__c,
                                                Inherit_Hierarchy__c,MISC__c,Ordering_Platform__c,Price_Match__c,Price_Variance__c,
                                                Proprietary_Flag__c,Special_Instructions__c,What_Can_Be_Done_To_Maintain_Account__c,LastModifiedDate FROM Fact_Sheet__c WHERE Account__c IN :accountIdSet];
        system.debug('customerIntelligentDocumentList==>'+customerIntelligentDocumentList);
        return customerIntelligentDocumentList;
    }
}