objects/Account.object
<CustomObject>
    <fields>
        <fullName>Initial_Site_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This flag is a system flag used by trigger on initial prospect creation.  Prevents trigger from firing twice.</description>
        <label>Initial Site Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Reassignment_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reassignment Queue</relationshipLabel>
        <relationshipName>Reassignment_Queue</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Reassignment_Queue</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requestor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Reassignment_Queue2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Auto Approved</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Reassignment Queue</label>
    <nameField>
        <displayFormat>RQ-{0000}</displayFormat>
        <label>Reassignment Queue	 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reassignment Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ApproveRejectProspect_TC.cls
/**
 * Created by Najma Ateeq for Story #S-386202(OD Case Number - 00617674)
 */
@isTest
private class ApproveRejectProspect_TC 
{

    static testMethod void myUnitTest() 
    {
        createTestData();
        createTestData1();
        ApproveRejectProspect approveRejectPro = new ApproveRejectProspect();
        system.assert(approveRejectPro.ReassignList.size() > 0);
        approveRejectPro.refreshView();
        approveRejectPro.Approve();
        approveRejectPro.Reject();
        approveRejectPro.Cancel();
        approveRejectPro.getoptions();
        approveRejectPro.gettypeofView();
        
    }
    static void createTestData1()
    {
        Account acc = Test_Utils.CreateAccount();
        //acc.initial_site_flag__c = true;
        //update acc;
        Reassignment_Queue__c reassignmentQ1 = new Reassignment_Queue__c();
        //reassignmentQ.Name = 'Test';
        reassignmentQ1.Requestor__c = UserInfo.getUserId();
        reassignmentQ1.Approver__c =  UserInfo.getUserId();
        reassignmentQ1.Account__c = acc.Id;
        reassignmentQ1.status__c = 'Pending Approval';
        insert reassignmentQ1;
    }
    
    static void createTestData()
    {
        ReassignUtils ru = new ReassignUtils();
        ApproveRejectProspect apprveRejctPrspct = new ApproveRejectProspect();
        apprveRejctPrspct.typeofView = 'My App';
        Account acc = Test_Utils.CreateAccount();
        //acc.initial_site_flag__c = true;
        //update acc;
        Reassignment_Queue__c reassignmentQ = new Reassignment_Queue__c();
        //reassignmentQ.Name = 'Test';
        reassignmentQ.Requestor__c = UserInfo.getUserId();
        reassignmentQ.Account__c = acc.Id;
        reassignmentQ.status__c = 'Pending Approval';
        insert reassignmentQ;
    }
}