objects/Account.object
<CustomObject>
    <fields>
        <fullName>AOPS_Cust_Id__c</fullName>
        <description>AOPS Customer Account Number</description>
        <externalId>true</externalId>
        <label>AOPS Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>AOPS_Seq_ID__c</fullName>
        <externalId>true</externalId>
        <label>AOPS Seq ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Oracle_Party_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Party ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Oracle_Party_Site_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Party Site ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Primary_Site__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Site</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Related_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>(Tech-Zone)</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site</fullName>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer Accounts</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Site</fullName>
        <active>true</active>
        <label>Site</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/AccountAssignments__c.object
<CustomObject>
    <description>This object is used to store Overlay Account Assignments from Legacy system and also Primary rep (Owner Id) assignments. The data will be then picked up by a Batch Apex job to do actual Account Team Assignments.</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <description>This will store the Legacy Account ID</description>
        <externalId>true</externalId>
        <label>AccountId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountType__c</fullName>
        <description>Type of Account, Customer or Site etc...</description>
        <label>AccountType</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to relate to the Account object for custom reporting.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>AccountTeamAssignments</relationshipLabel>
        <relationshipName>AccountTeamAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Entity_Id__c</fullName>
        <description>Entity Id it can be oracle_party_id, oracle_party_site_id, aops_cust_id or aops_seq_id.</description>
        <externalId>true</externalId>
        <label>Entity Id</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CUSTOMER</fullName>
                </value>
                <value>
                    <fullName>PROSPECT</fullName>
                </value>
                <value>
                    <fullName>ODN Customer</fullName>
                </value>
                <value>
                    <fullName>ODS Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ex_Id__c</fullName>
        <externalId>true</externalId>
        <label>Ex_Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID10__c</fullName>
        <description>Employee Id of Overlay Employee 10, which is assigned to Account Team</description>
        <label>Overlay Emp ID 10</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID11__c</fullName>
        <description>Employee Id of Overlay Employee 11, which is assigned to Account Team</description>
        <label>Overlay Emp ID 11</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID12__c</fullName>
        <description>Employee Id of Overlay Employee 12, which is assigned to Account Team</description>
        <label>Overlay Emp ID 12</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID13__c</fullName>
        <description>Employee Id of Overlay Employee 13, which is assigned to Account Team</description>
        <label>Overlay Emp ID 13</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID14__c</fullName>
        <description>Employee Id of Overlay Employee 14, which is assigned to Account Team</description>
        <label>Overlay Emp ID 14</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID15__c</fullName>
        <description>Employee Id of Overlay Employee 15, which is assigned to Account Team</description>
        <label>Overlay Emp ID 15</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID16__c</fullName>
        <label>Overlay Emp ID 16</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID17__c</fullName>
        <label>Overlay Emp ID 17</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID18__c</fullName>
        <label>Overlay Emp ID 18</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID19__c</fullName>
        <label>Overlay Emp ID 19</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID1__c</fullName>
        <description>Employee Id of Overlay Employee 1, which is assigned to Account Team</description>
        <label>Overlay Emp ID 1</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID20__c</fullName>
        <label>Overlay Emp ID 20</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID21__c</fullName>
        <label>Overlay Emp ID 21</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID22__c</fullName>
        <label>Overlay Emp ID 22</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID23__c</fullName>
        <label>Overlay Emp ID 23</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID24__c</fullName>
        <label>Overlay Emp ID 24</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID25__c</fullName>
        <label>Overlay Emp ID 25</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID26__c</fullName>
        <label>Overlay Emp ID 26</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID27__c</fullName>
        <label>Overlay Emp ID 27</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID28__c</fullName>
        <label>Overlay Emp ID 28</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID29__c</fullName>
        <label>Overlay Emp ID 29</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID2__c</fullName>
        <description>Employee Id of Overlay Employee 2, which is assigned to Account Team</description>
        <label>Overlay Emp ID 2</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID30__c</fullName>
        <label>Overlay Emp ID 30</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID3__c</fullName>
        <description>Employee Id of Overlay Employee 3, which is assigned to Account Team</description>
        <label>Overlay Emp ID 3</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID4__c</fullName>
        <description>Employee Id of Overlay Employee 4, which is assigned to Account Team</description>
        <label>Overlay Emp ID 4</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID5__c</fullName>
        <description>Employee Id of Overlay Employee 5, which is assigned to Account Team</description>
        <label>Overlay Emp ID 5</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID6__c</fullName>
        <description>Employee Id of Overlay Employee 6, which is assigned to Account Team</description>
        <label>Overlay Emp ID 6</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID7__c</fullName>
        <description>Employee Id of Overlay Employee 7, which is assigned to Account Team</description>
        <label>Overlay Emp ID 7</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID8__c</fullName>
        <description>Employee Id of Overlay Employee 8, which is assigned to Account Team</description>
        <label>Overlay Emp ID 8</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID9__c</fullName>
        <description>Employee Id of Overlay Employee 9, which is assigned to Account Team</description>
        <label>Overlay Emp ID 9</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole10__c</fullName>
        <label>Overlay Emp Role 10</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole11__c</fullName>
        <label>Overlay Emp Role 11</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole12__c</fullName>
        <label>Overlay Emp Role 12</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole13__c</fullName>
        <label>Overlay Emp Role 13</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole14__c</fullName>
        <label>Overlay Emp Role 14</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole15__c</fullName>
        <label>Overlay Emp Role 15</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole16__c</fullName>
        <label>Overlay Emp Role 16</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole17__c</fullName>
        <label>Overlay Emp Role 17</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole18__c</fullName>
        <label>Overlay Emp Role 18</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole19__c</fullName>
        <label>Overlay Emp Role 19</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole1__c</fullName>
        <label>Overlay Emp Role 1</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole2__c</fullName>
        <label>Overlay Emp Role 2</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole3__c</fullName>
        <label>Overlay Emp Role 3</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole4__c</fullName>
        <label>Overlay Emp Role 4</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole5__c</fullName>
        <label>Overlay Emp Role 5</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole6__c</fullName>
        <label>Overlay Emp Role 6</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole7__c</fullName>
        <label>Overlay Emp Role 7</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole8__c</fullName>
        <label>Overlay Emp Role 8</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole9__c</fullName>
        <label>Overlay Emp Role 9</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the record will be Open when created. Process when success and Error on issues</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Partially Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>AccountTeamAssignment</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>AssignmentsNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountTeamAssignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountAssignmentUpdatingSitesClass.cls
//Class to update the Party sites Id's and create customer Record

public class AccountAssignmentUpdatingSitesClass {  
    
    public void updateAssignData(List<AccountAssignments__c > currentRecords) {
       Set<String> accSet = new Set<String>();
       Map<String,Account> accMap = new Map<String,Account>();
       Map<String,Account> accMapOMX = new Map<String,Account>();

       List<AccountAssignments__c> accupsertList= new List<AccountAssignments__c>();

        for(AccountAssignments__c accAssgnmntObj : currentRecords)
        {
           // Take the Site Records
                if(  (accAssgnmntObj.Entity_Type__c == 'ODN Customer'  || accAssgnmntObj.Entity_Type__c == 'ODS Customer')  && accAssgnmntObj.AccountType__c =='S' )
                {
                accSet.add(accAssgnmntObj.Entity_Id__c);
                system.debug('in entity id');
                }
        }
        //get Party Site Id's and Account Id's for the account
        for(Account acc : [select id,OMX_Primary_Key__c,AOPS_Seq_ID__c,Oracle_Party_Site_ID__c ,Primary_Site__c,Related_Account__c,
        Related_Account__r.Oracle_Party_ID__c,Related_Account__r.OMX_Primary_Key__c,Related_Account__r.AOPS_Cust_Id__c
         from Account where 
        ( AOPS_Seq_ID__c in :accSet  or  OMX_Primary_Key__c in :accSet )  ])
            {
            if(acc.AOPS_Seq_ID__c!=null)
            accMap.put(acc.AOPS_Seq_ID__c,acc);
            else
            accMapOMX.put(acc.OMX_Primary_Key__c,acc);
            }
                           system.debug('accMap'+accMap);
                            system.debug('accMapOMX'+accMapOMX);

           for(AccountAssignments__c accAssgnmntObj : currentRecords)
            {
           // Take the Site Records
                if(  (accAssgnmntObj.Entity_Type__c == 'ODN Customer'  || accAssgnmntObj.Entity_Type__c == 'ODS Customer')  && 
                accAssgnmntObj.AccountType__c =='S' )
                {
                  // check if its a primary Site or not   
                  
                                            system.debug('Inside loop2');
                        if(accAssgnmntObj.Entity_Type__c == 'ODN Customer' && accMapOMX.containsKey(accAssgnmntObj.Entity_Id__c) ){
                        accAssgnmntObj.AccountId__c = accMapOMX.get(accAssgnmntObj.Entity_Id__c).Oracle_Party_Site_ID__c;  
                        accAssgnmntObj.Account__c =   accMapOMX.get(accAssgnmntObj.Entity_Id__c).Id; 
                        }
                        else if(accAssgnmntObj.Entity_Type__c == 'ODS Customer' && accMap.containsKey(accAssgnmntObj.Entity_Id__c) ){
                        accAssgnmntObj.AccountId__c = accMap.get(accAssgnmntObj.Entity_Id__c).Oracle_Party_Site_ID__c;  
                        accAssgnmntObj.Account__c =   accMap.get(accAssgnmntObj.Entity_Id__c).Id; 
                        }

            
                  if((accAssgnmntObj.Entity_Type__c == 'ODS Customer'  && accMap.containsKey(accAssgnmntObj.Entity_Id__c) && accMap.get(accAssgnmntObj.Entity_Id__c).Primary_Site__c== true ) ||
                  (accAssgnmntObj.Entity_Type__c == 'ODN Customer'  && accMapOMX.containsKey(accAssgnmntObj.Entity_Id__c) && accMapOMX.get(accAssgnmntObj.Entity_Id__c).Primary_Site__c== true ) ){
                      AccountAssignments__c accupsert= new AccountAssignments__c();
                        accupsert.AccountType__c ='A';
                        accupsert.Status__c='Open';
                        if(accAssgnmntObj.Entity_Type__c == 'ODN Customer' ){
                        accupsert.Entity_Type__c = 'ODN Customer' ;
                        accupsert.Entity_Id__c=accMapOMx.get(accAssgnmntObj.Entity_Id__c).Related_Account__r.omx_primary_key__C;
                        accupsert.Ex_Id__c=accMapOMx.get(accAssgnmntObj.Entity_Id__c).Related_Account__r.omx_primary_key__C;
                        accupsert.AccountId__c =accMapOMX.get(accAssgnmntObj.Entity_Id__c).Related_Account__r.Oracle_Party_ID__c;
                        accupsert.account__C=accMapOMX.get(accAssgnmntObj.Entity_Id__c).Related_Account__c;
                        }
                        else if(accAssgnmntObj.Entity_Type__c == 'ODS Customer' ){
                        accupsert.Entity_Type__c = 'ODS Customer' ;
                        accupsert.Entity_Id__c=accMap.get(accAssgnmntObj.Entity_Id__c).Related_Account__r.AOPS_Cust_Id__c;
                        accupsert.Ex_Id__c=accMap.get(accAssgnmntObj.Entity_Id__c).Related_Account__r.AOPS_Cust_Id__c;
                        accupsert.AccountId__c =accMap.get(accAssgnmntObj.Entity_Id__c).Related_Account__r.Oracle_Party_ID__c;
                        accupsert.account__C=accMap.get(accAssgnmntObj.Entity_Id__c).Related_Account__c;
                        }
                       
                                                accupsert.OverlayEmpID1__c= accAssgnmntObj .OverlayEmpID1__c;
                                                accupsert.OverlayEmpID2__c= accAssgnmntObj .OverlayEmpID2__c;
                                                accupsert.OverlayEmpID3__c= accAssgnmntObj .OverlayEmpID3__c;
                                                accupsert.OverlayEmpID4__c= accAssgnmntObj .OverlayEmpID4__c;
                                                accupsert.OverlayEmpID5__c= accAssgnmntObj .OverlayEmpID5__c;
                                                accupsert.OverlayEmpID6__c= accAssgnmntObj .OverlayEmpID6__c;
                                                accupsert.OverlayEmpID7__c= accAssgnmntObj .OverlayEmpID7__c;
                                                accupsert.OverlayEmpID8__c= accAssgnmntObj .OverlayEmpID8__c;
                                                accupsert.OverlayEmpID9__c= accAssgnmntObj .OverlayEmpID9__c;
                                                accupsert.OverlayEmpID10__c= accAssgnmntObj .OverlayEmpID10__c;
                                                accupsert.OverlayEmpID11__c= accAssgnmntObj .OverlayEmpID2__c;
                                                accupsert.OverlayEmpID12__c= accAssgnmntObj .OverlayEmpID12__c;
                                                accupsert.OverlayEmpID13__c= accAssgnmntObj .OverlayEmpID13__c;
                                                accupsert.OverlayEmpID14__c= accAssgnmntObj .OverlayEmpID14__c;
                                                accupsert.OverlayEmpID15__c= accAssgnmntObj .OverlayEmpID15__c;
                                                accupsert.OverlayEmpID16__c= accAssgnmntObj .OverlayEmpID16__c;
                                                accupsert.OverlayEmpID17__c= accAssgnmntObj .OverlayEmpID17__c;
                                                accupsert.OverlayEmpID18__c= accAssgnmntObj .OverlayEmpID18__c;
                                                accupsert.OverlayEmpID19__c= accAssgnmntObj .OverlayEmpID19__c;
                                                accupsert.OverlayEmpID20__c= accAssgnmntObj .OverlayEmpID20__c;
                                                accupsert.OverlayEmpID21__c= accAssgnmntObj .OverlayEmpID21__c;
                                                accupsert.OverlayEmpID22__c= accAssgnmntObj .OverlayEmpID22__c;
                                                accupsert.OverlayEmpID23__c= accAssgnmntObj .OverlayEmpID23__c;
                                                accupsert.OverlayEmpID24__c= accAssgnmntObj .OverlayEmpID24__c;
                                                accupsert.OverlayEmpID25__c= accAssgnmntObj .OverlayEmpID25__c;
                                                accupsert.OverlayEmpID26__c= accAssgnmntObj .OverlayEmpID26__c;
                                                accupsert.OverlayEmpID27__c= accAssgnmntObj .OverlayEmpID27__c;
                                                accupsert.OverlayEmpID28__c= accAssgnmntObj .OverlayEmpID28__c;
                                                accupsert.OverlayEmpID29__c= accAssgnmntObj .OverlayEmpID29__c;
                                                accupsert.OverlayEmpID30__c= accAssgnmntObj .OverlayEmpID30__c;
                                                accupsert.OverlayEmpRole1__c= accAssgnmntObj .OverlayEmpRole1__c;
                                                accupsert.OverlayEmpRole2__c= accAssgnmntObj .OverlayEmpRole2__c;
                                                accupsert.OverlayEmpRole3__c= accAssgnmntObj .OverlayEmpRole3__c;
                                                accupsert.OverlayEmpRole4__c= accAssgnmntObj .OverlayEmpRole4__c;
                                                accupsert.OverlayEmpRole5__c= accAssgnmntObj .OverlayEmpRole5__c;
                                                accupsert.OverlayEmpRole6__c= accAssgnmntObj .OverlayEmpRole6__c;
                                                accupsert.OverlayEmpRole7__c= accAssgnmntObj .OverlayEmpRole7__c;
                                                accupsert.OverlayEmpRole8__c= accAssgnmntObj .OverlayEmpRole8__c;
                                                accupsert.OverlayEmpRole9__c= accAssgnmntObj .OverlayEmpRole9__c;
                                                accupsert.OverlayEmpRole10__c= accAssgnmntObj .OverlayEmpRole10__c;
                                                accupsert.OverlayEmpRole11__c= accAssgnmntObj .OverlayEmpRole2__c;
                                                accupsert.OverlayEmpRole12__c= accAssgnmntObj .OverlayEmpRole12__c;
                                                accupsert.OverlayEmpRole13__c= accAssgnmntObj .OverlayEmpRole13__c;
                                                accupsert.OverlayEmpRole14__c= accAssgnmntObj .OverlayEmpRole14__c;
                                                accupsert.OverlayEmpRole15__c= accAssgnmntObj .OverlayEmpRole15__c;
                                                accupsert.OverlayEmpRole16__c= accAssgnmntObj .OverlayEmpRole16__c;
                                                accupsert.OverlayEmpRole17__c= accAssgnmntObj .OverlayEmpRole17__c;
                                                accupsert.OverlayEmpRole18__c= accAssgnmntObj .OverlayEmpRole18__c;
                                                accupsert.OverlayEmpRole19__c= accAssgnmntObj .OverlayEmpRole19__c;
                                                accupsert.OverlayEmpRole20__c= accAssgnmntObj .OverlayEmpRole20__c;
                                                accupsert.OverlayEmpRole21__c= accAssgnmntObj .OverlayEmpRole21__c;
                                                accupsert.OverlayEmpRole22__c= accAssgnmntObj .OverlayEmpRole22__c;
                                                accupsert.OverlayEmpRole23__c= accAssgnmntObj .OverlayEmpRole23__c;
                                                accupsert.OverlayEmpRole24__c= accAssgnmntObj .OverlayEmpRole24__c;
                                                accupsert.OverlayEmpRole25__c= accAssgnmntObj .OverlayEmpRole25__c;
                                                accupsert.OverlayEmpRole26__c= accAssgnmntObj .OverlayEmpRole26__c;
                                                accupsert.OverlayEmpRole27__c= accAssgnmntObj .OverlayEmpRole27__c;
                                                accupsert.OverlayEmpRole28__c= accAssgnmntObj .OverlayEmpRole28__c;
                                                accupsert.OverlayEmpRole29__c= accAssgnmntObj .OverlayEmpRole29__c;
                                                accupsert.OverlayEmpRole30__c= accAssgnmntObj .OverlayEmpRole30__c;
                                                accupsert.PrimaryEmpId__c= accAssgnmntObj .PrimaryEmpId__c;
                                                accupsert.PrimaryEmpRole__c= accAssgnmntObj.PrimaryEmpRole__c;

                                                
                  accupsertList.add(accupsert);                              
                  }
                }
            }// end of for loop
         if(accupsertList.size()>0)
         upsert accupsertList Ex_Id__c;
    }
     
    
    

}