objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/AccountAssignments__c.object
<CustomObject>
    <description>This object is used to store Overlay Account Assignments from Legacy system and also Primary rep (Owner Id) assignments. The data will be then picked up by a Batch Apex job to do actual Account Team Assignments.</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <description>This will store the Legacy Account ID</description>
        <externalId>true</externalId>
        <label>AccountId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountType__c</fullName>
        <description>Type of Account, Customer or Site etc...</description>
        <label>AccountType</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Id__c</fullName>
        <description>Entity Id it can be oracle_party_id, oracle_party_site_id, aops_cust_id or aops_seq_id.</description>
        <externalId>true</externalId>
        <label>Entity Id</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CUSTOMER</fullName>
                </value>
                <value>
                    <fullName>PROSPECT</fullName>
                </value>
                <value>
                    <fullName>ODN Customer</fullName>
                </value>
                <value>
                    <fullName>ODS Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OverlayEmpID10__c</fullName>
        <description>Employee Id of Overlay Employee 10, which is assigned to Account Team</description>
        <label>Overlay Emp ID 10</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID11__c</fullName>
        <description>Employee Id of Overlay Employee 11, which is assigned to Account Team</description>
        <label>Overlay Emp ID 11</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID12__c</fullName>
        <description>Employee Id of Overlay Employee 12, which is assigned to Account Team</description>
        <label>Overlay Emp ID 12</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID13__c</fullName>
        <description>Employee Id of Overlay Employee 13, which is assigned to Account Team</description>
        <label>Overlay Emp ID 13</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID14__c</fullName>
        <description>Employee Id of Overlay Employee 14, which is assigned to Account Team</description>
        <label>Overlay Emp ID 14</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID15__c</fullName>
        <description>Employee Id of Overlay Employee 15, which is assigned to Account Team</description>
        <label>Overlay Emp ID 15</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID1__c</fullName>
        <description>Employee Id of Overlay Employee 1, which is assigned to Account Team</description>
        <label>Overlay Emp ID 1</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID2__c</fullName>
        <description>Employee Id of Overlay Employee 2, which is assigned to Account Team</description>
        <label>Overlay Emp ID 2</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryEmpId__c</fullName>
        <description>Primary Employee id, mapped to Owner Id of the Account</description>
        <label>Primary Emp Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryEmpRole__c</fullName>
        <description>Role of the Primary Employee</description>
        <label>Primary Emp Role</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the record will be Open when created. Process when success and Error on issues</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Partially Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>AccountTeamAssignment</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>AssignmentsNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountTeamAssignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EmailServiceHandler_TC.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class EmailServiceHandler_TC {

    static testMethod void EmailServiceHandler_TC() {
        
        AccountAssignments__c accassign=new AccountAssignments__c();
        accassign.AccountId__c='12345';
        accassign.AccountType__c='A';
        accassign.Entity_Id__c='123456789';
        accassign.OverlayEmpID10__c='123';
        accassign.OverlayEmpID1__c='1231';
        accassign.OverlayEmpID11__c='1232';
        accassign.OverlayEmpID12__c='1233';
        accassign.OverlayEmpID13__c='1234';
        accassign.OverlayEmpID14__c='1235';
        accassign.OverlayEmpID15__c='1236';
        accassign.OverlayEmpID2__c='1237';
        insert accassign;
        
     // Create a new email, envelope object and Attachment
        Messaging.InboundEmail email = new Messaging.InboundEmail();
        Messaging.InboundEnvelope envelope = new Messaging.InboundEnvelope();
        
        email.subject = 'Start Account Assignment Job';
        email.plainTextBody = 'Hello, this a test email body. for testing purposes only. Bye';
        envelope.fromAddress = 'user@acme.com';


        // setup controller object       
        EmailServiceHandler reassign=new EmailServiceHandler();
        //reassign.strQuery='Select Id, AccountId__c, AccountType__c, Entity_Type__c, Entity_Id__c, PrimaryEmpId__c, PrimaryEmpRole__c from AccountAssignments__c where Status__c = \'Open\' and (Name Like \'%6\' OR Name Like \'%7\')';
        //Database.executeBatch(reassign);
        reassign.handleInboundEmail(email, envelope);
    }
}