objects/Account.object
<CustomObject>
    <fields>
        <fullName>Mod_5_EBS_Sync_Error__c</fullName>
        <label>Mod 5 EBS Sync Error</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Mod_5_EBS_Sync_Status__c</fullName>
        <description>This flag is to confirm that Delink Process Completed in EBS</description>
        <label>Mod 5 EBS Sync Status</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oracle_Party_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Party ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/OMXsiteSplitStatus.cls
global class OMXsiteSplitStatus {
 
 webservice static boolean getSplitSites (String partyID,String statusCode, String statusMessage) {
   account a = [select id,Mod_5_EBS_Sync_Error__c,Mod_5_EBS_Sync_Status__c from account where oracle_party_id__c = :partyid];
   a.Mod_5_EBS_Sync_Status__c = statusCode;
   if (statusMessage != null) {
    if (statusMessage.length() > 5000)
     a.Mod_5_EBS_Sync_Error__c = statusMessage.substring(0,5000);
    else
     a.Mod_5_EBS_Sync_Error__c = statusMessage;
   }
   update a;
   return true;
 }
 
}