objects/Account.object
<CustomObject>
    <fields>
        <fullName>AOPS_Cust_Id__c</fullName>
        <description>AOPS Customer Account Number</description>
        <externalId>true</externalId>
        <label>AOPS Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>AOPS_Seq_ID__c</fullName>
        <externalId>true</externalId>
        <label>AOPS Seq ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Oracle_Party_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Party ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ACE_Customer_Price_Changes__c.object
<CustomObject>
    <description>Price Change Process UI</description>
    <fields>
        <fullName>Approval_Type__c</fullName>
        <label>Approval Type</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer_Notification_Date_Approved__c</fullName>
        <label>Notification Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>ACE_Customer_Price_Changes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item_12_Month_Qty__c</fullName>
        <description>Accumulated SKU Sold Qty for this Core, Last 12 calendar months from current date
Same Time Period as of Sales</description>
        <label>Item 12 Month Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Owning_Customer_ID__c</fullName>
        <externalId>true</externalId>
        <label>Cust ID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owning_Customer_Legal__c</fullName>
        <label>Governed By Written Agreement (T/F)</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFDC_Notification_Flag__c</fullName>
        <label>SFDC Notification Flag</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SRM_Differential__c</fullName>
        <defaultValue>0</defaultValue>
        <label>SRM Differential $</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sales_Price_Change_Effective_Date_Min__c</fullName>
        <description>This holds the min value of the sales price effective date for the SKUs</description>
        <label>Price Change Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Spend_Impact_12_Month__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Estimated Total Annual Spend Change</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Customer Core Price Changes</label>
    <nameField>
        <label>Batch</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Core Price Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ACE_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is For ACE Custom Settings</description>
    <label>ACE_Settings</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>OD_Employee_ID__c</fullName>
        <externalId>true</externalId>
        <label>OD Employee ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/AceRelease_TC.cls
@isTest
private class AceRelease_TC 
{
    static testMethod void myUnitTest() 
    {

        Profile p = [select id from Profile where name='Field Sales' limit 1];
               
        User mgruser = new User(TimeZoneSidKey='America/Los_Angeles',ProfileId = p.id,LastName = 'ACE', FirstName = 'Manager', Email = 'ACE.manager@officedepot.com',Username ='ACE.manager@officedepot.com', Alias='test', CommunityNickname='test Approver', LanguageLocaleKey='en_US', LocaleSidKey='en_US', EmailEncodingKey='UTF-8', OD_Employee_ID__c='653466');
        Insert mgruser;

        User user = new User(TimeZoneSidKey='America/Los_Angeles',ProfileId = p.id,LastName = 'Rep', FirstName = 'ACE',Email='Rep.ACE@officedepot.com', Username ='Rep.ACE@officedepot.com', Alias='test12', CommunityNickname='test Approve', LanguageLocaleKey='en_US', EmailEncodingKey='UTF-8', LocaleSidKey='en_US',OD_Employee_ID__c='653486');
        Insert user;

        ACE_Settings__c desettings = new ACE_Settings__c();
        insert desettings; 
        
        Account acc = new Account (
                     name = 'SUN Test Account',
                     AOPS_Seq_ID__c = '123456',
                     AOPS_Cust_Id__c = '123456',
                     Oracle_Party_Id__c = '123456',
                     Billingcountry = 'USA',
                     BillingState = 'UT',
                     BillingStreet = '1040 N 326 W',
                     ownerid = user.id,
                     billingcity = 'Orem');
        insert acc;
        
        ACE_Customer_Price_Changes__c ace1 = new ACE_Customer_Price_Changes__c(
                                            Owning_Customer_Legal__c='T',
                                            name='test',
                                            SRM_Differential__c=5,
                                            Item_12_Month_Qty__c = 50,
                                            Total_Spend_Impact_12_Month__c=5,
                                            Customer__c = acc.id, 
                                            Owning_Customer_ID__c ='123456',
                                            Approval_Type__c = 1,
                                            Customer_Notification_Date_Approved__c = system.today(),
                                            SFDC_Notification_Flag__c = '2');
        insert ace1;
        
        ace1.Customer_Notification_Date_Approved__c = system.today();
        update ace1;
        
        ApexPages.currentPage().getParameters().Put('pchangeid',ace1.id);
        AceRelease Controller = new AceRelease();
        Controller.responseSelection = 'Scheduled';
        controller.getReleaseOptions();
        controller.rerenderDateSection();
        controller.save();
        controller.cancel();
        Controller.responseSelection = '';
        controller.rerenderDateSection();

        ACE_Customer_Price_Changes__c ace2 = new ACE_Customer_Price_Changes__c(
                                            Owning_Customer_Legal__c='T',
                                            name='test',
                                            SRM_Differential__c=5,
                                            Item_12_Month_Qty__c = 50,
                                            Total_Spend_Impact_12_Month__c=5,
                                            Customer__c = acc.id, 
                                            Owning_Customer_ID__c ='123456',
                                            Approval_Type__c = 1,
                                            Sales_Price_Change_Effective_Date_Min__c = system.today(),
                                            SFDC_Notification_Flag__c = '1');
        insert ace2;
        
        ApexPages.currentPage().getParameters().Put('pchangeid',ace2.id);
        AceRelease Controller1 = new AceRelease();
        controller1.responseSelection = 'Immediate';
        controller1.save();
        Controller.responseSelection = 'Scheduled';
        controller.getReleaseOptions();
        
    }
}