objects/Account.object
<CustomObject>
    <fields>
        <fullName>ADS_Current_Month__c</fullName>
        <description>Works with Average Daily Sales</description>
        <label>ADS-Current Month</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ADS_Last_Qtr__c</fullName>
        <label>ADS-Last Qtr</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MTD_Sales_TY__c</fullName>
        <description>Current Month Sales for this year</description>
        <inlineHelpText>Current Month Sales for this year</inlineHelpText>
        <label>MTD Sales TY</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month_Goal__c</fullName>
        <description>Current Month Sales Goal</description>
        <inlineHelpText>Current Month Sales Goal</inlineHelpText>
        <label>Month Goal</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quarter_Goal__c</fullName>
        <description>Quarter Sales Goal</description>
        <inlineHelpText>Quarter Sales Goal</inlineHelpText>
        <label>Quarter Goal</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>YTD_Sales_LY__c</fullName>
        <description>Last Year Sales</description>
        <inlineHelpText>Last Year Sales</inlineHelpText>
        <label>YTD Sales LY</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Year_Goal__c</fullName>
        <label>Year Goal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Test_FieldMgr_AccountSalesHistory.cls
/**************************************************************
*Name           : Test_FieldMgr_AccountSalesHistory 
*Created By     : Dheeraj(Appirio Off)
*Created Date   : 16th Feb,2012
*Purpose        : To test FieldMgr_AccountSalesHistoryExtension
********************************************************************/
@isTest
private class Test_FieldMgr_AccountSalesHistory {

    @isTest 
    private static void testAccountSalesHistoryForManager() { 
        Profile profileObj = [select id from profile where name=:Label.GT_Field_Sales_Label];
        String profId = profileObj.id;
        UserRole ContractDivisionRoleId = [SELECT Id from UserRole WHERE Name = 'Contract Division' limit 1];
        User userWithContractDivisionRole = [SELECT Id, Name FROM User WHERE UserRoleId = :ContractDivisionRoleId.Id AND isActive = true limit 1];
        System.runAs(userWithContractDivisionRole){
            Account account =  Test_Utils.CreateAccountForSalesHistory();
            FieldMgr_AccountSalesHistoryExtension extension = new FieldMgr_AccountSalesHistoryExtension();
            Test.startTest(); 
            List<AggregateResult> aggregateResult =  extension.getAggregateResult();
            
            extension.refresh();
            /*System.assertEquals((Double)aggregateResult[0].get('Year_Goal__c'), 10);
            System.assertEquals((Double)aggregateResult[0].get('YTD_Sales_LY__c'), 15);
            System.assertEquals((Double)aggregateResult[0].get('MTD_Sales_TY__c'), 2);
            System.assertEquals((Double)aggregateResult[0].get('Month_Goal__c'), 05);
            System.assertEquals((Double)aggregateResult[0].get('ADS_Last_Qtr__c'), 10);
            System.assertEquals((Double)aggregateResult[0].get('Quarter_Goal__c'), 8);
            System.assertEquals((Double)aggregateResult[0].get('ADS_Current_Month__c'), 6);*/
            
            
        }
        userWithContractDivisionRole.Profileid = profId;
        update userWithContractDivisionRole;
        System.runAs(userWithContractDivisionRole){
            Account account =  Test_Utils.CreateAccountForSalesHistory();
            FieldMgr_AccountSalesHistoryExtension extension = new FieldMgr_AccountSalesHistoryExtension();
           
            List<AggregateResult> aggregateResult =  extension.getAggregateResult();
            
            extension.refresh();
            /*System.assertEquals((Double)aggregateResult[0].get('Year_Goal__c'), 10);
            System.assertEquals((Double)aggregateResult[0].get('YTD_Sales_LY__c'), 15);
            System.assertEquals((Double)aggregateResult[0].get('MTD_Sales_TY__c'), 2);
            System.assertEquals((Double)aggregateResult[0].get('Month_Goal__c'), 05);
            System.assertEquals((Double)aggregateResult[0].get('ADS_Last_Qtr__c'), 10);
            System.assertEquals((Double)aggregateResult[0].get('Quarter_Goal__c'), 8);
            System.assertEquals((Double)aggregateResult[0].get('ADS_Current_Month__c'), 6);*/
            
            Test.stopTest();
        }
    }
}