objects/Account.object
<CustomObject>
    <fields>
        <fullName>AOPS_Cust_Id__c</fullName>
        <description>AOPS Customer Account Number</description>
        <externalId>true</externalId>
        <label>AOPS Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>AOPS_Seq_ID__c</fullName>
        <externalId>true</externalId>
        <label>AOPS Seq ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Oracle_Party_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Party ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Oracle_Party_Site_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Party Site ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/GPO_Category__c.object
<CustomObject>
    <fields>
        <fullName>AOPS_Number__c</fullName>
        <label>AOPS Number</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Private__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Private</label>
        <type>Checkbox</type>
    </fields>
    <label>GPO Category</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>GPO Category Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GPO Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GPO_Group__c.object
<CustomObject>
    <fields>
        <fullName>AOPS_Cust_ID__c</fullName>
        <description>GPO Group&apos;s Account AOPS Id, used as the group&apos;s identification number.</description>
        <formula>Account__r.AOPS_Cust_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>GPO Group&apos;s Account AOPS Id, used as the group&apos;s identification number.</inlineHelpText>
        <label>AOPS Cust ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Community_Name__c</fullName>
        <label>Community Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GPO_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GPO Template</label>
        <referenceTo>GPO_Template__c</referenceTo>
        <relationshipLabel>GPO Group</relationshipLabel>
        <relationshipName>GPO_Group</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Private__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Private</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Welcome_Title__c</fullName>
        <label>Title</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>GPO Group</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>GPO Group</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GPO Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GPO_Group_Detail__c.object
<CustomObject>
    <fields>
        <fullName>GPO_Group__c</fullName>
        <label>GPO Group</label>
        <referenceTo>GPO_Group__c</referenceTo>
        <relationshipLabel>Group Group Details</relationshipLabel>
        <relationshipName>Group_Group_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <defaultValue>&apos;Greeting Message&apos;</defaultValue>
        <description>Communities v2 - Default Value is Greeting Message and should not be changed. News and NEWSCRED are no longer used. 
Can be: 
&apos;Greeting Message&apos; or &apos;News&apos; or &apos;NEWSCRED&apos;</description>
        <inlineHelpText>Should be: Greeting Message</inlineHelpText>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>GPO Group Detail</label>
    <nameField>
        <label>GPO  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Group Group Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GPO_Template__c.object
<CustomObject>
    <label>GPO Template</label>
    <nameField>
        <label>GPO Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GPO Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CommunitiesBulkUpload_TC.cls
@isTest
global class CommunitiesBulkUpload_TC {
    static testMethod void unitTest() {
        Account acct = new Account ();
        acct.name = 'SUN Test Account';
        acct.BillingStreet = '1040 N 326 W';
        acct.billingcity = 'Orem';
        acct.BillingState = 'UT';
        acct.Billingcountry = 'USA';
        acct.Oracle_Party_Id__c = '1234563456';
        acct.Oracle_Party_Site_Id__c = '1234563456';
        acct.AOPS_Cust_Id__c = '123456';
        acct.AOPS_Seq_ID__c = '127456';
        insert acct;
        
        GPO_Category__c cat = new GPO_Category__c(AOPS_Number__c = '123456', Company_Name__c = 'name1', Private__c = false);
        GPO_Template__c temp1 = new GPO_Template__c(Name = 'Communities v2');
        GPO_Group__c defGrp = new GPO_Group__c(Community_Name__c = 'Default Group', Welcome_Title__c = 'test');
        insert defGrp;
        insert cat;
        insert temp1;
        
        GPO_Group_Detail__c dtl = new GPO_Group_Detail__c(Name = 'Standard Message 3', Type__c = 'Greeting Message', GPO_Group__c = defGrp.id);
        insert dtl;
        
        Test.startTest();
        
        SchedulableContext sc = null;
        CommunitiesBulkUpload testRun = new CommunitiesBulkUpload();
        testRun.execute(sc);
        Database.executeBatch(testRun,20);
        
        String CRON_EXP = '0 0 0 3 9 ? 2022';
        String jobId = System.schedule('testBasicScheduledApex',CRON_EXP ,new CommunitiesBulkUpload());
        //Database.BatchableContext bc = new Database.BatchableContext();
        
        Test.stopTest();
    }
}