objects/Account.object
<CustomObject>
    <fields>
        <fullName>AOPS_Cust_Id__c</fullName>
        <description>AOPS Customer Account Number</description>
        <externalId>true</externalId>
        <label>AOPS Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>AOPS_Seq_ID__c</fullName>
        <externalId>true</externalId>
        <label>AOPS Seq ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Address1__c</fullName>
        <label>Address1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Oracle_Party_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Party ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Partner_Sub_Agent_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Sub-Agent Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>End User Accounts</relationshipLabel>
        <relationshipName>Contact_End_User_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Agent</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Sub Agent)</relationshipLabel>
        <relationshipName>Sub_Agent</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <description>Partner Layout for Onboarding Partners</description>
        <label>Partner</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Decision_Maker__c</fullName>
        <label>Decision Maker</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <description>OMX Primary Key</description>
        <externalId>true</externalId>
        <inlineHelpText>OMX Primary Key</inlineHelpText>
        <label>OMX Primary Key</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Address1__c</fullName>
        <inlineHelpText>This field is required in order to convert  (Unless lead is directly linked to an account)</inlineHelpText>
        <label>Address1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Decision_Maker__c</fullName>
        <label>Decision Maker</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Used in PRM for deal registration</description>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Used in PRM for Deal Registration</description>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oracle_Party_Id__c</fullName>
        <label>Oracle Party Id</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Partner_Sub_Agent_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Sub-Agent Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Contact must at the Partner Sub-Agent Account.</errorMessage>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Sub_Agent__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads_Partner_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Sub-Agent Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Account must be of type &quot;Partner&quot;.</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Sub Agent)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Token_Market_Builder__c</fullName>
        <description>The Token used for Market Builder App</description>
        <label>Token Market Builder</label>
        <length>100</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/LeaddealShare_TC.cls
@istest
public class LeaddealShare_TC {
    static testMethod void leaddealTest() {
        List < user > users = new list < user > ();
        List < Account > accounts = new list < Account > ();
        List < Contact > contacts = new list < Contact > ();
        UserRole userRole_1 = [SELECT Id FROM UserRole WHERE DeveloperName = 'support' LIMIT 1];
        Profile profileObj = [select id from profile where name = 'System Administrator'];
        String prflId = profileObj.id;
        Id RTId = Schema.SobjectType.Lead.getRecordTypeInfosByName().get('Lead (Deals)').getRecordTypeId();
        string userName = 'abcd@officedepot.com';
        string email = userName;
        string[] name = userName.split('@');
        user u1 = new user(Username = userName, FirstName = name[1], LastName = name[0], Alias = name[0], CommunityNickname = userName, LocaleSidKey = 'en_US', EmailEncodingKey = 'UTF-8', Profileid = prflId, LanguageLocaleKey = 'en_US');
        u1.email = email;
        u1.UserRoleId = userRole_1.id;
        u1.IsActive = true;
        insert u1;
        System.runAs(u1) {
            Recordtype rtPartner = [Select id, Sobjecttype from recordtype where name = 'Partner' and Sobjecttype = 'Account'];
            Account acc = new Account();
            acc.name = 'Test Company';
            acc.OMX_Primary_Key__c = '123456';
            acc.Oracle_Party_Id__c = '123456';
            acc.AOPS_Cust_Id__c = '123456';
            acc.AOPS_Seq_ID__c = '123456';
            acc.OwnerID = u1.id;
            acc.Address1__c = 'address';
            acc.RecordTypeid = rtPartner.id;
            //insert acc1;
            accounts.add(acc);
            insert accounts;
            Contact con1 = new Contact();
            con1.LastName = 'Test1';
            con1.Decision_Maker__c = 'No';
            con1.AccountId = acc.id;
            insert con1;
            system.debug('con1'+con1);
            Profile p = [select Id, name from Profile where UserType = 'PowerPartner' limit 1];
            userName = 'xyz@officedepot.com';
            email = userName;
            name = userName.split('@');
            user u = new user(Username = userName, FirstName = name[1], LastName = name[0], Alias = name[0], CommunityNickname = userName, LocaleSidKey = 'en_US', EmailEncodingKey = 'UTF-8', Profileid = p.id, LanguageLocaleKey = 'en_US');
            u.email = email;
            u.ContactId = con1.id;
            u.IsActive = true;
            u.TimeZoneSidKey = 'America/Los_Angeles';
            u.Token_Market_Builder__c = 'pqr';
            users.add(u);
            insert users;
            Lead newld = new Lead();
            newld.last_name__c = 'Test';
            newld.lastname = 'Test';
            newld.firstName = 'Test';
            newld.first_name__c = 'Test';
            newld.company = 'Test Company';
            newld.Status = 'New';
            newld.RecordTypeId = RTId;
            newld.OwnerId = userinfo.getUserId();
            newld.Email = 'abc@gmail.com';
            newld.Sub_Agent__c = con1.AccountId;
            newld.Partner_Sub_Agent_Contact__c = con1.id;
            //leads.add(newld);
            system.debug('newld'+newld);
            insert newld;
            system.debug('newld'+newld);
            newld.Partner_Sub_Agent_Contact__c = con1.id;
            update newld;
        }
    }
}