objects/Account.object
<CustomObject>
    <fields>
        <fullName>AOPS_Cust_Id__c</fullName>
        <description>AOPS Customer Account Number</description>
        <externalId>true</externalId>
        <label>AOPS Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>AOPS_Seq_ID__c</fullName>
        <externalId>true</externalId>
        <label>AOPS Seq ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Address1__c</fullName>
        <label>Address1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address2__c</fullName>
        <label>Address2</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cadence_Call_Date_Override_Value__c</fullName>
        <description>Frequency at which this customer/site should be contacted.</description>
        <label>Cadence Call Date Override Value</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cadence_Call_Date_Override__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Overrides the custom configuration for call date frequency</description>
        <label>Cadence Call Date Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cadence_Call_Date__c</fullName>
        <label>Cadence Call Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>USA</fullName>
                    <default>true</default>
                    <label>USA</label>
                </value>
                <value>
                    <fullName>CAN</fullName>
                </value>
                <value>
                    <fullName>MEX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oracle_Party_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Party ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Oracle_Party_Site_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Party Site ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Primary_Site__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Site</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Related_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>(Tech-Zone)</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is used for Primary Owner Sales ID.</description>
        <label>Sales Person ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sales_Person__c.Primary__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Person__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site</fullName>
    </fields>
    <fields>
        <fullName>Site_Contact2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site Contact2</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Related_Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>notContain</operation>
                <value>(Tech-Zone)</value>
            </filterItems>
            <infoMessage>The Contact you select must be an existing contact that is tied to the customer/prospect.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (Site Contact2)</relationshipLabel>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_Contact3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site Contact3</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Related_Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>notContain</operation>
                <value>(Tech-Zone)</value>
            </filterItems>
            <infoMessage>The Contact you select must be an existing contact that is tied to the customer/prospect.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (Site Contact3)</relationshipLabel>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_Contact4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site Contact4</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Related_Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>notContain</operation>
                <value>(Tech-Zone)</value>
            </filterItems>
            <infoMessage>The Contact you select must be an existing contact that is tied to the customer/prospect.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (Site Contact4)</relationshipLabel>
        <relationshipName>Accounts4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_Contact5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site Contact5</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Related_Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>notContain</operation>
                <value>(Tech-Zone)</value>
            </filterItems>
            <infoMessage>The Contact you select must be an existing contact that is tied to the customer/prospect.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (Site Contact5)</relationshipLabel>
        <relationshipName>Accounts5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_Contact6__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site Contact6</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Related_Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>notContain</operation>
                <value>(Tech-Zone)</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (Site Contact6)</relationshipLabel>
        <relationshipName>Accounts6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Related_Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>notContain</operation>
                <value>(Tech-Zone)</value>
            </filterItems>
            <infoMessage>The Contact you select must be an existing contact that is tied to the customer/prospect.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (Site Contact1)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Dependency on Record Type:

For Prospect Accounts - Value = Prospect

For Customer Accounts values are: New,Active,Declining,At Risk,Lost</description>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>LOY</fullName>
                </value>
                <value>
                    <fullName>SOW</fullName>
                </value>
                <value>
                    <fullName>RET</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>UT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip/Postal Code</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Site</fullName>
        <active>true</active>
        <label>Site</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Sales_Person__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Person_IDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Person ID</label>
    <nameField>
        <label>Sales Person ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Person IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>OD_Employee_ID__c</fullName>
        <externalId>true</externalId>
        <label>OD Employee ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TaskEvents_TC.cls
//
// (c) 2015 Appirio, Inc.
//
// Test Class for TaskEvents trigger
//
// 6 Mar 2015     Appirio CM - S-302450
//
//


@isTest
private class TaskEvents_TC {

//split out task test methods to avoid running into the exec limit imposed bu executeoncetest.cls


    @isTest static void test_ITdev() {
        
        Profile sa = [SELECT Id FROM profile WHERE name = 'System Administrator'];
        
        //LSLEVIN 2.10.16 S-376887 updated below liens employee id to include OD
        User u1 = new User(alias = 'test123 ', email = 'proxy@proxy456.officedepot.com', OD_Employee_ID__c = 'xx123', emailencodingkey = 'UTF-8', lastname = 'test123', languagelocalekey = 'en_US', localesidkey = 'en_US', profileid = sa.Id, timezonesidkey = 'America/Los_Angeles', username = 'proxy@proxy456.com', isactive = true);
        insert u1;
  System.runAs(u1)
    {
        
        //Generate Type Maps
        Schema.DescribeSObjectResult CR = Schema.SObjectType.Case;
        Map<String, Schema.RecordTypeInfo> CRMapByName = CR.getRecordTypeInfosByName();

        Schema.DescribeSObjectResult TR = Schema.SObjectType.Task;
        Map<String, Schema.RecordTypeInfo> TRMapByName = TR.getRecordTypeInfosByName();


        //Create a case
        Case testCase = new Case();
        testCase.RecordTypeId = CRMapByName.get('IT Cases').getRecordTypeId();
        testCase.Subject = 'Test Case';
        insert testCase;

        test.startTest();

        //create an tasks for case
        //List<Task> testTasks = new List<Task>();

        Task ITDevTask = new Task();
        ITDevTask.recordtypeid = TRMapByName.get('Support Task').getRecordTypeId();
        ITDevTask.Task_Type__c = 'IT';
        ITDevTask.action__c = 'Development';
        ITDevTask.Status =  'Completed';
        ITDevTask.WhatId = testCase.id;
        insert ITDevTask;

        test.stopTest();
    }



    }

    @isTest static void test_BizRejectTask() {

        Profile sa = [SELECT Id FROM profile WHERE name = 'System Administrator'];
        
        //LSLEVIN 2.10.16 S-376887 updated below liens employee id to include OD
        User u1 = new User(alias = 'test123 ', email = 'proxy@proxy456.officedepot.com', OD_Employee_ID__c = 'xx123', emailencodingkey = 'UTF-8', lastname = 'test123', languagelocalekey = 'en_US', localesidkey = 'en_US', profileid = sa.Id, timezonesidkey = 'America/Los_Angeles', username = 'proxy@proxy456.com', isactive = true);
        insert u1;
  System.runAs(u1)
    {

        //Generate Type Maps
        Schema.DescribeSObjectResult CR = Schema.SObjectType.Case;
        Map<String, Schema.RecordTypeInfo> CRMapByName = CR.getRecordTypeInfosByName();

        Schema.DescribeSObjectResult TR = Schema.SObjectType.Task;
        Map<String, Schema.RecordTypeInfo> TRMapByName = TR.getRecordTypeInfosByName();


        //Create a case
        Case testCase = new Case();
        testCase.RecordTypeId = CRMapByName.get('IT Cases').getRecordTypeId();
        testCase.Subject = 'Test Case';
        testCase.IT_BU_Reviewer__c = u1.id;
        insert testCase;

        test.StartTest();
        //create an tasks for case
        //List<Task> testTasks = new List<Task>();
        Task BizRejectTask = new Task();
        BizRejectTask.recordtypeid = TRMapByName.get('Support Task').getRecordTypeId();
        BizRejectTask.Task_Type__c = 'Business';
        BizRejectTask.action__c = 'Validation';
        BizRejectTask.outcome__c = 'Rejected';
        BizRejectTask.Status =  'Completed';
        BizRejectTask.WhatId = testCase.id;
        insert BizRejectTask;

        test.StopTest();

    }

    }

    @isTest static void test_BizApprovedTask() {
        //Generate Type Maps
        Schema.DescribeSObjectResult CR = Schema.SObjectType.Case;
        Map<String, Schema.RecordTypeInfo> CRMapByName = CR.getRecordTypeInfosByName();

        Schema.DescribeSObjectResult TR = Schema.SObjectType.Task;
        Map<String, Schema.RecordTypeInfo> TRMapByName = TR.getRecordTypeInfosByName();

        Profile sa = [SELECT Id FROM profile WHERE name = 'System Administrator'];
        
        //LSLEVIN 2.10.16 S-376887 updated below liens employee id to include OD
        User u1 = new User(alias = 'test123 ', email = 'proxy@proxy456.officedepot.com', OD_Employee_ID__c = 'xx456', emailencodingkey = 'UTF-8', lastname = 'test123', languagelocalekey = 'en_US', localesidkey = 'en_US', profileid = sa.Id, timezonesidkey = 'America/Los_Angeles', username = 'proxy@proxy456.com', isactive = true);
        insert u1;
          System.runAs(u1)
    {

        //Create a case
        Case testCase = new Case();
        testCase.RecordTypeId = CRMapByName.get('IT Cases').getRecordTypeId();
        testCase.Subject = 'Test Case';
        testCase.IT_BU_Reviewer__c = u1.id;
        testCase.IT_Production_Date__c = system.today();
        insert testCase;


        //create an tasks for case
        //List<Task> testTasks = new List<Task>();

        test.StartTest();

        Task BizApprovedTask = new Task();
        BizApprovedTask.recordtypeid = TRMapByName.get('Support Task').getRecordTypeId();
        BizApprovedTask.Task_Type__c = 'Business';
        BizApprovedTask.action__c = 'Validation';
        BizApprovedTask.outcome__c = 'Approved';
        BizApprovedTask.Status =  'Completed';
        BizApprovedTask.WhatId = testCase.id;
        insert BizApprovedTask;

        test.StopTest();
    }




    }

    @isTest static void test_ITMigTask() {

        Profile sa = [SELECT Id FROM profile WHERE name = 'System Administrator'];
        
        //LSLEVIN 2.10.16 S-376887 updated below liens employee id to include OD
        User u1 = new User(alias = 'test123 ', email = 'proxy@proxy456.officedepot.com', OD_Employee_ID__c = 'xx123', emailencodingkey = 'UTF-8', lastname = 'test123', languagelocalekey = 'en_US', localesidkey = 'en_US', profileid = sa.Id, timezonesidkey = 'America/Los_Angeles', username = 'proxy@proxy456.com', isactive = true);
        insert u1;
  System.runAs(u1)
    {
        //Generate Type Maps
        Schema.DescribeSObjectResult CR = Schema.SObjectType.Case;
        Map<String, Schema.RecordTypeInfo> CRMapByName = CR.getRecordTypeInfosByName();

        Schema.DescribeSObjectResult TR = Schema.SObjectType.Task;
        Map<String, Schema.RecordTypeInfo> TRMapByName = TR.getRecordTypeInfosByName();


        //Create a case
        Case testCase = new Case();
        testCase.RecordTypeId = CRMapByName.get('IT Cases').getRecordTypeId();
        testCase.Subject = 'Test Case';
        insert testCase;


        test.StartTest();

        Task ITMigTask = new Task();
        ITMigTask.recordtypeid = TRMapByName.get('Support Task').getRecordTypeId();
        ITMigTask.Task_Type__c = 'IT';
        ITMigTask.action__c = 'Migration';
        ITMigTask.Status =  'Completed';
        ITMigTask.WhatId = testCase.id;
        insert ITMigTask;

        test.StopTest();

    }

    }

    @isTest static void test_BizMigValTask() {
        //Generate Type Maps
        Schema.DescribeSObjectResult CR = Schema.SObjectType.Case;
        Map<String, Schema.RecordTypeInfo> CRMapByName = CR.getRecordTypeInfosByName();

        Schema.DescribeSObjectResult TR = Schema.SObjectType.Task;
        Map<String, Schema.RecordTypeInfo> TRMapByName = TR.getRecordTypeInfosByName();

        Profile sa = [SELECT Id FROM profile WHERE name = 'System Administrator'];
        
        //LSLEVIN 2.10.16 S-376887 updated below liens employee id to include OD
        User u1 = new User(alias = 'test123 ', email = 'proxy@proxy456.officedepot.com', OD_Employee_ID__c = 'xx887', emailencodingkey = 'UTF-8', lastname = 'test123', languagelocalekey = 'en_US', localesidkey = 'en_US', profileid = sa.Id, timezonesidkey = 'America/Los_Angeles', username = 'proxy@proxy456.com', isactive = true);
        insert u1;
          System.runAs(u1)
    {

        //Create a case
        Case testCase = new Case();
        testCase.RecordTypeId = CRMapByName.get('IT Cases').getRecordTypeId();
        testCase.Subject = 'Test Case';
        testCase.IT_BU_Reviewer__c = u1.id;
        insert testCase;


        //create an tasks for case
        //List<Task> testTasks = new List<Task>();

        test.startTest();


        Task BizMigValTask = new Task();
        BizMigValTask.recordtypeid = TRMapByName.get('Support Task').getRecordTypeId();
        BizMigValTask.Task_Type__c = 'Business';
        BizMigValTask.action__c = 'Migration Validation';
        BizMigValTask.outcome__c = 'Rejected';
        BizMigValTask.Status =  'Completed';
        BizMigValTask.WhatId = testCase.id;
        Insert BizMigValTask;

        test.stopTest();
    }

    }

    @isTest static void test_AccountTask() {
        //Generate Type Maps
        Schema.DescribeSObjectResult AR = Schema.SObjectType.Account;
        Map<String, Schema.RecordTypeInfo> ARMapByName = AR.getRecordTypeInfosByName();

        Schema.DescribeSObjectResult TR = Schema.SObjectType.Task;
        Map<String, Schema.RecordTypeInfo> TRMapByName = TR.getRecordTypeInfosByName();

        Schema.DescribeSObjectResult CR = Schema.SObjectType.Contact;
        Map<String, Schema.RecordTypeInfo> CRMapByName = CR.getRecordTypeInfosByName();

        //Create User
        Profile sa = [SELECT Id FROM profile WHERE name = 'System Administrator'];
        //LSLEVIN 2.10.16 S-376887 updated below liens employee id to include OD
        User u1 = new User(alias = 'test123 ', email = 'proxy@proxy456.officedepot.com', OD_Employee_ID__c = 'xx7789', emailencodingkey = 'UTF-8', lastname = 'test123', languagelocalekey = 'en_US', localesidkey = 'en_US', profileid = sa.Id, timezonesidkey = 'America/Los_Angeles', username = 'proxy@proxy456.com', isactive = true);
        insert u1;
  System.runAs(u1)
    {
        //Create Sales Person
        Sales_Person__c sp = new Sales_Person__c (name = 'test', user__c = u1.id);
        insert sp;

        

        //create an account
        Account acc = new Account ();
        acc.name = 'Test Account';
        acc.BillingStreet = '1040 N 326 W';
        acc.billingcity = 'Orem';
        acc.BillingState = 'UT';
        acc.Billingcountry = 'USA';
        acc.Oracle_Party_Id__c = '123456';
        acc.AOPS_Cust_Id__c = '123456';
        acc.AOPS_Seq_ID__c = '123456';
        acc.OwnerID = u1.id;
        acc.Sales_PersonID__c = sp.id;
        insert acc;
        

       Account accSite = new Account ();
       accSite.name = 'Test Site';
       accSite.BillingStreet = '1040 N 326 W';
       accSite.billingcity = 'Orem';
       accSite.BillingState = 'UT';
       accSite.Billingcountry = 'US';
       accSite.Address1__c = '4785 S Citation Drive';
       accSite.Address2__c = '202';
       accSite.City__c = 'Delray Beach';
       accSite.State__c = 'FL';
       accSite.zip__c ='33351';
       accSite.Country__c = 'USA';
       accSite.County__c = 'US';
       accSite.Related_Account__c = acc.id;
       accSite.Primary_Site__c= true;
       accSite.Oracle_Party_Site_Id__c = 'testdata';
       accSite.AOPS_Cust_Id__c = '12345678';
       accSite.AOPS_Seq_ID__c = '12345678';
       accSite.Cadence_Call_Date__c = system.today();
       accSite.Stage__c = 'SOW';
       accSite.Cadence_Call_Date_Override__c = True;
       accSite.Cadence_Call_Date_Override_Value__c = 20;
       accSite.recordtypeid = ARMapByName.get('Site').getRecordTypeId();

       insert accSite;
       


        //Create Site Contacts

        List<Contact> contacts = new List<Contact>();

        for (Integer i = 0; i < 6; i++) {
            contacts.add(new Contact(lastname = 'Test' + i,accountid = acc.id));
        }

        insert contacts;


        
        //Associate site contacts
        accSite.Site_Primary_Contact__c = contacts.get(0).id;
        accSite.Site_Contact2__c = contacts.get(1).id;
        accSite.Site_Contact3__c = contacts.get(2).id;
        accSite.Site_Contact4__c = contacts.get(3).id;
        accSite.Site_Contact5__c = contacts.get(4).id;
        accSite.Site_Contact6__c = contacts.get(5).id;
        update accSite;

        //create an tasks for case
        //List<Task> testTasks = new List<Task>();

        test.startTest();

        Task AcctTask = new Task();
        AcctTask.recordtypeid = TRMapByName.get('Inside Sales').getRecordTypeId();
        AcctTask.Call_Disposition__c = 'Sales Related';
        AcctTask.action__c = 'Migration Validation';
        AcctTask.Status =  'Completed';
        AcctTask.Call_Disposition__c = 'Pricing Maintenance';
        AcctTask.Disposition_Code__c = 'Pricing escalation';
        AcctTask.WhatId = accSite.id;
        Insert AcctTask;
        system.debug('whatid' + AcctTask.WhatId);
        test.stopTest();
    }
    }



}