objects/Account.object
<CustomObject>
    <fields>
        <fullName>Oracle_Party_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Party ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ALL PRODUCTS</fullName>
                </value>
                <value>
                    <fullName>CBS</fullName>
                </value>
                <value>
                    <fullName>CPD-PRINT</fullName>
                </value>
                <value>
                    <fullName>DEVIATED PRICING</fullName>
                </value>
                <value>
                    <fullName>FURNITURE</fullName>
                </value>
                <value>
                    <fullName>MPS</fullName>
                </value>
                <value>
                    <fullName>OFFICE SUPPLIES</fullName>
                </value>
                <value>
                    <fullName>OTHER</fullName>
                </value>
                <value>
                    <fullName>PAPER</fullName>
                </value>
                <value>
                    <fullName>Partner Compensation Agreement</fullName>
                </value>
                <value>
                    <fullName>SCHOOL SUPPLIES</fullName>
                </value>
                <value>
                    <fullName>TECHNOLOGY</fullName>
                </value>
                <value>
                    <fullName>PROPRIETARY CONTRACT</fullName>
                </value>
                <value>
                    <fullName>CPD-PROMO</fullName>
                </value>
                <value>
                    <fullName>REBATES ONLY</fullName>
                </value>
                <value>
                    <fullName>NO CONTRACT- ADD DOCUMENTS TO REPOSITORY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>MPS</fullName>
        <active>true</active>
        <label>MPS</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ContractMessage__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <label>Contract Type</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Id</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>ContractMessage</relationshipLabel>
        <relationshipName>ContractMessage</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OraclePartyId__c</fullName>
        <label>OraclePartyId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesPersonId__c</fullName>
        <label>SalesPersonId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Support__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Support</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>ContractMessage</relationshipLabel>
        <relationshipName>ContractMessage</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ContractMessage</label>
    <nameField>
        <label>ContractMessage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ContractMessage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Product_Subtype__c</fullName>
        <label>Product Subtype</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>3 Ply Masks</fullName>
                </value>
                <value>
                    <fullName>Accessories</fullName>
                </value>
                <value>
                    <fullName>Accessories – Cabling</fullName>
                </value>
                <value>
                    <fullName>Accessories - I/O</fullName>
                </value>
                <value>
                    <fullName>Accessories - PC &amp; Server Upgrades</fullName>
                </value>
                <value>
                    <fullName>Antibacterial Soap</fullName>
                </value>
                <value>
                    <fullName>Audio</fullName>
                </value>
                <value>
                    <fullName>Automatic Toner Replenishment (ATR)</fullName>
                </value>
                <value>
                    <fullName>Batteries</fullName>
                </value>
                <value>
                    <fullName>Blue Ribbon</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
                <value>
                    <fullName>Brand Identity </fullName>
                </value>
                <value>
                    <fullName>Branding/Fundraising</fullName>
                </value>
                <value>
                    <fullName>Break room</fullName>
                    <label>Break Room</label>
                </value>
                <value>
                    <fullName>Business Essentials</fullName>
                </value>
                <value>
                    <fullName>Business Services</fullName>
                </value>
                <value>
                    <fullName>C2 Collaborative</fullName>
                </value>
                <value>
                    <fullName>Cameras</fullName>
                </value>
                <value>
                    <fullName>Charging Carts</fullName>
                </value>
                <value>
                    <fullName>Checks and Forms </fullName>
                </value>
                <value>
                    <fullName>Classroom Technology</fullName>
                </value>
                <value>
                    <fullName>Cleaning</fullName>
                </value>
                <value>
                    <fullName>Cleaning &amp; Maintenance</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Pilot Programs-Collaborative Classroom</fullName>
                    <label>Collaborative Classroom</label>
                </value>
                <value>
                    <fullName>Computing - Chromebooks</fullName>
                </value>
                <value>
                    <fullName>Computing - Desktops</fullName>
                </value>
                <value>
                    <fullName>Computing - Laptops</fullName>
                </value>
                <value>
                    <fullName>Computing - Tablets</fullName>
                </value>
                <value>
                    <fullName>Computing - Workstations</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>All Supplies</fullName>
                </value>
                <value>
                    <fullName>Asset Management</fullName>
                </value>
                <value>
                    <fullName>CBFS</fullName>
                </value>
                <value>
                    <fullName>CBS/Facilities</fullName>
                </value>
                <value>
                    <fullName>Contract Furniture</fullName>
                </value>
                <value>
                    <fullName>Email Marketing</fullName>
                </value>
                <value>
                    <fullName>Ergonomics</fullName>
                </value>
                <value>
                    <fullName>Facilities- Coffee</fullName>
                </value>
                <value>
                    <fullName>Filing &amp; Binding</fullName>
                </value>
                <value>
                    <fullName>Furniture - Catalog</fullName>
                </value>
                <value>
                    <fullName>Furniture - Interiors</fullName>
                </value>
                <value>
                    <fullName>General Consultation</fullName>
                </value>
                <value>
                    <fullName>Ink &amp; Toner</fullName>
                </value>
                <value>
                    <fullName>Instructional Solutions</fullName>
                </value>
                <value>
                    <fullName>K-12 Growth</fullName>
                </value>
                <value>
                    <fullName>Labels &amp; Forms</fullName>
                </value>
                <value>
                    <fullName>Legal Services</fullName>
                </value>
                <value>
                    <fullName>Logo Design</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>MPS</fullName>
                </value>
                <value>
                    <fullName>Multi-Category</fullName>
                </value>
                <value>
                    <fullName>Office Essentials</fullName>
                </value>
                <value>
                    <fullName>Office Products</fullName>
                </value>
                <value>
                    <fullName>Office Supplies</fullName>
                </value>
                <value>
                    <fullName>Paper</fullName>
                </value>
                <value>
                    <fullName>Print and Promo</fullName>
                </value>
                <value>
                    <fullName>Print Services</fullName>
                </value>
                <value>
                    <fullName>School Supplies</fullName>
                </value>
                <value>
                    <fullName>Search Marketing</fullName>
                </value>
                <value>
                    <fullName>SEO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Person__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Person_IDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Person ID</label>
    <nameField>
        <label>Sales Person ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Person IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Case_Contract_Create.cls
/**************************************************************************
*Created By :Wipro Offshore team
*Created Date : 11/05/2012
*Purpose :Create a ContractMessage record when Create contract button is clicked from the case.

Last Modified       :
Last Modified By    :
Last Modified Reason:
***************************************************************************/
//Call back to update the Record will be from ContractMessageService Apex class

global class Case_Contract_Create
{
   
   WebService static string Case_Contract_Create (String Case_opptyid,String Case_caseid)
   {    
        try
        {
            list<case> triggernewcase = new list<Case>();
            list<opportunity> triggernewopty = new list<opportunity>();
            triggernewopty = [Select id, ownerid, accountid,Product__c,Product_Subtype__c,Probability  from opportunity where id =: Case_opptyid];
            List<Sales_Person__c> salesperID=new List<Sales_Person__c>();
            set<id> set_opptyOwnerid=new set<id>(); 
            set<id> set_opptyid=new set<id>();
            set<id> set_opptyaccountid=new set<id>();
            list<opportunity> list_opportunity2bupdated = new list<opportunity>();
            list<ContractMessage__c> ocmc=new list<ContractMessage__c>();
            list<ContractMessage__c> ocmc3=new list<ContractMessage__c>();
            list<ContractMessage__c> lst_contractmsg=new list<ContractMessage__c>();  
            Map<id,Opportunity> map1_optyid =new Map<id,Opportunity>();
            string error;
            
            for(Opportunity lst_oppty: triggernewopty)
            {
               if((lst_oppty.Product__c =='MPS')||((lst_oppty.Product__c =='Ink & Toner')&&(lst_oppty.Product_Subtype__c=='Automatic Toner Replenishment (ATR)')))
               {
                   set_opptyOwnerid.add(lst_oppty.ownerid);
                   set_opptyaccountid.add(lst_oppty.accountid);
                   set_opptyid.add(lst_oppty.id);
                   map1_optyid.put(lst_oppty.id,lst_oppty); 
               }
               else
               {
                   error = ' Opportunity Product Should be MPS';
               }
            }
            Map<id,Sales_Person__c> map_salesperID =new Map<id,Sales_Person__c>();
            for (Sales_Person__c s: [select id,Name,user__c from Sales_Person__c where user__c in:set_opptyOwnerid ])
            {
                map_salesperID.put(s.user__c,s);
            }
            
            
            map<id,account> Map_oraclepartyid = new map<id,account>([select id,name,Oracle_Party_ID__c from account where id in:set_opptyaccountid]);

                for(Opportunity lst_oppty: triggernewopty)
                {

                      if((lst_oppty.Product__c=='MPS')||((lst_oppty.Product__c =='Ink & Toner')&&(lst_oppty.Product_Subtype__c=='Automatic Toner Replenishment (ATR)')))
                      {
                          ContractMessage__c ocmc1 = new ContractMessage__c();
                          ocmc1.Opportunity_Id__c = lst_oppty.id;
                          ocmc1.Contract_Type__c = 'MPS';
                          ocmc1.OraclePartyId__c =  Map_oraclepartyid.get(lst_oppty.accountid).Oracle_Party_ID__c;
                          ocmc1.SalesPersonId__c = map_salesperID.get(lst_oppty.OwnerId).Name;
                          ocmc1.Support__c = Case_caseid;
                          ocmc.add(ocmc1); 
                      
                      }
                      else
                       {
                           error = ' Opportunity Product Should be MPS';
                       }
                }
            if(ocmc.size()!=0)
            {   
                insert ocmc;
                error = 'Contract Message Created';
            }
            return (error);
        }
        catch(exception e)
        {
            string es = string.valueof(e);
            return es;
        }      
     }
}