objects/Account.object
<CustomObject>
    <fields>
        <fullName>AOPS_Seq_ID__c</fullName>
        <externalId>true</externalId>
        <label>AOPS Seq ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer Accounts</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Parent</fullName>
        <active>true</active>
        <label>Parent</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Customer_Transition__c.object
<CustomObject>
    <description>Object to Track Customer Conversion and Review Project</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Transition Relationship</relationshipLabel>
        <relationshipName>Customer_Transition_Relationship</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cascade_Down__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cascade Transition Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Review_Start_Date__c</fullName>
        <label>Review Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field will update dynamically per your selections.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>UnScheduled</fullName>
                    <color>#0B6FCE</color>
                    <default>true</default>
                    <label>UnScheduled</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                    <color>#78C953</color>
                    <label>Scheduled</label>
                </value>
                <value>
                    <fullName>ReScheduled</fullName>
                    <color>#E27001</color>
                    <label>ReScheduled</label>
                </value>
                <value>
                    <fullName>On Deck</fullName>
                    <color>#F3D904</color>
                    <label>On Deck</label>
                </value>
                <value>
                    <fullName>Launched</fullName>
                    <color>#009900</color>
                    <label>Launched</label>
                </value>
                <value>
                    <fullName>Transition Complete</fullName>
                    <color>#A53711</color>
                    <label>Transition Complete</label>
                </value>
                <value>
                    <fullName>Audit 2</fullName>
                    <color>#66E9BD</color>
                    <label>Audit 2</label>
                </value>
                <value>
                    <fullName>Loss of Customer</fullName>
                    <color>#0B24BE</color>
                    <label>Loss of Customer</label>
                </value>
                <value>
                    <fullName>OMX Extension in Development</fullName>
                    <color>#419249</color>
                    <label>OMX Extension in Development</label>
                </value>
                <value>
                    <fullName>Ready to Order</fullName>
                    <color>#B6E32E</color>
                    <label>Ready to Order</label>
                </value>
                <value>
                    <fullName>Ready for eCom Mod</fullName>
                    <color>#641CCF</color>
                    <label>Ready for eCom Mod</label>
                </value>
                <value>
                    <fullName>Redirect Stopped</fullName>
                    <color>#F96FB7</color>
                    <label>Redirect Stopped</label>
                </value>
                <value>
                    <fullName>Auto Redirected</fullName>
                    <color>#2F5D85</color>
                    <label>Auto Redirected</label>
                </value>
                <value>
                    <fullName>Awaiting Disposition</fullName>
                    <color>#AFCADF</color>
                    <label>Awaiting Disposition</label>
                </value>
                <value>
                    <fullName>Awaiting RFP</fullName>
                    <color>#8F6429</color>
                    <label>Awaiting RFP</label>
                </value>
                <value>
                    <fullName>Administrative Close</fullName>
                    <color>#EFAE73</color>
                    <label>Administrative Close</label>
                </value>
                <value>
                    <fullName>TOOP</fullName>
                    <color>#F96FB7</color>
                    <label>TOOP</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Transition</label>
    <nameField>
        <label>Customer Transition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Transition</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/MaintainStatusHierarchy1_TC.cls
// 
// (c) 2015 Appirio, Inc.
//
//
// 23 September 2016     Connor Flynn S-440217 (OD 00816640)

@isTest
private class MaintainStatusHierarchy1_TC
{
    static testMethod void MaintainStatusHierarchy1UnitTest()
    {
    List<recordtype> custRecId= [select id from recordtype where name ='Customer'];
    
    Account grandParentAcc = new Account();
    grandParentAcc.RecordtypeId = custRecId[0].id;
    grandParentAcc.AOPS_Seq_ID__c = '987654';
    grandParentAcc.OMX_Primary_Key__c='987654';
    grandParentAcc.Name='Grand Parent Test Account';
    insert grandParentAcc;
    
    Account parentAcc = new Account();
    parentAcc.RecordtypeId = custRecId[0].id;
    parentAcc.AOPS_Seq_ID__c = '654321';
    parentAcc.OMX_Primary_Key__c='654321';
    parentAcc.Name='Parent Test Account';
    parentAcc.parentid=grandParentAcc.id;
    insert parentAcc;
    
    Account acc = new Account();
    acc.RecordtypeId = custRecId[0].id;
    acc.AOPS_Seq_ID__c = '321987';
    acc.OMX_Primary_Key__c='321987';
    acc.Name='Test Account';
    acc.parentid=parentAcc.id;
    insert acc;
    
    Account noGPAcc = new Account();
    noGPAcc.RecordtypeId = custRecId[0].id;
    noGPAcc.AOPS_Seq_ID__c = '789456';
    noGPAcc.OMX_Primary_Key__c='789456';
    noGPAcc.Name='No GP Test Account';
    noGPAcc.parentid=grandParentAcc.id;
    insert noGPAcc;
    
    Account noParentAcc = new Account();
    noParentAcc.RecordtypeId = custRecId[0].id;
    noParentAcc.AOPS_Seq_ID__c = '123789';
    noParentAcc.OMX_Primary_Key__c='123789';
    noParentAcc.Name='No Parent Test Account';
    insert noParentAcc;
    
    List<Customer_Transition__c> insertCT = new List<Customer_Transition__c>();
    List<Customer_Transition__c> updateCT = new List<Customer_Transition__c>();
    
    Customer_Transition__c CTgrandParent = new Customer_Transition__c();
    CTgrandParent.Account__c=grandParentAcc.id;
    CTgrandParent.Status__c='Launched';
    CTgrandParent.Cascade_Down__c =false;
    //insert CTgrandParent;
    
    Customer_Transition__c CTparent = new Customer_Transition__c();
    CTparent.Account__c=parentAcc.id;
    CTparent.Status__c='Launched';
    CTparent.Cascade_Down__c =false;
    //insert CTparent;
    
    Customer_Transition__c CT = new Customer_Transition__c();
    CT.Account__c=acc.id;
    CT.Status__c='Launched';
    CT.Cascade_Down__c =false;
    //insert CT;
        
    Customer_Transition__c CTfornoGPAcc = new Customer_Transition__c();
    CTfornoGPAcc.Account__c=noGPAcc.id;
    CTfornoGPAcc.Status__c='Launched';
    CTfornoGPAcc.Cascade_Down__c =false;
    //insert CTfornoGPAcc;
    
    
    
    Customer_Transition__c CTnoParentAcc = new Customer_Transition__c();
    CTnoParentAcc.Account__c=noParentAcc.id;
    CTnoParentAcc.Status__c='Launched';
    CTnoParentAcc.Cascade_Down__c =false;
    //insert CTnoParentAcc;
    
    
    insertCT.add(CT);
    insertCT.add(CTparent);
    insertCT.add(CTgrandParent);
    insertCT.add(CTfornoGPAcc);
    insertCT.add(CTnoParentAcc);
    
    insert insertCT;
    
    CT.Account__c=acc.id;
    CT.Status__c = 'Launched' ;
    CT.Cascade_Down__c = true;
    //Connor Flynn S-440217 (OD 00816640) Start
    CT.Review_Start_Date__c = System.today();
    //Connor Flynn S-440217 (OD 00816640) END
    //update CT;
    
    CTparent.Account__c=acc.id;
    CTparent.Status__c = 'Launched' ;
    CTparent.Cascade_Down__c = true;
    //update CTparent;
    
    CTgrandParent.Account__c=acc.id;
    CTgrandParent.Status__c = 'Launched' ;
    CTgrandParent.Cascade_Down__c = true;
    //update CTgrandParent;
    
    CTfornoGPAcc.Account__c=noGPAcc.id;
    CTfornoGPAcc.Status__c = 'Launched' ;
    CTfornoGPAcc.Cascade_Down__c = true;
    //update CTfornoGPAcc;
    
    
    CTnoParentAcc.Account__c=noParentAcc.id;
    CTnoParentAcc.Status__c = 'Launched' ;
    CTnoParentAcc.Cascade_Down__c = true;
    //update CTnoParentAcc;
    
    
    
    updateCT.add(CT);
    updateCT.add(CTparent);
    updateCT.add(CTgrandParent);
    updateCT.add(CTfornoGPAcc);
    updateCT.add(CTnoParentAcc);
    
    update updateCT;
    
    
    }
}