objects/Account.object
<CustomObject>
    <fields>
        <fullName>CBS_Total_LY__c</fullName>
        <label>CBS Total LY</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CPD_Total_LY__c</fullName>
        <label>CPD Total LY</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Filing_Binding_Total_LY__c</fullName>
        <label>Filing &amp; Binding Total LY</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Furniture_Total_LY__c</fullName>
        <label>Furniture Total LY</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Ink_Toner_Total_LY__c</fullName>
        <label>Ink Toner Total LY</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Labels_Forms_Total_LY__c</fullName>
        <label>Labels &amp; Forms Total LY</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MPS_Total_LY__c</fullName>
        <label>MPS Total LY</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Miscellaneous_Total_LY__c</fullName>
        <label>Miscellaneous Total LY</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Office_Essentials_Total_LY__c</fullName>
        <label>Office Essentials Total LY</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Paper_Total_LY__c</fullName>
        <label>Paper Total LY</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tech_Total_LY__c</fullName>
        <label>Tech Total LY</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Writing_Drafting_Total_LY__c</fullName>
        <label>Writing Drafting Total LY</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TotalSalesLYDefault_TC.cls
@isTest
public class TotalSalesLYDefault_TC
{

public static testmethod  void TotalSalesLYDefault ()
{

Account acc = new Account(Name='Test Account');
acc.Paper_total_LY__c = null;
acc.Ink_Toner_total_LY__c=null;
acc.Furniture_total_LY__c = null;
acc.CBS_total_LY__c =null;
acc.CPD_total_LY__c=null;
acc.Tech_total_LY__c =null;
acc.Filing_Binding_total_LY__c =null;
acc.Labels_Forms_total_LY__c=null;
acc.Writing_Drafting_total_LY__c=null;
acc.Office_Essentials_total_LY__c =null;
acc.MPS_total_LY__c = null;
acc.Miscellaneous_total_LY__c=null;
insert acc;
TotalSalesLYDefault obj = new TotalSalesLYDefault();
database.executebatch(obj,1);
SchedulableContext sc;
obj.execute(sc);

}

}