objects/Account.object
<CustomObject>
    <fields>
        <fullName>AOPS_Cust_Id__c</fullName>
        <description>AOPS Customer Account Number</description>
        <externalId>true</externalId>
        <label>AOPS Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>AOPS_Seq_ID__c</fullName>
        <externalId>true</externalId>
        <label>AOPS Seq ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Address2__c</fullName>
        <label>Address2</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DNBI_CREDIT_OUTCOME__c</fullName>
        <description>THIS IS CREATED BY MOHAN TO TEST THE CREDIT OUTCOME</description>
        <label>DNBI Credit Outcome</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Duns_Enrichment__c</fullName>
        <description>Duns Enrichment loaded October 7th, 2014</description>
        <label>Duns Enrichment</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Oracle_Party_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Party ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer Accounts</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Customer_OfficeMax</fullName>
        <active>true</active>
        <description>RecordType for legacy OfficeMax Customers</description>
        <label>Customer (OfficeMax)</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Address_Abbreviation__c.object
<CustomObject>
    <fields>
        <fullName>Abbreviation__c</fullName>
        <label>Abbreviation</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Address Abbreviation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address Abbreviation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Dataloader_User__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>User_ID__c</fullName>
        <label>User ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Dataloader Users</label>
</CustomObject>

classes/TC_OMXAccountBeforeTrigger.cls
@isTest
public class TC_OMXAccountBeforeTrigger {
    static testMethod void Test_OMXAccountBeforeTrigger(){
        test.startTest();
        
        Address_Abbreviation__c addressAbb = new Address_Abbreviation__c(name='ILLINOIS',Abbreviation__c='IL');
        insert addressAbb;
        ID usrID = UserInfo.getUserId();
        Dataloader_User__c dataloaderUser = new Dataloader_User__c(name='Dataloader',User_ID__c='005E0000000R7xz');
        insert dataloaderUser;
        
   
        Account topAccount = new Account (name = 'GP SUN Test - Top Account',
                                          AOPS_Seq_ID__c = '123666',
                                          AOPS_Cust_Id__c = '123666',
                                          Oracle_Party_Id__c = '123666',
                                          recordtypeid=System.Label.Customer_OfficeMax,
                                          Billingcountry = 'USA',
                                          BillingState = 'UT',
                                          Ownerid=usrID,
                                          Duns_Enrichment__c = '12345', 
                                          DNBI_CREDIT_OUTCOME__c = 'Approved',
                                          BillingStreet = '1040 N 326 W',
                                          billingcity = 'Orem',
                                          OMX_Primary_Key__c = 'Test_OMX_1111', //S-367255 [12/10/2015]- Fix test class 
                                          address2__c='8351 United States, 8207 Niaga');
        insert topAccount;     
        topAccount.status__c ='Active';
        topAccount.recordtypeid = System.Label.Customer;      
        update topAccount;
        
        test.stopTest();
    }
}