objects/Account.object
<CustomObject>
    <fields>
        <fullName>AOPS_Cust_Id__c</fullName>
        <description>AOPS Customer Account Number</description>
        <externalId>true</externalId>
        <label>AOPS Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer Accounts</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <description>Prospect Accounts</description>
        <label>Prospect</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/CameleonCPQ__QxQuote__c.object
<CustomObject>
    <description>PROS Smart CPQx Quote</description>
    <fields>
        <fullName>CameleonCPQ__AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>PROS Quotes</relationshipLabel>
        <relationshipName>PROSQuotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CameleonCPQ__ExternalQuoteId__c</fullName>
        <label>External Quote</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CameleonCPQ__Status__c</fullName>
        <description>Quote Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Review Internally</fullName>
                </value>
                <value>
                    <fullName>Approved Internally</fullName>
                </value>
                <value>
                    <fullName>Presented to Customer</fullName>
                </value>
                <value>
                    <fullName>Accepted by Customer</fullName>
                </value>
                <value>
                    <fullName>In Review Internally (Post-Customer)</fullName>
                </value>
                <value>
                    <fullName>Fully Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected Internally</fullName>
                </value>
                <value>
                    <fullName>Rejected by Customer</fullName>
                </value>
                <value>
                    <fullName>Awaiting Account ID</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Term_Refresh_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract Term Refresh Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Core_Id__c</fullName>
        <label>Core Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Go_Live_Date__c</fullName>
        <label>Go Live Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PROSAgreement__AgreementStatus__c</fullName>
        <label>Agreement Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PROSAgreement__Agreement_Id__c</fullName>
        <label>Agreement Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PROSAgreement__EndDate__c</fullName>
        <label>End Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PROSAgreement__StartDate__c</fullName>
        <label>Start Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PricingAnalyst__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pricing Analyst</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PROS_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote_Accepted_Timestamp__c</fullName>
        <label>Quote Accepted Timestamp</label>
        <type>DateTime</type>
    </fields>
    <label>PROS Quote</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PROS Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>AOPS_Cust_Id__c</fullName>
        <label>AOPS Id</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PROSAgreement__Agreement_Id__c</fullName>
        <label>Agreement Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Agreement</fullName>
        <active>true</active>
        <label>Agreement</label>
    </recordTypes>
    <recordTypes>
        <fullName>Proprietary</fullName>
        <active>true</active>
        <label>Proprietary</label>
    </recordTypes>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/QxVFCPQCloneQuoteController.cls
/*
 * Copyright (c) 2015 - 2018 by PROS, Inc.  All Rights Reserved.
 * This software is the confidential and proprietary information of
 * PROS, Inc. ("Confidential Information").
 * You may not disclose such Confidential Information, and may only
 * use such Confidential Information in accordance with the terms of
 * the license agreement you entered into with PROS.
 */
 
/**
 * Clone Quote - Lightning/Classic controller.
 *
 * @author rderval
 */
public class QxVFCPQCloneQuoteController {
	
    /** The debugging service */
    //public static final CameleonCPQ.QxApiClient.IDebug IDebug = new CameleonCPQ.QxApiClient.DebugFactory().newInstance();
	
    /*Global variables*/
    private static final String QX_CLONE_LABEL_PREFIX = 'Clone of ';
    private static final String QX_CLONE_LABEL_SUFFIX = '';
    //public static String cloneQuoteName{get;set;}
    /** 
     * Constructor
     *
     * @param stdController The Salesforce standard controller
     */
    public QxVFCPQCloneQuoteController(ApexPages.StandardController stdController) {
         // Empty
    }

    /** 
     * Clone the Salesforce quote object (QxQuote__c)
     *
     * @param quoteId The source quote identifier.
     * @return CloneQuoteResult The result of the clone quote operation.
     * @throws QuoteCloneException Any error catched during the clone operation.
     */
    @RemoteAction
    public static CloneQuoteResult cloneSfdcQuote(String quoteId, String qtName) {
        CloneQuoteResult result = new CloneQuoteResult();
        System.debug('1');
        final Map<String, Schema.SObjectField> flds = Schema.SObjectType.CameleonCPQ__QxQuote__c.fields.getMap();
        final List<String> fieldList = new List<String>();
        System.debug('2');
        fieldList.addAll(flds.keySet());
        String quoFlds = '';
        for(integer i=0; i<fieldList.size(); i++)
          if (flds.get(fieldList[i]).getDescribe().IsCreateable() && fieldList[i] != 'PROSAgreement__Agreement_Id__c')
              quoFlds = quoFlds + (quoFlds.length()>0?', ':'') + fieldList[i];
        
        quoFlds = (quoFlds == '' ?  'Name, CameleonCPQ__Status__c' : quoFlds) ;  
        
        if(!quoFlds.containsIgnoreCase('PricingAnalyst__c'))
        	quoFlds =  quoFlds+', PricingAnalyst__c';
        
        final String qry = 'SELECT '+quoFlds+' FROM CameleonCPQ__QxQuote__c where Id=\''+quoteId+'\'';
        System.debug('Query'+qry);
        System.debug('3');
        SObject[] queryObject;
        try {
            System.debug('4');
           queryObject = Database.query(qry);       
        }
        catch(Exception e) {
            System.debug('5'+e);
            System.debug('5'+e.getStackTraceString());
           //CameleonCPQ.QxApiClient.IDebug.debug(Logginglevel.ERROR.name(),'Exception raised when executing query ['+qry+'] :'+e.getMessage());
           throw new QuoteCloneException(e.getMessage());
        }
        if(queryObject!=null && queryObject.size()>0) {
           CameleonCPQ__QxQuote__c[] oriQuoteList = new CameleonCPQ__QxQuote__c[]{ (CameleonCPQ__QxQuote__c)queryObject[0] };
           CameleonCPQ__QxQuote__c[] newQuoteList = oriQuoteList.deepClone(false);
           String name = (String)newQuoteList[0].get('Name');
            if(name!=null ){
                qtName = qtName != null && qtName.trim() != '' ? qtName.trim() :QX_CLONE_LABEL_PREFIX+(name.length()>71?name.substring(0,70):name)+QX_CLONE_LABEL_SUFFIX;
                System.debug('qtName :'+qtName);
                //System.debug('qtName :'+cloneQuoteName);
               newQuoteList[0].put('Name',qtName);
            }
            newQuoteList[0].put('OwnerId',UserInfo.getUserId());
            QxCPQQuoteHelper.cloneQuoteProcess(oriQuoteList[0],newQuoteList[0]);
           try {
               System.debug('6 :'+newQuoteList);
               if(!QxCPQQuoteCheckAccess.checkPricingAnalyst(oriQuoteList[0])){
                   insert newQuoteList[0];
               }
               else{
                   throw new QuoteCloneException('Can not edit when Pricing Analyst populated');
               }
           } catch (DmlException e) {
              throw new QuoteCloneException(e.getDmlMessage(0));
           }
           result.targetId = newQuoteList[0].Id;
        }
        return result; 
    }

    /** 
     * Clone the quote-x quote
     *
     * @param oriQuoteId The source quote identifier.
     * @param newQuoteId The target quote identifier.
     * @return CloneQuoteResult The result of the clone quote operation.
     * @throws CloneQuoteException Any error catched during the clone operation.
     */
    @RemoteAction
    public static CloneQuoteResult cloneQxQuote(final String oriQuoteId, final String newQuoteId) {
        CloneQuoteResult result = new CloneQuoteResult();

        final Map<Id,CameleonCPQ__QxQuote__c> q = new Map<Id, CameleonCPQ__QxQuote__c>(
            [SELECT Id, Name, CameleonCPQ__ExternalQuoteId__c FROM CameleonCPQ__QxQuote__c WHERE Id IN: new String[]{oriQuoteId, newQuoteId}]);         

        if (q.get(oriQuoteId)==null) {
            System.debug('1');
            throw new QuoteCloneException('Source quote does not exist');
        }
        if (q.get(newQuoteId)==null) {
            System.debug('2');
            throw new QuoteCloneException('Target quote does not exist');
        }

        // Step 1 :Initialize a quote-x session
        final CameleonCPQ.QxApiClient.InitSessionResponse apiResponse1 = CameleonCPQ.QxApiClient.InitSession(new CameleonCPQ.QxApiClient.InitSessionRequest());
        if(apiResponse1.qxException!=null) {
            System.debug('3'+apiResponse1.qxException);
           throw new QuoteCloneException(apiResponse1.qxException);
        }    

        // Step 2 :Clone the quote-x quote
        final CameleonCPQ.QxApiClient.CloneQuoteRequest apiRequest2 = new CameleonCPQ.QxApiClient.CloneQuoteRequest();
        final CameleonCPQ.QxApiClient.QxRequestContext qxReqCtx = new CameleonCPQ.QxApiClient.QxRequestContext();
        qxReqCtx.sessionId = apiResponse1.sessionId;
        qxReqCtx.crmQuoteId = oriQuoteId;
        qxReqCtx.qxQuoteId = q.get(oriQuoteId).CameleonCPQ__ExternalQuoteId__c;
        apiRequest2.qxReqCtx = qxReqCtx;
        CameleonCPQ.QxApiClient.CloneQuoteRequestBody requestBody = new CameleonCPQ.QxApiClient.CloneQuoteRequestBody();
        requestBody.description = q.get(newQuoteId).Name;
        apiRequest2.requestBody = requestBody;

        final CameleonCPQ.QxApiClient.CloneQuoteResponse apiResponse2 = CameleonCPQ.QxApiClient.cloneQuote(apiRequest2);
        if (apiResponse2.statusCode >= 400) {
            System.debug('4'+apiResponse2);
            System.debug('4'+qxReqCtx);
           throw new QuoteCloneException(apiResponse2.qxException);
        }
        else {
           q.get(newQuoteId).CameleonCPQ__ExternalQuoteId__c = apiResponse2.id;
            QxCPQQuoteCheckAccess.isClone = true;
           update q.get(newQuoteId);
           result.targetId = apiResponse2.id;
        }
        return result; 

    }

    /**
     * The result of a cloneQuote operation.
     */
    public class CloneQuoteResult {

        /** The ID of the cloned quote */
        public String targetId { get; set; }
    }

    /**
     * Exception class.
     */
    public class QuoteCloneException extends Exception {}


   
    /** 
     * Create & Publih the quote agreement
     *
     * @param qId The source Quote Id
     * @return Result The result of the publish quote operation.
     */
    @RemoteAction
    public static String createAgreement(ID qid){ 
		String result = 'OK';
		if(qid != null){
			
			List<CameleonCPQ__QxQuote__c> quotes = [SELECT Id,Name,PROSAgreement__AgreementStatus__c,CameleonCPQ__Status__c,CameleonCPQ__AccountId__r.AOPS_Cust_Id__c,Core_Id__c,PROSAgreement__StartDate__c,PROSAgreement__EndDate__c,Go_Live_Date__c FROM CameleonCPQ__QxQuote__c WHERE Id=: qid];
			
			if(quotes.size()>0){
                if(quotes[0].CameleonCPQ__AccountId__r.AOPS_Cust_Id__c != null && quotes[0].Core_Id__c != null){
                    if(quotes[0].PROSAgreement__AgreementStatus__c == null || (quotes[0].PROSAgreement__AgreementStatus__c != 'PendingPublish' && quotes[0].PROSAgreement__AgreementStatus__c != 'Published')){
                        if(quotes[0].CameleonCPQ__Status__c == 'Fully Approved'){
                            quotes[0].PROSAgreement__AgreementStatus__c='PendingPublish';
                            quotes[0].Quote_Accepted_Timestamp__c=DateTime.now();
                            if(quotes[0].Go_Live_Date__c == null || quotes[0].Go_Live_Date__c < Date.today())
                                quotes[0].Go_Live_Date__c=Date.today();
                            quotes[0].PROSAgreement__StartDate__c = DateTime.newInstance(quotes[0].Go_Live_Date__c.year() ,quotes[0].Go_Live_Date__c.month() ,quotes[0].Go_Live_Date__c.day(),0,0,0).format('yyyy-MM-dd') ;
                            if(quotes[0].PROSAgreement__EndDate__c == null)
                                quotes[0].PROSAgreement__EndDate__c = DateTime.newInstance(2999 ,12 ,31).format('yyyy-MM-dd') ;
                            try {
                                update quotes[0];       
                            }
                            catch(Exception e) {
                                result = e.getMessage();
                            }  
                        }else{
                            result = 'Quote must be Fully Approved to publish Agreement' ;
                        }
                    }else{
                        result = 'Agreement already being created/published!' ; 
                    }
                }else{
                    result = 'Core not generated and/or Customer AOPS Id not existing (Prospect)' ;
                }
				
			}
			
		}
		return result;
	 }

    
    /*
     * Refresh Contract Terms
     * 
     * @param qId The source Quote Id
     * @return Result The result of the refresh contract terms operation.
     */
    @RemoteAction
    public static String refreshContractTerms(ID qid){ 
		String result = 'OK';
		if(qid != null){
			
			List<CameleonCPQ__QxQuote__c> quotes = [SELECT Id,Name,CameleonCPQ__Status__c,Contract_Term_Refresh_Trigger__c FROM CameleonCPQ__QxQuote__c WHERE Id=: qid];
			
			if(quotes.size()>0){

				if(quotes[0].CameleonCPQ__Status__c == 'Draft'){
					quotes[0].Contract_Term_Refresh_Trigger__c = !quotes[0].Contract_Term_Refresh_Trigger__c;
					try {
						update quotes[0];       
					}
					catch(Exception e) {
						result = e.getMessage();
					}  
				}else{
					result = 'Quote must be Draft to refresh contract terms.' ;
				}
 
			}
			
		}
		return result;
	 }

}