objects/Account.object
<CustomObject>
    <fields>
        <fullName>AOPS_Cust_Id__c</fullName>
        <description>AOPS Customer Account Number</description>
        <externalId>true</externalId>
        <label>AOPS Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer Accounts</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Customer_Transition__c.object
<CustomObject>
    <description>Object to Track Customer Conversion and Review Project</description>
    <fields>
        <fullName>AOPS_ID__c</fullName>
        <description>AOPS ID entered after customer passes Mod 1.</description>
        <externalId>true</externalId>
        <label>AOPS ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Transition Relationship</relationshipLabel>
        <relationshipName>Customer_Transition_Relationship</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Customer Transition</label>
    <nameField>
        <label>Customer Transition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Transition</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/OfficeMax_OfficeDepot_CrossReference__c.object
<CustomObject>
    <fields>
        <fullName>AOPS_Id__c</fullName>
        <formula>text(value(AOPS_Number__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AOPS Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AOPS_Number__c</fullName>
        <label>AOPS Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_Date__c</fullName>
        <label>Created Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Customer_Transition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Transition</label>
        <referenceTo>Customer_Transition__c</referenceTo>
        <relationshipLabel>OfficeMaxOfficeDepot CrossReference</relationshipLabel>
        <relationshipName>OfficeMaxOfficeDepot_CrossReference</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OMX_Key__c</fullName>
        <label>OMX Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Desc__c</fullName>
        <formula>IF(text(Source__c)==&quot;O&quot;, &apos;TOOP&apos;, 
    IF(text(Source__c)==&quot;D&quot;, &apos;Existing Account&apos;, 
    IF(text(Source__c)==&quot;E&quot;, &apos;Existing Account&apos;, 
    IF(text(Source__c)==&quot;N&quot;, &apos;SFDC&apos;, text(Source__c)
    )
    )
 )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Source</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>O</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>S</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>OfficeMaxOfficeDepot CrossReference</label>
    <nameField>
        <displayFormat>MD-{0000}</displayFormat>
        <label>OfficeMaxOfficeDepot CrossReference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OfficeMaxOfficeDepot CrossReference</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/XrefData.cls
// Functionality to bring the Cross REference Data for Customer Transition Object
public class XrefData{
//variable declaration
ID CTid;
List<OfficeMax_OfficeDepot_CrossReference__c> LoadData= new List<OfficeMax_OfficeDepot_CrossReference__c>();

public XrefData(ApexPages.StandardController controller) {
    //get Transition Id
    CTid =ApexPages.currentPage().getParameters().get('ID');
    customer_transition__C  acc=[Select OMX_primary_key__C, account__r.aops_cust_id__C from customer_transition__C where Id=:CTid ];
    String OMXKey=acc.OMX_primary_key__C ;
    string aopskey=acc.account__r.aops_cust_id__C;
    
    //get Cross Reference Data
     LoadData=[SELECT id, AOPS_Number__c, Created_Date__c, OMX_Key__c, Source__c,Source_Desc__C,aops_id__C
      from OfficeMax_OfficeDepot_CrossReference__c 
     where OMX_Key__c = :OMXKey  or aops_id__C=:aopskey];
}

// Loading Data
public List<OfficeMax_OfficeDepot_CrossReference__c> getLoadData(){
return LoadData;
}
}