objects/Account.object
<CustomObject>
    <fields>
        <fullName>AOPS_Cust_Id__c</fullName>
        <description>AOPS Customer Account Number</description>
        <externalId>true</externalId>
        <label>AOPS Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>AOPS_Seq_ID__c</fullName>
        <externalId>true</externalId>
        <label>AOPS Seq ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Address2__c</fullName>
        <label>Address2</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DNBI_CREDIT_OUTCOME__c</fullName>
        <description>THIS IS CREATED BY MOHAN TO TEST THE CREDIT OUTCOME</description>
        <label>DNBI Credit Outcome</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Duns_Enrichment__c</fullName>
        <description>Duns Enrichment loaded October 7th, 2014</description>
        <label>Duns Enrichment</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Implementation_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for the Account Maintenance case owner ship calculation</description>
        <label>Implementation Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Oracle_Party_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Party ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sales_PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is used for Primary Owner Sales ID.</description>
        <label>Sales Person ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sales_Person__c.Primary__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Person__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer Accounts</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>GrandParent</fullName>
        <active>true</active>
        <description>Used for GP Maintenance</description>
        <label>GrandParent</label>
    </recordTypes>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <description>Prospect Accounts</description>
        <label>Prospect</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Dataloader_User__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>User_ID__c</fullName>
        <label>User ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Dataloader Users</label>
</CustomObject>

objects/DNBI_Credentials__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To provide the Credentials to connect to DNBI System</description>
    <fields>
        <fullName>DnB_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If Checked will enable the DNBI functionality in the Account Triggers</description>
        <label>DnB Active</label>
        <type>Checkbox</type>
    </fields>
    <label>DNBI Credentials</label>
</CustomObject>

objects/Sales_Person__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role_Relate_Id__c</fullName>
        <externalId>true</externalId>
        <label>Role Relate Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Person_IDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Person ID</label>
    <nameField>
        <label>Sales Person ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Person IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>OD_Employee_ID__c</fullName>
        <externalId>true</externalId>
        <label>OD Employee ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TC_AccountTriggers.cls
@isTest
public class TC_AccountTriggers {
    
    static testMethod void testAccountTriggers(){
        test.startTest();
        
        Dataloader_User__c dataloaderUser = new Dataloader_User__c(name='Dataloader',User_ID__c=UserInfo.getUserId().substring(0,15));
        insert dataloaderUser;
        
        Id rtId = [SELECT Id, Name, SobjectType, DeveloperName FROM RecordType where SobjectType='Account' and DeveloperName='GrandParent'].id;
        ID usrID = UserInfo.getUserId();
        
        Sales_Person__c s1= new Sales_Person__c();
        s1.IsActive__c=true;
        s1.Role_Relate_Id__c ='222222';
        s1.Primary__c =true;
        s1.user__c = usrID;
        insert s1;
        Sales_Person__c s2= new Sales_Person__c();
        s2.IsActive__c=true;
        s2.Role_Relate_Id__c ='333333';
        s2.Primary__c =true;
        s2.user__c = usrID;
        insert s2;
        
        Profile p = [SELECT Id FROM profile WHERE name='System Administrator'];   
        User u = new User(alias = 'test123 ', email='proxy@proxy456.officedepot.com',OD_Employee_ID__c='123466',emailencodingkey='UTF-8', lastname='test123',languagelocalekey='en_US',localesidkey='en_US', profileid = p.Id,timezonesidkey='America/Los_Angeles',username='proxy@proxy456.com',isactive=true);
        insert u; 
        DNBI_Credentials__c dnbi = new DNBI_Credentials__c(Name = 'Test123',DnB_Active__c= true);
        insert dnbi;
        Account topAccount = new Account (name = 'GP SUN Test - Top Account',
                                          AOPS_Seq_ID__c = '942114',
                                          AOPS_Cust_Id__c = '942114',
                                          Oracle_Party_Id__c = '942114',
                                          recordtypeid=rtId,
                                          Billingcountry = 'USA',
                                          BillingState = 'UT',
                                          Ownerid=usrID,
                                          Duns_Enrichment__c = '12345', 
                                          DNBI_CREDIT_OUTCOME__c = 'Approved',
                                          BillingStreet = '1040 N 326 W',
                                          billingcity = 'Orem',
                                          OMX_Primary_Key__c = 'Test_OMX_1111', //S-367255 [12/10/2015]- Fix test class 
                                          address2__c='8351 United States, 8207 Niaga',
                                          Sales_PersonID__c = s1.id);
        insert topAccount;    
        Account topAccount1 = new Account (name = 'GP SUN Test - Top Account',
                                           AOPS_Seq_ID__c = '94211411',
                                           AOPS_Cust_Id__c = '94211411',
                                           Oracle_Party_Id__c = '94211411',
                                           recordtypeid=rtId,
                                           Billingcountry = 'USA',
                                           BillingState = 'UT',
                                           Ownerid=usrID,
                                           Duns_Enrichment__c = '12345', 
                                           DNBI_CREDIT_OUTCOME__c = 'Approved',
                                           BillingStreet = '1040 N 326 W',
                                           billingcity = 'Orem',
                                           OMX_Primary_Key__c = 'Test_OMX_11111', //S-367255 [12/10/2015]- Fix test class 
                                           address2__c='8351 United States, 8207 Niaga',
                                           Sales_PersonID__c = s1.id,
                                           status__c ='Inactive');
        insert topAccount1;
        topAccount1.Sales_PersonID__c = s2.id;
        topAccount1.status__c ='Active';
        topAccount1.Implementation_Manager__c= u.id;
        topAccount1.Duns_Enrichment__c = '';
        topAccount1.DNBI_CREDIT_OUTCOME__c = '';
        topAccount1.address2__c =  '1234 United States, 3456 Niaga';
        update topAccount1;
        test.stopTest();
    }
    
    static testMethod void testAccountTriggers2(){
        test.startTest();
        DNBI_Credentials__c dnbi = new DNBI_Credentials__c(Name = 'Test123',DnB_Active__c= true);
        insert dnbi;
        Id ProspectRecordTypeID = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Prospect').getRecordTypeId();
        Account topAccount = new Account (name = 'GP SUN Test - Top Account',
                                          AOPS_Seq_ID__c = '942114',
                                          AOPS_Cust_Id__c = '942114',
                                          Oracle_Party_Id__c = '942114',
                                          recordtypeid=ProspectRecordTypeID,
                                          Billingcountry = 'USA',
                                          BillingState = 'UT',
                                          Duns_Enrichment__c = '12345', 
                                          DNBI_CREDIT_OUTCOME__c = 'Approved',
                                          BillingStreet = '1040 N 326 W',
                                          billingcity = 'Orem',
                                          OMX_Primary_Key__c = 'Test_OMX_1111', //S-367255 [12/10/2015]- Fix test class 
                                          address2__c='8351 United States, 8207 Niaga'
                                         );
        insert topAccount;
        topAccount.Address2__c = 'Test';
        update topAccount;
        test.stopTest();
    }
    static testMethod void testUpdateAOPSAssignedOnRecordTypeChange(){
        test.startTest();
        Dataloader_User__c dataloaderUser = new Dataloader_User__c(name='Dataloader',User_ID__c=UserInfo.getUserId().substring(0,15));
        insert dataloaderUser;
        ID usrID = UserInfo.getUserId();
        
        Account topAccount = new Account (name = 'GP SUN Test - Top Account',
                                          AOPS_Seq_ID__c = '942114',
                                          AOPS_Cust_Id__c = '942114',
                                          Oracle_Party_Id__c = '942114',
                                          Billingcountry = 'USA',
                                          BillingState = 'UT',
                                          Ownerid=usrID,
                                          Duns_Enrichment__c = '12345', 
                                          DNBI_CREDIT_OUTCOME__c = 'Approved',
                                          BillingStreet = '1040 N 326 W',
                                          billingcity = 'Orem',
                                          OMX_Primary_Key__c = 'Test_OMX_1111', //S-367255 [12/10/2015]- Fix test class 
                                          address2__c='8351 United States, 8207 Niaga',
                                          recordtypeId = '012E000000092k3'
                                         );
        insert topAccount;    
        Account acc = [select id,recordtypeId from Account where id =:topAccount.id];
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        update acc;
        test.stopTest();
    }
    
}