objects/Account.object
<CustomObject>
    <fields>
        <fullName>Parent_ID__c</fullName>
        <formula>iF(CONTAINS(RecordType.Name, &apos;Site&apos;), Related_Account__r.Parent.Cust_ID__c, 
  IF(RecordType.Name ==&apos;Customer (GT)&apos;, Parent.OMX_Primary_Key__c, 
   IF(RecordType.Name ==&apos;Customer (OfficeMax)&apos;  &amp;&amp; Parent.OMX_Primary_Key__c!=&apos;&apos;, Parent.OMX_Primary_Key__c, Parent.AOPS_Cust_Id__c

   
  )
 )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent ID</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer Accounts</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Admin_Context__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Admin Context</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>(Tech-Zone)</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (Admin Context)</relationshipLabel>
        <relationshipName>Contacts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GPO_Community__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GPO Community</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>(Tech-Zone)</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (GPO Community)</relationshipLabel>
        <relationshipName>Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/GPO_Community_Setup__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used for GPO Communities</description>
    <fields>
        <fullName>Admin_ProfileId__c</fullName>
        <description>This contains the ID for the super user admin profile and used to display admin header</description>
        <label>Admin ProfileId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Page__c</fullName>
        <label>Home Page</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Image_Path__c</fullName>
        <label>Image Path</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Keep_Alive_URL__c</fullName>
        <label>Keep Alive URL</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_Page__c</fullName>
        <label>Member Page</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>captcha_publicKey__c</fullName>
        <label>captcha publicKey</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>defaultRecordType__c</fullName>
        <label>defaultRecordType</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>defaultTemplate__c</fullName>
        <label>defaultTemplate</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>enabled_group_recordtypeid__c</fullName>
        <label>enabled group recordtypeid</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>signin_link__c</fullName>
        <label>signin link</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>GPO Community Setup</label>
</CustomObject>

objects/GPO_Group__c.object
<CustomObject>
    <fields>
        <fullName>Activated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>NOTE: Once activated, the Community can NOT be deactivated.</description>
        <inlineHelpText>NOTE: Once activated, the Community can NOT be deactivated.</inlineHelpText>
        <label>Activated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Community_Image__c</fullName>
        <label>Community Image</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Community_Name__c</fullName>
        <label>Community Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GPO_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GPO Template</label>
        <referenceTo>GPO_Template__c</referenceTo>
        <relationshipLabel>GPO Group</relationshipLabel>
        <relationshipName>GPO_Group</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <formula>IF(Account__r.ParentId != null, Account__r.ParentId,&apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Selected_Message__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Communities v2 - The Group&apos;s Selected Greeting Message that will display on the pre-login page.</description>
        <inlineHelpText>This is the Greeting Message that will display on the pre-login page.</inlineHelpText>
        <label>Selected Message</label>
        <referenceTo>GPO_Group_Detail__c</referenceTo>
        <relationshipLabel>GPO Group</relationshipLabel>
        <relationshipName>GPO_Group</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Welcome_Title__c</fullName>
        <label>Title</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>GPO Group</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>GPO Group</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GPO Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GPO_Group_Detail__c.object
<CustomObject>
    <fields>
        <fullName>GPO_Group__c</fullName>
        <label>GPO Group</label>
        <referenceTo>GPO_Group__c</referenceTo>
        <relationshipLabel>Group Group Details</relationshipLabel>
        <relationshipName>Group_Group_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Greeting_Message__c</fullName>
        <description>Communities v2</description>
        <inlineHelpText>Communities v2</inlineHelpText>
        <label>Greeting Message</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <defaultValue>&apos;Greeting Message&apos;</defaultValue>
        <description>Communities v2 - Default Value is Greeting Message and should not be changed. News and NEWSCRED are no longer used. 
Can be: 
&apos;Greeting Message&apos; or &apos;News&apos; or &apos;NEWSCRED&apos;</description>
        <inlineHelpText>Should be: Greeting Message</inlineHelpText>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>GPO Group Detail</label>
    <nameField>
        <label>GPO  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Group Group Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GPO_Lead__c.object
<CustomObject>
    <fields>
        <fullName>GPO_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Community this user registered under, this field is used in email template.</description>
        <inlineHelpText>Community that this user registered under</inlineHelpText>
        <label>GPO Group</label>
        <referenceTo>GPO_Group__c</referenceTo>
        <relationshipLabel>User Registrations</relationshipLabel>
        <relationshipName>User_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Registration</label>
    <nameField>
        <label>GPO  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Registrations</pluralLabel>
    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <label>Default</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GPO_Template__c.object
<CustomObject>
    <fields>
        <fullName>Home_Page__c</fullName>
        <label>Home Page</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_Page__c</fullName>
        <label>Member Page</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>GPO Template</label>
    <nameField>
        <label>GPO Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GPO Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <description>This field is only editable by System Admin or through uploading</description>
        <inlineHelpText>Editable by System Admin or through data upload</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sales Play</fullName>
                </value>
                <value>
                    <fullName>Marketing Interest</fullName>
                </value>
                <value>
                    <fullName>Sales Initiative</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>GT_Employee_ID__c</fullName>
        <description>This is the HR EMP Id from G&amp;T - Canada</description>
        <externalId>true</externalId>
        <label>GT Employee ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MB_Expiration_Date__c</fullName>
        <description>market Builder Exp date time for TOKEN</description>
        <label>MB Expiration Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OD_Employee_ID__c</fullName>
        <externalId>true</externalId>
        <label>OD Employee ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Token_Market_Builder__c</fullName>
        <description>The Token used for Market Builder App</description>
        <label>Token Market Builder</label>
        <length>100</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/xGPOSiteTemplate1ConExt_TC.cls
@isTest
private class xGPOSiteTemplate1ConExt_TC
{
    static testMethod void myUnitTest() 
    {
        User user = getTestUser('System Administrator','aaab@officedepot.com','227112');
        //Account parentAcc = Test_Utils.getTestAccount(user,'123456');
        System.runAs(user){
            Account account = Test_Utils.getTestAccount(user,'123456');
            Contact contact =  CreateContact(account.Id);
            GPO_Template__c gpoTemp = Test_Utils.createGPOTemplate('Sample Template',false);
            gpoTemp.Home_Page__c =  '/gpo/GPOHome';
            gpoTemp.Member_Page__c = '/gpo/GPOMember';
            insert gpoTemp;
            GPO_Community_Setup__c gpoCommunitySetup = Test_Utils.createGPOCommunitySetUp(gpoTemp,false);
            gpoCommunitySetup.member_page__C = '/gpo/GPOMember';
            gpoCommunitySetup.home_page__c = '/gpo/GPOHome';
            gpoCommunitySetup.image_path__c = '/gpo/servlet/servlet.FileDownload?file=';
            
            //gpoCommunitySetup.enabled_group_recordtypeid__c = '012M00000000jDDIAY';
            gpoCommunitySetup.enabled_group_recordtypeid__c = Schema.SObjectType.GPO_Group__c.getRecordTypeInfosByName().get('Enabled GPO Community').getRecordTypeId(); //S-321807
            gpoCommunitySetup.captcha_publicKey__c = '6Lc38AQTAAAAAKynztg9AZWXYB1a5h-YDj7EXKQi';
            insert gpoCommunitySetup ;
            // @Added by laxmikanth
            GPO_Community_Setup__c gpoCommunitySetUp1 = new GPO_Community_Setup__c();
            gpoCommunitySetUp1.Name = 'com2Settings';
            gpoCommunitySetup1.signin_link__c = 'https://oduat-officedepotcorp.cs78.force.com/gpo/GPOMember';
            insert gpoCommunitySetup1;
            // LK @
            GPO_Group__c gpoGroup = Test_Utils.createGPOGroup(gpoTemp, account, false);
            gpoGroup.Welcome_Title__c = 'Test GPO Group Title';
            //gpoGroup.RecordTypeId = '012M00000000jDEIAY';
            gpoGroup.RecordTypeId = Schema.SObjectType.GPO_Group__c.getRecordTypeInfosByName().get('Template Default').getRecordTypeId(); //S-321807
            gpoGroup.activated__c = true;
            //gpoGroup.Community_Image__c = att.Id;
            //gpoGroup.Parent__c = account.Id;
            gpogroup.Community_Name__c = 'Default Group';
            insert gpoGroup;
            System.debug('Testqwertyuiopoiuytrewertyuiopoiuytrew'+ gpoGroup);//Test
            GPO_Group_Detail__c ggd1 = new GPO_Group_Detail__c();
            ggd1.Greeting_Message__c = 'x';
            ggd1.GPO_Group__c = gpogroup.id;
            ggd1.Name = 'Standard Message 1';
            insert ggd1;
            update gpoGroup;
            Attachment att = new Attachment();
            att.Name = 'Test';
            att.body = Blob.valueOf('test');
            att.ParentId = gpoGroup.Id;
            insert att;
            gpoGroup.Community_Image__c = att.Id;
            update gpoGroup;
         
         GPO_Lead__c lead = Test_Utils.createGPOLead(account,true);
       // User portalUser = getCommunityUser('aaa@officedepot.com','227112',contact.Id);
       // System.runAs(portalUser){
          
          ApexPages.currentPage().getParameters().put('id','123456');
          ApexPages.currentPage().getParameters().put('recaptcha_challenge_field','test');
          ApexPages.currentPage().getParameters().put('recaptcha_response_field','test');
          GPOCommunityLandingController gpoCommunityLanding = new GPOCommunityLandingController();
          
          String pubKey = gpoCommunityLanding.publicKey;
          String clg = gpoCommunityLanding.challenge ;
          String res = gpoCommunityLanding.response ;
          PageReference chkusr = gpoCommunityLanding.checkUser();
          PageReference templateHome = gpoCommunityLanding.getTemplateHomePage();
          PageReference templateMember = gpoCommunityLanding.getTemplateMemberPage();
          String memberPage = gpoCommunityLanding.getMemberPage();
          String homePage = gpoCommunityLanding.getMemberPage();
          String imageRoot = gpoCommunityLanding.getImageRootPath();
          Boolean idImage = gpoCommunityLanding.getIsImageDefined();
         // Boolean gpoTemp = gpoCommunityLanding.getGPOTempateUsed();
          gpoCommunityLanding.newLead();
          //gpoCommunityLanding.saveLead();
          
          //GPO_Template__c temp = Test_Utils.createGPOTemplate('test XYZ' , true);
          //GPO_Group__c grp = Test_Utils.createGPOGroup(gpoTemp ,account  , true);
          
          GPO_Group_Detail__c  grpDetail = Test_Utils.createGPOGroupDetail(gpoGroup , 'test detail XXt',true);
           //GPOCommunityAuthLandingController  authLand = new GPOCommunityAuthLandingController ();
    gpoCommunityLanding.selectedGroup.ID  =gpoGroup.id; 
    xGPOSiteTemplate1ConExt tempCon = new xGPOSiteTemplate1ConExt(gpoCommunityLanding);
   // GPOSiteTemplate1ConExt tempCon2 = new GPOSiteTemplate1ConExt(authLand );
    tempCon.Cancel();
    tempCon.getNewsItems();
    
    //tempCon.NewsSave();
          
        }    
           
     }    
     
     
     static testMethod void myUnitTest2() {
      User user = getTestUser('System Administrator','aaab@officedepot.com','227112');
      //Account parentAcc = Test_Utils.getTestAccount(user,'123456');
      System.runAs(user){
        Account account = Test_Utils.getTestAccount(user,'123456');
        //Added for Case#00123471
        Account account1 = Test_Utils.getTestAccount(user,'123457');
        //end Case#00123471
         Account childAcc = Test_Utils.getTestAccount(user,'1234561');
        childAcc.ParentId = account.Id;
        update  childAcc;
        
       
        //account.Parent_ID__c =  parentAcc.Id;
        //update account;
        //modified below line for Case#00123471 
        Contact contact =  CreateContact(account1.Id);
        
        //User user = Test_Utils.getTestUser('System Administrator','aaa@officedepot.com','227112');
       
        GPO_Template__c gpoTemp = Test_Utils.createGPOTemplate('Sample Template',false);
        gpoTemp.Home_Page__c =  '/gpo/GPOHome';
        gpoTemp.Member_Page__c = '/gpo/GPOMember';
        insert gpoTemp;
        GPO_Community_Setup__c gpoCommunitySetup = Test_Utils.createGPOCommunitySetUp(gpoTemp,false);
        gpoCommunitySetup.member_page__C = '/gpo/GPOMember';
        gpoCommunitySetup.home_page__c = '/gpo/GPOHome';
        gpoCommunitySetup.image_path__c = '/gpo/servlet/servlet.FileDownload?file=';
        //gpoCommunitySetup.enabled_group_recordtypeid__c = '012M00000000jDDIAY';
        gpoCommunitySetup.enabled_group_recordtypeid__c = Schema.SObjectType.GPO_Group__c.getRecordTypeInfosByName().get('Enabled GPO Community').getRecordTypeId(); //S-321807
        insert gpoCommunitySetup ;
        
        //Communities v2 changes
        GPO_Community_Setup__c gpoCommunitySetUp2 = new GPO_Community_Setup__c();
            gpoCommunitySetUp2.Name = 'com2Settings';
            gpoCommunitySetUp2.defaultTemplate__c = gpoTemp.Id;
            gpoCommunitySetUp2.Admin_ProfileId__c = '00eE0000000IQxT';
            gpoCommunitySetUp2.defaultRecordType__c = '012E000000093wNIAQ';
            gpoCommunitySetup2.member_page__C = '/gpo/GPOMember';
            gpoCommunitySetup2.home_page__c = '/gpo/GPOHome';
            gpoCommunitySetup2.image_path__c = '/gpo/servlet/servlet.FileDownload?file=';
            gpoCommunitySetUp2.enabled_group_recordtypeid__c = '012E000000093wMIAQ';
            gpoCommunitySetup2.Keep_Alive_URL__c = 'https://business.officedepot.com/account/SSO/keepAlive.do';
            insert gpoCommunitySetup2;
        /*
            GPO_Group__c gpoGroup2 = Test_Utils.createGPOGroup(gpoTemp, account1, false);
            gpoGroup2.Welcome_Title__c = 'Test GPO Group Title';
            gpoGroup2.RecordTypeId = Schema.SObjectType.GPO_Group__c.getRecordTypeInfosByName().get('Template Default').getRecordTypeId(); //S-321807
            gpoGroup2.activated__c = true;
            gpogroup2.Community_Name__c = 'Default Group';
            insert gpoGroup2;
          */  
            
        //modified below line for Case#00123471  
        GPO_Group__c gpoGroup = Test_Utils.createGPOGroup(gpoTemp, account1, false);
            gpoGroup.Welcome_Title__c = 'Test GPO Group Title';
            //gpoGroup.RecordTypeId = '012M00000000jDEIAY';
            gpoGroup.RecordTypeId = Schema.SObjectType.GPO_Group__c.getRecordTypeInfosByName().get('Template Default').getRecordTypeId(); //S-321807
           gpoGroup.activated__c = true;
           gpogroup.Community_Name__c = 'Default Group';
            //gpoGroup.Community_Image__c = att.Id;
            //gpoGroup.Parent__c = account.Id;
        insert gpoGroup;
        GPO_Group_Detail__c ggd1 = new GPO_Group_Detail__c();
            ggd1.Greeting_Message__c = 'x';
            ggd1.GPO_Group__c = gpogroup.id;
            ggd1.Name = 'Standard Message 1';
            insert ggd1;
            gpoGroup.selected_message__c = ggd1.Id;
            update gpoGroup;
       Attachment att = new Attachment();
          att.Name = 'Test';
         att.body = Blob.valueOf('test');
         att.ParentId = gpoGroup.Id;
         insert att;
         gpoGroup.Community_Image__c = att.Id;
         update gpoGroup;
         
         GPO_Lead__c lead = Test_Utils.createGPOLead(account,true);
         GPO_Group_Detail__c  grpDetail = Test_Utils.createGPOGroupDetail(gpoGroup , 'test detail XXt',true);
          grpDetail.Type__c = 'News';
          update grpDetail;
          
        //User portalUser = getCommunityUser('aaa@officedepot.com','227112',contact.Id);
        User portalUser = getCommunityUser('a_227196@officedepot.com','227196',contact.Id);
        test.startTest();
        System.runAs(portalUser){
          xGPOCommunityAuthLandingController authLand = new xGPOCommunityAuthLandingController();
          authLand.defaultGroup.ID = gpoGroup.id;
          authLand.selectedGroup.ID  =gpoGroup.id; 
          ApexPages.currentPage().getParameters().put('gpoLeadId',lead.Id);
          ApexPages.currentPage().getParameters().put('appType','A');
          ApexPages.currentPage().getParameters().put('id',account.Id);
          ApexPages.currentPage().getParameters().put('up',account.Id);
          authLand.defaultTemplateGroup = gpoGroup;
          authLand.newEnabledGroup = gpoGroup;
           xGPOSiteTemplate1ConExt tempCon2 = new xGPOSiteTemplate1ConExt(authLand );
           
          tempCon2.enableCommunityWithTemplateDetails();
         
          tempCon2.NewsSave();
           //GPOCommunityAuthLandingController.ChildAccountDetail c = new GPOCommunityAuthLandingController.ChildAccountDetail(account,null,true);
           test.stopTest();
        }
      }
    }
    
     static User getCommunityUser(String userName,String empId,Id conId){
      Profile profileObj = [select id from profile where name= 'Customer Community Login User - GPO Admin'];
        String profId = profileObj.id;
        
        string email = userName;
        string[] name = userName.split('@');
        user u = new user(Username=userName,FirstName =name[1], LastName=name[0], Alias=name[0], CommunityNickname=userName, LocaleSidKey='en_US', EmailEncodingKey='UTF-8', Profileid = profId, LanguageLocaleKey='en_US');
        u.email=email;
        u.MB_Expiration_Date__c = System.now().addminutes(1);
        u.OD_Employee_ID__c =empId;
        u.GT_Employee_ID__c =empId;
        u.ContactId = conId;
        u.IsActive=true;
        u.TimeZoneSidKey='America/Los_Angeles';
        u.Token_Market_Builder__c ='xyz';
       // u.IsPortalEnabled = true;
        try{ 
            Insert u;
            system.debug('@@@User@@@ : '+u);
            return u;
        }
        catch(Exception e) {
            system.debug('Exception'+e);
        }
        return u;
    }
    public static Contact CreateContact(Id accountId) {
    Contact contact = new Contact(LastName = 'TEST',AccountId = accountId);
    contact.MailingCountry = 'MEX';
    contact.Admin_Context__c =  accountId;
    contact.GPO_Community__c =accountId;
    insert contact;
    
    return contact;
  }
  public static User getTestUser(String profileName,String userName,String empId){
        Profile profileObj = [select id from profile where name=: profileName];
        String profId = profileObj.id;
        UserRole ContractDivisionRoleId = [SELECT Id from UserRole WHERE Name = 'Contract Division' limit 1];
        string email = userName;
        string[] name = userName.split('@');
        user u = new user(Username=userName,FirstName =name[1], LastName=name[0], Alias=name[0], CommunityNickname=userName, LocaleSidKey='en_US', EmailEncodingKey='UTF-8', Profileid = profId, LanguageLocaleKey='en_US');
        u.email=email;
        u.MB_Expiration_Date__c = System.now().addminutes(1);
        u.OD_Employee_ID__c =empId;
        u.GT_Employee_ID__c =empId;
        u.IsActive=true;
        u.TimeZoneSidKey='America/Los_Angeles';
        u.Token_Market_Builder__c ='xyz';
        u.UserRoleId = ContractDivisionRoleId.Id;
        try{ 
            Insert u;
            system.debug('@@@User@@@ : '+u);
            return u;
        }
        catch(Exception e) {
            system.debug('Exception'+e);
        }
        return u;
    }   
    
}