objects/Account_Final_Staging__c.object
<CustomObject>
    <description>This is used for data sync from AOPS to SFDC.</description>
    <fields>
        <fullName>AOPS_Cust_Id__c</fullName>
        <description>AOPS Customer Account Number</description>
        <externalId>true</externalId>
        <label>AOPS Id</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Community_Postscript__c</fullName>
        <label>Community Postscript</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <label>Account Final Staging</label>
    <nameField>
        <label>Account Final Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts Final Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AOPS_Account_Addendum_Community__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCU043F_AECD10__c</fullName>
        <label>CCU043F_AECD10</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCU043F_AECUST__c</fullName>
        <externalId>true</externalId>
        <label>CCU043F_AECUST</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CXTC043F_ACTION__c</fullName>
        <label>CXTC043F_ACTION</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_Record_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unique Record ID</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>AOPS Account Addendum Community</label>
    <nameField>
        <label>AOPS Account Addendum Community Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AOPS Account Addendum Community</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AOPSAccountAddendumCommFinalProcessor_TC.cls
@IsTest
public class AOPSAccountAddendumCommFinalProcessor_TC {
    @isTest
    static void makeData() {
        List<AOPS_Account_Addendum_Community__c> lst = new List<AOPS_Account_Addendum_Community__c>{
          new AOPS_Account_Addendum_Community__c  (CCU043F_AECUST__c='857958585',CXTC043F_ACTION__c='C',CCU043F_AECD10__c='P',Unique_Record_ID__c='84948594'),
          new AOPS_Account_Addendum_Community__c  (CCU043F_AECUST__c='09284848',CXTC043F_ACTION__c='U',CCU043F_AECD10__c='P',Unique_Record_ID__c='2637427')};
    insert lst;
                                                   List<Account_Final_Staging__c> fnlLSt = new List<Account_Final_Staging__c>{
                                                       new Account_Final_Staging__c(AOPS_Cust_Id__c='857958585' ,Community_Postscript__c='P',Action__c='U'),
                                                      new Account_Final_Staging__c (AOPS_Cust_Id__c='09284848' ,Community_Postscript__c='P',Action__c='U')};

                                       insert     fnlLSt;
    test.startTest();
    system.enqueueJob(new AOPSAccountAddendumCommFinalProcessor(lst));
    test.stopTest();
    }
    
}