objects/Account.object
<CustomObject>
    <fields>
        <fullName>AOPS_Seq_ID__c</fullName>
        <externalId>true</externalId>
        <label>AOPS Seq ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Related_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>(Tech-Zone)</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Admin_Config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Administrative configurations such as endpoints, privileged users, etc.</description>
    <fields>
        <fullName>BatchSize__c</fullName>
        <description>This determine the batch size for the Account Assignment</description>
        <label>BatchSize</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tech_Depot_Auto_Assign_Opp__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to auto assign the TD opportunities</description>
        <label>Tech Depot Auto Assign Opp</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tech_Depot_Title__c</fullName>
        <description>Title to look into Team Members.</description>
        <label>Tech Depot Title</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tech_Depot_User__c</fullName>
        <description>To set the default user to the TD Opportunities</description>
        <label>Tech Depot User</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Admin Config</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>All Supplies</fullName>
                </value>
                <value>
                    <fullName>Asset Management</fullName>
                </value>
                <value>
                    <fullName>CBFS</fullName>
                </value>
                <value>
                    <fullName>CBS/Facilities</fullName>
                </value>
                <value>
                    <fullName>Contract Furniture</fullName>
                </value>
                <value>
                    <fullName>Email Marketing</fullName>
                </value>
                <value>
                    <fullName>Ergonomics</fullName>
                </value>
                <value>
                    <fullName>Facilities- Coffee</fullName>
                </value>
                <value>
                    <fullName>Filing &amp; Binding</fullName>
                </value>
                <value>
                    <fullName>Furniture - Catalog</fullName>
                </value>
                <value>
                    <fullName>Furniture - Interiors</fullName>
                </value>
                <value>
                    <fullName>General Consultation</fullName>
                </value>
                <value>
                    <fullName>Ink &amp; Toner</fullName>
                </value>
                <value>
                    <fullName>Instructional Solutions</fullName>
                </value>
                <value>
                    <fullName>K-12 Growth</fullName>
                </value>
                <value>
                    <fullName>Labels &amp; Forms</fullName>
                </value>
                <value>
                    <fullName>Legal Services</fullName>
                </value>
                <value>
                    <fullName>Logo Design</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>MPS</fullName>
                </value>
                <value>
                    <fullName>Multi-Category</fullName>
                </value>
                <value>
                    <fullName>Office Essentials</fullName>
                </value>
                <value>
                    <fullName>Office Products</fullName>
                </value>
                <value>
                    <fullName>Office Supplies</fullName>
                </value>
                <value>
                    <fullName>Paper</fullName>
                </value>
                <value>
                    <fullName>Print and Promo</fullName>
                </value>
                <value>
                    <fullName>Print Services</fullName>
                </value>
                <value>
                    <fullName>School Supplies</fullName>
                </value>
                <value>
                    <fullName>Search Marketing</fullName>
                </value>
                <value>
                    <fullName>SEO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>OD_Employee_ID__c</fullName>
        <externalId>true</externalId>
        <label>OD Employee ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Short_Title__c</fullName>
        <label>Short Title</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/WRF_Task__c.object
<CustomObject>
    <label>WRF Task</label>
    <nameField>
        <displayFormat>WRFtask-{000000}</displayFormat>
        <label>WRF Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WRF Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OpportunityOwner_Insert_TC.cls
@isTest
private class OpportunityOwner_Insert_TC
{

    static testMethod void OpportunityOwner_Insert_TC()
    {

        /*Schema.DescribeSObjectResult WR = Schema.SObjectType.WRF_Task__c; 
        Map<String,Schema.RecordTypeInfo> WRFMapByName = WR.getRecordTypeInfosByName();

        Schema.DescribeSObjectResult CR = Schema.SObjectType.Case; 
        Map<String,Schema.RecordTypeInfo> CRFMapByName = CR.getRecordTypeInfosByName();*/
        Profile p4 = [SELECT Id FROM profile WHERE name='System Administrator'];   
        User u1 = new User(alias = 'test123 ', email='proxy@proxy456654.officedepot.com',OD_Employee_ID__c='125886',emailencodingkey='UTF-8', lastname='teOfficedepot',languagelocalekey='en_US',localesidkey='en_US',short_title__c = 'TSR', profileid = p4.Id,timezonesidkey='America/Los_Angeles',username='proxy@7878.com',isactive=true);
        insert u1; 
        system.runas(u1)
        {
          
        Admin_Config__c ad= new Admin_Config__c();
        ad.name ='Default';
        ad.Tech_Depot_Title__c = 'TSR';
        ad.Tech_Depot_Auto_Assign_Opp__c =true;
        ad.Tech_Depot_User__c ='salesforce';
        ad.BatchSize__c ='100';
        insert ad;
        
        Account acc = new Account();
        acc.Aops_seq_id__c='12345';
        acc.Name='Realted';
        insert acc;
        Account acc1 = new Account();
        acc1.Name='TestAcc';
        acc1.Aops_seq_id__c='12345-111';
        acc1.Related_account__c = acc.Id;
        acc1.Name='Test';
        insert acc1;
        Account acc2 = new Account();
        acc2.Name='Test';
        insert acc2;

        AccountTeamMember atm = new AccountTeamMember();
        atm.UserId = u1.Id;
        atm.AccountId = acc1.Id;
        insert atm;

        
        
 
        Test.StartTest();
        

            opportunity opp = new Opportunity();
            opp.accountid=  acc1.id;
            opp.LeadSource = 'BSD NET';
            opp.Name='Test';
            opp.product__c = 'tech';
            opp.StageName='90%-Execute';
            opp.CloseDate=System.today();
            insert opp;
            
            opportunity opp1 = new Opportunity();
            opp1.accountid=  acc1.id;
            opp1.LeadSource = 'BSD NET';
            opp1.Name='Test2';
            opp1.product__c = 'tech';
            opp1.StageName='0%-Lost';
            opp1.CloseDate=System.today();
            insert opp1;
            opp1.StageName='90%-Execute';
            update opp1;
            
            executeoncetest.oppemailsend=true;
            
            
        Test.StopTest();
       }    
    }
}