objects/Account.object
<CustomObject>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Oracle_Party_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Party ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Oracle_Party_Site_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Party Site ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Related_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>(Tech-Zone)</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Split_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Split Record</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Prospect_Message__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>Prospect Account to which this message applies.</description>
        <inlineHelpText>Prospect Account to which this message applies.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Prospect Messages</relationshipLabel>
        <relationshipName>Prospect_Messages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Prospect Message</label>
    <nameField>
        <label>Prospect Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prospect Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OMXSplitSites.cls
global class OMXSplitSites {
 
 webservice static siteResponse getSplitSites (ID sfAcctID) {
   
   siteResponse PartySiteIDs = new siteResponse ();
   list<String> psIds = new list<String>();
   system.debug('Inside SiteResponse');
   Prospect_message__c pm = [select account__c from prospect_message__c where id = :sfAcctID];
   for (Account a: [select id,related_account__r.oracle_party_id__c,oracle_party_site_id__c,omx_primary_key__c from account where related_account__c = :pm.account__c and Split_Record__c = false]) {
       
       if (a.related_account__r.oracle_party_id__c == null) {
         system.debug('Party IDs not found for SFDC ID - ' + sfAcctID);
         break;
       }
       else if (PartySiteIDs.oracle_party_id == null) {
         PartySiteIDs.oracle_party_id = a.related_account__r.oracle_party_id__c;
         system.debug('Party ID Found - ' + PartySiteIDs.oracle_party_id);
       }
       
       if (a.oracle_party_site_id__c != null && !a.omx_primary_key__c.contains('OMX'))
        psIds.add(a.oracle_party_site_id__c);

   }
   if (psIds.size() > 0) {
     PartySiteIDs.oracle_party_sites = psIds;
     system.debug('PartySites Found - Total Sites:' +  psIds.size());
  }
   
   return PartySiteIDs;
 }
 
 global class siteResponse {
    webservice String ORACLE_PARTY_ID;
    webservice List<String> ORACLE_PARTY_SITES;
  }
}