objects/Account.object
<CustomObject>
    <fields>
        <fullName>AOPS_Cust_Id__c</fullName>
        <description>AOPS Customer Account Number</description>
        <externalId>true</externalId>
        <label>AOPS Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>AOPS_Seq_ID__c</fullName>
        <externalId>true</externalId>
        <label>AOPS Seq ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>DNBI_CREDIT_OUTCOME__c</fullName>
        <description>THIS IS CREATED BY MOHAN TO TEST THE CREDIT OUTCOME</description>
        <label>DNBI Credit Outcome</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Duns_Enrichment__c</fullName>
        <description>Duns Enrichment loaded October 7th, 2014</description>
        <label>Duns Enrichment</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oracle_Party_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Party ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Account_Profile__c.object
<CustomObject>
    <fields>
        <fullName>AOPS_SEQ_ID__c</fullName>
        <formula>Account__r.AOPS_Seq_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AOPS SEQ ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Profile</relationshipLabel>
        <relationshipName>Account_Profile1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Address_State__c</fullName>
        <label>Address State</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Tax_Status__c</fullName>
        <label>Tax Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Account Profile</label>
    <nameField>
        <label>Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Profile</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Account_Profile_Staging__c.object
<CustomObject>
    <description>This is a staging object only and used to process data uploaded from other systems into the Account Profile object.  Currently, it process Tax Certificate records only.</description>
    <fields>
        <fullName>Address_State__c</fullName>
        <label>Address State</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_ID__c</fullName>
        <label>Customer ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Tax_Status__c</fullName>
        <label>Tax Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Account Profile Staging</label>
    <nameField>
        <displayFormat>APS{000000000}</displayFormat>
        <label>Account Profile Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Profile Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/accountProfileStagingEventHandlerTest.cls
/** 
    (c) Appirio
    Created:        6/8/2015  Ben Lorenz
    Purpose:        Apex unit tests for class accountProfileStagingEventHandler
**/

@isTest
private class accountProfileStagingEventHandlerTest {
  static testMethod void testaccountprofileupsert() {
    Account_Profile__c [] apLst;
    //create account
    Account a = new Account ();
    a.name = 'TAX CERT TST ACCT';
    a.AOPS_Seq_ID__c = '123666';
    a.AOPS_Cust_Id__c = '123666';
    a.Oracle_Party_Id__c = '123666';
    a.Billingcountry = 'USA';
    a.BillingState = 'UT';
    a.Duns_Enrichment__c = '12345';
    a.DNBI_CREDIT_OUTCOME__c = 'Approved';
    a.BillingStreet = '1040 N 326 W';
    a.billingcity = 'Orem';
    insert a;
    test.startTest();
    apLst = [SELECT Id FROM Account_Profile__c WHERE Account__c = :a.Id];
    system.assert(apLst.isEmpty()==true);
    //insert account profile staging for insert to account profile
    Account_Profile_Staging__c aps = new Account_Profile_Staging__c();
    aps.Expiration_Date__c= date.newinstance(2039, 12, 31);
    aps.Address_State__c='UT';
    aps.Country_Code__c='USA';
    aps.Tax_Status__c='A';
    aps.Customer_ID__c='123666';
    insert aps;
    //validate new Account Profile recored was inserted to Account
    apLst = [SELECT Id, LastModifiedDate,CreatedDate FROM Account_Profile__c WHERE Account__c = :a.Id];
    system.assert(apLst.size()==1);
    system.assert(apLst[0].LastModifiedDate==apLst[0].CreatedDate);
    //insert second account profile staging for upsert to account profile
    Account_Profile_Staging__c aps2 = new Account_Profile_Staging__c();
    aps2.Expiration_Date__c= date.newinstance(2039, 12, 31);
    aps2.Address_State__c='UT';
    aps2.Country_Code__c='USA';
    aps2.Tax_Status__c='B';
    aps2.Customer_ID__c='123666';
    insert aps2;
    //validate
    apLst = [SELECT Id,LastModifiedDate,CreatedDate,Tax_Status__c FROM Account_Profile__c WHERE Account__c = :a.Id];
    system.assert(apLst.size()==1);
    system.assert(apLst[0].Tax_Status__c=='B');
  }
}