objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Account_Extension_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Extension Name</label>
        <referenceTo>Account_Extension__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Org__c</fullName>
        <formula>Account.Org__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Org</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Most_Favored_Contract_Language__c</fullName>
        <label>&quot;Most Favored&quot; Contract Language</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>X3rd_party_required_to_provide_a_securit__c</fullName>
        <inlineHelpText>3rd party required to provide a security assessment</inlineHelpText>
        <label>3rd party required to provide a security</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Needs validation</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ContractHistory__c.object
<CustomObject>
    <fields>
        <fullName>Account_Extension_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Extension Name</label>
        <referenceTo>Account_Extension__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts1554724632</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Org__c</fullName>
        <formula>Account__r.Org__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Org</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract History</relationshipLabel>
        <relationshipName>Contract_History1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Most_Favored_Contract_Language__c</fullName>
        <label>&quot;Most Favored&quot; Contract Language</label>
        <length>15000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>X3rd_party_required_to_provide_a_securit__c</fullName>
        <inlineHelpText>3rd party required to provide a security assessment</inlineHelpText>
        <label>3rd party required to provide a security</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Needs validation</fullName>
                    <color>#FFFFFF</color>
                    <label>Needs validation</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                    <color>#FFFFFF</color>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>No</fullName>
                    <color>#FFFFFF</color>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                    <color>#FFFFFF</color>
                    <label>Unknown</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract History</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ContractHistoryCompareControllerTest.cls
/*************************************************************
*Name : ContractHistoryCompareControllerTest
*Created By : Sandesh Ganjare
*Created Date :
*Purpose : Test class for ContractHistoryCompareController class
*JIRA: NAIT-124929
****************************************************************/
@isTest
public with sharing class ContractHistoryCompareControllerTest {
    @TestSetup public static void setup()
    {
        Account a = new Account();
        a.Name='Test Account';
        INSERT a;
        
        Contract c = new Contract();
        c.Name='Test COntract';
        c.AccountId = a.id;
        INSERT c;
        
        List<ContractHistory__c> lstch = new List<ContractHistory__c>();
        ContractHistory__c ch = new ContractHistory__c(); 
        ch.most_favored_contract_language__c = 'Test';
        ch.Contract__c = c.id;
        lstch.add(ch);

        ContractHistory__c ch1 = new ContractHistory__c(); 
        ch1.most_favored_contract_language__c = 'Test1';
        ch1.Contract__c = c.id;
        lstch.add(ch1);

        ContractHistory__c ch2 = new ContractHistory__c(); 
        ch2.most_favored_contract_language__c = 'Test1';
        ch2.Contract__c = c.id;
        lstch.add(ch2);

        INSERT lstch;
    
    }

    static testMethod  void getContractHistoryList_Test (){       
        List<Contract> contractList = [Select id From Contract ORDER BY id Limit 1];
        Test.StartTest();
        List<ContractHistory__c> chlst = ContractHistoryCompareController.getContractHistoryList(String.valueOf(contractList[0].Id));
        Test.StopTest();

        System.assertEquals(true, chlst != null);  
    }

    static testMethod  void getContractFieldsData_Test (){       
        List<Contract> contractList = [Select id From Contract ORDER BY id Limit 1];
        Test.StartTest();
        Map<string, string> fieldmap = ContractHistoryCompareController.getContractFieldsData();
        Test.StopTest();

        System.assertEquals(true, fieldmap != null);  
    }

    static testMethod  void getContractHistoryCompareData_Test (){    
           
        List<String> str = new List<String>();
            str.add('most_favored_contract_language__c');
            str.add('x3rd_party_required_to_provide_a_securit__c');
            str.add('account_extension_name__c');
            str.add('account_name__c');
            str.add('account_org__c');
            String fields = JSON.serialize(str);
            system.debug('=>'+fields);
        List<Contract> contractList = [Select id From Contract ORDER BY id Limit 1];
        List<ContractHistory__c> ContractHistoryList = [SELECT Id, Name, LastModifiedDate, LastModifiedBy.Name FROM ContractHistory__c];
        Test.StartTest();
        List<ContractHistoryCompareController.ContractHistoryWrapper> chwlst = ContractHistoryCompareController.getContractHistoryCompareData(ContractHistoryList[0].Name,'current',String.valueOf(contractList[0].Id),true,fields);
        Test.StopTest();

        System.assertEquals(true, chwlst != null);  
    }
    static testMethod  void getContractHistoryCompareData_Test1 (){    
           
        List<String> str = new List<String>();
            str.add('most_favored_contract_language__c');
            str.add('x3rd_party_required_to_provide_a_securit__c');
            str.add('account_extension_name__c');
            str.add('account_name__c');
            str.add('account_org__c');
            String fields = JSON.serialize(str);
            //system.debug('=>'+fields);
        List<Contract> contractList = [Select id From Contract ORDER BY id Limit 1];
        List<ContractHistory__c> ContractHistoryList = [SELECT Id, Name, LastModifiedDate, LastModifiedBy.Name FROM ContractHistory__c WHERE Contract__c =: contractList[0].Id];
        system.debug('ContractHistoryList=>'+ContractHistoryList.size());
        Test.StartTest();
        List<ContractHistoryCompareController.ContractHistoryWrapper> chwlst = ContractHistoryCompareController.getContractHistoryCompareData(ContractHistoryList[0].Name,ContractHistoryList[1].Name,String.valueOf(contractList[0].Id),true,fields);
        Test.StopTest();

        System.assertEquals(true, chwlst != null);  
    }
}