objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Single User</fullName>
                </value>
                <value>
                    <fullName>Multi-User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Org/Company</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Accounts/Sites</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer Accounts</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <description>Prospect Accounts</description>
        <label>Prospect</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Decision_Maker__c</fullName>
        <label>Decision Maker</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Org</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <inlineHelpText>This field is required in order to convert  (Unless lead is directly linked to an account)</inlineHelpText>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Decision_Maker__c</fullName>
        <label>Decision Maker</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <formula>TEXT(Account.Type)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Org</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PLOC_Opportunity_Stage__c</fullName>
        <description>PLOC Opportunity</description>
        <label>PLOC Opportunity Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Identify Prospect (1.0)</fullName>
                </value>
                <value>
                    <fullName>Qualify Appointment Set (1.5)</fullName>
                </value>
                <value>
                    <fullName>Qualify Prospect (2.0)</fullName>
                </value>
                <value>
                    <fullName>Solution Appointment Set (3.0)</fullName>
                </value>
                <value>
                    <fullName>Introduce Solution (4.0)</fullName>
                </value>
                <value>
                    <fullName>Solution Introduction Complete (5.0)</fullName>
                </value>
                <value>
                    <fullName>Discovery Workshop (Verbal Commitment) (6.0)</fullName>
                </value>
                <value>
                    <fullName>Virtual Workshop (6.2)</fullName>
                </value>
                <value>
                    <fullName>Onsite Discovery Roundtable (6.3)</fullName>
                </value>
                <value>
                    <fullName>Onsite Discovery Workshop (6.5)</fullName>
                </value>
                <value>
                    <fullName>Present Solution (7.0)</fullName>
                </value>
                <value>
                    <fullName>Due Dilligence &amp; Planning (8.0)</fullName>
                </value>
                <value>
                    <fullName>Negotiate SOW (9.0)</fullName>
                </value>
                <value>
                    <fullName>Finalize SOW (10.0)</fullName>
                </value>
                <value>
                    <fullName>Integration and Implementation (11.0)</fullName>
                </value>
                <value>
                    <fullName>Manage Account (12.0)</fullName>
                </value>
                <value>
                    <fullName>District not ready - Leadership changes (200.1)</fullName>
                </value>
                <value>
                    <fullName>District not ready - Data Issues (200.2)</fullName>
                </value>
                <value>
                    <fullName>District not ready - Technology Issue (200.3)</fullName>
                </value>
                <value>
                    <fullName>District not ready - Funding Issue (200.4)</fullName>
                </value>
                <value>
                    <fullName>District not interested (200.5)</fullName>
                </value>
                <value>
                    <fullName>IBM Target (200.6)</fullName>
                </value>
                <value>
                    <fullName>District Not Ready - Resources (200.7)</fullName>
                </value>
                <value>
                    <fullName>District Not Ready - Standards (200.8)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Subtype__c</fullName>
        <label>Product Subtype</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>3 Ply Masks</fullName>
                </value>
                <value>
                    <fullName>Accessories</fullName>
                </value>
                <value>
                    <fullName>Accessories – Cabling</fullName>
                </value>
                <value>
                    <fullName>Accessories - I/O</fullName>
                </value>
                <value>
                    <fullName>Accessories - PC &amp; Server Upgrades</fullName>
                </value>
                <value>
                    <fullName>Antibacterial Soap</fullName>
                </value>
                <value>
                    <fullName>Audio</fullName>
                </value>
                <value>
                    <fullName>Automatic Toner Replenishment (ATR)</fullName>
                </value>
                <value>
                    <fullName>Batteries</fullName>
                </value>
                <value>
                    <fullName>Blue Ribbon</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
                <value>
                    <fullName>Brand Identity </fullName>
                </value>
                <value>
                    <fullName>Branding/Fundraising</fullName>
                </value>
                <value>
                    <fullName>Break room</fullName>
                    <label>Break Room</label>
                </value>
                <value>
                    <fullName>Business Essentials</fullName>
                </value>
                <value>
                    <fullName>Business Services</fullName>
                </value>
                <value>
                    <fullName>C2 Collaborative</fullName>
                </value>
                <value>
                    <fullName>Cameras</fullName>
                </value>
                <value>
                    <fullName>Charging Carts</fullName>
                </value>
                <value>
                    <fullName>Checks and Forms </fullName>
                </value>
                <value>
                    <fullName>Classroom Technology</fullName>
                </value>
                <value>
                    <fullName>Cleaning</fullName>
                </value>
                <value>
                    <fullName>Cleaning &amp; Maintenance</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Pilot Programs-Collaborative Classroom</fullName>
                    <label>Collaborative Classroom</label>
                </value>
                <value>
                    <fullName>Computing - Chromebooks</fullName>
                </value>
                <value>
                    <fullName>Computing - Desktops</fullName>
                </value>
                <value>
                    <fullName>Computing - Laptops</fullName>
                </value>
                <value>
                    <fullName>Computing - Tablets</fullName>
                </value>
                <value>
                    <fullName>Computing - Workstations</fullName>
                </value>
                <value>
                    <fullName>Other Equipment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Watson_Door_Opener__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Need a new Opportunity Field specific to Education</description>
        <label>Watson Door Opener</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Watson_Notes__c</fullName>
        <label>Opportunity Status Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <description>Representation of Customer Relationship Hierarchy Node</description>
    <fields>
        <fullName>Business_Name__c</fullName>
        <label>Business Name</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <externalId>true</externalId>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesDataBatch__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SalesDataBatch</label>
        <type>Checkbox</type>
    </fields>
    <label>Org</label>
    <nameField>
        <displayFormat>Org-{0000}</displayFormat>
        <label>Org Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CreateProspectCmpController_TC.cls
@isTest
public class CreateProspectCmpController_TC {
    private static testMethod void MyunitTest() {
        User oUser = [select id,Name,TimeZoneSidKey,Username,Alias,Country,Email,FirstName,LastName,IsActive,IsPortalEnabled 
                      FROM User Where id =: userInfo.getUserId()];
        String recid =  [select id from recordtype where name = 'Prospect (BizBox)' Limit 1].Id;
        CreateProspectCmpController.getRecordTypeNamesAndIds(recid);
        //  String acctype = 'select id from recordtype where name ='Prospect (BizBox)' Limit 1';
        
        system.runAs(oUser)
        {
            recordtype rc1 = [SELECT Id FROM RecordType WHERE SObjectType = 'Opportunity' and name='Field Sales (US)' limit 1];
            //Creating org record
            Org__c Org = new Org__c();
            Org.Business_Name__c = 'NewOrg';
            Org.SalesDataBatch__c = true;
            insert Org;
            
            // Create a test account
            Account testAcct = new Account(Name = 'My Test Account');
            testAcct.Account_Type__c= 'Prospect';
            insert testAcct;
            
            // Create opportunity
            Opportunity oppt = new Opportunity(Name = 'New mAWS Deal',
                                               AccountID = testAcct.ID,
                                               StageName = 'Qualify',                           
                                               ownerId=oUser.id,  
                                               RecordTypeId = rc1.id,
                                               Amount = 3000,
                                               CloseDate = System.today(),
                                               Watson_Door_Opener__c=true,
                                               PLOC_Opportunity_Stage__c='Identify Prospect (1.0)',
                                               Product_Subtype__c='Other Equipment',      
                                               Watson_Notes__C='My text');
            insert oppt;
            
            //Creating contact  
            Contact con1 = new Contact();
            con1.LastName = 'Test1';
            con1.Decision_Maker__c = 'No';
            con1.AccountId = testAcct.id;
            insert con1;
            CreateProspectCmpController.getProspectAndOpp();  
        }
    }
    
    private static testMethod void MyunitTest1() {
        String recid =  [select id from recordtype where name = 'Prospect (Tech-Zone)' Limit 1].Id;
        CreateProspectCmpController.getRecordTypeNamesAndIds(recid);
        User oUser = [select id,Name,TimeZoneSidKey,Username,Alias,Country,Email,FirstName,LastName,IsActive,IsPortalEnabled 
                      FROM User Where id =: userInfo.getUserId()];
        system.runAs(oUser){ 
            //creating lead
            Lead leads=new Lead();
            leads.LastName='Test name';
            leads.FirstName='Test name2';
            leads.Status='Open';
            leads.Company='Test Company';
            insert leads;
            CreateProspectCmpController.onloadAccPicklistVaues(leads.id);
            CreateProspectCmpController.onLoadData(leads.Id);
            CreateProspectCmpController.getAssignSpecificOwnerName(userInfo.getUserId());
            
        }
        
    }
    private static testMethod void MyunitTest2() {
        String pObjName='test';
        String pControllingFieldName='Test 2';
        String pDependentFieldName='Test 3';
        String ctrlPicklistVal='Test 4';
        CreateProspectCmpController.getAccVericalPickValues(pObjName, pControllingFieldName, pDependentFieldName, ctrlPicklistVal);
    }
    
    private static testMethod void MyunitTest3() {
    Test.startTest();
         String recid1 =  [select id from recordtype where name = 'Customer (Business Pro)' Limit 1].Id;
        CreateProspectCmpController.getRecordTypeNamesAndIds(recid1);
        
            String recid =  [select id from recordtype where name = 'Prospect (GT)' Limit 1].Id;
        CreateProspectCmpController.getRecordTypeNamesAndIds(recid);
        CreateProspectCmpController.setCtAndOppRT(recid);
        User oUser = [select id,Name,Username,Alias,Country,Email,FirstName,LastName,IsActive,IsPortalEnabled 
                      FROM User Where id =: userInfo.getUserId()];
        recordtype ld= [SELECT id FROM RecordType where name='Lead (US)' limit 1];
        recordtype accre= [SELECT id FROM RecordType where name='Prospect' limit 1];
        system.runAs(oUser){
            
            Lead leads = new Lead();
            leads.LastName='Test name';
            leads.FirstName='Test name2';
            leads.Status='Open';
            leads.Company='Test Company';
            leads.city__c='Bangalore';
            leads.state__c='LA';
            leads.zip__c='123123';
            leads.RecordTypeId=ld.id;
            leads.Decision_Maker__c='No';
            insert leads;
            String leadId=''+leads.Id;
            system.debug('leadId'+leadId);
            String leadData='{"LastName":"Test name","FirstName":"Test name2","Status":"Open","Company":"Test Company","city__c":"Bangalore","State__c":"LA","zip__c":"123123","RecordTypeId":"'+ld.id+'","Decision_Maker__c":"No"}';
            system.debug('leadata'+leadData);
            
            String newOrFamiliyOrgRecData='[{"Business_Name__c":"Test Org ","SalesDataBatch__c":true}]';
            system.debug('newOrFamiliyOrgRecData'+newOrFamiliyOrgRecData);
            
            String decisionMaking='No';
            
            String parentOrgData='[{"Business_Name__c":"Test Org1","SalesDataBatch__c":true,"DUNS_Number__c":"1234567","D_B_ID__c":"1234567"}]';
            System.debug('parentOrgData'+parentOrgData);
            Org__c org1 =new Org__c();
            org1.Business_Name__c = 'Test Org1';
            org1.SalesDataBatch__c = true;
            insert org1;
            String parentOrgSFId='' + org1.Id;
            
            String contactData1='{"LastName":"Test1","Decision_Maker__c":"No"}';
            //String contactData1= ''+[select id,LastName,Decision_Maker__c from contact where id=:contactData.Id];
            System.debug('contactData1'+contactData1);
            
            String prospectData='{"name":"Test acc","Phone":"1231231234","RecordTypeId":"'+accre.Id+'","address1__c":"Address1","city__c":"Hyderabad","state__c":"LA","Country__c":"USA","zip__c":"123123"}';
            system.debug('prospectData'+prospectData);
            
            
            CreateProspectCmpController.populateparentaccount('Test',prospectData);

            Pricing_Template__c  PT = New Pricing_Template__c(Name='Test Template',Parent_Id__c='22089559');
            Insert PT;
            
            Test.stopTest();
            Account testAcct = new Account(Name = 'My Test Account');
            testAcct.Account_Type__c= 'Prospect';
            insert testAcct;
            // Parent_Id__c is null 
             CreateProspectCmpController.populateparentaccount(PT.Name,prospectData);
             
              testAcct.AOPS_Cust_Id__c=PT.Parent_Id__c;
              Update testAcct;
            // Parent_Id__c not null
             CreateProspectCmpController.populateparentaccount(PT.Name,prospectData);
             // PricingTemplate is null
             CreateProspectCmpController.populateparentaccount(null,prospectData);
             
             
            /*Opportunity opp=new Opportunity();
Opportunity oppt = new Opportunity(Name = 'New mAWS Deal',
AccountID = prospectrec.ID,
StageName = 'Qualify',                           
ownerId=oUser.id,  
RecordTypeId = '012E000000093HNIAY',
Amount = 3000,
CloseDate = System.today(),
Watson_Door_Opener__c=true,
PLOC_Opportunity_Stage__c='Identify Prospect (1.0)',
Product_Subtype__c='Other Equipment',      
Watson_Notes__C='My text'); */
            // String oppRec='{"AccountID":"0011k00000D74m6AAB","StageName":"Qualify","ownerId":"0051k000000eWdk","RecordTypeId":"012E000000093HNIAY","Amount":"3000","CloseDate":"'+system.today()+'","Watson_Door_Opener__c":true,"PLOC_Opportunity_Stage__c":"Identify Prospect (1.0)","Product_Subtype__c":"Other Equipment","Watson_Notes__C":"My text"}';
            String oppRec='';
            Boolean isCreateOppRec=false;
            CreateProspectCmpController.onloadAccPicklistVaues(leads.id);
            CreateProspectCmpController.saveProspect(prospectData, contactData1, parentOrgData,
                                                     newOrFamiliyOrgRecData, decisionMaking, parentOrgSFId
                                                     , leadId,  leadData);
            leadId='';
            decisionMaking='Yes';
            newOrFamiliyOrgRecData='{"Business_Name__c":"Test Org ","SalesDataBatch__c":true}';
            CreateProspectCmpController.saveProspect(prospectData, contactData1, parentOrgData,
                                                     newOrFamiliyOrgRecData, decisionMaking, parentOrgSFId, 
                                                     leadId,  leadData);
                                                     
            
        } 
        
    }
    
    private static testMethod void MyunitTest4() {
        Lead ld=new Lead();
        ld.LastName='Test name';
        ld.FirstName='Test name2';
        ld.Status='Open';
        ld.Company='Test Company';
        ld.city__c='Bangalore';
        ld.state__c='LA';
        ld.zip__c='123123';
        ld.Decision_Maker__c='No';
        insert ld;
        CreateProspectCmpController.getLeadConvert(ld);
    }  
    
}