objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Owner_Manager_Name__c</fullName>
        <formula>Sales_PersonID__r.User__r.Manager__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Owner Manager Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordType_Name__c</fullName>
        <description>RecordType Name as Text</description>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RecordType Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is used for Primary Owner Sales ID.</description>
        <label>Sales Person ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sales_Person__c.Primary__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Person__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site</fullName>
    </fields>
    <fields>
        <fullName>YTD_Sales_LY_IMU2__c</fullName>
        <formula>If((YTD_Sales_LY__c = 0 || YTD_Sales_LY__c = null), 0, (YTD_Sales_LY_IMU__c /  YTD_Sales_LY__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>YTD Sales LY IMU %</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>YTD_Sales_LY__c</fullName>
        <description>Last Year Sales</description>
        <inlineHelpText>Last Year Sales</inlineHelpText>
        <label>YTD Sales LY</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>YTD_Sales_TY_IMU2__c</fullName>
        <formula>If((YTD_Sales_TY__c = 0 || YTD_Sales_TY__c = null), 0, (YTD_Sales_TY_IMU__c /  YTD_Sales_TY__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>YTD Sales TY IMU %</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer Accounts</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>GrandParent</fullName>
        <active>true</active>
        <description>Used for GP Maintenance</description>
        <label>GrandParent</label>
    </recordTypes>
    <recordTypes>
        <fullName>Parent</fullName>
        <active>true</active>
        <label>Parent</label>
    </recordTypes>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <description>Prospect Accounts</description>
        <label>Prospect</label>
    </recordTypes>
    <recordTypes>
        <fullName>Site</fullName>
        <active>true</active>
        <label>Site</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>RecordType_Name__c</fullName>
        <description>RecordType as Text</description>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RecordType Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Person__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Person_IDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Person ID</label>
    <nameField>
        <label>Sales Person ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Person IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WorkRequestController.cls
public class WorkRequestController {
    public class FlowData{
        @AuraEnabled  
        public Account accRec { get; set; }
        @AuraEnabled  
        public Opportunity oppRec { get; set; }
        @AuraEnabled  
        public String type { get; set; }
        @AuraEnabled  
        public String casetypevar { get; set; }
        @AuraEnabled  
        public String message { get; set; }
        
        public FlowData(Account accRec,Opportunity oppRec,String type,String casetypevar,String message){
            this.accRec =  accRec;
            this.oppRec =  oppRec;
            this.type =  type;
            this.casetypevar = casetypevar;
            this.message = message;
            
        }
    }
    
    @AuraEnabled
    public static FlowData getData(Id recId) {
        Account acc = new Account();
        Opportunity opp = new Opportunity();
        String type ='';
        String casetypevar ='';
        String errormessage ='';
        String OId=recId;
        String prefix_Acc = '001';
        String prefix_Opp = '006';
        Boolean result = OId.startsWith(prefix_Acc);
        Boolean result1 = OId.startsWith(prefix_Opp);
        if(OId.startsWith(prefix_Acc)){
            acc=[select id,RecordType_Name__c,YTD_Sales_LY__c,YTD_Sales_TY_IMU2__c,YTD_Sales_LY_IMU2__c,Account_Owner_Manager_Name__c,Sales_PersonID__r.User__r.Name,
                 Name,Owner.Name from Account where id=:recId];
           /* if(acc.Owner.Name=='Dataloader' && acc.Sales_PersonID__r.User__r.Name=='Dataloader'){
                errormessage = 'This account has an invalid Sales ID. Please ask your Manager to assign the account to a valid Sales Rep ID through Optymyze and then process your pricing request. Thank you.'; 
                
            }
            if(errormessage != null || errormessage !='')*/
                if(acc.RecordType_Name__c=='Customer'||acc.RecordType_Name__c=='GrandParent'||acc.RecordType_Name__c=='Great Grandparent'||acc.RecordType_Name__c=='Parent') 
            { 
                type = 'Customer'; 
                casetypevar = 'Renewal'; 
                system.debug('====type==='+type);
                system.debug('====casetypevar==='+casetypevar);
            } 
        }
        if(OId.startsWith(prefix_Opp)){
            List<case> case1 = new List<case>();
            case1 = [select id from case where WRF_Opportunity__c=:recId and recordtype.name ='Work Request'];
            system.debug('====Case1===='+case1);
            if(case1.Size() > 0){
                system.debug('---Hi---');
                errormessage = 'This opportunity is already tied to a Work Request case!';
            }
            opp = [select id,AccountId,Account.name,Account.Owner.Name,Account.Sales_PersonID__r.User__r.Name,Account.RecordType_Name__c from Opportunity where id=:recId];
            system.debug('=====opp.Account.Owner.Name======'+opp.Account.Owner.Name);
            system.debug('=====opp.Account.Sales_PersonID__r.User__r.Name======'+opp.Account.Sales_PersonID__r.User__r.Name);
           /* if(opp.Account.Owner.Name=='Dataloader' && opp.Account.Sales_PersonID__r.User__r.Name=='Dataloader'){
                errormessage = 'This account has an invalid Sales ID. Please ask your Manager to assign the account to a valid Sales Rep ID through Optymyze and then process your pricing request. Thank you.';
            }*/
            
            if(errormessage == null || errormessage ==''){
            
            if(opp.Account.RecordType_Name__c=='Prospect') 
            { 
                type = 'opp only'; 
                casetypevar = 'New Contract'; 
            } 
            
            
            if(opp.Account.RecordType_Name__c=='Customer'||opp.Account.RecordType_Name__c=='GrandParent'||opp.Account.RecordType_Name__c=='Great Grandparent'||opp.Account.RecordType_Name__c=='Parent' ||opp.Account.RecordType_Name__c=='Customer (OfficeMax)' 
               ||opp.Account.RecordType_Name__c=='Site (OfficeMax)') 
            { 
                type = 'opp only'; 
                casetypevar = 'Renewal'; 
            } 
            }
        }
        
        FlowData Data= new FlowData(acc,opp,type,casetypevar,errormessage);
        system.debug('====Data===='+Data);
        return Data;
    }
    
}