objects/Account.object
<CustomObject>
    <fields>
        <fullName>Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Org/Company</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Accounts/Sites</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <description>Representation of Customer Relationship Hierarchy Node</description>
    <fields>
        <fullName>Business_Name__c</fullName>
        <label>Business Name</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Org</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipName>Orgs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Org</label>
    <nameField>
        <displayFormat>Org-{0000}</displayFormat>
        <label>Org Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountController_TC.cls
@isTest()
public class AccountController_TC {
      @IsTest
    Static void AccountControllertest(){
        
        Org__c OrN = new Org__c();
        OrN.Business_name__C = 'Test';
        insert OrN;
        
        Org__c OrN1 = new Org__c();
        OrN1.Business_name__C = 'Test1';
        OrN1.Parent_Org__C=OrN.Id;
        insert OrN1;
        
        Account Acc = new Account();
        Acc.Name='Test';
        Acc.Org__c = OrN.id;
        insert Acc;
        
        AccountController.findAll(Acc.id);
        AccountController.findAll(OrN.id);
        
    } 
}