objects/Account.object
<CustomObject>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Related_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>(Tech-Zone)</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site</fullName>
    </fields>
    <fields>
        <fullName>Split_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Split Record</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer Accounts</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Parent</fullName>
        <active>true</active>
        <label>Parent</label>
    </recordTypes>
    <recordTypes>
        <fullName>Site</fullName>
        <active>true</active>
        <label>Site</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Customer_Transition__c.object
<CustomObject>
    <description>Object to Track Customer Conversion and Review Project</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Transition Relationship</relationshipLabel>
        <relationshipName>Customer_Transition_Relationship</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mod4FlowStatus__c</fullName>
        <description>Drives the split Bulk process Batch classes. Used in 
&quot;Mod5BulkSplitCreateBatch
&quot;
 Mod5BulkSplitDeleteBatch
Mod5LaunchBatchClassBulk
Mod5BulkBatch
&quot; Mod5InsertCntcBatchV3
&quot;</description>
        <label>Mod5FlowStatus</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Splitted</fullName>
                </value>
                <value>
                    <fullName>SplitUpdated</fullName>
                </value>
                <value>
                    <fullName>Contact Processed</fullName>
                </value>
                <value>
                    <fullName>SplitSubmitted</fullName>
                </value>
                <value>
                    <fullName>SplitCont</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Bulk Split Create</fullName>
                </value>
                <value>
                    <fullName>Bulk Split Created</fullName>
                </value>
                <value>
                    <fullName>Bulk Split Delete</fullName>
                </value>
                <value>
                    <fullName>Bulk Split Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Parent_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Parent Name on the Account object</description>
        <label>Parent Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Transition (Account)</relationshipLabel>
        <relationshipName>Customer_Transition</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Written_Agreement_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Written Agreement Customer Level ID</label>
        <referenceTo>Customer_Transition__c</referenceTo>
        <relationshipLabel>Customer Transition (Written Agreement Customer Level)</relationshipLabel>
        <relationshipName>Customer_Transition</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Transition</label>
    <nameField>
        <label>Customer Transition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Transition</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Customer_Transition_Dtls__c.object
<CustomObject>
    <fields>
        <fullName>Account_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer_Transition_Dtls</relationshipLabel>
        <relationshipName>Customer_Transition_Dtls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bill_To_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Transition Details (Bill To Account)</relationshipLabel>
        <relationshipName>Customer_Transition_Details1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Transition_ID__c</fullName>
        <label>Customer Transition ID</label>
        <referenceTo>Customer_Transition__c</referenceTo>
        <relationshipLabel>Customer Transition Details</relationshipLabel>
        <relationshipName>Customer_Transition_Dtls</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <description>OMX Primary Key for Consignee, Cost Center and PO</description>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Split_Record__c</fullName>
        <formula>if( Account_ID__r.Split_Record__c==true,&quot;Y&quot;,&quot;N&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Split Record</label>
        <type>Text</type>
    </fields>
    <label>Customer Transition Details</label>
    <nameField>
        <displayFormat>CTD-{000000000}</displayFormat>
        <label>CTD Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Transition Details</pluralLabel>
    <recordTypes>
        <fullName>Sites</fullName>
        <active>true</active>
        <label>Sites</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CustTransParentChildLevel__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Mod5BulkLaunchBatchInterval__c</fullName>
        <description>This is for scheduler of batch class  Mod5LaunchBatchClassBulk</description>
        <label>Mod5BulkLaunchBatchInterval</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mod5LaunchBulkBatchID__c</fullName>
        <label>Mod5LaunchBulkBatchID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Cust Trans Parent Child Level</label>
</CustomObject>

objects/Split_Account_Detail__c.object
<CustomObject>
    <fields>
        <fullName>BatchProcessed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used in  Mod5 Helper Class. Used to update the processing in batches for Split accounts</description>
        <label>BatchProcessed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Split Account Details (Billing Account)</relationshipLabel>
        <relationshipName>Split_Account_Details2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Transition_Detail_Id__c</fullName>
        <label>Customer Transition Detail Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Transition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Customer Transition</label>
        <referenceTo>Customer_Transition__c</referenceTo>
        <relationshipLabel>Split Account Details</relationshipLabel>
        <relationshipName>Split_Account_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Main_Account_Name__c</fullName>
        <label>NEW ACCOUNT NAME</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_Account__c</fullName>
        <label>NEW OMX ACCOUNT #</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NEW_BILL_TO_OMX_CONSIGNEE__c</fullName>
        <label>NEW BILL TO OMX CONSIGNEE #</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NEW_MAIN_ACCT_ADDRESS__c</fullName>
        <label>NEW MAIN ACCT ADDRESS</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Header_Billing_Account_Code__c</fullName>
        <label>New Header Billing Account Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Header_Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>New Header Billing Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Split Account Details (New Header Billing Account)</relationshipLabel>
        <relationshipName>Split_Account_Details3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Split Account Details</relationshipLabel>
        <relationshipName>Split_Account_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SHIP_TO_CONSIGNEE__c</fullName>
        <formula>Ship_To_Account__r.OMX_Primary_Key__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SHIP TO CONSIGNEE #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Split Account Details (Ship To Account)</relationshipLabel>
        <relationshipName>Split_Account_Details1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Split Account Detail</label>
    <nameField>
        <label>Split Account Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Split Account Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Mod5BulkBatchTest.cls
// Appirio 2015
//
// Test class for Mod5BulkBatch 
// NBOCK - Original - 11.25.2015 - S-366874
@isTest
private class Mod5BulkBatchTest {
  static testmethod void testMod51(){
    //create test data
    Account acc = Test_Utils.createAccount('Customer (OfficeMax)');
        acc.Name = 'TestOriginalAccount';
        acc.Split_Record__c = false;
        acc.OMX_Primary_Key__c = '123456';
        insert acc; 
        
        Test.startTest();
               
    Account acc3 = Test_Utils.createAccount('Site (OfficeMax)');
        acc3.Name = 'TestMasterAccount2';
        acc3.Split_Record__c = false;
        acc3.OMX_Primary_Key__c = '123458';
        acc3.Related_Account__c = acc.Id;
        insert acc3;
    Account acc2 = Test_Utils.createAccount('Site (OfficeMax)');
        acc2.Name = 'TestMasterAccount';
        acc2.Split_Record__c = false;
        acc2.OMX_Primary_Key__c = '123457';
        acc2.Related_Account__c = acc3.Id;
        insert acc2;                        
    Customer_Transition__c ct = Test_Utils.createCustomerTransaction(false, acc);
        ct.OMX_Primary_Key__c = '1234567';
        ct.Mod4FlowStatus__c = 'SplitSubmitted';
        ct.Account__c = acc.Id;
        insert ct;
    Customer_Transition_Dtls__c details = Test_Utils.createCustomerTransDetails('Sites');
        details.Account_ID__c = acc2.Id;
        details.Bill_To_Account__c = acc2.Id;
        details.OMX_Primary_Key__c = '123456789';
        details.Customer_Transition_ID__c = ct.Id;
        insert details;
    Split_Account_Detail__c sad = Test_Utils.createSplitAccount(false, ct, acc);
        sad.Master_Account__c = acc2.Id;
        sad.NEW_MAIN_ACCT_ADDRESS__c = '123457';
        sad.BatchProcessed__c = false;
        sad.NEW_BILL_TO_OMX_CONSIGNEE__c = '123457';
        sad.Ship_To_Account__c = acc2.Id;
        sad.Billing_Account__c = acc2.Id;
        sad.Main_Account_Name__c = 'TestMasterAccount';
        sad.Customer_Transition_Detail_Id__c = details.Id;
        sad.New_Header_Billing_Account__c = acc2.Id;
        insert sad;
    CustTransParentChildLevel__c customSetting = new CustTransParentChildLevel__c();
      customSetting.Name = 'Parent';
      insert customSetting;
    List<Split_Account_Detail__c> splitAccountList = [SELECT Id, Customer_Transition__r.OMX_Primary_Key__c, SHIP_TO_CONSIGNEE__c, 
                                                        Billing_Account__c, NEW_BILL_TO_OMX_CONSIGNEE__c, Master_Account__c, 
                                                        Original_Account__r.ownerId, Original_Account__c, NEW_MAIN_ACCT_ADDRESS__c, 
                                                        Customer_Transition__r.Mod4FlowStatus__c, BatchProcessed__c, New_Header_Billing_Account_Code__c 
                                                        FROM Split_Account_Detail__c 
                                                        WHERE Id = :sad.Id];
     //run batch
    //Test.startTest();
      Mod5BulkBatch m = new Mod5BulkBatch();
      Database.QueryLocator ql = m.start(null);
      m.execute(null,splitAccountList);
      m.Finish(null);
    Test.stopTest();

    List<CustTransParentChildLevel__c> PCLevel2 = [SELECT Mod5LaunchBulkBatchID__C,Mod5BulkLaunchBatchInterval__c FROM
      CustTransParentChildLevel__c];
    System.assert(PCLevel2.size() > 0);
  } 

static testmethod void testMod52(){
    //create test data
    Account acc = Test_Utils.createAccount('Customer (OfficeMax)');
        acc.Name = 'TestOriginalAccount';
        acc.Split_Record__c = false;
        acc.OMX_Primary_Key__c = '123456';
        insert acc;                        
    Account acc3 = Test_Utils.createAccount('Site (OfficeMax)');
        acc3.Name = 'TestMasterAccount2';
        acc3.Split_Record__c = false;
        acc3.OMX_Primary_Key__c = '123458';
        acc3.Related_Account__c = acc.Id;
        insert acc3;
        
        Test.startTest();
        
    Account acc2 = Test_Utils.createAccount('Site (OfficeMax)');
        acc2.Name = 'TestMasterAccount';
        acc2.Split_Record__c = false;
        acc2.OMX_Primary_Key__c = '123457';
        acc2.Related_Account__c = acc3.Id;
        insert acc2;                
    Customer_Transition__c ct = Test_Utils.createCustomerTransaction(false, acc);
        ct.OMX_Primary_Key__c = '1234567';
        ct.Mod4FlowStatus__c = 'SplitSubmitted';
        ct.Account__c = acc.Id;
        insert ct;
    Customer_Transition_Dtls__c details = Test_Utils.createCustomerTransDetails('Sites');
        details.Account_ID__c = acc2.Id;
        details.Bill_To_Account__c = acc2.Id;
        details.OMX_Primary_Key__c = '123456789';
        details.Customer_Transition_ID__c = ct.Id;
        insert details;
    Split_Account_Detail__c sad = Test_Utils.createSplitAccount(false, ct, acc);
        sad.Master_Account__c = acc2.Id;
        sad.BatchProcessed__c = false;
        sad.NEW_BILL_TO_OMX_CONSIGNEE__c = '123457';
        sad.Ship_To_Account__c = acc2.Id;
        sad.Billing_Account__c = acc2.Id;
        sad.Main_Account_Name__c = 'TestMasterAccount';
        sad.Customer_Transition_Detail_Id__c = details.Id;
        sad.New_Header_Billing_Account__c = acc3.Id;
        sad.Original_Account__c = acc.Id;
        insert sad;
    CustTransParentChildLevel__c customSetting = new CustTransParentChildLevel__c();
      customSetting.Name = 'Parent';
      insert customSetting;
    List<Split_Account_Detail__c> splitAccountList = [SELECT Id, Customer_Transition__r.OMX_Primary_Key__c, SHIP_TO_CONSIGNEE__c, 
                                                        Billing_Account__c, NEW_BILL_TO_OMX_CONSIGNEE__c, Master_Account__c, 
                                                        Original_Account__r.ownerId, Original_Account__c, NEW_MAIN_ACCT_ADDRESS__c, 
                                                        Customer_Transition__r.Mod4FlowStatus__c, BatchProcessed__c, New_Header_Billing_Account_Code__c 
                                                        FROM Split_Account_Detail__c 
                                                        WHERE Id = :sad.Id];
     //run batch
      //Test.startTest();
      Mod5BulkBatch m = new Mod5BulkBatch();
      Database.QueryLocator ql = m.start(null);
      m.execute(null,splitAccountList);
      m.Finish(null);
    Test.stopTest();

    List<CustTransParentChildLevel__c> PCLevel2 = [SELECT Mod5LaunchBulkBatchID__C,Mod5BulkLaunchBatchInterval__c FROM
      CustTransParentChildLevel__c];
    System.assert(PCLevel2.size() > 0);
  }
}