objects/Account.object
<CustomObject>
    <fields>
        <fullName>AOPS_Cust_Id__c</fullName>
        <description>AOPS Customer Account Number</description>
        <externalId>true</externalId>
        <label>AOPS Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>AOPS_Seq_ID__c</fullName>
        <externalId>true</externalId>
        <label>AOPS Seq ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Oracle_Party_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Party ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer Accounts</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Ace_Customer_Core_Changes__c.object
<CustomObject>
    <description>Price Change Process UI</description>
    <fields>
        <fullName>ACE_Customer_Price_Changes__c</fullName>
        <label>Batch</label>
        <referenceTo>ACE_Customer_Price_Changes__c</referenceTo>
        <relationshipLabel>Customer Core Changes</relationshipLabel>
        <relationshipName>Ace_Customer_Core_Changes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CoreID__c</fullName>
        <externalId>true</externalId>
        <label>CoreID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_12_Month_Qty__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Accumulated SKU Sold Qty for this Core, Last 12 calendar months from current date
Same Time Period as of Sales</description>
        <label>Item 12 Month Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Item_3_Month_Qty__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Accumulated SKU Sold Qty for this Core, Last 3 calendar months from current date
Same Time Period as of Sales</description>
        <label>Item 3 Month Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Item_3_Month_Sales__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Accumulated SKU Sales for this Core, Last 3 calendar months from current date</description>
        <label>Item 3 Month Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Item_6_Month_Qty__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Accumulated SKU Sold Qty for this Core, Last 6 calendar months from current date
Same Time Period as of Sales</description>
        <label>Item 6 Month Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Item_6_Month_Sales__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Vendavo PA</description>
        <label>Item 6 Month Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Item_9_Month_Qty__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Accumulated SKU Sold Qty for this Core, Last 9 calendar months from current date
Same Time Period as of Sales</description>
        <label>Item 9 Month Qty</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SRM_Differential__c</fullName>
        <defaultValue>0</defaultValue>
        <label>SRM Differential $</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Spend_Impact_12_Month__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Spend Impact 12 Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>batchId__c</fullName>
        <label>batchId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Customer Core Changes</label>
    <nameField>
        <label>Core</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Core Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ACE_Customer_Price_Changes__c.object
<CustomObject>
    <description>Price Change Process UI</description>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>ACE_Customer_Price_Changes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Hosted_Catalog__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Hosted Catalog flag for Hosted Catalog bucket</description>
        <label>Hosted Catalog</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Item_12_Month_Qty__c</fullName>
        <description>Accumulated SKU Sold Qty for this Core, Last 12 calendar months from current date
Same Time Period as of Sales</description>
        <label>Item 12 Month Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Item_3_Month_Qty__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Accumulated SKU Sold Qty for this Core, Last 3 calendar months from current date
Same Time Period as of Sales</description>
        <label>Item 3 Month Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Item_3_Month_Sales__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Accumulated SKU Sales for this Core, Last 3 calendar months from current date</description>
        <label>Item 3 Month Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Item_6_Month_Qty__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Accumulated SKU Sold Qty for this Core, Last 6 calendar months from current date
Same Time Period as of Sales</description>
        <label>Item 6 Month Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Item_6_Month_Sales__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Vendavo PA</description>
        <label>Item 6 Month Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Item_9_Month_Qty__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Accumulated SKU Sold Qty for this Core, Last 9 calendar months from current date
Same Time Period as of Sales</description>
        <label>Item 9 Month Qty</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Owning_Customer_ID__c</fullName>
        <externalId>true</externalId>
        <label>Cust ID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFDC_Notification_Flag__c</fullName>
        <label>SFDC Notification Flag</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SRM_Differential__c</fullName>
        <defaultValue>0</defaultValue>
        <label>SRM Differential $</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Spend_Impact_12_Month__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Estimated Total Annual Spend Change</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>batchId__c</fullName>
        <label>batchId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Customer Core Price Changes</label>
    <nameField>
        <label>Batch</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Core Price Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Ace_Customer_SKU_Changes__c.object
<CustomObject>
    <description>Price Change Process UI</description>
    <fields>
        <fullName>Ace_Customer_Core_Changes__c</fullName>
        <label>Customer Core Changes</label>
        <referenceTo>Ace_Customer_Core_Changes__c</referenceTo>
        <relationshipLabel>Customer SKU Changes</relationshipLabel>
        <relationshipName>Ace_Customer_SKU_Changes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Hosted_Catalog__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Hosted Catalog flag for Hosted Catalog bucket</description>
        <label>Hosted Catalog</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Item_12_Month_Qty__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Accumulated SKU Sold Qty for this Core, Last 12 calendar months from current date
Same Time Period as of Sales</description>
        <label>12 Month Usage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Item_3_Month_Qty__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Accumulated SKU Sold Qty for this Core, Last 3 calendar months from current date
Same Time Period as of Sales</description>
        <label>3 Month Usage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Item_3_Month_Sales__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Accumulated SKU Sales for this Core, Last 3 calendar months from current date</description>
        <label>Item 3 Month Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Item_6_Month_Qty__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Accumulated SKU Sold Qty for this Core, Last 6 calendar months from current date
Same Time Period as of Sales</description>
        <label>6 Month Usage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Item_6_Month_Sales__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Vendavo PA</description>
        <label>Item 6 Month Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Item_9_Month_Qty__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Accumulated SKU Sold Qty for this Core, Last 9 calendar months from current date
Same Time Period as of Sales</description>
        <label>9 Month Usage</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Owning_Customer_ID__c</fullName>
        <label>Owning Customer ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFDC_Notification_Flag__c</fullName>
        <label>SFDC Notification Flag</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SKU__c</fullName>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SRM_Differential__c</fullName>
        <defaultValue>0</defaultValue>
        <label>SRM Differential $</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Spend_Impact_12_Month__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Spend Impact 12 Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>batchId__c</fullName>
        <label>batchId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Customer SKU Changes</label>
    <nameField>
        <label>Customer SKU Changes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer SKU Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ACE_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is For ACE Custom Settings</description>
    <fields>
        <fullName>Level1Access__c</fullName>
        <description>Level1Access</description>
        <label>Level1Access</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level2Access__c</fullName>
        <description>Level2Access</description>
        <label>Level2Access</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level3Access__c</fullName>
        <description>Level3Access</description>
        <label>Level3Access</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <label>ACE_Settings</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Short_Title__c</fullName>
        <label>Short Title</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ACE_Customer_List_TC.cls
@isTest (SeeAllData=false)
private class ACE_Customer_List_TC 
{
    static testMethod void ACE_Customer_List_CoverMethods()
    {
        Profile TestProfile= [select id from profile where name='System Administrator'];
        User TestUser = new User(Alias = 'newUser', Email='newuser@officedepot.com.uat', 
                 EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                 LocaleSidKey='en_US', ProfileId = TestProfile.Id, 
                 TimeZoneSidKey='America/Los_Angeles', UserName='newuser@test.officedepot.com', short_title__c='DSM');
        insert TestUser; 
         System.runAs(TestUser){
        User currentUser = new User();
        currentUser.id = Userinfo.getUserId();
        currentUser.short_title__c = 'RVP';
        update currentUser;
        
       
            Group Group1 = new Group(Name ='Remediation Team');
            insert Group1;
            GroupMember GroupMembers = new GroupMember(
                                 GroupId = Group1.Id,
                                 UserOrGroupId = currentUser.id
                                );
            insert GroupMembers;    
            Group Group2 = new Group(Name ='Hosted Catalog Team');
            insert Group2;
            GroupMember GroupMembers1 = new GroupMember(
                                 GroupId = Group2.Id,
                                 UserOrGroupId = currentUser.id
                                );
            insert GroupMembers1; 
        
                    ACE_Settings__c aceSettingCE = new ACE_Settings__c (Name ='test',Level1Access__c ='DSM',Level2Access__c='RSD',Level3Access__c='RVP');
        insert aceSettingCE ;
  
        
        Account acc = new Account(
                                    Name = 'Testing'    
                                    ,AOPS_Seq_ID__c = '123456',AOPS_Cust_Id__c = '123456',Oracle_Party_Id__c = '123456',
                                    Billingcountry = 'USA',BillingState = 'UT',BillingStreet = '1040 N 326 W',billingcity = 'Orem'                                
                                    );
        insert acc;
        List<ACE_Customer_Price_Changes__c> aceCustPriceChangesList = new List<ACE_Customer_Price_Changes__c>();
        ACE_Customer_Price_Changes__c aceCustPriceChanges = new ACE_Customer_Price_Changes__c (name='batch1',
                                         Customer__c = acc.id,
                                         Owning_Customer_ID__c = '123456',
                                         SRM_Differential__c =5,
                                         Item_12_Month_Qty__c =2,
                                         Total_Spend_Impact_12_Month__c=5000,
                                         SFDC_Notification_Flag__c  = '1',
                                         Hosted_Catalog__c = true                                     
                                        );
        aceCustPriceChangesList.add (aceCustPriceChanges );    
        insert      aceCustPriceChangesList ;  
        Ace_Customer_Core_Changes__c ace2 = new Ace_Customer_Core_Changes__c(name = 'Test1',CoreID__c = '123456', ACE_Customer_Price_Changes__c = aceCustPriceChangesList[0].id);
        insert ace2;

        List<Ace_Customer_SKU_Changes__c > lst_sku = new List<Ace_Customer_SKU_Changes__c >();
        Ace_Customer_SKU_Changes__c ace3 = new Ace_Customer_SKU_Changes__c(SKU__c = '123456',status__c='Active',batchId__c='abc',Item_3_Month_Qty__c=12.12,Item_6_Month_Qty__c=12.12,Item_9_Month_Qty__c=12.12,Item_6_Month_Sales__c=12.12,Item_3_Month_Sales__c=12.12,
                        Item_9_Month_Sales__c=12.12,Total_Spend_Impact_3_Month__c=12.12,Total_Spend_Impact_6_Month__c=12.12,Total_Spend_Impact_9_Month__c=12.12,Item_12_Month_Qty__c = 50,Item_12_Month_Sales__c=12.12,Total_Spend_Impact_12_Month__c=123.12,name='test', Ace_Customer_Core_Changes__c = ace2.id);
        insert ace3;
        
                                          
        
        
        
                                                             
        ApexPages.currentPage().getParameters().put('searchWord','TEst');
        ApexPages.currentPage().getParameters().put('batch','batch1');
        ApexPages.currentPage().getParameters().put('selectedCustomer',acc.id);       
        ApexPages.currentPage().getParameters().put('selectedCustomerName',acc.name);
        ACE_Customer_List ACECustomerListCls = new ACE_Customer_List();
        ACECustomerListCls.searchText = 'Testing';
        ACECustomerListCls.skuFilterSelection = 'Verified';
        ACECustomerListCls.renderUpload();
        ACECustomerListCls.findskus();
        ACECustomerListCls.SkunextPage();
        ACECustomerListCls.getskuDisableNext();
        
        ACECustomerListCls.SkuprevPage();
        ACECustomerListCls.getskuDisablePrevious();
        ACECustomerListCls.SearchRecords();

        test.startTest();        
        //sorting
        ACECustomerListCls.sortCust();
        ACECustomerListCls.getFieldName = 'Customer';
        ACECustomerListCls.sortCust();
        ACECustomerListCls.getFieldName = 'Cores';
        ACECustomerListCls.sortCust();
        ACECustomerListCls.getFieldName = 'effectiveDate';
        ACECustomerListCls.sortCust();
        ACECustomerListCls.getFieldName = 'notifydate';
        ACECustomerListCls.sortCust();
        ACECustomerListCls.getFieldName = 'customerid';
        ACECustomerListCls.sortCust();        
        ACECustomerListCls.getFieldName = 'notifStatus';
        ACECustomerListCls.sortCust();
        ACECustomerListCls.getFieldName = 'pricechangestatus';
        ACECustomerListCls.sortCust();
        ACECustomerListCls.getFieldName = 'sfdcBucket';
        ACECustomerListCls.sortCust();
        
        
        
        //end sorting
        
        ACECustomerListCls.releaseEarly();
        ACECustomerListCls.processSelected();
        
       
        ACECustomerListCls.ApproveRec();
        ACECustomerListCls.RejectRec();
        Test.StopTest();
         }
    }
    /* //access level : hosted nonverified
    static testMethod void ACE_Customer_List_CoverMethods1()
    {
        
        Profile TestProfile= [select id from profile where name='System Administrator'];
        User TestUser = new User(Alias = 'newUser', Email='newuser@officedepot.com.uat', 
                 EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                 LocaleSidKey='en_US', ProfileId = TestProfile.Id, 
                 TimeZoneSidKey='America/Los_Angeles', UserName='newuser@test.officedepot.com');
        insert TestUser; 
        User currentUser = new User();
        currentUser.id = Userinfo.getUserId();
        currentUser.short_title__c = 'RSD';
        update currentUser;
        System.runAs(TestUser){
            Group Group1 = new Group(Name ='Remediation Team');
            insert Group1;
            GroupMember GroupMembers = new GroupMember(
                                 GroupId = Group1.Id,
                                 UserOrGroupId = currentUser.id
                                );
            insert GroupMembers;    
            Group Group2 = new Group(Name ='Hosted Catalog Team');
            insert Group2;
            GroupMember GroupMembers1 = new GroupMember(
                                 GroupId = Group2.Id,
                                 UserOrGroupId = Userinfo.getUserId()
                                );
            insert GroupMembers1;   
        }
        ACE_Settings__c aceSettingCE = new ACE_Settings__c (Name ='test',Level1Access__c ='DSM',Level2Access__c='RSD',Level3Access__c='RVP');
        insert aceSettingCE ;
        Account acc = new Account(
                                    Name = 'Testing'    
                                    ,AOPS_Seq_ID__c = '123456',AOPS_Cust_Id__c = '123456',Oracle_Party_Id__c = '123456',
                                    Billingcountry = 'USA',BillingState = 'UT',BillingStreet = '1040 N 326 W',billingcity = 'Orem'                                
                                    );
        insert acc;
        List<ACE_Customer_Price_Changes__c> aceCustPriceChangesList = new List<ACE_Customer_Price_Changes__c>();
        ACE_Customer_Price_Changes__c aceCustPriceChanges = new ACE_Customer_Price_Changes__c (name='batch1',
                                         Customer__c = acc.id,
                                         Owning_Customer_ID__c = '123456',
                                         SRM_Differential__c =5,
                                         Item_12_Month_Qty__c =2,
                                         Total_Spend_Impact_12_Month__c=5000,
                                         SFDC_Notification_Flag__c  = '1',
                                         Hosted_Catalog__c = true                                     
                                        );
        aceCustPriceChangesList.add (aceCustPriceChanges );    
        insert      aceCustPriceChangesList ;  
        Ace_Customer_Core_Changes__c ace2 = new Ace_Customer_Core_Changes__c(name = 'Test1',CoreID__c = '123456', ACE_Customer_Price_Changes__c = aceCustPriceChangesList[0].id);
        insert ace2;

        List<Ace_Customer_SKU_Changes__c > lst_sku = new List<Ace_Customer_SKU_Changes__c >();
        Ace_Customer_SKU_Changes__c ace3 = new Ace_Customer_SKU_Changes__c(SKU__c = '123456',status__c='Active',batchId__c='abc',Item_3_Month_Qty__c=12.12,Item_6_Month_Qty__c=12.12,Item_9_Month_Qty__c=12.12,Item_6_Month_Sales__c=12.12,Item_3_Month_Sales__c=12.12,
                        Item_9_Month_Sales__c=12.12,Total_Spend_Impact_3_Month__c=12.12,Total_Spend_Impact_6_Month__c=12.12,Total_Spend_Impact_9_Month__c=12.12,Item_12_Month_Qty__c = 50,Item_12_Month_Sales__c=12.12,Total_Spend_Impact_12_Month__c=123.12,name='test', Ace_Customer_Core_Changes__c = ace2.id);
        insert ace3;
        
                                          
        
        
        
                                                             
        ApexPages.currentPage().getParameters().put('searchWord','TEst');
        ApexPages.currentPage().getParameters().put('batch','batch1');
        ApexPages.currentPage().getParameters().put('selectedCustomer',acc.id); 
        ApexPages.currentPage().getParameters().put('selectedCustomerName',acc.name);       
        ACE_Customer_List ACECustomerListCls = new ACE_Customer_List();
        ACECustomerListCls.getFieldName = 'notifStatus';
        ACECustomerListCls.searchText = 'Testing';
        ACECustomerListCls.skuFilterSelection = 'NotVerified';
        ACECustomerListCls.renderUpload();
        ACECustomerListCls.findskus();
        ACECustomerListCls.OwnerValue = 'PendingApproval'; //Owned by me
        ACECustomerListCls.SearchRecords();
        ACECustomerListCls.nextPage();
        ACECustomerListCls.getDisableNext();
        test.startTest();
        
        ACECustomerListCls.skuFilterSelection = 'Verified';
        ACECustomerListCls.findskus();
        
        ACECustomerListCls.prevPage();
        ACECustomerListCls.getDisablePrevious();
        //sorting
       
        ACECustomerListCls.getFieldName = 'annualspend';
        ACECustomerListCls.sortCust();
        //ACECustomerListCls.getFieldName = 'annualspndchange';
        //ACECustomerListCls.sortCust();
        //end sorting
        ACECustomerListCls.getFieldName = 'notifStatus';
        ACECustomerListCls.releaseEarly();
        ACECustomerListCls.processSelected();
        
        ACECustomerListCls.ApproveRec();
        ACECustomerListCls.RejectRec();
        Test.StopTest();
    }*/
    //access level : general
    static testMethod void ACE_Customer_List_CoverMethods2()
    {
        
         Profile TestProfile= [select id from profile where name='System Administrator'];
        User TestUser = new User(Alias = 'newUser', Email='newuser@officedepot.com.uat', 
                 EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                 LocaleSidKey='en_US', ProfileId = TestProfile.Id, 
                 TimeZoneSidKey='America/Los_Angeles', UserName='newuser@test.officedepot.com', short_title__c='DSM');
        insert TestUser; 
        system.runAs(TestUser){
        ACE_Settings__c aceSettingCE = new ACE_Settings__c (Name ='test',Level1Access__c ='DSM',Level2Access__c='RSD',Level3Access__c='RVP');
        insert aceSettingCE ;
        Account acc = new Account(
                                    Name = 'Testing'    
                                    ,AOPS_Seq_ID__c = '123456',AOPS_Cust_Id__c = '123456',Oracle_Party_Id__c = '123456',
                                    Billingcountry = 'USA',BillingState = 'UT',BillingStreet = '1040 N 326 W',billingcity = 'Orem'                                
                                    );
        insert acc;
        List<ACE_Customer_Price_Changes__c> aceCustPriceChangesList = new List<ACE_Customer_Price_Changes__c>();
        ACE_Customer_Price_Changes__c aceCustPriceChanges = new ACE_Customer_Price_Changes__c (name='batch1',
                                         Customer__c = acc.id,
                                         Owning_Customer_ID__c = '123456',
                                         SRM_Differential__c =5,
                                         Item_12_Month_Qty__c =2,
                                         Total_Spend_Impact_12_Month__c=5000,
                                         SFDC_Notification_Flag__c  = '1',
                                         Hosted_Catalog__c = true                                     
                                        );
        aceCustPriceChangesList.add (aceCustPriceChanges );    
        insert      aceCustPriceChangesList ;  
        Ace_Customer_Core_Changes__c ace2 = new Ace_Customer_Core_Changes__c(name = 'Test1',CoreID__c = '123456', ACE_Customer_Price_Changes__c = aceCustPriceChangesList[0].id);
        insert ace2;

        List<Ace_Customer_SKU_Changes__c > lst_sku = new List<Ace_Customer_SKU_Changes__c >();
        Ace_Customer_SKU_Changes__c ace3 = new Ace_Customer_SKU_Changes__c(SKU__c = '123456',status__c='Active',batchId__c='abc',Item_3_Month_Qty__c=12.12,Item_6_Month_Qty__c=12.12,Item_9_Month_Qty__c=12.12,Item_6_Month_Sales__c=12.12,Item_3_Month_Sales__c=12.12,
                        Item_9_Month_Sales__c=12.12,Total_Spend_Impact_3_Month__c=12.12,Total_Spend_Impact_6_Month__c=12.12,Total_Spend_Impact_9_Month__c=12.12,Item_12_Month_Qty__c = 50,Item_12_Month_Sales__c=12.12,Total_Spend_Impact_12_Month__c=123.12,name='test', Ace_Customer_Core_Changes__c = ace2.id);
        insert ace3;
        
                                          
        
        
        
                                                             
        ApexPages.currentPage().getParameters().put('searchWord','TEst');
        ApexPages.currentPage().getParameters().put('batch','batch1');
        ApexPages.currentPage().getParameters().put('selectedCustomer',acc.id);   
        ApexPages.currentPage().getParameters().put('selectedCustomerName',acc.name);       
        ACE_Customer_List ACECustomerListCls = new ACE_Customer_List();
        ACECustomerListCls.searchText = 'Testing';
        ACECustomerListCls.OwnerValue = 'All'; //All
        ACECustomerListCls.skuFilterSelection = 'NotVerified';
        ACECustomerListCls.renderUpload();
        ACECustomerListCls.findskus();
       
        ACECustomerListCls.SearchRecords();
        test.startTest();
        ACECustomerListCls.getFieldName = 'notifStatus';
        ACECustomerListCls.nextPage();
        ACECustomerListCls.getDisableNext();
        
        ACECustomerListCls.prevPage();
        ACECustomerListCls.getDisablePrevious();
        //sorting
       
        ACECustomerListCls.getFieldName = 'annualspend';
        ACECustomerListCls.sortCust();
        ACECustomerListCls.getFieldName = 'annualspndchange';
        ACECustomerListCls.sortCust();
        ACECustomerListCls.getFieldName = 'NoOfSKUGovernedByActiveWrittenAgreement';
        ACECustomerListCls.sortCust();
        ACECustomerListCls.getFieldName = 'reps';
        ACECustomerListCls.sortCust();
        //end sorting
        
        ACECustomerListCls.releaseEarly();
        ACECustomerListCls.processSelected();
        
        ACECustomerListCls.ApproveRec();
        ACECustomerListCls.RejectRec();        
        Test.StopTest();
        }
    }


static testMethod void ACE_Customer_List_CoverMethods3()
    {
        Profile TestProfile= [select id from profile where name='System Administrator'];
        User TestUser = new User(Alias = 'newUser', Email='newuser@officedepot.com.uat', 
                 EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                 LocaleSidKey='en_US', ProfileId = TestProfile.Id, 
                 TimeZoneSidKey='America/Los_Angeles', UserName='newuser@test.officedepot.com', short_title__c='DSM');
        insert TestUser; 
        system.runAs(TestUser){
        
        ACE_Settings__c aceSettingCE = new ACE_Settings__c (Name ='test',Level1Access__c ='DSM',Level2Access__c='RSD',Level3Access__c='RVP');
        insert aceSettingCE ;
        Account acc = new Account(
                                    Name = 'Testing'    
                                    ,AOPS_Seq_ID__c = '123456',AOPS_Cust_Id__c = '123456',Oracle_Party_Id__c = '123456',
                                    Billingcountry = 'USA',BillingState = 'UT',BillingStreet = '1040 N 326 W',billingcity = 'Orem'                                
                                    );
        insert acc;
        List<ACE_Customer_Price_Changes__c> aceCustPriceChangesList = new List<ACE_Customer_Price_Changes__c>();
        ACE_Customer_Price_Changes__c aceCustPriceChanges = new ACE_Customer_Price_Changes__c (name='batch1',
                                         Customer__c = acc.id,
                                         Owning_Customer_ID__c = '123456',
                                         SRM_Differential__c =5,
                                         Item_12_Month_Qty__c =2,
                                         Total_Spend_Impact_12_Month__c=5000,
                                         SFDC_Notification_Flag__c  = '1',
                                         Hosted_Catalog__c = true                                    
                                        );
        aceCustPriceChangesList.add (aceCustPriceChanges );    
        insert      aceCustPriceChangesList ;  
        Ace_Customer_Core_Changes__c ace2 = new Ace_Customer_Core_Changes__c(name = 'Test1',CoreID__c = '123456', ACE_Customer_Price_Changes__c = aceCustPriceChangesList[0].id);
        insert ace2;

        List<Ace_Customer_SKU_Changes__c > lst_sku = new List<Ace_Customer_SKU_Changes__c >();
        Ace_Customer_SKU_Changes__c ace3 = new Ace_Customer_SKU_Changes__c(SKU__c = '123456',status__c='Active',batchId__c='abc',Item_3_Month_Qty__c=12.12,Item_6_Month_Qty__c=12.12,Item_9_Month_Qty__c=12.12,Item_6_Month_Sales__c=12.12,Item_3_Month_Sales__c=12.12,
                        Item_9_Month_Sales__c=12.12,Total_Spend_Impact_3_Month__c=12.12,Total_Spend_Impact_6_Month__c=12.12,Total_Spend_Impact_9_Month__c=12.12,Item_12_Month_Qty__c = 50,Item_12_Month_Sales__c=12.12,Total_Spend_Impact_12_Month__c=123.12,name='test', Ace_Customer_Core_Changes__c = ace2.id);
        insert ace3;
        
                                          
        
        
        
                                                             
        ApexPages.currentPage().getParameters().put('searchWord','TEst');
        ApexPages.currentPage().getParameters().put('batch','batch1');
        ApexPages.currentPage().getParameters().put('selectedCustomer',acc.id);   
        ApexPages.currentPage().getParameters().put('selectedCustomerName',acc.name);       
        ACE_Customer_List ACECustomerListCls = new ACE_Customer_List();
        ACECustomerListCls.searchText = 'Testing';
        ACECustomerListCls.OwnerValue = 'Owned by me';
        ACECustomerListCls.skuFilterSelection = 'NotVerified';
        ACECustomerListCls.renderUpload();
        ACECustomerListCls.findskus();
       
        ACECustomerListCls.SearchRecords();
        test.startTest();
        ACECustomerListCls.nextPage();
        ACECustomerListCls.getDisableNext();
        
        ACECustomerListCls.prevPage();
        ACECustomerListCls.getDisablePrevious();
        //sorting
       
        ACECustomerListCls.getFieldName = 'annualspend';
        ACECustomerListCls.sortCust();
        ACECustomerListCls.getFieldName = 'annualspndchange';
        ACECustomerListCls.sortCust();
        ACECustomerListCls.getFieldName = 'NoOfSKUGovernedByActiveWrittenAgreement';
        ACECustomerListCls.sortCust();
        ACECustomerListCls.getFieldName = 'reps';
        ACECustomerListCls.sortCust();
        ACECustomerListCls.getFieldName = 'SKU';
        ACECustomerListCls.sortCust();
        //end sorting
        
        ACECustomerListCls.releaseEarly();
        ACECustomerListCls.processSelected();
        
        ACECustomerListCls.ApproveRec();
        ACECustomerListCls.RejectRec();        
        Test.StopTest();
        }
    }
    
    static testMethod void ACE_Customer_List_CoverMethods4()
    {
        Profile TestProfile= [select id from profile where name='System Administrator'];
        User TestUser = new User(Alias = 'newUser', Email='newuser@officedepot.com.uat', 
                 EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                 LocaleSidKey='en_US', ProfileId = TestProfile.Id, 
                 TimeZoneSidKey='America/Los_Angeles', UserName='newuser@test.officedepot.com', short_title__c='DSM');
        insert TestUser; 
          System.runAs(TestUser){
        User currentUser = new User();
        currentUser.id = Userinfo.getUserId();
        currentUser.short_title__c = 'RVP';
        update currentUser;
        
      
            Group Group1 = new Group(Name ='Remediation Team');
            insert Group1;
            GroupMember GroupMembers = new GroupMember(
                                 GroupId = Group1.Id,
                                 UserOrGroupId = currentUser.id
                                );
            insert GroupMembers;    
            Group Group2 = new Group(Name ='Hosted Catalog Team');
            insert Group2;
            GroupMember GroupMembers1 = new GroupMember(
                                 GroupId = Group2.Id,
                                 UserOrGroupId = currentUser.id
                                );
            insert GroupMembers1;  
            
                    ACE_Settings__c aceSettingCE = new ACE_Settings__c (Name ='test',Level1Access__c ='DSM',Level2Access__c='RSD',Level3Access__c='RVP');
        insert aceSettingCE ;
 
        
        Account acc = new Account(
                                    Name = 'Testing'    
                                    ,AOPS_Seq_ID__c = '123456',AOPS_Cust_Id__c = '123456',Oracle_Party_Id__c = '123456',
                                    Billingcountry = 'USA',BillingState = 'UT',BillingStreet = '1040 N 326 W',billingcity = 'Orem'                                
                                    );
        insert acc;
        List<ACE_Customer_Price_Changes__c> aceCustPriceChangesList = new List<ACE_Customer_Price_Changes__c>();
        ACE_Customer_Price_Changes__c aceCustPriceChanges = new ACE_Customer_Price_Changes__c (name='batch1',
                                         Customer__c = acc.id,
                                         Owning_Customer_ID__c = '123456',
                                         SRM_Differential__c =5,
                                         Item_12_Month_Qty__c =2,
                                         Total_Spend_Impact_12_Month__c=5000,
                                         SFDC_Notification_Flag__c  = '1',
                                         Hosted_Catalog__c = true                                     
                                        );
        aceCustPriceChangesList.add (aceCustPriceChanges );    
        insert      aceCustPriceChangesList ;  
        Ace_Customer_Core_Changes__c ace2 = new Ace_Customer_Core_Changes__c(name = 'Test1',CoreID__c = '123456', ACE_Customer_Price_Changes__c = aceCustPriceChangesList[0].id);
        insert ace2;

        List<Ace_Customer_SKU_Changes__c > lst_sku = new List<Ace_Customer_SKU_Changes__c >();
        Ace_Customer_SKU_Changes__c ace3 = new Ace_Customer_SKU_Changes__c(SKU__c = '123456',status__c='Active',batchId__c='abc',Item_3_Month_Qty__c=12.12,Item_6_Month_Qty__c=12.12,Item_9_Month_Qty__c=12.12,Item_6_Month_Sales__c=12.12,Item_3_Month_Sales__c=12.12,
                        Item_9_Month_Sales__c=12.12,Total_Spend_Impact_3_Month__c=12.12,Total_Spend_Impact_6_Month__c=12.12,Total_Spend_Impact_9_Month__c=12.12,Item_12_Month_Qty__c = 50,Item_12_Month_Sales__c=12.12,Total_Spend_Impact_12_Month__c=123.12,name='test', Ace_Customer_Core_Changes__c = ace2.id);
        insert ace3;
        
                                          
        
        
        
                                                             
        ApexPages.currentPage().getParameters().put('searchWord','TEst');
        ApexPages.currentPage().getParameters().put('batch','batch1');
        ApexPages.currentPage().getParameters().put('selectedCustomer',acc.id);       
        ApexPages.currentPage().getParameters().put('selectedCustomerName',acc.name);
        ACE_Customer_List ACECustomerListCls = new ACE_Customer_List();
        ACECustomerListCls.searchText = 'Testing';
        ACECustomerListCls.skuFilterSelection = 'Verified';
        ACECustomerListCls.OwnerValue = 'Owned by me';
        ACECustomerListCls.renderUpload();
        ACECustomerListCls.findskus();
        ACECustomerListCls.SkunextPage();
        ACECustomerListCls.getskuDisableNext();
        
        ACECustomerListCls.SkuprevPage();
        ACECustomerListCls.getskuDisablePrevious();
        ACECustomerListCls.SearchRecords();

        test.startTest();        
        //sorting
        ACECustomerListCls.sortCust();
        ACECustomerListCls.getFieldName = 'Customer';
        ACECustomerListCls.sortCust();
        ACECustomerListCls.getFieldName = 'Cores';
        ACECustomerListCls.sortCust();
        ACECustomerListCls.getFieldName = 'effectiveDate';
        ACECustomerListCls.sortCust();
        ACECustomerListCls.getFieldName = 'notifydate';
        ACECustomerListCls.sortCust();
        ACECustomerListCls.getFieldName = 'customerid';
        ACECustomerListCls.sortCust();        
        ACECustomerListCls.getFieldName = 'notifStatus';
        ACECustomerListCls.sortCust();
        ACECustomerListCls.getFieldName = 'pricechangestatus';
        ACECustomerListCls.sortCust();
        ACECustomerListCls.getFieldName = 'sfdcBucket';
        ACECustomerListCls.sortCust();
        
        
        
        //end sorting
        
        ACECustomerListCls.releaseEarly();
        ACECustomerListCls.processSelected();
        
       
        ACECustomerListCls.ApproveRec();
        ACECustomerListCls.RejectRec();
        Test.StopTest();
    }
    }
    
    static testMethod void ACE_Customer_List_CoverMethods5()
    {
        Profile TestProfile= [select id from profile where name='System Administrator'];
        User TestUser = new User(Alias = 'newUser', Email='newuser@officedepot.com.uat', 
                 EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                 LocaleSidKey='en_US', ProfileId = TestProfile.Id, 
                 TimeZoneSidKey='America/Los_Angeles', UserName='newuser@test.officedepot.com', short_title__c='DSM');
        insert TestUser; 
            System.runAs(TestUser){
        User currentUser = new User();
        currentUser.id = Userinfo.getUserId();
        currentUser.short_title__c = 'RVP';
        update currentUser;
        
    
            Group Group1 = new Group(Name ='Remediation Team');
            insert Group1;
            GroupMember GroupMembers = new GroupMember(
                                 GroupId = Group1.Id,
                                 UserOrGroupId = currentUser.id
                                );
            insert GroupMembers;    
            Group Group2 = new Group(Name ='Hosted Catalog Team');
            insert Group2;
            GroupMember GroupMembers1 = new GroupMember(
                                 GroupId = Group2.Id,
                                 UserOrGroupId = currentUser.id
                                );
            insert GroupMembers1;  
                    ACE_Settings__c aceSettingCE = new ACE_Settings__c (Name ='test',Level1Access__c ='DSM',Level2Access__c='RSD',Level3Access__c='RVP');
        insert aceSettingCE ;
 
        
        Account acc = new Account(
                                    Name = 'Testing'    
                                    ,AOPS_Seq_ID__c = '123456',AOPS_Cust_Id__c = '123456',Oracle_Party_Id__c = '123456',
                                    Billingcountry = 'USA',BillingState = 'UT',BillingStreet = '1040 N 326 W',billingcity = 'Orem'                                
                                    );
        insert acc;
        List<ACE_Customer_Price_Changes__c> aceCustPriceChangesList = new List<ACE_Customer_Price_Changes__c>();
        ACE_Customer_Price_Changes__c aceCustPriceChanges = new ACE_Customer_Price_Changes__c (name='batch1',
                                         Customer__c = acc.id,
                                         Owning_Customer_ID__c = '123456',
                                         SRM_Differential__c =5,
                                         Item_12_Month_Qty__c =2,
                                         Total_Spend_Impact_12_Month__c=5000,
                                         SFDC_Notification_Flag__c  = '1',
                                         Hosted_Catalog__c = true                                     
                                        );
        aceCustPriceChangesList.add (aceCustPriceChanges );    
        insert      aceCustPriceChangesList ;  
        Ace_Customer_Core_Changes__c ace2 = new Ace_Customer_Core_Changes__c(name = 'Test1',CoreID__c = '123456', ACE_Customer_Price_Changes__c = aceCustPriceChangesList[0].id);
        insert ace2;

        List<Ace_Customer_SKU_Changes__c > lst_sku = new List<Ace_Customer_SKU_Changes__c >();
        Ace_Customer_SKU_Changes__c ace3 = new Ace_Customer_SKU_Changes__c(SKU__c = '123456',status__c='Active',batchId__c='abc',Item_3_Month_Qty__c=12.12,Item_6_Month_Qty__c=12.12,Item_9_Month_Qty__c=12.12,Item_6_Month_Sales__c=12.12,Item_3_Month_Sales__c=12.12,
                        Item_9_Month_Sales__c=12.12,Total_Spend_Impact_3_Month__c=12.12,Total_Spend_Impact_6_Month__c=12.12,Total_Spend_Impact_9_Month__c=12.12,Item_12_Month_Qty__c = 50,Item_12_Month_Sales__c=12.12,Total_Spend_Impact_12_Month__c=123.12,name='test', Ace_Customer_Core_Changes__c = ace2.id);
        insert ace3;
        
                                          
        
        
        
                                                             
        ApexPages.currentPage().getParameters().put('searchWord','TEst');
        ApexPages.currentPage().getParameters().put('batch','batch1');
        ApexPages.currentPage().getParameters().put('selectedCustomer',acc.id);       
        ApexPages.currentPage().getParameters().put('selectedCustomerName',acc.name);
        ACE_Customer_List ACECustomerListCls = new ACE_Customer_List();
        ACECustomerListCls.searchText = 'Testing';
        ACECustomerListCls.skuFilterSelection = 'Verified';
        ACECustomerListCls.OwnerValue = 'Owned by others';
        ACECustomerListCls.renderUpload();
        ACECustomerListCls.findskus();
        ACECustomerListCls.SkunextPage();
        ACECustomerListCls.getskuDisableNext();
        
        ACECustomerListCls.SkuprevPage();
        ACECustomerListCls.getskuDisablePrevious();
        ACECustomerListCls.SearchRecords();

        test.startTest();        
        //sorting
        ACECustomerListCls.sortCust();
        ACECustomerListCls.getFieldName = 'Customer';
        ACECustomerListCls.sortCust();
        ACECustomerListCls.getFieldName = 'Cores';
        ACECustomerListCls.sortCust();
        ACECustomerListCls.getFieldName = 'effectiveDate';
        ACECustomerListCls.sortCust();
        ACECustomerListCls.getFieldName = 'notifydate';
        ACECustomerListCls.sortCust();
        ACECustomerListCls.getFieldName = 'customerid';
        ACECustomerListCls.sortCust();        
        ACECustomerListCls.getFieldName = 'notifStatus';
        ACECustomerListCls.sortCust();
        ACECustomerListCls.getFieldName = 'pricechangestatus';
        ACECustomerListCls.sortCust();
        ACECustomerListCls.getFieldName = 'sfdcBucket';
        ACECustomerListCls.sortCust();
        
        
        
        //end sorting
        
        ACECustomerListCls.releaseEarly();
        ACECustomerListCls.processSelected();
        
       
        ACECustomerListCls.ApproveRec();
        ACECustomerListCls.RejectRec();
        Test.StopTest();
    }
    }
}