objects/Account.object
<CustomObject>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Primary_BillTo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary BillTo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Site</fullName>
    </fields>
    <recordTypes>
        <fullName>Site</fullName>
        <active>true</active>
        <label>Site</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/AOPS_Flag__c.object
<CustomObject>
    <label>AOPS Flags</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>AOPS Flag Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AOPS Flags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Customer_Transition__c.object
<CustomObject>
    <description>Object to Track Customer Conversion and Review Project</description>
    <fields>
        <fullName>AOPS_Flag__c</fullName>
        <label>AOPS Flag</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Key__c</fullName>
        <label>Bill To Key</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Ship_2_Bill_2_Code__c</fullName>
        <description>This is the code that is set from the delta file that indicates there is a OMX Bill 2 address available to use for the consignee/site address value.</description>
        <inlineHelpText>This is the code that is set from the delta file that indicates there is a OMX Bill 2 address available to use for the consignee/site address value.</inlineHelpText>
        <label>Ship 2 Bill 2 Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Customer Transition</label>
    <nameField>
        <label>Customer Transition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Transition</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Customer_Transition_Dtls__c.object
<CustomObject>
    <fields>
        <fullName>AOPS_Flag__c</fullName>
        <externalId>true</externalId>
        <label>AOPS Flag</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer_Transition_Dtls</relationshipLabel>
        <relationshipName>Customer_Transition_Dtls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Transition_ID__c</fullName>
        <label>Customer Transition ID</label>
        <referenceTo>Customer_Transition__c</referenceTo>
        <relationshipLabel>Customer Transition Details</relationshipLabel>
        <relationshipName>Customer_Transition_Dtls</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <description>OMX Primary Key for Consignee, Cost Center and PO</description>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Ship_2_Bill_2_Code__c</fullName>
        <description>Code from OMX concerning if the record is a ship2, bill2</description>
        <inlineHelpText>Code from OMX concerning if the record is a ship2, bill2</inlineHelpText>
        <label>Ship 2 Bill 2 Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Customer Transition Details</label>
    <nameField>
        <displayFormat>CTD-{000000000}</displayFormat>
        <label>CTD Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Transition Details</pluralLabel>
    <recordTypes>
        <fullName>Sites</fullName>
        <active>true</active>
        <label>Sites</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Split_Account_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Transition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Customer Transition</label>
        <referenceTo>Customer_Transition__c</referenceTo>
        <relationshipLabel>Split Account Details</relationshipLabel>
        <relationshipName>Split_Account_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Master_Account__c</fullName>
        <label>NEW OMX ACCOUNT #</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NEW_BILL_TO_OMX_CONSIGNEE__c</fullName>
        <label>NEW BILL TO OMX CONSIGNEE #</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Split Account Detail</label>
    <nameField>
        <label>Split Account Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Split Account Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Mod5BillToKeyClass.cls
public class Mod5BillToKeyClass {

public void Mod5BillToKeyClassMethod(Set<ID> custTransId, List<Customer_Transition__c> trgCTList )
    {

     Map<Id,String> maphiersplit= new Map<Id,String>();
     Id Site = Schema.SObjectType.Customer_Transition_Dtls__c.getRecordTypeInfosByName().get('Sites').getRecordTypeId();
     List<Customer_Transition_Dtls__c> CTDtls= new  List<Customer_Transition_Dtls__c> ();
    set<String> omx = new set<String>();

       
   // get the transition detail records where Billing code is B  
   if(custTransId.size()>0){
   
   for(Split_Account_Detail__c split: [select Id,Master_Account__c from Split_Account_Detail__c where Customer_Transition__c in:custTransId  and
     (NEW_BILL_TO_OMX_CONSIGNEE__c='' or NEW_BILL_TO_OMX_CONSIGNEE__c=null)]){
       if(!omx.contains(split.Master_Account__c ))
       omx.add(split.Master_Account__c);
     }
     
   
   
              CTDtls = [Select id, Customer_Transition_ID__c,Customer_Transition_ID__r.Id,omx_primary_key__C,
              Account_ID__r.Primary_BillTo__C 
              from Customer_Transition_Dtls__c 
              where Customer_Transition_ID__c IN :custTransId  and
              
               ( Ship_2_Bill_2_Code__c ='B' or  Ship_2_Bill_2_Code__c ='SB' ) and
               AOPS_Flag__c ='Y' and 
                recordtypeId=:Site  order by Account_ID__r.Primary_BillTo__C   desc];
                         
               for(Customer_Transition_Dtls__c CTD:CTDtls )
               {                     
                            if(!maphiersplit.containsKey(CTD.Customer_Transition_ID__r.Id))
                            maphiersplit.put(CTD.Customer_Transition_ID__r.Id,CTD.omx_primary_key__C);
                         
                 
               }
       
       }
     
              for (Customer_Transition__c CT : trgCTList)
              {                 
                            if ((!maphiersplit.isEmpty()) && (maphiersplit.size()>0) && (maphiersplit.containsKey(CT.Id))){
                             if(!omx.contains(CT.omx_primary_key__C ))
                             CT.Bill_To_Key__c  = maphiersplit.get(CT.Id);
                            
                            }
                             
             }
    }
}