objects/Account.object
<CustomObject>
    <fields>
        <fullName>AOPS_Cust_Id__c</fullName>
        <description>AOPS Customer Account Number</description>
        <externalId>true</externalId>
        <label>AOPS Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>AOPS_Seq_ID__c</fullName>
        <externalId>true</externalId>
        <label>AOPS Seq ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Legacy_CreatedDate__c</fullName>
        <label>Legacy Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Legacy_LastModifiedDate__c</fullName>
        <label>Legacy Last Modified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Oracle_Party_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Party ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Phone_Ext__c</fullName>
        <description>Phone Extension</description>
        <label>Phone Ext.</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>(Tech-Zone)</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is used for Primary Owner Sales ID.</description>
        <label>Sales Person ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sales_Person__c.Primary__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Person__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_OMX_Primary_Key__c</fullName>
        <formula>Account.OMX_Primary_Key__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account OMX Primary Key</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Source__c</fullName>
        <label>Contact Source</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAST_ORDER_DATE_OF_CONTACT__c</fullName>
        <label>Last Order Date Of Contact</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>Language</description>
        <inlineHelpText>Language</inlineHelpText>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                    <default>true</default>
                    <label>English</label>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legacy_CreatedDate__c</fullName>
        <label>Legacy CreatedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Legacy_LastModifiedDate__c</fullName>
        <label>Legacy LastModifiedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <description>OMX Primary Key</description>
        <externalId>true</externalId>
        <inlineHelpText>OMX Primary Key</inlineHelpText>
        <label>OMX Primary Key</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Phone_Ext__c</fullName>
        <description>Phone Extension</description>
        <label>Phone1 Ext</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>Contact Role</description>
        <inlineHelpText>eBilling &amp; Account Payable contacts need to be added to iReceivables.</inlineHelpText>
        <label>Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounts Payable</fullName>
                </value>
                <value>
                    <fullName>CIO</fullName>
                </value>
                <value>
                    <fullName>eBilling</fullName>
                </value>
                <value>
                    <fullName>End User</fullName>
                </value>
                <value>
                    <fullName>Executive Level</fullName>
                </value>
                <value>
                    <fullName>IT Buyer</fullName>
                </value>
                <value>
                    <fullName>IT Decision Maker</fullName>
                </value>
                <value>
                    <fullName>IT Director</fullName>
                </value>
                <value>
                    <fullName>IT influencer</fullName>
                </value>
                <value>
                    <fullName>Price Change Approver</fullName>
                </value>
                <value>
                    <fullName>Price Change Notification/Viewer</fullName>
                </value>
                <value>
                    <fullName>Super User</fullName>
                </value>
                <value>
                    <fullName>Purchasing Manager</fullName>
                </value>
                <value>
                    <fullName>O/S Order Placer</fullName>
                </value>
                <value>
                    <fullName>Tech Order Placer</fullName>
                </value>
                <value>
                    <fullName>Frn Order Placer</fullName>
                </value>
                <value>
                    <fullName>Product Selector</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>Payment/Credit</fullName>
                </value>
                <value>
                    <fullName>Applicant</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Dotcom user</fullName>
                </value>
                <value>
                    <fullName>Receiver</fullName>
                </value>
                <value>
                    <fullName>Catalog</fullName>
                </value>
                <value>
                    <fullName>Certification</fullName>
                </value>
                <value>
                    <fullName>Partner Sales Rep</fullName>
                </value>
                <value>
                    <fullName>Tax Exemption</fullName>
                </value>
                <value>
                    <fullName>PO Report Recipient</fullName>
                </value>
                <value>
                    <fullName>Alibaba Buyer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SITE_OMX_Primary_Key__c</fullName>
        <label>SITE OMX Primary Key</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Salutation__c</fullName>
        <label>Salutation</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GTContact_Delta__c.object
<CustomObject>
    <description>This is used for the G&amp;T - Contact Delta</description>
    <fields>
        <fullName>Account_OMX_Primary_Key__c</fullName>
        <description>This is the Account OMX_Primary_Key to which the Contact has to be linked to</description>
        <label>Account_OMX_Primary_Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_OMX_primary_key__c</fullName>
        <description>This is the HFA Id of the contact</description>
        <label>Contact_OMX_primary_key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Source__c</fullName>
        <label>Contact Source</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Fax__c</fullName>
        <label>Fax</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Order_Date_Of_Contact__c</fullName>
        <label>Last Order Date Of Contact</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Legacy_CreatedDate__c</fullName>
        <label>Legacy CreatedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Legacy_LastModifiedDate__c</fullName>
        <label>Legacy LastModifiedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MailingCity__c</fullName>
        <label>MailingCity</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MailingCountry__c</fullName>
        <label>MailingCountry</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MailingPostalCode__c</fullName>
        <label>MailingPostalCode</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MailingState__c</fullName>
        <label>MailingState</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Ext__c</fullName>
        <label>Phone Ext</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Processed_Status__c</fullName>
        <description>This determines the Status of the Record Whether its Processed or not By Default its Open</description>
        <label>Processed Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Process Max</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SFDC_Id__c</fullName>
        <label>SFDC Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SITE_OMX_Primary_Key__c</fullName>
        <label>SITE OMX Primary Key</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Salutation__c</fullName>
        <label>Salutation</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>GTContact Delta</label>
    <nameField>
        <label>Last  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GTContact Delta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GNT_Contact_Batch_Test.cls
@isTest 

private class GNT_Contact_Batch_Test{
static testMethod void validate_GNT_Contact_Batch()
{
 GTContact_Delta__c gtc = new GTContact_Delta__c();
    gtc.name='Niraj';
    gtc.processed_status__c='Open';
    gtc.Account_OMX_Primary_Key__c='NZE-11051';
    gtc.Contact_OMX_primary_key__c='NZE-10051';         
 insert gtc; 
 
 GTContact_Delta__c gtc1 = new GTContact_Delta__c();
    gtc1.name='Abha';
    gtc1.processed_status__c='Error';
    gtc1.Account_OMX_Primary_Key__c='NZE-12451';
    gtc1.Contact_OMX_primary_key__c='NZE-12451';         
 insert gtc1; 
 
  GTContact_Delta__c gtcMAX = new GTContact_Delta__c();
    gtcMAX.name='Test Contact';
    gtcMAX.processed_status__c='Open';
    gtcMAX.Account_OMX_Primary_Key__c='NZE-11051';
    gtcMAX.Contact_Source__c= 'MAX'  ;      
 insert gtcMAX ; 
 
 
 
 
 Account acc= new Account();
        acc.OMX_Primary_Key__c='NZE-11051';
      //  acc.Related_Account__c=
        acc.name = 'SUN Test Account';
        acc.BillingStreet = '1040 N 326 W';
        acc.billingcity = 'Orem';
        acc.BillingState = 'UT';
        acc.Billingcountry = 'USA';
        acc.Oracle_Party_Id__c = '123456';
        acc.AOPS_Cust_Id__c = '123456';
        acc.AOPS_Seq_ID__c = '123456';
        acc.OwnerID = '005E0000000lNbV';// This is the salesforce User ID
        acc.Sales_PersonID__c = 'a0AE0000000GGMn'; //Sales person Id for the Salesforce USer   
 insert acc;
 
  Account acc1= new Account();
        acc1.OMX_Primary_Key__c='NZE-11000';
        acc1.Related_Account__c=acc.id;
        acc1.name = 'SUN Test Account';
        acc1.BillingStreet = '1040 N 326 W';
        acc.billingcity = 'Orem';
        acc1.BillingState = 'UT';
        acc1.Billingcountry = 'USA';
       
      //  acc.OwnerID = '005E0000000lNbV';// This is the salesforce User ID
       // acc1.Sales_PersonID__c = 'a0AE0000000GGMn'; //Sales person Id for the Salesforce USer   
 insert acc1;
 
 GTContact_Delta__c gtc9 = new GTContact_Delta__c();
    gtc9.name='Nirajabc';
    gtc9.SFDC_Id__c =''; 
    gtc9.processed_status__c='Process Max';
    gtc9.Account_OMX_Primary_Key__c='NZE-11000';
    gtc9.Contact_OMX_primary_key__c='NZE-12441';         
 insert gtc9;
 
 Contact con = new Contact();
    con.lastname='Sinha';
    con.OMX_Primary_Key__c='NZE-10051';
    con.AccountId = acc.id;                
 insert con;
 
 Contact con1 = new Contact();
    con1.lastname='Rani';
    con1.OMX_Primary_Key__c='NZE-12451';
    con1.AccountId = acc.id;                
 insert con1;
 Contact con2 = new Contact();
    con2.lastname='Rani';
    con2.OMX_Primary_Key__c='NZE-12441';
    con2.AccountId = acc.id;                
// insert con2;
 
 
 
 GTContact_Delta__c gtc2 = new GTContact_Delta__c();
    gtc2.name='Niraj';
    gtc2.SFDC_Id__c =''; 
    gtc2.processed_status__c='Open';
    gtc2.Account_OMX_Primary_Key__c='NZE-11051';
    gtc2.Contact_OMX_primary_key__c='NZE-12441';         
 insert gtc2;
 
 GTContact_Delta__c gtc3 = new GTContact_Delta__c();
    gtc3.name='Niraj';
    gtc3.SFDC_Id__c =con1.id; 
    gtc3.processed_status__c='Open';
    gtc3.Account_OMX_Primary_Key__c='NZE-11051';
    gtc3.Contact_OMX_primary_key__c='NZE-12441';         
 insert gtc3;  
 
 account acc2= new account();
 acc2.OMX_Primary_Key__c='NZE-11251';
        acc2.name = 'SUN Test account';
        acc2.BillingStreet = '1040 N 326 W';
        acc2.billingcity = 'Orem';
        acc2.BillingState = 'UT';
        acc2.Billingcountry = 'USA';
        acc2.Oracle_Party_Id__c = '1234567';
        acc2.AOPS_Cust_Id__c = '1234567';
        acc2.AOPS_Seq_ID__c = '1234567';
        acc2.OwnerID = '005E0000000lNbV';// This is the salesforce User ID
        acc2.Sales_PersonID__c = 'a0AE0000000GGMn'; //Sales person Id for the Salesforce USer
   
 insert acc2;
 
 
 /*Contact con2 = new Contact();
    con2.lastname='Sinha';
    con2.OMX_Primary_Key__c=null;
    con2.AccountId = acc2.id;                  
 insert con2;*/
 
 
 
        Datetime dt = System.now();
        String scheduleString='0';
        scheduleString+=' '+ dt.minute();
        scheduleString+=' '+ dt.hour();
        scheduleString+=' '+ dt.day();
        scheduleString+=' '+ dt.month();
        scheduleString+=' ?';
        scheduleString+=' '+ dt.year();     
        System.debug('currently scheduled.' + scheduleString); 

        String CRON_EXP = '0 0 0 3 9 ? 2022';    
           
       String QURY = 'SELECT Id, Name,Site_OMX_primary_key__c,Contact_OMX_primary_key__c, '+
     'LastActivityDate, Title__c, MailingCountry__c, MailingState__c, '+
     'MailingCity__c, Street__c, MailingPostalCode__c, Email__c, Phone__c, Phone_Ext__c, Fax__c, First_Name__c, Legacy_LastModifiedDate__c, '+
     'Legacy_CreatedDate__c, Account_OMX_Primary_Key__c,  Last_Order_Date_Of_Contact__c, Salutation__c, Language__c, Role__c, '+
     'Email_Permission_Flag_c__c, SFDC_Id__c, Error_Message__c,Contact_Source__c, ContactStatus__c, Processed_Status__c from GTContact_Delta__c '+
     'where Processed_Status__c!=\'Processed\'';
     
     
Test.startTest();
GNT_Contact_Batch gcb2=new GNT_Contact_Batch();
GNT_Contact_Batch gcb1=new GNT_Contact_Batch('');
GNT_Contact_Batch gcb=new GNT_Contact_Batch(QURY);
database.executebatch(gcb, 100);
System.schedule('Assignment error Batch',CRON_EXP , gcb);
Test.stopTest();



}
}