objects/Account.object
<CustomObject>
    <fields>
        <fullName>AOPS_Cust_Id__c</fullName>
        <description>AOPS Customer Account Number</description>
        <externalId>true</externalId>
        <label>AOPS Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>AOPS_Seq_ID__c</fullName>
        <externalId>true</externalId>
        <label>AOPS Seq ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>USA</fullName>
                    <default>true</default>
                    <label>USA</label>
                </value>
                <value>
                    <fullName>CAN</fullName>
                </value>
                <value>
                    <fullName>MEX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Oracle_Party_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Party ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Oracle_Party_Site_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Party Site ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Primary_Product__c</fullName>
        <description>This field is used to identify the difference between the MPS Prospect and Others</description>
        <label>Primary Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All Supplies</fullName>
                </value>
                <value>
                    <fullName>CBS</fullName>
                </value>
                <value>
                    <fullName>CPD-Print</fullName>
                </value>
                <value>
                    <fullName>CPD-Promo</fullName>
                </value>
                <value>
                    <fullName>Furniture</fullName>
                </value>
                <value>
                    <fullName>Ink &amp; Toner</fullName>
                </value>
                <value>
                    <fullName>Paper</fullName>
                </value>
                <value>
                    <fullName>MPS</fullName>
                </value>
                <value>
                    <fullName>Tech</fullName>
                </value>
                <value>
                    <fullName>Filing &amp; Binding</fullName>
                </value>
                <value>
                    <fullName>Labels &amp; Forms</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>Office Essentials</fullName>
                </value>
                <value>
                    <fullName>Writing &amp; Drafting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is used for Primary Owner Sales ID.</description>
        <label>Sales Person ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sales_Person__c.Primary__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Person__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>UT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip/Postal Code</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Data_Staging_Table__c.object
<CustomObject>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_2__c</fullName>
        <label>Address Line 2</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Email__c</fullName>
        <label>Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_First_Name__c</fullName>
        <label>Contact First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Last_Name__c</fullName>
        <label>Contact Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Phone__c</fullName>
        <label>Contact Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>This holds the County Filed form the Prospect  and the data will be feed by the Template Prospect upload</description>
        <label>Country</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OMX_Rep_Number__c</fullName>
        <label>OMX Rep #</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Amount__c</fullName>
        <label>Opportunity Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <label>Opportunity Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Stage__c</fullName>
        <label>Opportunity Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1%-Qualifying Prospect</fullName>
                </value>
                <value>
                    <fullName>10%-Appointment Secured</fullName>
                </value>
                <value>
                    <fullName>25%-Initial Approach</fullName>
                </value>
                <value>
                    <fullName>50%-Presentation</fullName>
                </value>
                <value>
                    <fullName>75%-Negotiate &amp; Finalize</fullName>
                </value>
                <value>
                    <fullName>90%-Execute</fullName>
                </value>
                <value>
                    <fullName>100%-Won</fullName>
                </value>
                <value>
                    <fullName>0%-Lost</fullName>
                </value>
                <value>
                    <fullName>0%-Walkaway</fullName>
                </value>
                <value>
                    <fullName>0%-Duplicate/Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Product__c</fullName>
        <label>Primary Product</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Probability__c</fullName>
        <label>Probability</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SalesRepID__c</fullName>
        <description>This hold the SalesRep ID from the Prospect upload template - OfficeDepot ex: IS20116</description>
        <label>SalesRepID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WCW_Count__c</fullName>
        <label>WCW Count</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <label>Data Staging Table</label>
    <nameField>
        <label>Data Staging Table Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Staging Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Amount__c</fullName>
        <formula>IF(RecordTypeId == $Label.Opportunity_GT_Record_Type || RecordTypeId == $Label.Opportunity_GTCompuComReferral, Amount_CAD__c , Amount )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Person__c.object
<CustomObject>
    <fields>
        <fullName>ExtIDSalesPerson__c</fullName>
        <externalId>true</externalId>
        <label>ExtIDSalesPerson</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Person_IDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Person ID</label>
    <nameField>
        <label>Sales Person ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Person IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>OD_Employee_ID__c</fullName>
        <externalId>true</externalId>
        <label>OD Employee ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OMX_Rep_Number__c</fullName>
        <description>the legacy OfficeMax 4 digit rep number from mainframe (n_srep)</description>
        <externalId>true</externalId>
        <label>OMX Rep #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ProspectUpload_Batch_OD_TC.cls
@isTest()
private class ProspectUpload_Batch_OD_TC 
{
   static testMethod void ProspectUpload_Batch_OD_TC()
   {
       System.runAs(new user(ID = UserInfo.getUserID())){
   
      Profile p = [SELECT Id FROM profile WHERE name='System Administrator'];
       User us1 = new User(alias = 'us_1',OMX_Rep_Number__c='9876', email='proxy@proxy1456.officedepot.com',OD_Employee_ID__c='113456',emailencodingkey='UTF-8', lastname='lastnam1',languagelocalekey='en_US',localesidkey='en_US', profileid = p.Id,timezonesidkey='America/Los_Angeles',username='12proxy@proxy456.com');
       insert us1;
       
       system.runas(us1)
       {
           
       
      
         Sales_Person__c testsalesper= new Sales_Person__c();
       testsalesper.ExtIDSalesPerson__c='9876';
       testsalesper.Primary__c=true;
       testsalesper.IsActive__c=true;
       testsalesper.Name='271991';
       testsalesper.user__c=us1.id;
       
          
       insert testsalesper;
          
        Account acct = new Account ();
        acct.name = 'SUN Test Account';
        acct.BillingStreet = '1040 N 326 W';
        acct.billingcity = 'Orem';
        acct.BillingState = 'UT';
        acct.Billingcountry = 'USA';
        acct.Oracle_Party_Id__c = '1234563456';
        acct.Oracle_Party_Site_Id__c = '1234563456';
        acct.AOPS_Cust_Id__c = '123456';
        acct.AOPS_Seq_ID__c = '127456';
        acct.OwnerID = us1.id;// This is the salesforce User ID
        //acc.Sales_PersonID__c = 'a0AE0000000GGMn'; //Sales person Id for the Salesforce USer
      //  acct.Sales_PersonID__c =testsalesper.id;
        insert acct;
           
        Test.startTest();
                
       Data_Staging_Table__c testdata= new Data_Staging_Table__c();
       testdata.SalesRepID__C='271991';
       testdata.name='271991';
       testdata.OMX_Rep_Number__c='9876';
       testdata.Company_Name__c='Office max pros1';
       testdata.Website__c='http://www.test.com';
       testdata.WCW_Count__c=18;
       testdata.Address_Line_1__c='Test add';
       testdata.Address_Line_2__c='test add1';
       testdata.City__c='Test city';
       testdata.State__c='AL';
       testdata.Country__c='CAN';
       testdata.Zip__c='76543';
       testdata.Contact_First_Name__c='Office max First name1';
       testdata.Contact_Last_Name__c='office max last name1';
       testdata.Contact_Phone__c='8765456765';
       testdata.Contact_Email__c='abc@abc.com';
       testdata.Opportunity_Name__c='office max opp1';
       testdata.Primary_Product__c='CBS';
       testdata.Opportunity_Amount__c=25345;
       testdata.Probability__c=75;
       testdata.Opportunity_Stage__c='25%-Initial Approach';
       testdata.Primary_Competitor__c='Office depot1';
       testdata.Anticipated_Close_Date__c=System.now().date();
       testdata.Customer_Lifecycle__c='Acquisition';
       testdata.OMX_Primary_Key__c='test';
       testdata.Notes__c='This is to test if the note gets related to the opportunity that is inserted from here.';
       testdata.Status__c='OD Not Started';
       
      insert testdata;
       
       
       
      /* List <Data_Staging_Table__c> lstdatastaging = new List<Data_Staging_Table__c>();
       for(Data_Staging_Table__c test2:lstdatastaging)
       {
       test2.OMX_Primary_Key__c=null;
       test2.Company_Name__c='Wipro';
       test2.Address_Line_1__c='bhyter';
       test2.City__c='noida';
       test2.State__c='UP';
       test2.Zip__c='uty';
       }
       lstdatastaging.add(test2) ;
       */
       
      //List<Data_Staging_Table__c> lstdatastaging = new List<Data_Staging_Table__c>();
       
    //  lstdatastaging 
       
       
     //  Data_Staging_Table__c testdata1 = new Data_Staging_Table__c();
      // testdata.SalesRepID__C='testingtesting';
       //testdata.name='';
      // testdata1.Company_Name__c='';
       //testdata1.OMX_Primary_Key__c=null;
       //lstdatastaging.add(testdata);
       //insert testdata1;
       
      // Data_Staging_Table__c testdata2 = new Data_Staging_Table__c();
      /*Data_Staging_Table__c testdata2 = new Data_Staging_Table__c();

       testdata2.Contact_Last_Name__c='sinha';
       lstdatastaging.add(testdata2);
             
       
       Data_Staging_Table__c testdata3 = new Data_Staging_Table__c();
       testdata3.OMX_Primary_Key__c='twoiu';
       testdata3.OMX_Rep_Number__c='9876';
       lstdatastaging.add(testdata3);*/
          // if(!lstdatastaging.isempty()){
       //update lstdatastaging;
           }
       
       
       
       string CRON_EXP= '0 0 0 3 9 ? 2022'; 
       String s = 'Select Id, SalesRepID__C, Company_Name__c, Website__c, WCW_Count__c, Sector__c, Buying_Group__C, Segment__C, Error__c,'+
    'Address_Line_1__c, Address_Line_2__c, City__c, State__c, Zip__c, Country__c, Contact_First_Name__c, Contact_Last_Name__c, Contact_Title__c,'+
    'Contact_Phone__c,Contact_Email__c, Pricing_template_cd__c, Industry_OD_SIC_Rep__c, Primary_Product__c, Primary_Competitor__c, Anticipated_Close_Date__c,'+
    'Customer_Lifecycle__c, Status__c,ProspectID__c from Data_Staging_Table__c where Status__c = \'OD Not Started\' ';
       
       ProspectUpload_Batch_OD assignBatch = new ProspectUpload_Batch_OD();
       assignBatch.strQuery =s;
       database.executebatch(assignBatch, 1); 
      
       System.schedule('AssignmentBatch1',CRON_EXP , assignBatch);
   
      ProspectUpload_Batch_OD assignBatch1 = new ProspectUpload_Batch_OD(s);
       System.schedule('Assignment Batch',CRON_EXP , assignBatch1);
       database.executebatch(assignBatch1, 1); 
       Test.stopTest();
   } 
   }
                    }