objects/Account.object
<CustomObject>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Related_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>(Tech-Zone)</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site</fullName>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer Accounts</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Site</fullName>
        <active>true</active>
        <label>Site</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Customer_Transition__c.object
<CustomObject>
    <description>Object to Track Customer Conversion and Review Project</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Transition Relationship</relationshipLabel>
        <relationshipName>Customer_Transition_Relationship</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cascade_Down__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cascade Transition Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field will update dynamically per your selections.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>UnScheduled</fullName>
                    <color>#0B6FCE</color>
                    <default>true</default>
                    <label>UnScheduled</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                    <color>#78C953</color>
                    <label>Scheduled</label>
                </value>
                <value>
                    <fullName>ReScheduled</fullName>
                    <color>#E27001</color>
                    <label>ReScheduled</label>
                </value>
                <value>
                    <fullName>On Deck</fullName>
                    <color>#F3D904</color>
                    <label>On Deck</label>
                </value>
                <value>
                    <fullName>Launched</fullName>
                    <color>#009900</color>
                    <label>Launched</label>
                </value>
                <value>
                    <fullName>Transition Complete</fullName>
                    <color>#A53711</color>
                    <label>Transition Complete</label>
                </value>
                <value>
                    <fullName>Audit 2</fullName>
                    <color>#66E9BD</color>
                    <label>Audit 2</label>
                </value>
                <value>
                    <fullName>Loss of Customer</fullName>
                    <color>#0B24BE</color>
                    <label>Loss of Customer</label>
                </value>
                <value>
                    <fullName>OMX Extension in Development</fullName>
                    <color>#419249</color>
                    <label>OMX Extension in Development</label>
                </value>
                <value>
                    <fullName>Ready to Order</fullName>
                    <color>#B6E32E</color>
                    <label>Ready to Order</label>
                </value>
                <value>
                    <fullName>Ready for eCom Mod</fullName>
                    <color>#641CCF</color>
                    <label>Ready for eCom Mod</label>
                </value>
                <value>
                    <fullName>Redirect Stopped</fullName>
                    <color>#F96FB7</color>
                    <label>Redirect Stopped</label>
                </value>
                <value>
                    <fullName>Auto Redirected</fullName>
                    <color>#2F5D85</color>
                    <label>Auto Redirected</label>
                </value>
                <value>
                    <fullName>Awaiting Disposition</fullName>
                    <color>#AFCADF</color>
                    <label>Awaiting Disposition</label>
                </value>
                <value>
                    <fullName>Awaiting RFP</fullName>
                    <color>#8F6429</color>
                    <label>Awaiting RFP</label>
                </value>
                <value>
                    <fullName>Administrative Close</fullName>
                    <color>#EFAE73</color>
                    <label>Administrative Close</label>
                </value>
                <value>
                    <fullName>TOOP</fullName>
                    <color>#F96FB7</color>
                    <label>TOOP</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Transition</label>
    <nameField>
        <label>Customer Transition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Transition</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Split_Account_Detail__c.object
<CustomObject>
    <fields>
        <fullName>AP_CONTACT_FIRST_NAME__c</fullName>
        <label>AP CONTACT FIRST NAME</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AP_CONTACT_LAST_NAME__c</fullName>
        <label>AP CONTACT LAST NAME</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AP_CONTACT_TELEPHONE__c</fullName>
        <label>AP CONTACT TELEPHONE #</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Customer_Transition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Customer Transition</label>
        <referenceTo>Customer_Transition__c</referenceTo>
        <relationshipLabel>Split Account Details</relationshipLabel>
        <relationshipName>Split_Account_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Main_Account_Name__c</fullName>
        <label>NEW ACCOUNT NAME</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_Account__c</fullName>
        <label>NEW OMX ACCOUNT #</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NEW_BILLING_TYPE_AT_HEADER_LEVEL__c</fullName>
        <label>NEW BILLING TYPE AT HEADER LEVEL</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NEW_BILL_TO_OMX_CONSIGNEE__c</fullName>
        <label>NEW BILL TO OMX CONSIGNEE #</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NEW_MAIN_ACCT_ADDRESS__c</fullName>
        <label>NEW MAIN ACCT ADDRESS</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Original_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Split Account Details</relationshipLabel>
        <relationshipName>Split_Account_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Split Account Detail</label>
    <nameField>
        <label>Split Account Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Split Account Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/afterTriggerSplitDEtails_TC.cls
@isTest
public class afterTriggerSplitDEtails_TC
{
    static testMethod void afterTriggerSplitDEtails_Test() 
    {
    
    Account acc = new Account(Name='Test_Acc',OMX_Primary_Key__c='123458');
    
      Id SiteOMX = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Site (OfficeMax)').getRecordTypeId();
    insert acc;
    Account site = new Account(Name='Test_Acc',OMX_Primary_Key__c='123456',recordtypeid=SiteOMX,Related_Account__c=acc.id);
    
    insert site;
    Customer_Transition__c ctRec = new Customer_Transition__c(name='Customer Transition of Test_Acc', 
         Account__c = acc.id, Cascade_down__c = true,OMX_Primary_Key__c='123458' );
    insert ctRec;
    Split_Account_Detail__c eachCTdtls = new Split_Account_Detail__c();
    eachCTdtls.status__c='';
    eachCTdtls.Master_Account__c ='123458-01';
    eachCTdtls.Customer_Transition__c =ctRec.id;
    eachCTdtls.AP_CONTACT_FIRST_NAME__c ='First';
    eachCTdtls.AP_CONTACT_LAST_NAME__c ='Last';
    eachCTdtls.NEW_BILLING_TYPE_AT_HEADER_LEVEL__c ='Di';
    eachCTdtls.Original_Account__c = acc.id;
    eachCTdtls.AP_CONTACT_TELEPHONE__c ='12345698789';
    eachCTdtls.NEW_BILL_TO_OMX_CONSIGNEE__c = '123456';
    eachCTdtls.NEW_MAIN_ACCT_ADDRESS__c = '123456';
    eachCTdtls.Main_Account_Name__c ='New Name';
    
    
    insert eachCTdtls;
    eachCTdtls.Master_Account__c ='123458';
    eachCTdtls.status__c='Uploaded';
    update eachCTdtls;
    }
}