objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tier_1_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relationship to a Tier 1 Partner in the Tier 1 Object</description>
        <label>Diversity Partner / Reseller</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Partner Customer Detail</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>YTD_Sales_TY__c</fullName>
        <description>Current Year Sales</description>
        <label>YTD Sales TY</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <description>Partner Layout for Onboarding Partners</description>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>IMU__c</fullName>
        <label>IMU%</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opportunity_Amount__c</fullName>
        <formula>IF(RecordTypeId == $Label.Opportunity_GT_Record_Type || RecordTypeId == $Label.Opportunity_GTCompuComReferral, Amount_CAD__c , Amount )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>All Supplies</fullName>
                </value>
                <value>
                    <fullName>Asset Management</fullName>
                </value>
                <value>
                    <fullName>CBFS</fullName>
                </value>
                <value>
                    <fullName>CBS/Facilities</fullName>
                </value>
                <value>
                    <fullName>Contract Furniture</fullName>
                </value>
                <value>
                    <fullName>Email Marketing</fullName>
                </value>
                <value>
                    <fullName>Ergonomics</fullName>
                </value>
                <value>
                    <fullName>Facilities- Coffee</fullName>
                </value>
                <value>
                    <fullName>Filing &amp; Binding</fullName>
                </value>
                <value>
                    <fullName>Furniture - Catalog</fullName>
                </value>
                <value>
                    <fullName>Furniture - Interiors</fullName>
                </value>
                <value>
                    <fullName>General Consultation</fullName>
                </value>
                <value>
                    <fullName>Ink &amp; Toner</fullName>
                </value>
                <value>
                    <fullName>Instructional Solutions</fullName>
                </value>
                <value>
                    <fullName>K-12 Growth</fullName>
                </value>
                <value>
                    <fullName>Labels &amp; Forms</fullName>
                </value>
                <value>
                    <fullName>Legal Services</fullName>
                </value>
                <value>
                    <fullName>Logo Design</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>MPS</fullName>
                </value>
                <value>
                    <fullName>Multi-Category</fullName>
                </value>
                <value>
                    <fullName>Office Essentials</fullName>
                </value>
                <value>
                    <fullName>Office Products</fullName>
                </value>
                <value>
                    <fullName>Office Supplies</fullName>
                </value>
                <value>
                    <fullName>Paper</fullName>
                </value>
                <value>
                    <fullName>Print and Promo</fullName>
                </value>
                <value>
                    <fullName>Print Services</fullName>
                </value>
                <value>
                    <fullName>School Supplies</fullName>
                </value>
                <value>
                    <fullName>Search Marketing</fullName>
                </value>
                <value>
                    <fullName>SEO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Partner__c.object
<CustomObject>
    <description>This oject will contain a list of Tier 1 Partner which includes woman owned, verteran owned etc . . .</description>
    <fields>
        <fullName>Opportunity_Amount__c</fullName>
        <description>Aggregate Opportunity Amount associated to the accounts associated to the partner</description>
        <label>Opportunity Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>YTD_Sales_TY__c</fullName>
        <description>YTD_Sales_TY</description>
        <label>YTD Sales TY</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Diversity Partner / Reseller</label>
    <nameField>
        <label>Diversity Partner / Reseller Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Diversity Partners / Resellers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Tier1_Extension.cls
public class Tier1_Extension {
    
    private final Partner__c partner = null;
    
    public List<Opportunity> lstAccountOpportunities {get;set;}

      public Tier1_Extension(ApexPages.StandardController controller) {
          partner = (Partner__c)controller.getRecord();
          lstAccountOpportunities = LoadOpportunitiesForChildAccounts();
      }
  
  public List<Opportunity> LoadOpportunitiesForChildAccounts() {     
      return [SELECT id, AccountId, Account.Name, Name, StageName, Product__c, Opportunity_Amount__c, Account.YTD_SALES_TY__c, IMU__c, Owner.Name, LastModifiedDate
              FROM opportunity 
              Where Account.Tier_1_Partner__c = :partner.ID
              and Status__c = 'Open'
             Order by AccountId, Opportunity_Amount__c Desc ];
  }
 
}