objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Owner__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; 
&amp; Sales_PersonID__r.User__r.Id, 
Sales_PersonID__r.User__r.FirstName+&apos; &apos;+Sales_PersonID__r.User__r.LastName 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Owner</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer Accounts</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Account_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Account_Owner__c</fullName>
        <label>Account Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Profile</relationshipLabel>
        <relationshipName>Account_Profile1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Address_State__c</fullName>
        <label>Address State</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Profile_Unique_Name__c</fullName>
        <externalId>true</externalId>
        <label>Profile Unique Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Tax_Status__c</fullName>
        <label>Tax Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Account Profile</label>
    <nameField>
        <label>Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Profile</pluralLabel>
    <recordTypes>
        <fullName>TaxCertStatus</fullName>
        <active>true</active>
        <label>TaxCertStatus</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Unique_Acc_Profile_Name_TC.cls
@isTest
private class Unique_Acc_Profile_Name_TC
{
 static testMethod void UnitTest()
 {
        Schema.DescribeSObjectResult A_P_R = Schema.SObjectType.Account_Profile__c;
        Map<String,Schema.RecordTypeInfo> A_P_RMapByName = A_P_R.getRecordTypeInfosByName();
        Date TDy = System.today();
        Schema.DescribeSObjectResult AR = Schema.SObjectType.Account;
        Map<String,Schema.RecordTypeInfo> ARMapByName = AR.getRecordTypeInfosByName();
        
        Account acc = new Account ();
        acc.name = 'SUN Test Account';
        acc.BillingStreet = '1040 N 326 W';
        acc.billingcity = 'Orem';
        acc.BillingState = 'UT';
        acc.Billingcountry = 'USA';
        acc.recordtypeid= ARMapByName.get('Customer').getRecordTypeId();
        insert acc;

  Account_Profile__c AccPrf = new Account_Profile__c(Account__c=acc.id,
                                                     Account_Owner__c='abc',
                                                     RecordTypeId=A_P_RMapByName.get('MPS/Tech').getRecordTypeId());
     
     insert AccPrf;

 Account_Profile__c AP_tx = new Account_Profile__c(
       	Account__c=acc.id,
       	Account_Owner__c='abc',
       	RecordTypeId=A_P_RMapByName.get('TaxCertStatus').getRecordTypeId(),
       	Expiration_Date__c = TDy.addDays(6),
		Address_State__c = 'FL',
      	Country_Code__c = 'USA',
      	Tax_Status__c = 'A',
      	Profile_Unique_Name__c = null,
      	Name = 'Tax Certificate Status'       
       ); 
 insert AP_Tx;
     
     AP_tx.Profile_Unique_Name__c = AP_tx.RecordTypeId + '-' + AP_tx.Account__c + AP_tx.Address_State__c;  
     
 Delete AP_tx;     

//This record should create a Tax record but not create an email or a log record in log_object Day 365 out
  Account_Profile__c AP_Tx_Exp365 = new Account_Profile__c(
       	Account__c=acc.id,
       	Account_Owner__c='abc',
       	RecordTypeId=A_P_RMapByName.get('TaxCertStatus').getRecordTypeId(),
       	Expiration_Date__c = TDy.addDays(365),
		Address_State__c = 'SC',
      	Country_Code__c = 'USA',
      	Tax_Status__c = 'A',
      	Profile_Unique_Name__c = '^^',
      	Name = 'Tax Certificate Status'       
       ); 
 insert AP_Tx_Exp365;
     
     AP_Tx_Exp365.Profile_Unique_Name__c = AP_Tx_Exp365.RecordTypeId + '-' + AP_Tx_Exp365.Account__c + AP_Tx_Exp365.Address_State__c;
     
 Delete AP_Tx_Exp365;     
     
//This record should create a Tax record, an email and a log record in log_object Day 59 out     
     Account_Profile__c AP_Tx_Exp60 = new Account_Profile__c(
       	Account__c=acc.id,
       	Account_Owner__c='abc',
       	RecordTypeId=A_P_RMapByName.get('TaxCertStatus').getRecordTypeId(),
       	Expiration_Date__c = TDy.addDays(59),
		Address_State__c = 'FL',
      	Country_Code__c = 'USA',
      	Tax_Status__c = 'A',
      	Profile_Unique_Name__c = '^^',
      	Name = 'Tax Certificate Status'       
       ); 
  insert  AP_Tx_Exp60;
     
      AP_Tx_Exp60.Profile_Unique_Name__c = AP_Tx_Exp60.RecordTypeId + '-' + AP_Tx_Exp60.Account__c + AP_Tx_Exp60.Address_State__c;
     
  delete  AP_Tx_Exp60;     
     
//This record should create a Tax record, an email and a log record in log_object Day 29 out          
  Account_Profile__c AP_Tx_Exp30 = new Account_Profile__c(
       	Account__c=acc.id,
       	Account_Owner__c='abc',
       	RecordTypeId=A_P_RMapByName.get('TaxCertStatus').getRecordTypeId(),
       	Expiration_Date__c = TDy.addDays(29),
		Address_State__c = 'FL',
      	Country_Code__c = 'USA',
      	Tax_Status__c = 'A',
      	Profile_Unique_Name__c = '^^',
      	Name = 'Tax Certificate Status'       
       ); 
 insert AP_Tx_Exp30;
     
     AP_Tx_Exp30.Profile_Unique_Name__c = AP_Tx_Exp30.RecordTypeId + '-' + AP_Tx_Exp30.Account__c + AP_Tx_Exp30.Address_State__c;   
     
  delete  AP_Tx_Exp30;         
//This record should create a Tax record, an email and a log record in log_object Day 7 out       
    Account_Profile__c AP_Tx_Exp7 = new Account_Profile__c(
       	Account__c=acc.id,
       	Account_Owner__c='abc',
       	RecordTypeId=A_P_RMapByName.get('TaxCertStatus').getRecordTypeId(),
       	Expiration_Date__c = TDy.addDays(6),
		Address_State__c = 'FL',
      	Country_Code__c = 'USA',
      	Tax_Status__c = 'A',
      	Profile_Unique_Name__c = null,
      	Name = 'Tax Certificate Status'       
       ); 
 insert AP_Tx_Exp7;
     
     AP_Tx_Exp7.Profile_Unique_Name__c = AP_Tx_Exp7.RecordTypeId + '-' + AP_Tx_Exp7.Account__c + AP_Tx_Exp7.Address_State__c;  
     
 Delete AP_tx_Exp7;
//This record should create a similar type record but not create an email or a log record in log_object  Day 5 out 
    Account_Profile__c AP_Tx_Exp5 = new Account_Profile__c(
       	Account__c=acc.id,
       	Account_Owner__c='abc',
       	RecordTypeId=A_P_RMapByName.get('TaxCertStatus').getRecordTypeId(),
       	Expiration_Date__c = TDy.addDays(5),
		Address_State__c = 'FL',
      	Country_Code__c = 'USA',
      	Tax_Status__c = 'A',
      	Profile_Unique_Name__c = '^^',
      	Name = 'Tax Certificate Status'       
       ); 
 insert AP_Tx_Exp5;
     
     AP_Tx_Exp5.Profile_Unique_Name__c = AP_Tx_Exp5.RecordTypeId + '-' + AP_Tx_Exp5.Account__c + AP_Tx_Exp5.Address_State__c;  
  
 }
}