objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Account_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Profile</relationshipLabel>
        <relationshipName>Account_Profile1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account Profile</label>
    <nameField>
        <label>Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Profile</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Data_Load__c.object
<CustomObject>
    <fields>
        <fullName>Attribute10__c</fullName>
        <label>Attribute10</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute11__c</fullName>
        <label>Attribute11</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute12__c</fullName>
        <label>Attribute12</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute13__c</fullName>
        <label>Attribute13</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute14__c</fullName>
        <label>Attribute14</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute15__c</fullName>
        <label>Attribute15</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute16__c</fullName>
        <label>Attribute16</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute17__c</fullName>
        <label>Attribute17</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute18__c</fullName>
        <label>Attribute18</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute19__c</fullName>
        <label>Attribute19</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute1__c</fullName>
        <label>Attribute1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute20__c</fullName>
        <label>Attribute20</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute21__c</fullName>
        <label>Attribute21</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute24__c</fullName>
        <label>Attribute5</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute25__c</fullName>
        <label>Attribute25</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute26__c</fullName>
        <label>Attribute26</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute27__c</fullName>
        <label>Attribute27</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute28__c</fullName>
        <label>Attribute28</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute29__c</fullName>
        <label>Attribute29</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute2__c</fullName>
        <label>Attribute2</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute3__c</fullName>
        <label>Attribute3</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute4__c</fullName>
        <label>Attribute4</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute9__c</fullName>
        <label>Attribute9</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Data Load</label>
    <nameField>
        <label>Data Load Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Loads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/cpmDataLoad_Batch_TC.cls
@isTest

private class cpmDataLoad_Batch_TC
{

    static testMethod Void cpmDataLoad_Batch_TC()
    {
            Case cs = new Case();
            cs.Description='Test case';
            cs.Subject='Test';
            cs.Status='New';
            insert cs;
            
            Account acc = new Account();
            acc.Name='Test Account';
            insert acc;
            
            Schema.DescribeSObjectResult des = Schema.SObjectType.account_profile__c; 
            Map<String,Schema.RecordTypeInfo> accProRecMap= des.getRecordTypeInfosByName(); 
            Schema.RecordTypeInfo accProrecrdinfo = accProRecMap.get('CPM Data');
            Id CPMRecTypeId = accProrecrdinfo.getRecordTypeId();
            
            account_profile__c accPro = new account_profile__c();
            accPro.Account__c = acc.id;
            accPro.RecordTypeId = CPMRecTypeId;
            insert accPro;
            
            
            Data_Load__c DL = new   Data_Load__c();
            DL.Attribute1__c='3';
            DL.Attribute10__c='3';
            DL.Attribute11__c='3';
            DL.Attribute12__c='3';
            DL.Attribute13__c='3';
            DL.Attribute14__c='3';
            DL.Attribute15__c='3';
            DL.Attribute16__c='3';
            DL.Attribute17__c='3';
            DL.Attribute18__c='3';
            DL.Attribute19__c='3';
            DL.Attribute2__c='1/1/2013 05:08:37';
            DL.Attribute20__c='3';
            DL.Attribute21__c='3';
            DL.Attribute25__c='3';
            DL.Attribute26__c='3';
            DL.Attribute27__c='3';
            DL.Attribute28__c='3';
            DL.Attribute29__c='3';
            DL.Attribute3__c=acc.id;
            DL.Attribute4__c=cs.casenumber;
            DL.Attribute24__c='3';
            DL.Attribute9__c='3';
            insert DL;
            
            Account acc1 = new Account();
            acc1.Name='Test Account';
            insert acc1;
            
            Data_Load__c DL1 = new   Data_Load__c();
            DL1.Attribute3__c=acc1.id;
            DL1.Attribute2__c='1/1/2013 05:08:37';
            insert DL1;
            
            cpmDataLoad_Batch batch1 = new cpmDataLoad_Batch();
            database.executeBatch(batch1 );
            String expr = '0 0 0 4 5 ? 2020';  
            System.schedule('Batch',expr , batch1 );
            
    }

}