objects/Account.object
<CustomObject>
    <fields>
        <fullName>Filing_Binding_LY__c</fullName>
        <description>Binders Sales Last Year</description>
        <inlineHelpText>Binders Sales Last Year</inlineHelpText>
        <label>Filing &amp; Binding LY</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Filing_Binding_TY__c</fullName>
        <description>Binders Sales This Year</description>
        <inlineHelpText>Binders Sales This Year</inlineHelpText>
        <label>Filing &amp; Binding TY</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Office_Essentials_Pot__c</fullName>
        <description>Filing Storage Potential</description>
        <inlineHelpText>Filing Storage Potential</inlineHelpText>
        <label>Office Essentials Pot</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Paper_Pot__c</fullName>
        <description>Paper Potential</description>
        <inlineHelpText>Paper Potential</inlineHelpText>
        <label>Paper Pot</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tech_TY__c</fullName>
        <description>Technology Sales This Year</description>
        <inlineHelpText>Technology Sales This Year</inlineHelpText>
        <label>Tech TY</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_TY_Sales_to_Date__c</fullName>
        <formula>Filing_Binding_TY__c + CBS_TY__c + CPD_TY__c + Office_Essentials_TY__c + Furniture_TY__c + Ink_Toner_TY__c + Labels_Forms_TY__c + Paper_TY__c + Writing_Drafting_TY__c + Miscellaneous_TY__c + Tech_TY__c + MPS_TY__c + Contract_Furniture_TY__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total TY Sales to Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Test_FieldRVP_AccountProductData.cls
/**************************************************************
*Name           : Test_FieldRVP_AccountProductData 

********************************************************************/
@isTest
private class Test_FieldRVP_AccountProductData {
    @isTest 
    private static void testAccountProductDataExtension() {
    
     
             
        //List<User> Userwithregion_list = [SELECT Id, Name from User WHERE isactive= true AND region__c = 'Northeast' limit 1];
        Profile profilealias = [SELECT Id FROM profile WHERE name='System Administrator'];
        User Userwithregion= new User(alias = 'test123 ', email='proxy@officedepot.com',emailencodingkey='UTF-8', lastname='test123',languagelocalekey='en_US',localesidkey='en_US', profileid = profilealias.Id,timezonesidkey='America/Los_Angeles',username='proxy@proxy456.com',isactive= true,region__c = 'Northeast');
        insert Userwithregion;
            
      UserRole ContractDivisionRoleId = [SELECT Id from UserRole WHERE Name = 'Contract Division' limit 1];
//        User userWithContractDivisionRole = [SELECT Id, Name FROM User WHERE UserRoleId = :ContractDivisionRoleId.Id AND isActive = true limit 1];        
            Set<Id> stId = new Set<Id>();
            stId.add(ContractDivisionRoleId.Id);
            
            System.runAs(Userwithregion){
            Account account =  Test_Utils.CreateAccountForProductData();    
            Account account1 =  Test_Utils.CreateAccountForProductData();             
       
            FieldRVP_AccountProductDataExtension extension = new FieldRVP_AccountProductDataExtension();
       
            Test.startTest();
            extension.refresh(); 
            List<AggregateResult> aggregateResult =  extension.getAggregateResult();
            Set<id> st =extension.getAllSubOrdinateRoleID(stId) ;
            // Test that aggregate result is calculated for manager 
            //System.assertEquals((Double)aggregateResult[0].get('Office_Essentials_Pot__c'), 40);
         //   System.assertEquals((Double)aggregateResult[0].get('Total_TY_Sales_to_Date__c'), 970);
         //   System.assertEquals((Double)aggregateResult[0].get('Paper_TY'), 10);
         //   System.assertEquals((Double)aggregateResult[0].get('Filing_Binding_TY__c'), 40);
           // System.assertEquals((Double)aggregateResult[0].get('Total_Potential_to_Date'), 420);
        //    System.assertEquals((Double)aggregateResult[0].get('Tech_TY__c'), 600);
            //System.assertEquals((Double)aggregateResult[0].get('Paper_Pot__c'), 20);
        //    System.assertEquals((Double)aggregateResult[0].get('Filing_Binding_LY__c'), 40);
        //    System.assertEquals((Double)aggregateResult[0].get('Paper_LY'), 20);            
                    
            Test.stopTest();
        }
  }   
}