objects/Account.object
<CustomObject>
    <fields>
        <fullName>AOPS_Cust_Id__c</fullName>
        <description>AOPS Customer Account Number</description>
        <externalId>true</externalId>
        <label>AOPS Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Address1__c</fullName>
        <label>Address1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address2__c</fullName>
        <label>Address2</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Open_Opp_Amt__c</fullName>
        <label>Open Opp Amt</label>
        <summarizedField>Opportunity.Amount</summarizedField>
        <summaryFilterItems>
            <field>Opportunity.IsClosed</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Oracle_Party_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Party ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Payment_Term__c</fullName>
        <label>Payment Term</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Account Billing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip_5digit__c</fullName>
        <formula>TRIM(LEFT( Zip__c , 5))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Zip-5digit</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Account_Setup_Request__c.object
<CustomObject>
    <description>Test for click tools intergration</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Setup Request (Account Name)</relationshipLabel>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OPERATION__c</fullName>
        <defaultValue>&quot;I&quot;</defaultValue>
        <description>Automatic Account Setup Flag</description>
        <label>OPERATION</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ORACLE_PARTY_ID__c</fullName>
        <label>ORACLE PARTY ID</label>
        <length>48</length>
        <type>Text</type>
    </fields>
    <label>Account Setup Request</label>
    <nameField>
        <label>Account Setup Request</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Setup Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/API_Reports.cls
// This class contains web service methods thats called to return Account and Case Information
@RestResource(urlMapping='/api/Reports/*')
global class API_Reports {

    //This methods takes parameter on which report is needed and calls the method accordingly. Its a Get call
     @HttpGet
    global static List<sObject>  doGet() 
    {
         RestRequest req = RestContext.request;
         RestResponse res = RestContext.response;
         String ReportName = req.params.get('Report_Name');
         //for report GetLinkageAccountsByDateRange
         if(ReportName=='GetLinkageAccountsByDateRange')
         {
             Date FromDate = Date.Parse(req.params.get('FromDate'));
             Date ToDate   = Date.Parse(req.params.get('ToDate'));
             Return  API_Reports.GetLinkageAccountsByDateRange(FromDate,ToDate);
         }
        //for report GetLinkageAccountContactsByDateRange
         if(ReportName=='GetLinkageAccountContactsByDateRange')
         {
             Date FromDate = Date.Parse(req.params.get('FromDate'));
             Date ToDate   = Date.Parse(req.params.get('ToDate'));
             Return  API_Reports.GetLinkageAccountContactsByDateRange(FromDate,ToDate);
         }
         //for report GetCasesByTypeAndStatus       
         if(ReportName=='GetCasesByTypeAndStatus')
         {
             String QueueName = req.params.get('QueueName');
             String Type      = req.params.get('Type');
             String Status    = req.params.get('Status');
             Return  API_Reports.GetCasesByTypeAndStatus(QueueName,Status,Type);
         }
         
        Return null;
    }
    //This methods calls method to update Case Data .Its a Post call
    @HttpPost
    global static String UpdateCaseStatusById_Post(String Report_Name,String CaseId,String Status,String QueueName,String SupportComments) {
      
       if(Report_Name=='UpdateCaseStatusByID')
          Return API_Reports.UpdateCaseStatusByID(CaseId,Status,QueueName,SupportComments);
        
        Return Null;  
    }
    
    Public static List<Account> GetLinkageAccountsByDateRange(Date FromDate,Date ToDate) {
      Return [SELECT  Oracle_Party_ID__c,AOPS_Cust_Id__c,Name,Address1__c,Address2__c,City__c,State__c,
                      Zip_5digit__c,Open_Opp_Amt__c,
                      (SELECT Name FROM Accounts3__r 
                        WHERE (OPERATION__c = 'E') OR ( OPERATION__c ='S') 
                                                   OR ( OPERATION__c ='I')
                        ) 
             FROM account 
             WHERE Payment_Term__c='Account Billing' 
                 AND AOPS_Cust_Id__c != null 
                 AND Oracle_Party_ID__c != null 
                 AND CreatedDate >=:FromDate
                 AND CreatedDate<=:ToDate];
    }
   //This methods gets the linked Contracts for the account for a given range 
    Public static List<Account> GetLinkageAccountContactsByDateRange(Date FromDate,Date ToDate) {        
         Return [SELECT Oracle_Party_ID__c,AOPS_Cust_Id__c,Name,
                     (SELECT ContractNumber,Payment_Terms__c 
                       FROM Contracts) 
                 FROM account 
                 WHERE Payment_Term__c='Account Billing' 
                    AND AOPS_Cust_Id__c != null 
                    AND Oracle_Party_ID__c != null 
                    AND CreatedDate >=:FromDate
                    AND CreatedDate<=:ToDate];
                    
    }
    //This methods gets the Cases by queried Parameters   
    Public Static List<Case> GetCasesByTypeAndStatus(String sQueueName,String sStatus,String sType)
    {
        
        Return [SELECT CaseNumber,Type,Status,Subject,Description,Account.AOPS_Cust_Id__c,Support_Type__c,Support_Sub_Type__c 
                FROM Case 
                WHERE //Type=:sType
                 Status=:sStatus
                AND Ownerid IN (SELECT Id 
                              FROM Group 
                              WHERE  Type = 'Queue' 
                               AND NAME =:sQueueName)];
                
    }
     //This methods Updates the Case   
    Public Static  String UpdateCaseStatusByID(String CaseId,String sStatus,String sQueueName,String sSupportComments)
    {
      
        Set<String> sStatusProcess=New Set<String>{'New','Case Review','In Progress', 'Closed'};
        
        
        if((sQueueName=='AR Billing Bot Queue' || sQueueName=='AR Credit Queue') &&  !sStatusProcess.Contains(sStatus))
                  Return 'Not a Valid Input Status';   
        else
        {  
       
            List<Group> QueueId=[SELECT Id from Group WHERE Type = 'Queue' AND NAME =:sQueueName];
            
            
             if(QueueId.size()>0)
             {
                 Case C=[SELECT Id,Status,OwnerId
                        FROM Case 
                        WHERE Id=:CaseId];
                        
                 C.Status=sStatus;
                 C.OwnerId=QueueId[0].Id;
                 
                 Update C;
              
                 if(String.isNotEmpty(sSupportComments))
                 {
                        CaseComment CC=New CaseComment();
                        CC.CommentBody=sSupportComments;
                        CC.ParentId = C.Id;
                        Insert CC;
                     
                 }
            
             }
             else
                  Return 'Invalid Queue Name'; 
          }
         Return Null;
         
        
    }
}