objects/Account.object
<CustomObject>
    <fields>
        <fullName>AOPS_Cust_Id__c</fullName>
        <description>AOPS Customer Account Number</description>
        <externalId>true</externalId>
        <label>AOPS Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>AOPS_Seq_ID__c</fullName>
        <externalId>true</externalId>
        <label>AOPS Seq ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Oracle_Party_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Party ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Oracle_Party_Site_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Party Site ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sales_PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is used for Primary Owner Sales ID.</description>
        <label>Sales Person ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sales_Person__c.Primary__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Person__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer Accounts</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <description>Prospect Accounts</description>
        <label>Prospect</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/AccountAssignments__c.object
<CustomObject>
    <description>This object is used to store Overlay Account Assignments from Legacy system and also Primary rep (Owner Id) assignments. The data will be then picked up by a Batch Apex job to do actual Account Team Assignments.</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <description>This will store the Legacy Account ID</description>
        <externalId>true</externalId>
        <label>AccountId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountType__c</fullName>
        <description>Type of Account, Customer or Site etc...</description>
        <label>AccountType</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Id__c</fullName>
        <description>Entity Id it can be oracle_party_id, oracle_party_site_id, aops_cust_id or aops_seq_id.</description>
        <externalId>true</externalId>
        <label>Entity Id</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CUSTOMER</fullName>
                </value>
                <value>
                    <fullName>PROSPECT</fullName>
                </value>
                <value>
                    <fullName>ODN Customer</fullName>
                </value>
                <value>
                    <fullName>ODS Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OverlayEmpID10__c</fullName>
        <description>Employee Id of Overlay Employee 10, which is assigned to Account Team</description>
        <label>Overlay Emp ID 10</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID11__c</fullName>
        <description>Employee Id of Overlay Employee 11, which is assigned to Account Team</description>
        <label>Overlay Emp ID 11</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID12__c</fullName>
        <description>Employee Id of Overlay Employee 12, which is assigned to Account Team</description>
        <label>Overlay Emp ID 12</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID13__c</fullName>
        <description>Employee Id of Overlay Employee 13, which is assigned to Account Team</description>
        <label>Overlay Emp ID 13</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID14__c</fullName>
        <description>Employee Id of Overlay Employee 14, which is assigned to Account Team</description>
        <label>Overlay Emp ID 14</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID15__c</fullName>
        <description>Employee Id of Overlay Employee 15, which is assigned to Account Team</description>
        <label>Overlay Emp ID 15</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID16__c</fullName>
        <label>Overlay Emp ID 16</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID17__c</fullName>
        <label>Overlay Emp ID 17</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID18__c</fullName>
        <label>Overlay Emp ID 18</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID19__c</fullName>
        <label>Overlay Emp ID 19</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID1__c</fullName>
        <description>Employee Id of Overlay Employee 1, which is assigned to Account Team</description>
        <label>Overlay Emp ID 1</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID20__c</fullName>
        <label>Overlay Emp ID 20</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID21__c</fullName>
        <label>Overlay Emp ID 21</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID22__c</fullName>
        <label>Overlay Emp ID 22</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID23__c</fullName>
        <label>Overlay Emp ID 23</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID24__c</fullName>
        <label>Overlay Emp ID 24</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID25__c</fullName>
        <label>Overlay Emp ID 25</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID26__c</fullName>
        <label>Overlay Emp ID 26</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID27__c</fullName>
        <label>Overlay Emp ID 27</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID28__c</fullName>
        <label>Overlay Emp ID 28</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID29__c</fullName>
        <label>Overlay Emp ID 29</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID2__c</fullName>
        <description>Employee Id of Overlay Employee 2, which is assigned to Account Team</description>
        <label>Overlay Emp ID 2</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID30__c</fullName>
        <label>Overlay Emp ID 30</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID3__c</fullName>
        <description>Employee Id of Overlay Employee 3, which is assigned to Account Team</description>
        <label>Overlay Emp ID 3</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID4__c</fullName>
        <description>Employee Id of Overlay Employee 4, which is assigned to Account Team</description>
        <label>Overlay Emp ID 4</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID5__c</fullName>
        <description>Employee Id of Overlay Employee 5, which is assigned to Account Team</description>
        <label>Overlay Emp ID 5</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID6__c</fullName>
        <description>Employee Id of Overlay Employee 6, which is assigned to Account Team</description>
        <label>Overlay Emp ID 6</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID7__c</fullName>
        <description>Employee Id of Overlay Employee 7, which is assigned to Account Team</description>
        <label>Overlay Emp ID 7</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID8__c</fullName>
        <description>Employee Id of Overlay Employee 8, which is assigned to Account Team</description>
        <label>Overlay Emp ID 8</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID9__c</fullName>
        <description>Employee Id of Overlay Employee 9, which is assigned to Account Team</description>
        <label>Overlay Emp ID 9</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole10__c</fullName>
        <label>Overlay Emp Role 10</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole11__c</fullName>
        <label>Overlay Emp Role 11</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole12__c</fullName>
        <label>Overlay Emp Role 12</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole13__c</fullName>
        <label>Overlay Emp Role 13</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole14__c</fullName>
        <label>Overlay Emp Role 14</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole15__c</fullName>
        <label>Overlay Emp Role 15</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole16__c</fullName>
        <label>Overlay Emp Role 16</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole17__c</fullName>
        <label>Overlay Emp Role 17</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole18__c</fullName>
        <label>Overlay Emp Role 18</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole19__c</fullName>
        <label>Overlay Emp Role 19</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole1__c</fullName>
        <label>Overlay Emp Role 1</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole20__c</fullName>
        <label>Overlay Emp Role 20</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole21__c</fullName>
        <label>Overlay Emp Role 21</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole22__c</fullName>
        <label>Overlay Emp Role 22</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole23__c</fullName>
        <label>Overlay Emp Role 23</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole24__c</fullName>
        <label>Overlay Emp Role 24</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole25__c</fullName>
        <label>Overlay Emp Role 25</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole26__c</fullName>
        <label>Overlay Emp Role 26</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole27__c</fullName>
        <label>Overlay Emp Role 27</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole28__c</fullName>
        <label>Overlay Emp Role 28</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole29__c</fullName>
        <label>Overlay Emp Role 29</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole2__c</fullName>
        <label>Overlay Emp Role 2</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole30__c</fullName>
        <label>Overlay Emp Role 30</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole3__c</fullName>
        <label>Overlay Emp Role 3</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole4__c</fullName>
        <label>Overlay Emp Role 4</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole5__c</fullName>
        <label>Overlay Emp Role 5</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole6__c</fullName>
        <label>Overlay Emp Role 6</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole7__c</fullName>
        <label>Overlay Emp Role 7</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole8__c</fullName>
        <label>Overlay Emp Role 8</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole9__c</fullName>
        <label>Overlay Emp Role 9</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryEmpId__c</fullName>
        <description>Primary Employee id, mapped to Owner Id of the Account</description>
        <label>Primary Emp Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryEmpRole__c</fullName>
        <description>Role of the Primary Employee</description>
        <label>Primary Emp Role</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>AccountTeamAssignment</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>AssignmentsNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountTeamAssignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountAssignments_Batch_Open_TC.cls
@isTest
private class AccountAssignments_Batch_Open_TC 
{

    static testMethod void myUnitTest() 
    {
        Account acc = new Account ();
        acc.name = 'SUN Test Account';
        acc.BillingStreet = '1040 N 326 W';
        acc.billingcity = 'Orem';
        acc.BillingState = 'UT';
        acc.Billingcountry = 'USA';
        acc.Oracle_Party_Id__c = '123456';
        acc.AOPS_Cust_Id__c = '123456';
        acc.AOPS_Seq_ID__c = '123456';
        acc.OwnerID = '005E0000000lNbV';// This is the salesforce User ID
        acc.Sales_PersonID__c = 'a0AE0000000GGMn'; //Sales person Id for the Salesforce USer
        insert acc;
        
        Account accSite = new Account ();
        accSite.name = 'SUN Test Account';
        accSite.BillingStreet = '1040 N 326 W';
        accSite.billingcity = 'Orem';
        accSite.BillingState = 'UT';
        accSite.Billingcountry = 'USA';
        accSite.Oracle_Party_Site_Id__c = '12345678';
        accSite.AOPS_Cust_Id__c = '12345678';
        accSite.AOPS_Seq_ID__c = '12345678';
        insert accSite;

        AccountAssignments__c assign1 = new AccountAssignments__c();
        assign1.AccountId__c = '123456';
        assign1.AccountType__c = 'A';
        assign1.Entity_Type__c = 'CUSTOMER';
        assign1.Entity_Id__c = '123456';
        assign1.PrimaryEmpId__c = '000000';
        assign1.PrimaryEmpRole__c = '000000';
        assign1.OverlayEmpID1__c = '179556';
        assign1.OverlayEmpRole1__c = '11111';
        assign1.OverlayEmpID2__c = '595673';
        assign1.OverlayEmpRole2__c = '22222';
        assign1.OverlayEmpID3__c = '601832';
        assign1.OverlayEmpRole3__c = '333333';
        assign1.OverlayEmpID4__c = '234567';
        assign1.OverlayEmpRole4__c = '44444';
        assign1.OverlayEmpID5__c = '234567';
        assign1.OverlayEmpRole5__c = '44444';
        assign1.OverlayEmpID6__c = '234567';
        assign1.OverlayEmpRole6__c = '44444';
        assign1.OverlayEmpID7__c = '234567';
        assign1.OverlayEmpRole7__c = '44444';
        assign1.OverlayEmpID8__c = '234567';
        assign1.OverlayEmpRole8__c = '44444';
        assign1.OverlayEmpID9__c = '234567';
        assign1.OverlayEmpRole9__c = '44444';
        assign1.OverlayEmpID10__c = '234567';
        assign1.OverlayEmpRole10__c = '44444';
        assign1.OverlayEmpID11__c = '234567';
        assign1.OverlayEmpRole11__c = '44444';
        assign1.OverlayEmpID12__c = '234567';
        assign1.OverlayEmpRole12__c = '44444';
        assign1.OverlayEmpID13__c = '234567';
        assign1.OverlayEmpRole13__c = '44444';
        assign1.OverlayEmpID14__c = '234567';
        assign1.OverlayEmpRole14__c = '44444';
        assign1.OverlayEmpID15__c = '234567';
        assign1.OverlayEmpRole15__c = '44444';
        
        assign1.OverlayEmpID16__c = '179556';
        assign1.OverlayEmpRole16__c = '11111';
        assign1.OverlayEmpID17__c = '595673';
        assign1.OverlayEmpRole17__c = '22222';
        assign1.OverlayEmpID18__c = '601832';
        assign1.OverlayEmpRole18__c = '333333';
        assign1.OverlayEmpID19__c = '234567';
        assign1.OverlayEmpRole19__c = '44444';
        assign1.OverlayEmpID20__c = '234567';
        assign1.OverlayEmpRole20__c = '44444';
        assign1.OverlayEmpID21__c = '234567';
        assign1.OverlayEmpRole21__c = '44444';
        assign1.OverlayEmpID22__c = '234567';
        assign1.OverlayEmpRole22__c = '44444';
        assign1.OverlayEmpID23__c = '234567';
        assign1.OverlayEmpRole23__c = '44444';
        assign1.OverlayEmpID24__c = '234567';
        assign1.OverlayEmpRole24__c = '44444';
        assign1.OverlayEmpID25__c = '234567';
        assign1.OverlayEmpRole25__c = '44444';
        assign1.OverlayEmpID26__c = '234567';
        assign1.OverlayEmpRole26__c = '44444';
        assign1.OverlayEmpID27__c = '234567';
        assign1.OverlayEmpRole27__c = '44444';
        assign1.OverlayEmpID28__c = '234567';
        assign1.OverlayEmpRole28__c = '44444';
        assign1.OverlayEmpID29__c = '234567';
        assign1.OverlayEmpRole29__c = '44444';
        assign1.OverlayEmpID30__c = '234567';
        assign1.OverlayEmpRole30__c = '44444';
        assign1.Status__c = 'open';
        
        insert assign1;

        AccountAssignments__c assign2 = new AccountAssignments__c();
        assign2.AccountId__c = '12345678';
        assign2.AccountType__c = 'S';
        assign2.Entity_Type__c = 'CUSTOMER';
        assign2.Entity_Id__c = '12345678';
        assign2.PrimaryEmpId__c = '000000';
        assign2.PrimaryEmpRole__c = '000000';
        assign2.OverlayEmpID1__c = '104344';
        assign2.OverlayEmpRole1__c = '111111';
        assign2.OverlayEmpID2__c = '595673';
        assign2.OverlayEmpRole2__c = '222222';
        assign2.OverlayEmpID3__c = '600980';
        assign2.OverlayEmpRole3__c = '333333';
        assign2.OverlayEmpID4__c = '';
        assign2.OverlayEmpRole4__c = '';
        assign2.Status__c = 'open';
        
       insert assign2;        
   
        AccountAssignments__c assign3 = new AccountAssignments__c();
        assign3.AccountId__c = '1234567890';
        assign3.AccountType__c = 'S';
        assign3.Entity_Type__c = 'PROSPECT';
        assign3.Entity_Id__c = '1234567890';
        assign3.PrimaryEmpId__c = '000000';
        assign3.PrimaryEmpRole__c = '000000';
        assign3.OverlayEmpID1__c = '104344';
        assign3.OverlayEmpRole1__c = '111111';

        
        insert assign3; 
        
        
        Datetime dt = System.now();
        String scheduleString='0';
        scheduleString+=' '+ dt.minute();
        scheduleString+=' '+ dt.hour();
        scheduleString+=' '+ dt.day();
        scheduleString+=' '+ dt.month();
        scheduleString+=' ?';
        scheduleString+=' '+ dt.year();     
        System.debug('currently scheduled.' + scheduleString); 

        String CRON_EXP = '0 0 0 3 9 ? 2022';       
        
        Test.startTest();
        AccountAssignments_Batch_Open assignBatch = new AccountAssignments_Batch_Open();
        assignBatch.strQuery = 'Select Id, AccountId__c, AccountType__c, Entity_Type__c, Entity_Id__c, PrimaryEmpId__c, PrimaryEmpRole__c, ' 
                            +' OverlayEmpID1__c, OverlayEmpID2__c, OverlayEmpID3__c, OverlayEmpID4__c, OverlayEmpID5__c, OverlayEmpID6__c, OverlayEmpID7__c, OverlayEmpID8__c,' 
                            +' OverlayEmpID9__c, OverlayEmpID10__c, OverlayEmpID11__c, OverlayEmpID12__c, OverlayEmpID13__c, OverlayEmpID14__c, OverlayEmpID15__c,' 
                            +' OverlayEmpID16__c, OverlayEmpID17__c, OverlayEmpID18__c, OverlayEmpID19__c, OverlayEmpID20__c, OverlayEmpID21__c, OverlayEmpID22__c, OverlayEmpID23__c,' 
                            +' OverlayEmpID24__c, OverlayEmpID25__c, OverlayEmpID26__c, OverlayEmpID27__c, OverlayEmpID28__c, OverlayEmpID29__c, OverlayEmpID30__c,' 
                            +' OverlayEmpRole1__c, OverlayEmpRole2__c, OverlayEmpRole3__c, OverlayEmpRole4__c, OverlayEmpRole5__c, OverlayEmpRole6__c, '
                            +' OverlayEmpRole7__c, OverlayEmpRole8__c, OverlayEmpRole9__c, OverlayEmpRole10__c, OverlayEmpRole11__c, OverlayEmpRole12__c,' 
                            +' OverlayEmpRole13__c, OverlayEmpRole14__c, OverlayEmpRole15__c,OverlayEmpRole16__c, OverlayEmpRole17__c, OverlayEmpRole18__c, OverlayEmpRole19__c, OverlayEmpRole20__c,'
                            +' OverlayEmpRole21__c, OverlayEmpRole22__c, OverlayEmpRole23__c, OverlayEmpRole24__c, OverlayEmpRole25__c, OverlayEmpRole26__c, OverlayEmpRole27__c,'
                            +' OverlayEmpRole28__c, OverlayEmpRole29__c, OverlayEmpRole30__c,Status__c, Error_Message__c'
                            +' from AccountAssignments__c where Status__c = \'open\'';
                            
        database.executebatch(assignBatch, 100);
        System.schedule('Assignment Batche',CRON_EXP , assignBatch);

       /* AccountAssignments_Error_Batch assignErrorBatch = new AccountAssignments_Error_Batch();
        assignErrorBatch.strQuery = 'Select Id, AccountId__c, AccountType__c, Entity_Type__c, Entity_Id__c, PrimaryEmpId__c, PrimaryEmpRole__c, ' 
                            +' OverlayEmpID1__c, OverlayEmpID2__c, OverlayEmpID3__c, OverlayEmpID4__c, OverlayEmpID5__c, OverlayEmpID6__c, OverlayEmpID7__c, OverlayEmpID8__c,' 
                            +' OverlayEmpID9__c, OverlayEmpID10__c, OverlayEmpID11__c, OverlayEmpID12__c, OverlayEmpID13__c, OverlayEmpID14__c, OverlayEmpID15__c,' 
                            +' OverlayEmpID16__c, OverlayEmpID17__c, OverlayEmpID18__c, OverlayEmpID19__c, OverlayEmpID20__c, OverlayEmpID21__c, OverlayEmpID22__c, OverlayEmpID23__c,' 
                            +' OverlayEmpID24__c, OverlayEmpID25__c, OverlayEmpID26__c, OverlayEmpID27__c, OverlayEmpID28__c, OverlayEmpID29__c, OverlayEmpID30__c,' 
                            +' OverlayEmpRole1__c, OverlayEmpRole2__c, OverlayEmpRole3__c, OverlayEmpRole4__c, OverlayEmpRole5__c, OverlayEmpRole6__c, '
                            +' OverlayEmpRole7__c, OverlayEmpRole8__c, OverlayEmpRole9__c, OverlayEmpRole10__c, OverlayEmpRole11__c, OverlayEmpRole12__c,' 
                            +' OverlayEmpRole13__c, OverlayEmpRole14__c, OverlayEmpRole15__c,OverlayEmpRole16__c, OverlayEmpRole17__c, OverlayEmpRole18__c, OverlayEmpRole19__c, OverlayEmpRole20__c,'
                            +' OverlayEmpRole21__c, OverlayEmpRole22__c, OverlayEmpRole23__c, OverlayEmpRole24__c, OverlayEmpRole25__c, OverlayEmpRole26__c, OverlayEmpRole27__c,'
                            +' OverlayEmpRole28__c, OverlayEmpRole29__c, OverlayEmpRole30__c,Status__c, Error_Message__c'
                            +' from AccountAssignments__c where Status__c = \'TestData\'';
        database.executebatch(assignErrorBatch, 200);
        System.schedule('Assignment error Batch',CRON_EXP , assignErrorBatch);*/
        
        // added for the story #S-418600 (00715635) #START
        String qry  = 'Select Id, AccountId__c, AccountType__c, Entity_Type__c, Entity_Id__c, PrimaryEmpId__c, PrimaryEmpRole__c, ' 
                            +' OverlayEmpID1__c, OverlayEmpID2__c, OverlayEmpID3__c, OverlayEmpID4__c, OverlayEmpID5__c, OverlayEmpID6__c, OverlayEmpID7__c, OverlayEmpID8__c,' 
                            +' OverlayEmpID9__c, OverlayEmpID10__c, OverlayEmpID11__c, OverlayEmpID12__c, OverlayEmpID13__c, OverlayEmpID14__c, OverlayEmpID15__c,' 
                            +' OverlayEmpID16__c, OverlayEmpID17__c, OverlayEmpID18__c, OverlayEmpID19__c, OverlayEmpID20__c, OverlayEmpID21__c, OverlayEmpID22__c, OverlayEmpID23__c,' 
                            +' OverlayEmpID24__c, OverlayEmpID25__c, OverlayEmpID26__c, OverlayEmpID27__c, OverlayEmpID28__c, OverlayEmpID29__c, OverlayEmpID30__c,' 
                            +' OverlayEmpRole1__c, OverlayEmpRole2__c, OverlayEmpRole3__c, OverlayEmpRole4__c, OverlayEmpRole5__c, OverlayEmpRole6__c, '
                            +' OverlayEmpRole7__c, OverlayEmpRole8__c, OverlayEmpRole9__c, OverlayEmpRole10__c, OverlayEmpRole11__c, OverlayEmpRole12__c,' 
                            +' OverlayEmpRole13__c, OverlayEmpRole14__c, OverlayEmpRole15__c,OverlayEmpRole16__c, OverlayEmpRole17__c, OverlayEmpRole18__c, OverlayEmpRole19__c, OverlayEmpRole20__c,'
                            +' OverlayEmpRole21__c, OverlayEmpRole22__c, OverlayEmpRole23__c, OverlayEmpRole24__c, OverlayEmpRole25__c, OverlayEmpRole26__c, OverlayEmpRole27__c,'
                            +' OverlayEmpRole28__c, OverlayEmpRole29__c, OverlayEmpRole30__c,Status__c, Error_Message__c'
                            +' from AccountAssignments__c where Status__c = \'open\'';
        
        AccountAssignments_Batch_Open assignBatch1 = new AccountAssignments_Batch_Open(qry);                   
        database.executebatch(assignBatch1, 100);
        
        AccountAssignments_Batch_Open assignBatch2 = new AccountAssignments_Batch_Open('');
        
        system.assertNotEquals(assignBatch2, null); 
        // added for the story #S-418600 (00715635) #END
        
        Test.stopTest();

    }
}