objects/Account.object
<CustomObject>
    <fields>
        <fullName>AOPS_Cust_Id__c</fullName>
        <description>AOPS Customer Account Number</description>
        <externalId>true</externalId>
        <label>AOPS Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>AOPS_Seq_ID__c</fullName>
        <externalId>true</externalId>
        <label>AOPS Seq ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Cust_ID__c</fullName>
        <formula>if( $RecordType.Name = &quot;Site&quot;, AOPS_Seq_ID__c , 
if( $RecordType.Name = &quot;Customer&quot; &amp;&amp; Grandparent__c = &quot;No&quot;, AOPS_Cust_Id__c, 
if( $RecordType.Name = &quot;Parent&quot; , AOPS_Cust_Id__c, 
if( $RecordType.Name = &quot;Great Grandparent&quot; , AOPS_Cust_Id__c, 
if( $RecordType.Name = &quot;GrandParent&quot;  &amp;&amp; LEN(AOPS_Cust_Id__c) = 1, &quot;0000000&quot; + AOPS_Cust_Id__c, 
if( $RecordType.Name = &quot;GrandParent&quot; &amp;&amp; LEN(AOPS_Cust_Id__c) = 2, &quot;000000&quot; + AOPS_Cust_Id__c, 
if( $RecordType.Name = &quot;GrandParent&quot; &amp;&amp; LEN(AOPS_Cust_Id__c) = 3, &quot;00000&quot; + AOPS_Cust_Id__c, 
if( $RecordType.Name = &quot;GrandParent&quot; &amp;&amp; LEN(AOPS_Cust_Id__c) = 4, &quot;0000&quot; + AOPS_Cust_Id__c, 
if( $RecordType.Name = &quot;GrandParent&quot;  &amp;&amp; LEN(AOPS_Cust_Id__c) = 5, &quot;000&quot; + AOPS_Cust_Id__c, 
if( $RecordType.Name = &quot;GrandParent&quot;  &amp;&amp; LEN(AOPS_Cust_Id__c) = 6, &quot;00&quot; + AOPS_Cust_Id__c, 
if( $RecordType.Name = &quot;Customer (OfficeMax)&quot; ,OMX_Mainframe_Account_Number__c, 
if( $RecordType.Name = &quot;Site (OfficeMax)&quot; ,OMX_Mainframe_Account_Number__c+ &apos;-&apos;+OMX_Mainframe_Consignee_ID__c, 
if( $RecordType.Name = &quot;Site (GT)&quot; ,OMX_Primary_Key__c, 
if( $RecordType.Name = &quot;Customer (GT)&quot; ,OMX_Primary_Key__c, 
null 
))))))))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cust ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DEPT_REQUIRED_CODE__c</fullName>
        <label>DEPT_REQUIRED_CODE</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LOCATION_REQ_CODE_7__c</fullName>
        <label>LOCATION_REQ_CODE_7</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_REQUIRED_CODE__c</fullName>
        <label>PO_REQUIRED_CODE</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RELEASE_REQUIRED_CODE__c</fullName>
        <label>RELEASE_REQUIRED_CODE</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>(Tech-Zone)</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site</fullName>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer Accounts</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Site</fullName>
        <active>true</active>
        <label>Site</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/AOPS_DEPT_CCU001F__c.object
<CustomObject>
    <fields>
        <fullName>CCU001F_CUSTOMER_DEPT_KEY__c</fullName>
        <defaultValue>&apos; &apos;</defaultValue>
        <label>CCU001F_CUSTOMER_DEPT_KEY</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCU001F_CUSTOMER_ID__c</fullName>
        <externalId>true</externalId>
        <label>CCU001F_CUSTOMER_ID</label>
        <length>8</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KEY__c</fullName>
        <externalId>true</externalId>
        <label>KEY</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>AOPS_DEPT_CCU001F</label>
    <nameField>
        <label>AOPS_DEPT_CCU001F Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AOPS_DEPT_CCU001F</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AOPS_DESKTOP_CCU003F__c.object
<CustomObject>
    <fields>
        <fullName>CCU003F_ADDRESS_SEQ__c</fullName>
        <defaultValue>0</defaultValue>
        <label>CCU003F_ADDRESS_SEQ</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCU003F_CUSTOMER_ID__c</fullName>
        <externalId>true</externalId>
        <label>CCU003F_CUSTOMER_ID</label>
        <length>8</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCU003F_CUST_LOCATION_KEY__c</fullName>
        <defaultValue>&apos; &apos;</defaultValue>
        <label>CCU003F_CUST_LOCATION_KEY</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KEY__c</fullName>
        <externalId>true</externalId>
        <label>KEY</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>AOPS_DESKTOP_CCU003F</label>
    <nameField>
        <label>AOPS_DESKTOP_CCU003F Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AOPS_DESKTOP_CCU003F</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AOPS_PO_FCU009P__c.object
<CustomObject>
    <fields>
        <fullName>FCU009P_CUSTOMER_ID__c</fullName>
        <externalId>true</externalId>
        <label>FCU009P_CUSTOMER_ID</label>
        <length>8</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FCU009P_PO_NBR__c</fullName>
        <defaultValue>&apos; &apos;</defaultValue>
        <label>FCU009P_PO_NBR</label>
        <length>22</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KEY__c</fullName>
        <externalId>true</externalId>
        <label>KEY</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>AOPS_PO_FCU009P</label>
    <nameField>
        <label>AOPS_PO_FCU009P Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AOPS_PO_FCU009P</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AOPS_RELEASE_CCU005F__c.object
<CustomObject>
    <fields>
        <fullName>CCU005F_CUSTOMER_ID__c</fullName>
        <externalId>true</externalId>
        <label>CCU005F_CUSTOMER_ID</label>
        <length>8</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCU005F_RELEASE_NBR__c</fullName>
        <defaultValue>&apos; &apos;</defaultValue>
        <label>CCU005F_RELEASE_NBR</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <externalId>true</externalId>
        <label>Key</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>AOPS_RELEASE_CCU005F</label>
    <nameField>
        <label>AOPS_RELEASE_CCU005F Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AOPS_RELEASE_CCU005F</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Cust_ID__c</fullName>
        <formula>Account.Cust_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Cost_Center__c</fullName>
        <description>For AOPS, accounting related field.</description>
        <inlineHelpText>For AOPS, accounting related field.</inlineHelpText>
        <label>Cost Center</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_PO_Number__c</fullName>
        <description>For AOPS, accounting related field.</description>
        <inlineHelpText>For AOPS, accounting related field.</inlineHelpText>
        <label>Customer PO Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Desktop__c</fullName>
        <description>For AOPS, accounting related field.</description>
        <inlineHelpText>For AOPS, accounting related field.</inlineHelpText>
        <label>Desktop</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <description>For AOPS, accounting related field.</description>
        <inlineHelpText>For AOPS, accounting related field.</inlineHelpText>
        <label>Release</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes (Ship To Account)</relationshipLabel>
        <relationshipName>Quotes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/EndlessAisleQuoteSetup_TC.cls
@IsTest
public class EndlessAisleQuoteSetup_TC
{
	public EndlessAisleQuoteSetup_TC()
	{

	}

	@TestSetup
	static void makeData()
	{
		Account account1 = new Account();
		account1.Name = 'TestAccount1';
		account1.AOPS_Cust_Id__c = '1';
		account1.PO_REQUIRED_CODE__c = '1';
		account1.DEPT_REQUIRED_CODE__c = '1';
		account1.RELEASE_REQUIRED_CODE__c = '1';
		account1.LOCATION_REQ_CODE_7__c = '1';
		account1.RecordTypeId = [SELECT Id, Name FROM RecordType WHERE Name = 'Customer'].Id;
		insert account1;

		Account site1 = new Account();
		site1.Name = 'TestAccount2';
		site1.RecordTypeId = [SELECT Id, Name FROM RecordType WHERE Name = 'Site'].Id;
		site1.Related_Account__c = account1.Id;
		site1.AOPS_Seq_Id__c = '1';
		insert site1;

		Opportunity opp1 = new Opportunity();
		opp1.Name = 'TestOpp1';
		opp1.StageName = 'Propose';
		opp1.CloseDate = Date.today();
		opp1.AccountId = account1.Id;
		insert opp1;

		Contact contact1 = new Contact();
		contact1.FirstName = 'moe';
		contact1.LastName = 'moe';
		contact1.Email = 'moe@moe.com';
		contact1.AccountId = account1.Id;
		insert contact1;

		Quote quote1 = new Quote();
		quote1.OpportunityId = opp1.Id;
		quote1.Ship_To_Account__c = site1.Id;
		quote1.Name = 'TestQuote1';
		quote1.Desktop__c = '1';
		quote1.Cost_Center__c = '1';
		quote1.Release__c = '1';
		quote1.Customer_PO_Number__c = '1';
		insert quote1;

		Quote q = [SELECT Id, Ship_To_Account__r.AOPS_Seq_Id__c, AccountId, Account.Cust_Id__c FROM Quote WHERE Id = :quote1.Id];

		AOPS_DEPT_CCU001F__c costCenter = new AOPS_DEPT_CCU001F__c();
		costCenter.CCU001F_CUSTOMER_ID__c = q.Account.Cust_Id__c;
		costCenter.CCU001F_CUSTOMER_DEPT_KEY__c = '1';
		costCenter.KEY__c = '1';
		insert costCenter;

		AOPS_PO_FCU009P__c poNumber = new AOPS_PO_FCU009P__c();
		poNumber.FCU009P_CUSTOMER_ID__c = q.Account.Cust_Id__c;
		poNumber.FCU009P_PO_NBR__c = '1';
		poNumber.KEY__c = '1';
		insert poNumber;

		AOPS_DESKTOP_CCU003F__c desktopNumber = new AOPS_DESKTOP_CCU003F__c();
		desktopNumber.CCU003F_CUSTOMER_ID__c = q.Account.Cust_Id__c;
		desktopNumber.CCU003F_ADDRESS_SEQ__c = Decimal.valueOf(q.Ship_To_Account__r.AOPS_Seq_Id__c);
		desktopNumber.CCU003F_CUST_LOCATION_KEY__c = '1';
		desktopNumber.KEY__c = '1';
		insert desktopNumber;

		AOPS_RELEASE_CCU005F__c releaseNumber = new AOPS_RELEASE_CCU005F__c();
		releaseNumber.CCU005F_CUSTOMER_ID__c = q.Account.Cust_Id__c;
		releaseNumber.CCU005F_RELEASE_NBR__c = '1';
		releaseNumber.KEY__c = '1';
		insert releaseNumber;
	}

	@IsTest
	public static void testFieldRestrictions()
	{
		Quote q = [SELECT Id, AccountId FROM Quote WHERE Name = 'TestQuote1'];

		Test.startTest();
		String response = EndlessAisleQuoteSetup.getFieldRestrictions(q.Id);
		List<Account> accounts = (List<Account>)JSON.deserialize(response, List<Account>.class);
		System.assertEquals(accounts.size(), 1);
		Test.stopTest();
	}

	@IsTest
	public static void testQuoteWizardValues()
	{
		Quote q = [SELECT Id, Ship_To_Account__r.Id, Contact.Id FROM Quote WHERE Name = 'TestQuote1'];

		Test.startTest();
		String response = EndlessAisleQuoteSetup.getTechQuoteWizardValues(q.Id);
		Map<String, Object> responses = (Map<String, Object>)JSON.deserializeUntyped(response);
		System.assertEquals(responses.get('costCenter'), '1');
		System.assertEquals(responses.get('poNumber'), '1');
		System.assertEquals(responses.get('desktopNumber'), '1');
		System.assertEquals(responses.get('releaseNumber'), '1');
		System.assertEquals(((Map<String, Object>)responses.get('shipTo')).get('recordId'), q.Ship_To_Account__r.Id);
		System.assertEquals(((Map<String, Object>)responses.get('contact')).get('recordId'), q.Contact.Id);
		Test.stopTest();
	}

	@IsTest
	public static void testCostCenterResults()
	{
		Quote q = [SELECT Id, Name FROM Quote WHERE Name = 'TestQuote1'];

		Test.startTest();
		String response = EndlessAisleQuoteSetup.getCostCenterResults(q.Id, '');
		System.debug(response);
		List<AOPS_DEPT_CCU001F__c> responses = (List<AOPS_DEPT_CCU001F__c>)JSON.deserialize(response, List<AOPS_DEPT_CCU001F__c>.class);
		System.assertEquals(responses.size(), 1);
		Test.stopTest();
	}

	@IsTest
	public static void testCostCenterResultsFail()
	{
		Test.startTest();
		String response = EndlessAisleQuoteSetup.getCostCenterResults('zzz', '');
		System.debug(response);
		List<AOPS_DEPT_CCU001F__c> responses = (List<AOPS_DEPT_CCU001F__c>)JSON.deserialize(response, List<AOPS_DEPT_CCU001F__c>.class);
		System.assertEquals(responses.size(), 0);
		Test.stopTest();
	}

	@IsTest
	public static void testPONumberResults()
	{
		Quote q = [SELECT Id, Name FROM Quote WHERE Name = 'TestQuote1'];

		Test.startTest();
		String response = EndlessAisleQuoteSetup.getPONumberResults(q.Id, '');
		List<AOPS_PO_FCU009P__c> responses = (List<AOPS_PO_FCU009P__c>)JSON.deserialize(response, List<AOPS_PO_FCU009P__c>.class);
		System.assertEquals(responses.size(), 1);
		Test.stopTest();
	}

	@IsTest
	public static void testPONumberResultsFail()
	{
		Test.startTest();
		String response = EndlessAisleQuoteSetup.getPONumberResults('zzz', '');
		List<AOPS_PO_FCU009P__c> responses = (List<AOPS_PO_FCU009P__c>)JSON.deserialize(response, List<AOPS_PO_FCU009P__c>.class);
		System.assertEquals(responses.size(), 0);
		Test.stopTest();
	}

	@IsTest
	public static void testDesktopNumberResults()
	{
		Quote q = [SELECT Id, Name FROM Quote WHERE Name = 'TestQuote1'];

		Test.startTest();
		String response = EndlessAisleQuoteSetup.getDesktopNumberResults(q.Id, '');
		List<AOPS_DESKTOP_CCU003F__c> responses = (List<AOPS_DESKTOP_CCU003F__c>)JSON.deserialize(response, List<AOPS_DESKTOP_CCU003F__c>.class);
		System.assertEquals(responses.size(), 1);
		Test.stopTest();
	}

	@IsTest
	public static void testDesktopNumberResultsFail()
	{
		Test.startTest();
		String response = EndlessAisleQuoteSetup.getDesktopNumberResults('zzz', '');
		List<AOPS_DESKTOP_CCU003F__c> responses = (List<AOPS_DESKTOP_CCU003F__c>)JSON.deserialize(response, List<AOPS_DESKTOP_CCU003F__c>.class);
		System.assertEquals(responses.size(), 0);
		Test.stopTest();
	}

	@IsTest
	public static void testReleaseNumberResults()
	{
		Quote q = [SELECT Id, Name FROM Quote WHERE Name = 'TestQuote1'];

		Test.startTest();
		String response = EndlessAisleQuoteSetup.getReleaseNumberResults(q.Id, '');
		List<AOPS_RELEASE_CCU005F__c> responses = (List<AOPS_RELEASE_CCU005F__c>)JSON.deserialize(response, List<AOPS_RELEASE_CCU005F__c>.class);
		System.assertEquals(responses.size(), 1);
		Test.stopTest();
	}

	@IsTest
	public static void testReleaseNumberResultsFail()
	{
		Test.startTest();
		String response = EndlessAisleQuoteSetup.getReleaseNumberResults('zzz', '');
		List<AOPS_RELEASE_CCU005F__c> responses = (List<AOPS_RELEASE_CCU005F__c>)JSON.deserialize(response, List<AOPS_RELEASE_CCU005F__c>.class);
		System.assertEquals(responses.size(), 0);
		Test.stopTest();
	}

	@IsTest
	public static void testShipToResults()
	{
		Quote q = [SELECT Id, Name FROM Quote WHERE Name = 'TestQuote1'];

		Test.startTest();
		String response = EndlessAisleQuoteSetup.getShipToResults(q.Id, '');
		List<Account> responses = (List<Account>)JSON.deserialize(response, List<Account>.class);
		System.assertEquals(responses.size(), 1);
		Test.stopTest();
	}

	@IsTest
	public static void testShipToResultsFail()
	{
		Test.startTest();
		String response = EndlessAisleQuoteSetup.getShipToResults('zzz', '');
		List<Account> responses = (List<Account>)JSON.deserialize(response, List<Account>.class);
		System.assertEquals(responses.size(), 0);
		Test.stopTest();
	}

	@IsTest
	public static void testContactResults()
	{
		Quote q = [SELECT Id, Name FROM Quote WHERE Name = 'TestQuote1'];

		Test.startTest();
		String response = EndlessAisleQuoteSetup.getContactResults(q.Id, '');
		List<Contact> responses = (List<Contact>)JSON.deserialize(response, List<Contact>.class);
		System.assertEquals(responses.size(), 1);
		Test.stopTest();
	}

	@IsTest
	public static void testContactResultsFail()
	{
		Test.startTest();
		String response = EndlessAisleQuoteSetup.getContactResults('zzz', '');
		List<Contact> responses = (List<Contact>)JSON.deserialize(response, List<Contact>.class);
		System.assertEquals(responses.size(), 0);
		Test.stopTest();
	}

	@IsTest
	public static void testSetTechQuoteWizardValues()
	{
		Quote q = [SELECT Id, Name FROM Quote WHERE Name = 'TestQuote1'];
		Account shipTo = [SELECT Id FROM Account WHERE Name = 'TestAccount2'];
		Contact contact = [SELECT Id FROM Contact WHERE FirstName = 'moe'];

		Map<String, Object> params = new Map<String, Object>();
		params.put('costCenter', '1');
		params.put('poNumber', '1');
		params.put('desktopNumber', '1');
		params.put('releaseNumber', '1');
		params.put('shipTo', shipTo.Id);
		params.put('contact', contact.Id);

		Test.startTest();
		Boolean didUpdate = EndlessAisleQuoteSetup.setTechQuoteWizardValues(q.Id, params);
		System.assertEquals(didUpdate, true);
		Test.stopTest();
	}
}