objects/Account.object
<CustomObject>
    <fields>
        <fullName>Address1__c</fullName>
        <label>Address1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address2__c</fullName>
        <label>Address2</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>USA</fullName>
                    <default>true</default>
                    <label>USA</label>
                </value>
                <value>
                    <fullName>CAN</fullName>
                </value>
                <value>
                    <fullName>MEX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Duns_Number__c</fullName>
        <description>Duns Number from Data Warehousing</description>
        <label>Duns Number</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Industry_OD_SIC_DB__c</fullName>
        <description>DataWareHouse Provided Attribute,  
Populated as Part of enrichment (Integration) b/w SFDC and Data Warehouse</description>
        <label>Industry (OD SIC) - D&amp;B</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oracle_Party_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Party ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Oracle_Party_Site_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Party Site ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Org_WCW_Count_DB__c</fullName>
        <description>Total Org White Collar Workers - Firmographic Append</description>
        <label>Org WCW Count - D&amp;B</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Org_WCW_Count_Rep__c</fullName>
        <defaultValue>0</defaultValue>
        <label>White Collar Workers</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Related_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>(Tech-Zone)</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is used for Primary Owner Sales ID.</description>
        <label>Sales Person ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sales_Person__c.Primary__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Person__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Segment_Code__c</fullName>
        <formula>Case(Segment__c,
&quot;Federal&quot;, &quot;GF&quot;,
&quot;State&quot;, &quot;GS&quot;,
&quot;Local&quot;, &quot;GL&quot;,
&quot;Higher-Ed&quot;,&quot;EH&quot;,
&quot;K-12&quot;,&quot;EK&quot;,
&quot;Non-Profit&quot;,&quot;GO&quot;,
&quot;Small $10K-$75K&quot;, &quot;IS&quot;, 
&quot;Small &lt; $10K&quot;, &quot;SM&quot;,
&quot;Medium $75K-$150K&quot;, &quot;MD&quot;,
&quot;Standard $150K-$250K&quot;, &quot;LS&quot;,
&quot;Key $250K-$500K&quot;, &quot;LK&quot;,
&quot;Major $500K-$1M&quot;, &quot;LM&quot;,
&quot;Enterprise $1M+&quot;,&quot;GB&quot;,&quot;OT&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Segment Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site</fullName>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip/Postal Code</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <description>Prospect Accounts</description>
        <label>Prospect</label>
    </recordTypes>
    <recordTypes>
        <fullName>Site</fullName>
        <active>true</active>
        <label>Site</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Prospect_Message__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>Prospect Account to which this message applies.</description>
        <inlineHelpText>Prospect Account to which this message applies.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Prospect Messages</relationshipLabel>
        <relationshipName>Prospect_Messages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Message_Complete__c</fullName>
        <description>NP - Not Processed
IP - In Process
P - Processed</description>
        <label>Message Complete</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NP</fullName>
                    <default>true</default>
                    <label>NP</label>
                </value>
                <value>
                    <fullName>IP</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Prospect Message</label>
    <nameField>
        <label>Prospect Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prospect Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Person__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role_Relate_Id__c</fullName>
        <externalId>true</externalId>
        <label>Role Relate Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Person_IDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Person ID</label>
    <nameField>
        <label>Sales Person ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Person IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ProspectService.cls
/**************************************************************************
*Created By :
*Created Date :
*Purpose :
SOA calls this class via web service call to get prospects for insert or update
into E-Business Suite.

Last Modified       : 05/19/2012
Last Modified By    : Phil Price
Last Modified Reason: Add Oracle party_id to party_site_id to message.


**************************************************************************/

global class ProspectService  {
  
  public class ProspectServiceException extends Exception {}

  global class SalesCustomerProspectCreation {
    webservice List<ServiceProspect> prospects; 
  }
    
  global class ServiceProspect {
    webservice String Duns_Number;
    webservice String Industry;
    webservice String Organization_Name;
    webservice String Organization_OD_WCW;
    webservice String Organization_SFDC_Id;
    webservice String Organization_Status;
    webservice String Organization_WCW;
    webservice String Segment;
    webservice String Rep;
    webservice String Oracle_Party_Id;
    webservice List<ServiceProspectSite> site;
  }
  
  global class ServiceProspectSite {
    webservice String Address_Line1;
    webservice String Address_Line2;
    webservice String City;
    webservice String Country;
    webservice String Oracle_Party_Site_Id;
    webservice String Party_Site_Name;
    webservice String Party_Site_OD_WCW;
    webservice String Party_Site_SFDC_Id;
    webservice String Party_Site_Status;
    webservice String Party_Site_Use_Type;
    webservice String Party_Site_WCW;
    webservice String State;
    webservice String Zip;
    webservice String Rep;
  }
  
  webservice static SalesCustomerProspectCreation GetSubmittedProspects() {

  SalesCustomerProspectCreation retProspList = new SalesCustomerProspectCreation();

    RecordType recType = [select id from recordtype where name = 'Prospect'];

    List<Prospect_Message__c> prosMsgs = [select id, account__c from prospect_message__c where message_complete__c = 'NP'];

    List<Id> acctsToProc = new List<Id>();
    Map<Id, ServiceProspect> spMap = new Map<Id, ServiceProspect>();
    Map<ID,String> ownertoRelate = new Map<ID,String> ();
    Set<ID> ownerIDs = new Set<ID>();

    for(Prospect_Message__c lclPm : prosMsgs)
      acctsToProc.add(lclPm.account__c);
     
    Map<Id, Account> prospectAccounts = new Map<Id,Account>(
    [select Duns_Number__c, Industry_OD_SIC_DB__c, Name, Org_WCW_Count_Rep__c, 
                Id, Status__c, Org_WCW_Count_DB__c, Segment_code__c, sales_personid__r.name,Sales_PersonID__r.role_relate_id__c,
                Oracle_Party_ID__c,ownerid
       from account 
      where recordtypeid = :recType.id
        and id in :acctsToProc]);
        
  for(Account a : prospectAccounts.values())
   ownerIDs.add(a.ownerid);

  Map<Id, Account> prospectSiteAccounts = new Map<Id, Account>(
    [select related_account__c, Name, Org_WCW_Count_Rep__c, Id, status__c, sales_personid__r.name,Sales_PersonID__r.role_relate_id__c,
                address1__c, address2__c, city__c, country__c, state__c, zip__c, Oracle_Party_Site_Id__c,ownerid
       from account 
      where related_account__r.id in :prospectAccounts.keySet()]);
      
  for (account a:prospectSiteAccounts.values())
      ownerIDs.add(a.ownerid);
      
  for (sales_person__c s:[select user__c,Role_Relate_Id__c from sales_person__c where user__c in :ownerIDs and isactive__c=true and Primary__c=true])
        ownertoRelate.put(s.user__c,s.Role_Relate_Id__c);

  for (Account lclAcct : prospectAccounts.values() ) {
    ServiceProspect sp      = new ServiceProspect();
    sp.Duns_Number          = lclAcct.Duns_Number__c;
    sp.Industry             = lclAcct.Industry_OD_SIC_DB__c;
    sp.Organization_Name    = lclAcct.Name;
    //sp.Rep                  = lclAcct.Sales_PersonID__r.role_relate_id__c;
    if (ownertoRelate.containskey(lclAcct.ownerid))
      sp.Rep = ownertoRelate.get(lclAcct.ownerid);
    else
	  sp.Rep                  = lclAcct.Sales_PersonID__r.role_relate_id__c;
    sp.Organization_SFDC_Id = lclAcct.Id;
    sp.Organization_Status  = lclAcct.Status__c;
    sp.Segment              = lclAcct.Segment_code__c;
    sp.Oracle_Party_Id      = lclAcct.Oracle_Party_ID__c;
        
    try {
      sp.Organization_OD_WCW = lclAcct.Org_WCW_Count_Rep__c.toPlainString();
    } catch(Exception e) {
      sp.Organization_OD_WCW = '';
    }

    try {
      sp.Organization_WCW = lclAcct.Org_WCW_Count_DB__c.toPlainString();
    } catch(Exception e) {
      sp.Organization_WCW = '';
    }
    
    spMap.put(lclAcct.Id, sp);
  }

  for(Account lclSite : prospectSiteAccounts.values()) {

    Id relId = lclSite.related_account__c;

    if (spMap.containsKey(relId)) {

      ServiceProspectSite lclSps = new ServiceProspectSite();
      lclSps.Party_Site_Name      = lclSite.Name;
      //lclSps.Rep                  = lclSite.Sales_PersonID__r.role_relate_id__c;
	  if (ownertoRelate.containskey(lclSite.ownerid))
		 lclSps.Rep = ownertoRelate.get(lclSite.ownerid);
	  else
		 lclSps.Rep                  = lclSite.Sales_PersonID__r.role_relate_id__c;
      lclSps.Address_Line1        = lclSite.Address1__c;
      lclSps.Address_Line2        = lclSite.Address2__c;
      lclSps.City                 = lclSite.City__c;
      lclSps.Country              = lclSite.Country__c;
      lclSps.Party_Site_SFDC_Id   = lclSite.id;
      lclSps.Party_Site_Status    = lclSite.status__c;
      lclSps.State                = lclSite.State__c;
      lclSps.Zip                  = lclSite.zip__c;
      lclSps.Oracle_Party_Site_Id = lclSite.Oracle_Party_Site_ID__c;
      
      try {
        lclSps.Party_Site_OD_WCW = lclSite.Org_WCW_Count_Rep__c.toPlainString();
      } catch(Exception e) {
        lclSps.Party_Site_OD_WCW = '';
      }

      ServiceProspect spRec = new ServiceProspect();
      spRec = spMap.get(relId);
      
      if (spRec.site == null)
        spRec.site = new List<ServiceProspectSite>();

            spRec.site.add(lclSps);
            spMap.put(relId, spRec); // replace entry for this id with new one that includes this site
    }
  }

  retProspList.prospects = spMap.values();

    // Update the Message_complete__c field to 'IP'.
  List <Prospect_Message__c> lclProspMsgList = [select Message_Complete__c 
                                                  from prospect_message__c 
                                                  where id in :prosMsgs];            

  for(Prospect_Message__c lclMsg : lclProspMsgList) {
    lclMsg.Message_Complete__c = 'IP';   
  }

    upsert(lclProspMsgList);
  
  return retProspList;
  }
}