objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Reassignment_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reassignment Queue</relationshipLabel>
        <relationshipName>Reassignment_Queue</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approve_Reject_Date__c</fullName>
        <label>Approve/Reject Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Reassignment_Queue</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>New Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Reassignment_Queue1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requestor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Reassignment_Queue2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Auto Approved</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Reassignment Queue</label>
    <nameField>
        <displayFormat>RQ-{0000}</displayFormat>
        <label>Reassignment Queue	 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reassignment Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ReassignAccount_TC.cls
@isTest
public class ReassignAccount_TC 
{
   public static testMethod void myUnitTest() 
{
          
Profile pf = [Select Id from Profile where Name = 'System Administrator'];
User u = new User();
u.FirstName = 'Test';
u.LastName = 'User';
u.Email = 'testuser@officedepot.com';
u.CompanyName = 'test.com';
u.Title = 'Test User';
u.Username = 'nitishuser@officedepot.com';
u.Alias = 'testuser';
u.CommunityNickname = 'Test User';
u.TimeZoneSidKey = 'America/Mexico_City';
u.LocaleSidKey = 'en_US';
u.EmailEncodingKey = 'ISO-8859-1';
u.ProfileId = pf.Id;
//u.Default_Group__c='All';
u.LanguageLocaleKey = 'en_US';
insert u;
system.runAs(u)
 {
Account acc = new Account();
acc.OwnerId=u.id; 
acc.name='test1';
insert acc;  

Reassignment_Queue__c rq = new Reassignment_Queue__c();
rq.Account__c = acc.id;
rq.Requestor__c = u.id;
rq.New_Owner__c = u.id;
rq.Approver__c = u.id;
rq.Status__c = 'Failed';
rq.Approve_Reject_Date__c= system.now();
insert rq;

test.starttest();
PageReference pgRef = Page.ReassignProspect;
Test.setCurrentPage(pgRef);
ApexPages.StandardController sc = new ApexPages.StandardController(acc);
ApexPages.currentPage().getParameters().put('id', acc.id);
ReassignAccount Resacc = new ReassignAccount(sc);
Resacc.createAssignment();
Resacc.SaveRecord();
Resacc.CancelRec();
Resacc.getaccList();
test.stoptest();



}
    
}
}