objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Extension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Extension</label>
        <referenceTo>Account_Extension__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address1__c</fullName>
        <label>Address1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Split_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Split Record</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer Accounts</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Account_Dormant__c.object
<CustomObject>
    <fields>
        <fullName>AccountExtension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Extension</label>
        <referenceTo>Account_Extension__c</referenceTo>
        <relationshipName>Account_Dormant</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address1__c</fullName>
        <externalId>true</externalId>
        <label>Address1</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Original_Account_ID__c</fullName>
        <externalId>true</externalId>
        <label>Original Account ID</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Dormant Account Duplicate</label>
    <nameField>
        <label>Account Dormant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dormant Account Duplicates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account_Extension__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Extensions (Account)</relationshipLabel>
        <relationshipName>Account_to_extension</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address1__c</fullName>
        <label>Address1</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Original_Account_ID__c</fullName>
        <externalId>true</externalId>
        <label>Original Account ID</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Split_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Split Record</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Extension</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Extensions</pluralLabel>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>[Customer]</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Customer_Transition__c.object
<CustomObject>
    <description>Object to Track Customer Conversion and Review Project</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Transition Relationship</relationshipLabel>
        <relationshipName>Customer_Transition_Relationship</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OMX_Primary_Key__c</fullName>
        <externalId>true</externalId>
        <label>OMX Primary Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Customer Transition</label>
    <nameField>
        <label>Customer Transition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Transition</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Account_TC.cls
@isTest
private class Account_TC {
  static testmethod void Accounttest_method(){
    //create test data
    
           // Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        /*User u = new User(Alias = 'st11', Email='standarduser@officedepot.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='dataloadernorth@officedepot.com');
insert u;*/

User u=[select Id, name from User where UserName='dataloadernorth@officedepot.com'];

    Account acc = Test_Utils.createAccount('Customer (OfficeMax)');
      acc.Name = 'TestOriginalAccount';
      acc.Split_Record__c = false;
      acc.OMX_Primary_Key__c = '123456';
     acc.address1__C = 'Test';

      insert acc;
      
           acc.address1__C = 'Test1';
 update acc;
             Account_Extension__c ae=[select id from account_extension__c where Original_Account_ID__c=:acc.id];                          
             
                          
             Account_Dormant__C ad = new Account_Dormant__c(AccountExtension__c = ae.id);
             insert ad;
             ae.address1__C='Test1';
             update ae;
             
                System.runas(u){
                Customer_Transition__C rec=[select Id from Customer_Transition__C where account__C=:acc.Id];
             delete rec;
                       delete acc;
      try{                 
      Account acc1 = Test_Utils.createAccount('Customer (OfficeMax)');
      acc1.Name = 'TestOriginalAccount';
      acc1.Split_Record__c = false;
      acc1.OMX_Primary_Key__c = '123456';
      acc1.address1__C = 'Test';
      acc1.Account_Extension__c=ae.Id;
      insert acc1;
} catch(Exception e) {}

                }
   
             
             
       }      
      }