objects/Account.object
<CustomObject>
    <fields>
        <fullName>Cust_ID__c</fullName>
        <formula>if( $RecordType.Name = &quot;Site&quot;, AOPS_Seq_ID__c , 
if( $RecordType.Name = &quot;Customer&quot; &amp;&amp; Grandparent__c = &quot;No&quot;, AOPS_Cust_Id__c, 
if( $RecordType.Name = &quot;Parent&quot; , AOPS_Cust_Id__c, 
if( $RecordType.Name = &quot;Great Grandparent&quot; , AOPS_Cust_Id__c, 
if( $RecordType.Name = &quot;GrandParent&quot;  &amp;&amp; LEN(AOPS_Cust_Id__c) = 1, &quot;0000000&quot; + AOPS_Cust_Id__c, 
if( $RecordType.Name = &quot;GrandParent&quot; &amp;&amp; LEN(AOPS_Cust_Id__c) = 2, &quot;000000&quot; + AOPS_Cust_Id__c, 
if( $RecordType.Name = &quot;GrandParent&quot; &amp;&amp; LEN(AOPS_Cust_Id__c) = 3, &quot;00000&quot; + AOPS_Cust_Id__c, 
if( $RecordType.Name = &quot;GrandParent&quot; &amp;&amp; LEN(AOPS_Cust_Id__c) = 4, &quot;0000&quot; + AOPS_Cust_Id__c, 
if( $RecordType.Name = &quot;GrandParent&quot;  &amp;&amp; LEN(AOPS_Cust_Id__c) = 5, &quot;000&quot; + AOPS_Cust_Id__c, 
if( $RecordType.Name = &quot;GrandParent&quot;  &amp;&amp; LEN(AOPS_Cust_Id__c) = 6, &quot;00&quot; + AOPS_Cust_Id__c, 
if( $RecordType.Name = &quot;Customer (OfficeMax)&quot; ,OMX_Mainframe_Account_Number__c, 
if( $RecordType.Name = &quot;Site (OfficeMax)&quot; ,OMX_Mainframe_Account_Number__c+ &apos;-&apos;+OMX_Mainframe_Consignee_ID__c, 
if( $RecordType.Name = &quot;Site (GT)&quot; ,OMX_Primary_Key__c, 
if( $RecordType.Name = &quot;Customer (GT)&quot; ,OMX_Primary_Key__c, 
null 
))))))))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cust ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ACE_Customer_Price_Changes__c.object
<CustomObject>
    <description>Price Change Process UI</description>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>ACE_Customer_Price_Changes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Owning_Customer_Legal__c</fullName>
        <label>Governed By Written Agreement (T/F)</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Unlock__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Record_Unlock</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reschduled_For_Reminder__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will capture if the notification date or sales price effective date has been modified by batch job for reminder or escalation</description>
        <label>Reschduled For Reminder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Price_Change_Effective_Date_Min__c</fullName>
        <description>This holds the min value of the sales price effective date for the SKUs</description>
        <label>Price Change Effective Date</label>
        <type>Date</type>
    </fields>
    <label>Customer Core Price Changes</label>
    <nameField>
        <label>Batch</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Core Price Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ACE_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is For ACE Custom Settings</description>
    <fields>
        <fullName>BatchName__c</fullName>
        <label>BatchName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EsclationDays__c</fullName>
        <label>EsclationDays</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expiry_Days__c</fullName>
        <label>Expiry Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Processing_Window__c</fullName>
        <label>Processing Window (In Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vendavo_Update_End_Date__c</fullName>
        <description>Vendavo Update End Date</description>
        <label>Vendavo Update End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vendavo_Update_Start_Date__c</fullName>
        <description>Vendavo Update Start Date</description>
        <label>Vendavo Update Start Date</label>
        <type>Date</type>
    </fields>
    <label>ACE_Settings</label>
</CustomObject>

classes/AceUnlockedAccounts_Homepg.cls
public with sharing class AceUnlockedAccounts_Homepg {

public ID custSKUChangesID {get;set;}
public String pageval {get;set;}
public Boolean skuRender {get;set;}
public Integer List_size = 50;
public Integer total_size{get;set;}
public Integer counter = 0;
public Map<ID,Integer> offset {get;set;}
public Integer reminderDays,escalationDays;
public List<ACE_Customer_Price_Changes__c> lUnlockAccounts{get;set;}

  

    public AceUnlockedAccounts_Homepg() {  
    	offset = new Map<ID,Integer> ();   
    	reminderDays=0;escalationDays=0;
    	ACE_Settings__c aceSetting =[SELECT Id,processing_window__c,EsclationDays__c,Expiry_Days__c, Name, BatchName__c,Vendavo_Update_Start_Date__c,Vendavo_Update_End_Date__c from ACE_Settings__c limit 1];      
        if (aceSetting.Expiry_Days__c != null)
          reminderDays = (Integer)aceSetting.Expiry_Days__c;
        if (aceSetting.EsclationDays__c != null)
          escalationDays = (Integer)aceSetting.EsclationDays__c;
        generateList();
    }
    
    public void generateList()
    {
        lUnlockAccounts = new list<ACE_Customer_Price_Changes__c>();        
        lUnlockAccounts= [select id,customer__r.owner.name,customer__r.name,customer__r.cust_ID__c,
                                  Sales_Price_Change_Effective_Date_Min__c,
                                  Reschduled_For_Reminder__c,
                                  Owning_Customer_Legal__c
                                            from ACE_Customer_Price_Changes__c 
                                            where Record_Unlock__c = true and customer__r.ownerID =: UserInfo.getUserID()
                                            limit :List_size OFFSET :counter]; 
        total_size = [select count() from ACE_Customer_Price_Changes__c where Record_Unlock__c = true and customer__r.ownerID =: UserInfo.getUserID()];                                        
        
        for (ace_customer_price_changes__c a: lUnlockAccounts) {

        	if (!a.Reschduled_For_Reminder__c) {
        	  if (a.Owning_Customer_Legal__c == 'T')
        	    offset.put(a.id,reminderDays+escalationDays);
        	  else
        	    offset.put(a.id,reminderDays);
        	}
        	else
        	  offset.put(a.id,0);
        	  
        }                          
                           
        
    }
    public void nextPage(){
        counter = counter+List_size; 
          
        generateList();
        
    }
    public void prevPage(){
        counter = counter-List_size;
        generateList();
       
    }
    
    public Boolean getDisablePrevious() {
     
      if (counter>0) return true; else return false;
    }
    
    public Boolean getDisableNext() { 
      if (counter + list_size < total_size) return true; else return false;
    }

}