objects/Account.object
<CustomObject>
    <fields>
        <fullName>AOPS_Cust_Id__c</fullName>
        <description>AOPS Customer Account Number</description>
        <externalId>true</externalId>
        <label>AOPS Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>AOPS_Seq_ID__c</fullName>
        <externalId>true</externalId>
        <label>AOPS Seq ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Oracle_Party_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Party ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Oracle_Party_Site_ID__c</fullName>
        <externalId>true</externalId>
        <label>Oracle Party Site ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer Accounts</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <description>Prospect Accounts</description>
        <label>Prospect</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/AccountAssignments__c.object
<CustomObject>
    <description>This object is used to store Overlay Account Assignments from Legacy system and also Primary rep (Owner Id) assignments. The data will be then picked up by a Batch Apex job to do actual Account Team Assignments.</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <description>This will store the Legacy Account ID</description>
        <externalId>true</externalId>
        <label>AccountId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountType__c</fullName>
        <description>Type of Account, Customer or Site etc...</description>
        <label>AccountType</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Id__c</fullName>
        <description>Entity Id it can be oracle_party_id, oracle_party_site_id, aops_cust_id or aops_seq_id.</description>
        <externalId>true</externalId>
        <label>Entity Id</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CUSTOMER</fullName>
                </value>
                <value>
                    <fullName>PROSPECT</fullName>
                </value>
                <value>
                    <fullName>ODN Customer</fullName>
                </value>
                <value>
                    <fullName>ODS Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OverlayEmpID10__c</fullName>
        <description>Employee Id of Overlay Employee 10, which is assigned to Account Team</description>
        <label>Overlay Emp ID 10</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID11__c</fullName>
        <description>Employee Id of Overlay Employee 11, which is assigned to Account Team</description>
        <label>Overlay Emp ID 11</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID12__c</fullName>
        <description>Employee Id of Overlay Employee 12, which is assigned to Account Team</description>
        <label>Overlay Emp ID 12</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID13__c</fullName>
        <description>Employee Id of Overlay Employee 13, which is assigned to Account Team</description>
        <label>Overlay Emp ID 13</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID14__c</fullName>
        <description>Employee Id of Overlay Employee 14, which is assigned to Account Team</description>
        <label>Overlay Emp ID 14</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID15__c</fullName>
        <description>Employee Id of Overlay Employee 15, which is assigned to Account Team</description>
        <label>Overlay Emp ID 15</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID1__c</fullName>
        <description>Employee Id of Overlay Employee 1, which is assigned to Account Team</description>
        <label>Overlay Emp ID 1</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID2__c</fullName>
        <description>Employee Id of Overlay Employee 2, which is assigned to Account Team</description>
        <label>Overlay Emp ID 2</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID3__c</fullName>
        <description>Employee Id of Overlay Employee 3, which is assigned to Account Team</description>
        <label>Overlay Emp ID 3</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID4__c</fullName>
        <description>Employee Id of Overlay Employee 4, which is assigned to Account Team</description>
        <label>Overlay Emp ID 4</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID5__c</fullName>
        <description>Employee Id of Overlay Employee 5, which is assigned to Account Team</description>
        <label>Overlay Emp ID 5</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID6__c</fullName>
        <description>Employee Id of Overlay Employee 6, which is assigned to Account Team</description>
        <label>Overlay Emp ID 6</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID7__c</fullName>
        <description>Employee Id of Overlay Employee 7, which is assigned to Account Team</description>
        <label>Overlay Emp ID 7</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID8__c</fullName>
        <description>Employee Id of Overlay Employee 8, which is assigned to Account Team</description>
        <label>Overlay Emp ID 8</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpID9__c</fullName>
        <description>Employee Id of Overlay Employee 9, which is assigned to Account Team</description>
        <label>Overlay Emp ID 9</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole10__c</fullName>
        <label>Overlay Emp Role 10</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole11__c</fullName>
        <label>Overlay Emp Role 11</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole12__c</fullName>
        <label>Overlay Emp Role 12</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole13__c</fullName>
        <label>Overlay Emp Role 13</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole14__c</fullName>
        <label>Overlay Emp Role 14</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole15__c</fullName>
        <label>Overlay Emp Role 15</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole1__c</fullName>
        <label>Overlay Emp Role 1</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole2__c</fullName>
        <label>Overlay Emp Role 2</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole3__c</fullName>
        <label>Overlay Emp Role 3</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole4__c</fullName>
        <label>Overlay Emp Role 4</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole5__c</fullName>
        <label>Overlay Emp Role 5</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole6__c</fullName>
        <label>Overlay Emp Role 6</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole7__c</fullName>
        <label>Overlay Emp Role 7</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole8__c</fullName>
        <label>Overlay Emp Role 8</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverlayEmpRole9__c</fullName>
        <label>Overlay Emp Role 9</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryEmpId__c</fullName>
        <description>Primary Employee id, mapped to Owner Id of the Account</description>
        <label>Primary Emp Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryEmpRole__c</fullName>
        <description>Role of the Primary Employee</description>
        <label>Primary Emp Role</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the record will be Open when created. Process when success and Error on issues</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Partially Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>AccountTeamAssignment</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>AssignmentsNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountTeamAssignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountAssignments_Clean_Batch_TC.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
Description: This Is test class to do unit testing and check test code coverage for class 'AccountAssignments_Clean_Batch'.

Created By: Sunil Bansal
Created Date: 21-May-2012

Modified By:
Modified Date:

Modify Reason:
 
 */
@isTest
private class AccountAssignments_Clean_Batch_TC 
{

    static testMethod void myUnitTest() 
    {
        Account acc = new Account ();
        acc.name = 'SUN Test Account';
        acc.BillingStreet = '1040 N 326 W';
        acc.billingcity = 'Orem';
        acc.BillingState = 'UT';
        acc.Billingcountry = 'USA';
        acc.Oracle_Party_Id__c = '123456';
        acc.AOPS_Cust_Id__c = '123456';
        acc.AOPS_Seq_ID__c = '123456';
        insert acc;
        
        Account accSite = new Account ();
        accSite.name = 'SUN Test Account';
        accSite.BillingStreet = '1040 N 326 W';
        accSite.billingcity = 'Orem';
        accSite.BillingState = 'UT';
        accSite.Billingcountry = 'USA';
        accSite.Oracle_Party_Site_Id__c = '12345678';
        accSite.AOPS_Cust_Id__c = '12345678';
        accSite.AOPS_Seq_ID__c = '12345678';
        insert accSite;

        AccountAssignments__c assign1 = new AccountAssignments__c();
        assign1.AccountId__c = '123456';
        assign1.AccountType__c = 'A';
        assign1.Entity_Type__c = 'CUSTOMER';
        assign1.Entity_Id__c = '1234568763';
        assign1.PrimaryEmpId__c = '439874';
        assign1.PrimaryEmpRole__c = 'TestRole';
        assign1.OverlayEmpID1__c = '179556';
        assign1.OverlayEmpRole1__c = '11111';
        assign1.OverlayEmpID2__c = '595673';
        assign1.OverlayEmpRole2__c = '22222';
        assign1.OverlayEmpID3__c = '601832';
        assign1.OverlayEmpRole3__c = '333333';
        assign1.OverlayEmpID4__c = '234567';
        assign1.OverlayEmpRole4__c = '44444';
        assign1.OverlayEmpID5__c = '234567';
        assign1.OverlayEmpRole5__c = '44444';
        assign1.OverlayEmpID6__c = '234567';
        assign1.OverlayEmpRole6__c = '44444';
        assign1.OverlayEmpID7__c = '234567';
        assign1.OverlayEmpRole7__c = '44444';
        assign1.OverlayEmpID8__c = '234567';
        assign1.OverlayEmpRole8__c = '44444';
        assign1.OverlayEmpID9__c = '234567';
        assign1.OverlayEmpRole9__c = '44444';
        assign1.OverlayEmpID10__c = '234567';
        assign1.OverlayEmpRole10__c = '44444';
        assign1.OverlayEmpID11__c = '234567';
        assign1.OverlayEmpRole11__c = '44444';
        assign1.OverlayEmpID12__c = '234567';
        assign1.OverlayEmpRole12__c = '44444';
        assign1.OverlayEmpID13__c = '234567';
        assign1.OverlayEmpRole13__c = '44444';
        assign1.OverlayEmpID14__c = '234567';
        assign1.OverlayEmpRole14__c = '44444';
        assign1.OverlayEmpID15__c = '234567';
        assign1.OverlayEmpRole15__c = '44444';
        assign1.Status__c = 'TestData';
        
        insert assign1;

        AccountAssignments__c assign2 = new AccountAssignments__c();
        assign2.AccountId__c = '12345678';
        assign2.AccountType__c = 'S';
        assign2.Entity_Type__c = 'CUSTOMER';
        assign2.Entity_Id__c = '1234567238';
        assign2.PrimaryEmpId__c = '179475';
        assign2.PrimaryEmpRole__c = 'TestRole';
        assign2.OverlayEmpID1__c = '104344';
        assign2.OverlayEmpRole1__c = '111111';
        assign2.OverlayEmpID2__c = '595673';
        assign2.OverlayEmpRole2__c = '222222';
        assign2.OverlayEmpID3__c = '600980';
        assign2.OverlayEmpRole3__c = '333333';
        assign2.OverlayEmpID4__c = '';
        assign2.OverlayEmpRole4__c = '';
        assign2.Status__c = 'Processed';
        
        insert assign2;        
   
        AccountAssignments__c assign3 = new AccountAssignments__c();
        assign3.AccountId__c = '1234567890';
        assign3.AccountType__c = 'S';
        assign3.Entity_Type__c = 'PROSPECT';
        assign3.Entity_Id__c = '1234567845';
        assign3.PrimaryEmpId__c = '179475';
        assign3.PrimaryEmpRole__c = 'TestRole';
        assign3.OverlayEmpID1__c = '104344';
        assign3.OverlayEmpRole1__c = '111111';
        assign3.Status__c = 'Processed';
        
        insert assign3; 

        
        Test.startTest();
            DateTime dt = DateTime.now();
            String strQuery = 'Select Id from AccountAssignments__c where Status__c = \'Processed\' ';
            AccountAssignments_Clean_Batch assignCleanBatch = new AccountAssignments_Clean_Batch(strQuery);
            database.executebatch(assignCleanBatch, 2000);
            
            // added for the story #S-418600 (00715635) #START
            AccountAssignments_Clean_Batch assignCleanBatch1 = new AccountAssignments_Clean_Batch();
            AccountAssignments_Clean_Batch assignCleanBatch2 = new AccountAssignments_Clean_Batch('');
            
            String CRON_EXP = '0 0 0 3 9 ? 2022';       
            System.schedule('Assignment clean Batch',CRON_EXP , assignCleanBatch);
            
            system.assertNotEquals(assignCleanBatch2, null);
            
            // added for the story #S-418600 (00715635) #END
            
        Test.stopTest();

    }
}