objects/Account.object
<CustomObject>
    <fields>
        <fullName>AOPS_Cust_Id__c</fullName>
        <description>AOPS Customer Account Number</description>
        <externalId>true</externalId>
        <label>AOPS Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Site</fullName>
    </fields>
    <recordTypes>
        <fullName>Site</fullName>
        <active>true</active>
        <label>Site</label>
    </recordTypes>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Account_Final_Staging__c.object
<CustomObject>
    <description>This is used for data sync from AOPS to SFDC.</description>
    <fields>
        <fullName>AOPS_Cust_Id__c</fullName>
        <description>AOPS Customer Account Number</description>
        <externalId>true</externalId>
        <label>AOPS Id</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Number_Of_Attempts__c</fullName>
        <label>Number Of Attempts</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sync_Failed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync Failed</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Final Staging</label>
    <nameField>
        <label>Account Final Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts Final Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account_Site_Final_Staging__c.object
<CustomObject>
    <description>This object is account site final staging for AOPS to SFDC sync to store AOPS account address sequences.</description>
    <fields>
        <fullName>AOPS_Cust_Id__c</fullName>
        <label>AOPS Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Address_Master_Changed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Address Master Changed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_Of_Attempts__c</fullName>
        <label>Number Of Attempts</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sync_Failed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync Failed</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Site Final Staging</label>
    <nameField>
        <label>Account Site Final Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Sites Final Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sync_batch_setting__mdt.object
<CustomObject>
    <fields>
        <fullName>batch_size__c</fullName>
        <label>batch size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>delay_next_job__c</fullName>
        <label>delay next job</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>sync batch setting</label>
    <pluralLabel>sync batch settings</pluralLabel>
</CustomObject>

classes/AOPSAccountRetryProcessor.cls
public class AOPSAccountRetryProcessor implements Queueable {

    private List<String> accountIdList;
    private static Integer NO_OF_RETRIES = 1;

    public AOPSAccountRetryProcessor(List<String> accountIdList) {
        this.accountIdList = accountIdList;
    }

    public void execute(QueueableContext context) {
        Savepoint sp = Database.setSavepoint();
        list<sync_batch_setting__mdt> sbs= [SELECT Id, batch_size__c, delay_next_job__c from sync_batch_setting__mdt where DeveloperName='number_of_retries' limit 1];
        if(sbs.size()>0) {
            NO_OF_RETRIES =sbs[0].batch_size__c.intValue();
        }     

        try {
            List<Account_Final_Staging__c> accountFinalStagingList = [SELECT Id, aops_cust_id__c, Sync_Failed__c, Number_Of_Attempts__c FROM Account_Final_Staging__c 
            WHERE Sync_Failed__c = true and (Number_Of_Attempts__c = null or Number_Of_Attempts__c < :NO_OF_RETRIES) AND aops_cust_id__c IN :accountIdList];
            for (Account_Final_Staging__c acctRec : accountFinalStagingList) {
                acctRec.Sync_Failed__c = false;
                if (acctRec.Number_Of_Attempts__c == null) 
                    acctRec.Number_Of_Attempts__c = 1;
                else
                    acctRec.Number_Of_Attempts__c = acctRec.Number_Of_Attempts__c + 1;
            }
            update accountFinalStagingList;
        } catch(Exception ex) {
            System.debug('AOPSAccountCronJob: Exception while retrying failed records for account final staging records.'+ ex.getMessage());
        }

        try {
            List<Account_Site_Final_Staging__c> siteList = [SELECT Id, aops_cust_id__c, Sync_Failed__c, Number_Of_Attempts__c FROM Account_Site_Final_Staging__c 
            WHERE ((Is_Address_Master_Changed__c = true and sync_failed__c = false) or sync_failed__c = true) and (Number_Of_Attempts__c = null or Number_Of_Attempts__c < :NO_OF_RETRIES) AND aops_cust_id__c IN :accountIdList];
            for (Account_Site_Final_Staging__c site : siteList) {
                site.Sync_Failed__c = false;
                if (site.Number_Of_Attempts__c == null) 
                    site.Number_Of_Attempts__c = 1;
                else
                    site.Number_Of_Attempts__c = site.Number_Of_Attempts__c + 1;
            }
            update siteList;
        } catch(Exception ex) {
            System.debug('AOPSAccountCronJob: Exception while retrying failed records for account site final staging records.'+ ex.getMessage());
        }
    }
}