objects/Ace_Customer_Core_Changes__c.object
<CustomObject>
    <description>Price Change Process UI</description>
    <fields>
        <fullName>ACE_Customer_Price_Changes__c</fullName>
        <label>Batch</label>
        <referenceTo>ACE_Customer_Price_Changes__c</referenceTo>
        <relationshipLabel>Customer Core Changes</relationshipLabel>
        <relationshipName>Ace_Customer_Core_Changes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>batchId__c</fullName>
        <label>batchId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Customer Core Changes</label>
    <nameField>
        <label>Core</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Core Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ACE_Customer_Price_Changes__c.object
<CustomObject>
    <description>Price Change Process UI</description>
    <fields>
        <fullName>batchId__c</fullName>
        <label>batchId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Customer Core Price Changes</label>
    <nameField>
        <label>Batch</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Core Price Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AceCustomerCoreChangesButtons.cls
public class AceCustomerCoreChangesButtons {
 


  public String batch {get;set;}
  public ID customerPriceID {get;set;}
  public Ace_Customer_Core_Changes__c aceCustCoreChanges {get;set;}
  public boolean Redirect {get;set;}
  public String redirectURL {get;set;}
  
  public AceCustomerCoreChangesButtons(ApexPages.StandardController controller) {
     
     Redirect = false; 
     aceCustCoreChanges = (Ace_Customer_Core_Changes__c)controller.getRecord();
     Ace_Customer_Core_Changes__c ap = [SELECT ACE_Customer_Price_Changes__r.id,ACE_Customer_Price_Changes__r.batchid__c from Ace_Customer_Core_Changes__c  where id = :aceCustCoreChanges.id];
     
     batch = ap.ACE_Customer_Price_Changes__r.batchid__c;
     customerPriceID = ap.ACE_Customer_Price_Changes__r.id;
     
     
       
  }
  
 
  
  public void summaryGridRedirect() { 
    Redirect = true;
    redirectURL = '/apex/ACE_Summary_Grid_New?batch=' + batch;
  }
  
  public void customerPriceRedirect() { 
    Redirect = true;
    redirectURL = '/' + customerPriceID;
  }

  
  }