objects/AOPS_Contact_Phone__c.object
<CustomObject>
    <description>Sync staging data</description>
    <fields>
        <fullName>CCU320F_AREA_CODE__c</fullName>
        <label>AREA CODE</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCU320F_BRAND__c</fullName>
        <label>BRAND CODE</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCU320F_CNTRY_CODE__c</fullName>
        <label>COUNTRY CODE</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCU320F_CONTACT_DFT_NUMBER__c</fullName>
        <label>CNT DEFAULT NUMBER</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCU320F_CONTACT_ID__c</fullName>
        <externalId>true</externalId>
        <label>CONTACT ID</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCU320F_CUSTOMER_ID__c</fullName>
        <externalId>true</externalId>
        <label>CUSTOMER ID</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCU320F_EXTENSION__c</fullName>
        <label>EXTENSION</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCU320F_INVALID_PHONE__c</fullName>
        <label>INVALD PHONE FLAG</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCU320F_LESS_PHONE__c</fullName>
        <label>LESS PHONE</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCU320F_NBR_TYPE__c</fullName>
        <label>NUMBER TYPE</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCU320F_NUMBER__c</fullName>
        <label>NUMBER</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCU320F_PHONE_SEQ__c</fullName>
        <label>PHONE SEQ</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCU320F_PREFIX__c</fullName>
        <label>PREFIX</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CXTCNTP_ACTION__c</fullName>
        <label>Action</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CXTCNTP_AOPS_KEY1__c</fullName>
        <label>AOPS KEY1 Account/Prospect</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CXTCNTP_AOPS_KEY2__c</fullName>
        <label>AOPS KEY2 Address/Contact</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CXTCNTP_AOPS_KEY3__c</fullName>
        <label>AOPS KEY3 Contact point/...</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CXTCNTP_MSG_TYPE__c</fullName>
        <label>Message Type</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CXTCNTP_TIMESTAMP__c</fullName>
        <label>DB TIMESTAMP</label>
        <length>26</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Updated__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Record Updated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SYNC_STATUS_MESSAGE__c</fullName>
        <externalId>true</externalId>
        <label>SYNC STATUS MESSAGE</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_Record_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unique Record ID</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>AOPS Contact Phone</label>
    <nameField>
        <label>AOPS Contact Phone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AOPS Contact Phones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AOPSContactPhoneProcessor.cls
public class AOPSContactPhoneProcessor {

    public static boolean process(Map<String,Object> aopsDataMap) {
        
        if (aopsDataMap == null) {
            return false;
        }
        AOPS_CONTACT_PHONE__c contactPhone = new AOPS_CONTACT_PHONE__c();
        populateObject(aopsDataMap, contactPhone);
        
        Schema.SObjectField uniqueField = AOPS_CONTACT_PHONE__c.Fields.Unique_Record_ID__c;                
        Database.UpsertResult upsertResult = Database.upsert(contactPhone, uniqueField, false);
        return upsertResult.isSuccess();
    }
    
    private static void populateObject(Map<String,Object> source, AOPS_CONTACT_PHONE__c target) {
        
        target.Unique_Record_ID__c = String.valueOf(Integer.valueOf((String)source.get('CXTCNTP_AOPS_KEY1'))) + 
            						 String.valueOf(Integer.valueOf((String)source.get('CXTCNTP_AOPS_KEY2'))) + 
                            		 String.valueOf(Integer.valueOf((String)source.get('CXTCNTP_AOPS_KEY3')));
        target.CXTCNTP_MSG_TYPE__c = (String) source.get('CXTCNTP_MSG_TYPE');
        target.CXTCNTP_AOPS_KEY1__c = String.valueOf(Integer.valueOf((String) source.get('CXTCNTP_AOPS_KEY1')));
        target.CXTCNTP_AOPS_KEY2__c = String.valueOf(Integer.valueOf((String) source.get('CXTCNTP_AOPS_KEY2')));
        target.CXTCNTP_AOPS_KEY3__c = String.valueOf(Integer.valueOf((String) source.get('CXTCNTP_AOPS_KEY3')));
        target.CXTCNTP_TIMESTAMP__c = (String) source.get('CXTCNTP_TIMESTAMP');
        target.CCU320F_PHONE_SEQ__c = String.valueOf(Integer.valueOf((String)source.get('CCU320F_PHONE_SEQ'))); 
        target.CCU320F_CONTACT_ID__c = String.valueOf(Integer.valueOf((String)source.get('CCU320F_CONTACT_ID')));
        target.CCU320F_CUSTOMER_ID__c = String.valueOf(Integer.valueOf((String)source.get('CCU320F_CUSTOMER_ID')));        
        target.CCU320F_CNTRY_CODE__c = (String) source.get('CCU320F_CNTRY_CODE');
        target.CCU320F_AREA_CODE__c = (String) source.get('CCU320F_AREA_CODE');
        target.CCU320F_PREFIX__c = (String) source.get('CCU320F_PREFIX');
        target.CCU320F_NUMBER__c = (String) source.get('CCU320F_NUMBER');
        target.CCU320F_EXTENSION__c = (String) source.get('CCU320F_EXTENSION');
        target.CCU320F_NBR_TYPE__c = (String) source.get('CCU320F_NBR_TYPE');
        target.CCU320F_CONTACT_DFT_NUMBER__c = (String) source.get('CCU320F_CONTACT_DFT_NUMBER');
        target.CCU320F_LESS_PHONE__c = (String) source.get('CCU320F_LESS_PHONE');
        target.CCU320F_INVALID_PHONE__c = (String) source.get('CCU320F_INVALID_PHONE');
        target.CCU320F_BRAND__c = (String) source.get('CCU320F_BRAND');
        target.CXTCNTP_ACTION__c = (String) source.get('CXTCNTP_ACTION');
        target.SYNC_STATUS_MESSAGE__c = '';
        // Specify that the record has been updated. Note that this will be reset
        // to false in a trigger if the request is not the most recent one.
        target.Record_Updated__c = true;
    }
}