objects/AOPS_STG_CONTACT_MASTER__c.object
<CustomObject>
    <fields>
        <fullName>CCU300F_NAME_1__c</fullName>
        <label>CCU300F_NAME_1</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CXTCNTM_TIMESTAMP__c</fullName>
        <label>DB TIMESTAMP</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_Record_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unique Record ID</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>AOPS CONTACT MASTER</label>
    <nameField>
        <label>AOPS STAGING CONTACT MASTER</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AOPS CONTACT MASTER</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AOPSContactMasterTrigger_TC.cls
@IsTest
public class AOPSContactMasterTrigger_TC {

    @IsTest
    static void insertRecord() {
        AOPS_STG_CONTACT_MASTER__c stagingRecord1 = new AOPS_STG_CONTACT_MASTER__c(Unique_Record_ID__c='123456', CCU300F_NAME_1__c ='Te', CXTCNTM_TIMESTAMP__c='2020-03-30-01.03.14.3151');
        Schema.SObjectField uniqueField = AOPS_STG_CONTACT_MASTER__c.Fields.Unique_Record_ID__c;                
        Database.UpsertResult upsertResult = Database.upsert(stagingRecord1, uniqueField, false);
        
        AOPS_STG_CONTACT_MASTER__c stagingRecord2 = new AOPS_STG_CONTACT_MASTER__c(Unique_Record_ID__c='123456', CCU300F_NAME_1__c ='Te', CXTCNTM_TIMESTAMP__c='2020-03-30-01.03.14.3150');
        uniqueField = AOPS_STG_CONTACT_MASTER__c.Fields.Unique_Record_ID__c;                
        upsertResult = Database.upsert(stagingRecord2, uniqueField, false);
    }
    
}