objects/AOPS_Contact_Ship_Address__c.object
<CustomObject>
    <fields>
        <fullName>CCU310F_ADDR_SEQ__c</fullName>
        <label>Address Seq</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCU310F_ALLOW_BUY__c</fullName>
        <label>Allowed to Buy</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCU310F_CONTACT_ID__c</fullName>
        <externalId>true</externalId>
        <label>Contact ID</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCU310F_CUSTOMER_ID__c</fullName>
        <label>Customer ID</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCU310F_DFT_SHIP_CONT__c</fullName>
        <label>Default Ship Contact</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CXTCNTS_TIMESTAMP__c</fullName>
        <label>DB TIMESTAMP</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Updated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Record Updated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unique_Record_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unique Record ID</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>AOPS Contact Ship Address</label>
    <nameField>
        <label>AOPS Contact Ship Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AOPS Contact Ship Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact_Final_Staging__c.object
<CustomObject>
    <fields>
        <fullName>AOPS_Account_Number__c</fullName>
        <label>AOPS Account Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AOPS_Contact_Number__c</fullName>
        <label>AOPS Contact Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_Record_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unique Record ID</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Contact Final Staging</label>
    <nameField>
        <label>Contact Final Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts Final Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AOPSContactShipToFinalProcessor_TC.cls
@IsTest
public class AOPSContactShipToFinalProcessor_TC {
    @isTest
    public static void makedata() {
         List<AOPS_Contact_Ship_Address__c> contactMasterRecs = new List<AOPS_Contact_Ship_Address__c> {
            new AOPS_Contact_Ship_Address__c(Unique_Record_ID__c='111111111', CCU310F_CONTACT_ID__c='111111111', CCU310F_ADDR_SEQ__c='0001', CCU310F_DFT_SHIP_CONT__c='Y', CCU310F_ALLOW_BUY__c='N', CXTCNTS_TIMESTAMP__c='2020-06-30-01.03.14.3151', CCU310F_CUSTOMER_ID__c='9558038' ,Record_Updated__c=true),
            new AOPS_Contact_Ship_Address__c(Unique_Record_ID__c='111111112', CCU310F_CONTACT_ID__c='111111112', CCU310F_ADDR_SEQ__c='0002', CCU310F_DFT_SHIP_CONT__c='Y', CCU310F_ALLOW_BUY__c='N', CXTCNTS_TIMESTAMP__c='2020-06-30-01.03.14.3151', CCU310F_CUSTOMER_ID__c='9558037' ,Record_Updated__c=true),
            new AOPS_Contact_Ship_Address__c(Unique_Record_ID__c='111111113', CCU310F_CONTACT_ID__c='111111113', CCU310F_ADDR_SEQ__c='0003', CCU310F_DFT_SHIP_CONT__c='Y', CCU310F_ALLOW_BUY__c='N', CXTCNTS_TIMESTAMP__c='2020-06-30-01.03.14.3151', CCU310F_CUSTOMER_ID__c='9558036' ,Record_Updated__c=true) };
            
          insert contactMasterRecs;

        List<Contact_Final_Staging__c> finalStagingRec = new List<Contact_Final_Staging__c>{
            new Contact_Final_Staging__c  (Unique_Record_ID__c='111111111', AOPS_Contact_Number__c='111111111' ,AOPS_Account_Number__c='9558038'),
            new Contact_Final_Staging__c  (Unique_Record_ID__c='111111112', AOPS_Contact_Number__c='111111112' ,AOPS_Account_Number__c='9558037'),
            new Contact_Final_Staging__c  (Unique_Record_ID__c='111111113', AOPS_Contact_Number__c='111111113' ,AOPS_Account_Number__c='9558036')};
            
        insert finalStagingRec;
       
        test.startTest();
        System.enqueueJob(new AOPSContactShipToFinalProcessor(contactMasterRecs));
        test.stopTest();
    }
}