objects/CameleonCPQ__QxQuoteLine__c.object
<CustomObject>
    <description>PROS Smart CPQx Quote Line</description>
    <fields>
        <fullName>CameleonCPQ__LineTemplateId__c</fullName>
        <label>Line Template Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CameleonCPQ__QuoteId__c</fullName>
        <label>Quote</label>
        <referenceTo>CameleonCPQ__QxQuote__c</referenceTo>
        <relationshipLabel>PROS Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Compliance_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Compliance Quote</label>
        <referenceTo>CameleonCPQ__QxQuote__c</referenceTo>
        <relationshipLabel>CPTs</relationshipLabel>
        <relationshipName>CPTs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Compliance_Violation_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Compliance Violation Quote</label>
        <referenceTo>CameleonCPQ__QxQuote__c</referenceTo>
        <relationshipLabel>Compliance Violations</relationshipLabel>
        <relationshipName>Compliance_Violation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Core_Ineligible__c</fullName>
        <label>Core Ineligible</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>Quote can’t be moved forward with workflow (Submit/Approve/Published).</description>
        <label>Error Message</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Executive_Summary_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Executive Summary Quote</label>
        <referenceTo>CameleonCPQ__QxQuote__c</referenceTo>
        <relationshipLabel>Executive Summary</relationshipLabel>
        <relationshipName>ExecutiveSummary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricing_Type__c</fullName>
        <label>Pricing Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Quote</label>
        <referenceTo>CameleonCPQ__QxQuote__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rebate_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rebate Quote</label>
        <referenceTo>CameleonCPQ__QxQuote__c</referenceTo>
        <relationshipLabel>Rebates</relationshipLabel>
        <relationshipName>Rebates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sync_Proposed__c</fullName>
        <label>Final Proposed</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>PROS Quote Line</label>
    <nameField>
        <label>Item Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PROS Quote Lines</pluralLabel>
    <recordTypes>
        <fullName>CPT</fullName>
        <active>true</active>
        <label>CPT</label>
    </recordTypes>
    <recordTypes>
        <fullName>InheritedCPT</fullName>
        <active>true</active>
        <label>InheritedCPT</label>
    </recordTypes>
    <recordTypes>
        <fullName>Product</fullName>
        <active>true</active>
        <label>Product</label>
    </recordTypes>
    <recordTypes>
        <fullName>Rebate</fullName>
        <active>true</active>
        <label>Rebate</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/QxCPQQuoteLineItemHelper.cls
/*
 * Copyright (c) 2018 by PROS, Inc.  All Rights Reserved.
 * This software is the confidential and proprietary information of
 * PROS, Inc. ("Confidential Information").
 * You may not disclose such Confidential Information, and may only
 * use such Confidential Information in accordance with the terms of
 * the license agreement you entered into with PROS.
 *
 *
 *@author : Romain Derval
 */
public class QxCPQQuoteLineItemHelper {
   
    /*
    * Assign Quote Line Item Record Type & Filtered Quote Look Up
    */ 
    public static void assignQuoteLineType(List<CameleonCPQ__QxQuoteLine__c> qlis){
        //Retrieve Quote Line Items Record Type List
        Id productRTId = Schema.SObjectType.CameleonCPQ__QxQuoteLine__c.getRecordTypeInfosByName().get('Product').getRecordTypeId();
        Id rebateRTId = Schema.SObjectType.CameleonCPQ__QxQuoteLine__c.getRecordTypeInfosByName().get('Rebate').getRecordTypeId();
        Id cptRTId = Schema.SObjectType.CameleonCPQ__QxQuoteLine__c.getRecordTypeInfosByName().get('CPT').getRecordTypeId();
        Id complianceViolationRTId = Schema.SObjectType.CameleonCPQ__QxQuoteLine__c.getRecordTypeInfosByName().get('Compliance Violation').getRecordTypeId();
        Id executiveSummaryRTId = Schema.SObjectType.CameleonCPQ__QxQuoteLine__c.getRecordTypeInfosByName().get('Executive Summary').getRecordTypeId();        
        Id inheritedCPTRTId = Schema.SObjectType.CameleonCPQ__QxQuoteLine__c.getRecordTypeInfosByName().get('InheritedCPT').getRecordTypeId();
        
        for(CameleonCPQ__QxQuoteLine__c qli : qlis){
            
            if(qli.CameleonCPQ__LineTemplateId__c!=null){
                if(qli.CameleonCPQ__LineTemplateId__c =='ComplianceViolationLT'){
                    qli.RecordTypeId = complianceViolationRTId;
                    qli.Compliance_Quote__c = null;
                    qli.Product_Quote__c = null;
                    qli.Rebate_Quote__c = null;
                    qli.Compliance_Violation_Quote__c=qli.CameleonCPQ__QuoteId__c;
                    qli.Executive_Summary_Quote__c=null;
                }else if(qli.CameleonCPQ__LineTemplateId__c =='ComplianceLT'){
                    qli.RecordTypeId = cptRTId;
                    qli.Compliance_Quote__c = qli.CameleonCPQ__QuoteId__c;
                    qli.Product_Quote__c = null;
                    qli.Rebate_Quote__c = null;
                    qli.Compliance_Violation_Quote__c=null;
                    qli.Executive_Summary_Quote__c=null;
                }else if(qli.CameleonCPQ__LineTemplateId__c =='InheritedComplianceLT' || qli.CameleonCPQ__LineTemplateId__c =='InheritedCompliancePerDeptLT' ){
                    qli.RecordTypeId = inheritedCPTRTId;
                    qli.Compliance_Quote__c = null;
                    qli.Product_Quote__c = null;
                    qli.Rebate_Quote__c = null;
                    qli.Compliance_Violation_Quote__c=null;
                    qli.Executive_Summary_Quote__c=null;
                }else if(qli.CameleonCPQ__LineTemplateId__c =='ExecutiveSummaryLT'){
                    qli.RecordTypeId = executiveSummaryRTId;
                    qli.Compliance_Quote__c = null;
                    qli.Product_Quote__c = null;
                    qli.Rebate_Quote__c = null;
                    qli.Compliance_Violation_Quote__c=null;
                    qli.Executive_Summary_Quote__c=qli.CameleonCPQ__QuoteId__c; 
                }else if(qli.CameleonCPQ__LineTemplateId__c =='ProductLineTemplate'){
                    qli.RecordTypeId = productRTId;
                    qli.Product_Quote__c = qli.CameleonCPQ__QuoteId__c;
                    qli.Rebate_Quote__c = null;
                    qli.Compliance_Quote__c = null;
                    qli.Compliance_Violation_Quote__c=null;
                    qli.Executive_Summary_Quote__c=null;
                    
                    //Assign Error Message
                    if(qli.Pricing_Type__c == 'Core' && qli.Core_Ineligible__c=='Y'){
                        qli.Error_Message__c='The product is not eligible for core';
                    }else if (qli.Sync_Proposed__c < 0.01){
                        qli.Error_Message__c='Cannot price below $0.01';
                    }
                }else if(qli.CameleonCPQ__LineTemplateId__c =='RebateLT'){
                    qli.RecordTypeId = rebateRTId;
                    qli.Rebate_Quote__c = qli.CameleonCPQ__QuoteId__c;
                    qli.Product_Quote__c = null;
                    qli.Compliance_Quote__c = null;
                    qli.Compliance_Violation_Quote__c=null;
                    qli.Executive_Summary_Quote__c=null;
                }
            }

            }
        }
 

}