objects/Case_Message__c.object
<CustomObject>
    <description>Case Message with details for any attachments or comments created on the case.</description>
    <fields>
        <fullName>Account_Number__c</fullName>
        <description>The account number pulled from the Account.Cust_ID__c field on the case.</description>
        <inlineHelpText>The account number pulled from the Account.Cust_ID__c field on the case.</inlineHelpText>
        <label>Account Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attachment_Id__c</fullName>
        <description>The Attactment id for the case if there is one.</description>
        <label>Attachment Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Case_Comment_Id__c</fullName>
        <description>The comment for the case if there is one.</description>
        <label>Case Comment Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Case_Message_Action__c</fullName>
        <description>The action for the message.</description>
        <label>Case Message Action</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Case_Message_Actions</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Message_Destination__c</fullName>
        <description>What is the destination system for this message.</description>
        <label>Case Message Destination</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Case_Message_Destination</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Message_Status__c</fullName>
        <description>The status of the Case Message</description>
        <label>Case Message Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Case_Message_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>The Case associated with the message.</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Messages</relationshipLabel>
        <relationshipName>Case_Messages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <description>The CreatedBy user&apos;s first name.</description>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Freshdesk_Id__c</fullName>
        <description>The Id of the freshdesk ticket.</description>
        <inlineHelpText>The Id of the freshdesk ticket.</inlineHelpText>
        <label>Freshdesk Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Freshdesk_Queue__c</fullName>
        <defaultValue>&quot;6000024568&quot;</defaultValue>
        <description>The Freshdesk Queue Id corresponding to to a group/queue in Freshdesk.</description>
        <label>Freshdesk Queue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Freshdesk_Type__c</fullName>
        <description>The type used to post to freshdesk.</description>
        <label>Freshdesk Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <description>The CreatedBy user&apos;s last name.</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OracleCX_Id__c</fullName>
        <description>The Id of the incident in the Oracle CX System.</description>
        <inlineHelpText>The Id of the incident in the Oracle CX System.</inlineHelpText>
        <label>OracleCX Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OracleCX_Queue__c</fullName>
        <defaultValue>&quot;Default&quot;</defaultValue>
        <description>The Oracle CX Queue Id corresponding to to a group/queue in OCX.</description>
        <label>OracleCX Queue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>The Phone number of the user, used to create cases in OracleCX</description>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Queue_Developer_Name__c</fullName>
        <description>The developer name of the queue associated with the case associated with the message.</description>
        <inlineHelpText>The developer name of the queue associated with the case associated with the message.</inlineHelpText>
        <label>Queue Developer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Email__c</fullName>
        <description>CreatedBy User Email</description>
        <label>User Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The user associate with the case.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Case_Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Message</label>
    <nameField>
        <displayFormat>CM-{000000000}</displayFormat>
        <label>Case Message Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case_Message_Route__mdt.object
<CustomObject>
    <description>A map of Queue Developer Names to External Destination such as FRESHDESK or ORACLECX.</description>
    <fields>
        <fullName>Freshdesk_Type__c</fullName>
        <description>The Type used to post to freshdesk.</description>
        <label>Freshdesk Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Queue_Developer_Name__c</fullName>
        <description>The developer name of the Salesforce Queue</description>
        <label>Queue Developer Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Remote_Destination_Id__c</fullName>
        <description>The Id of the remote group/queue.</description>
        <label>Remote Destination Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remote_Destination__c</fullName>
        <description>The remote system we are sending the message to.</description>
        <label>Remote Destination</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Case Message Route</label>
    <pluralLabel>Case Message Route</pluralLabel>
</CustomObject>

objects/Dispatch_Setting__c.object
<CustomObject>
    <description>Setting used to configure dispatch queueables.</description>
    <fields>
        <fullName>Chain__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether of not the queueable should continue chaining after execution.</description>
        <inlineHelpText>Should the queue continue chaining?</inlineHelpText>
        <label>Chain</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dispatch_Query__c</fullName>
        <description>The query used to select records to dispatch.</description>
        <inlineHelpText>The query used to select records to dispatch.</inlineHelpText>
        <label>Dispatch Query</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Headers__c</fullName>
        <description>Headers in json format passed to the callout.</description>
        <inlineHelpText>Headers in json format passed to the callout.</inlineHelpText>
        <label>Headers</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Order_By_Field_API_Name__c</fullName>
        <defaultValue>&quot;CreatedDate&quot;</defaultValue>
        <description>The API name of the field to order by.</description>
        <inlineHelpText>The API name of the field to order by.</inlineHelpText>
        <label>Order By Field API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Direction__c</fullName>
        <description>Sort direction for records consumed bu the dispatch process.</description>
        <inlineHelpText>Sort direction for records consumed bu the dispatch process.</inlineHelpText>
        <label>Order Direction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DESC</fullName>
                    <default>true</default>
                    <label>DESC</label>
                </value>
                <value>
                    <fullName>ASC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Remote_URL__c</fullName>
        <description>The URL of the site to post messages to.</description>
        <inlineHelpText>The URL of the site to post messages to.</inlineHelpText>
        <label>Remote URL</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_Field_API_Name__c</fullName>
        <defaultValue>&quot;Status__c&quot;</defaultValue>
        <description>The API name of the field used to track the status. Defaults to Status__c</description>
        <inlineHelpText>The API name of the field used to track the status. Defaults to Status__c</inlineHelpText>
        <label>Status Field API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Dispatch Setting</label>
    <nameField>
        <label>DispatchSetting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dispatch Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Case_Message_Actions.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>CREATED</fullName>
    </customValue>
    <customValue>
        <fullName>UPDATED</fullName>
    </customValue>
    <description>The actions to indicate an event on a case.</description>
    <masterLabel>Case Message Actions</masterLabel>
</GlobalValueSet>

globalValueSets/Case_Message_Destination.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>FRESHDESK</fullName>
    </customValue>
    <customValue>
        <fullName>ORACLECX</fullName>
    </customValue>
    <description>The Destination of the Case Message</description>
    <masterLabel>Case Message Destination</masterLabel>
</GlobalValueSet>

globalValueSets/Case_Message_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>FAILED</fullName>
    </customValue>
    <customValue>
        <fullName>RESUBMIT</fullName>
    </customValue>
    <customValue>
        <fullName>NEW</fullName>
        <default>true</default>
        <label>NEW</label>
    </customValue>
    <customValue>
        <fullName>PENDING</fullName>
    </customValue>
    <customValue>
        <fullName>HOLDING</fullName>
    </customValue>
    <customValue>
        <fullName>SUBMITTED</fullName>
    </customValue>
    <customValue>
        <fullName>PROCESSED</fullName>
    </customValue>
    <description>The picklist value set for the internal status entry of the case message.</description>
    <masterLabel>Case Message Status</masterLabel>
</GlobalValueSet>

classes/CaseMessageDispatch_TC.cls
/**************************************************************
* This is use to test scenarios related to CaseMessageDispatch which is part Dispatch and the Single Ticketing project.
*
* @author Adam Albright, adam.albright@officedepot.com
* @since 2020-01-17
*/

@IsTest
public without sharing class CaseMessageDispatch_TC {


    static User soa_connection_user = [SELECT Id, Name FROM User WHERE Name='Soa Connection'];
    static Map<String, Schema.RecordTypeInfo> case_recordtype_developername_map = Schema.Case.getSObjectType().getDescribe().getRecordTypeInfosByDeveloperName();
    static List<Case_Message_Route__mdt>  message_routes = [
        SELECT 
            Id, 
            Queue_Developer_Name__c, 
            Remote_Destination__c, 
            Remote_Destination_Id__c 
        FROM Case_Message_Route__mdt
    ];

    
    public class CaseMessageDispatchMock implements HttpCalloutMock {
        Integer req_status = 201;
        public CaseMessageDispatchMock(){}
        public CaseMessageDispatchMock(Integer req_status){
            this.req_status = req_status;
        }

        public HTTPResponse respond(HTTPRequest request) {
            HttpResponse response = new HttpResponse();
            response.setStatusCode(this.req_status);
            return response;
        }
    }

    @IsTest
    static void run_case_message_dispatch_validation(){
        Test.startTest();
        try {
            new CaseMessageDispatch().validate();
        } catch (QueryException e) {
            insert new Dispatch_Setting__c(
                Name='CaseMessageDispatch',
                Dispatch_Query__c = 'SELECT Account_Number__c, Attachment_Id__c, Case_Comment_Id__c, Case_Message_Action__c, Case_Message_Destination__c, Case__c, CreatedDate, FirstName__c, Freshdesk_Id__c, Freshdesk_Queue__c, Freshdesk_Type__c, Id, LastName__c, Name, OracleCX_Id__c, OracleCX_Queue__c, Phone__c, User_Email__c, Case_Message_Status__c, User__c FROM Case_Message__c WHERE CreatedDate=today AND ',
                Remote_URL__c = 'https://localhost',
                Headers__c = '{"Content-Type": "application/xml"}',
                Order_By_Field_API_Name__c = 'CreatedDate',
                Order_Direction__c='DESC',
                Status_Field_API_Name__c='Case_Message_Status__c',
                Chain__c=false
            );
            new CaseMessageDispatch().validate();
        }
        Test.stopTest();
    }

    @IsTest
    static void test_that_case_messages_get_processed(){
        Set<String> freshdesk_queue_names = new Set<String>();
        Set<String> ocx_queue_names = new Set<String>();
        for(Case_Message_Route__mdt route: message_routes)
            if(route.Remote_Destination__c == 'FRESHDESK')
                freshdesk_queue_names.add(route.Queue_Developer_Name__c);
            else if(route.Remote_Destination__c == 'ORACLECX')
                ocx_queue_names.add(route.Queue_Developer_Name__c);


        List<Group> freshdesk_groups = [SELECT Id, Name, DeveloperName FROM Group WHERE DeveloperName IN :freshdesk_queue_names];
        List<Group> ocx_groups = [SELECT Id, Name, DeveloperName FROM Group WHERE DeveloperName IN :ocx_queue_names];


        List<Case> test_cases = new List<Case>{
            new Case(
                Subject='Some Test Case',
                Description='This is a big test description.',
                LastModifiedById = UserInfo.getUserId(),
                Remote_Destination__c = 'FRESHDESK',
                Freshdesk_Id__c = 2,
                OwnerId = freshdesk_groups[0].Id,
                RecordTypeId = case_recordtype_developername_map.get('Support').getRecordTypeId()
            ),
            new Case(
                Subject='Some Test Case',
                Description='This is a big test description.',
                LastModifiedById = UserInfo.getUserId(),
                Remote_Destination__c = 'ORACLECX',
                OracleCX_Id__c = 3,
                OwnerId = ocx_groups[0].Id,
                RecordTypeId = case_recordtype_developername_map.get('Support').getRecordTypeId() // Gotta set this, or messages are not created. 
            )
        };

        insert new Dispatch_Setting__c(
            Name='CaseMessageDispatch',
            Dispatch_Query__c = 'SELECT Account_Number__c, Attachment_Id__c, Case_Comment_Id__c, Case_Message_Action__c, Case_Message_Destination__c, Case__c, CreatedDate, FirstName__c, Freshdesk_Id__c, Freshdesk_Queue__c, Freshdesk_Type__c, Id, LastName__c, Name, OracleCX_Id__c, OracleCX_Queue__c, Phone__c, User_Email__c, Case_Message_Status__c, User__c FROM Case_Message__c WHERE CreatedDate=today AND ',
            Remote_URL__c = 'https://localhost',
            Headers__c = '{"Content-Type": "application/xml"}',
            Order_By_Field_API_Name__c = 'CreatedDate',
            Order_Direction__c='DESC',
            Status_Field_API_Name__c='Case_Message_Status__c',
            Chain__c=false
        );

        TriggerHandler.bypass('CaseMessageTriggerHandler');
        insert test_cases;

        Test.setMock(HttpCalloutMock.class, new CaseMessageDispatchMock());
        Test.startTest();
    
        List<Case_Message__c> messages = [SELECT Id, Case_Message_Status__c FROM Case_Message__c];
        System.assert(messages.size() == 2, 'Messages did not get generated.');
        for (Case_Message__c msg: messages){
            System.assert(msg.Case_Message_Status__c == 'NEW');
        }

        System.enqueueJob(new CaseMessageDispatch());

        Test.stopTest();
        TriggerHandler.clearBypass('CaseMessageTriggerHandler');
        List<Case_Message__c> processed_messages = [SELECT Id, Case_Message_Status__c FROM Case_Message__c WHERE Case_Message_Status__c = 'PROCESSED'];
        List<Case_Message__c> new_messages = [SELECT Id, Case_Message_Status__c FROM Case_Message__c WHERE Case_Message_Status__c = 'NEW'];

        System.assert(processed_messages.size() == 1, 'Expected 1 record, Got ' + processed_messages);
        System.assert(new_messages.size() == 1, 'Expected 1 record, Got ' + new_messages);
    }

    @IsTest
    static void test_that_case_messages_get_failed(){
        Set<String> freshdesk_queue_names = new Set<String>();
        Set<String> ocx_queue_names = new Set<String>();
        for(Case_Message_Route__mdt route: message_routes)
            if(route.Remote_Destination__c == 'FRESHDESK')
                freshdesk_queue_names.add(route.Queue_Developer_Name__c);
            else if(route.Remote_Destination__c == 'ORACLECX')
                ocx_queue_names.add(route.Queue_Developer_Name__c);


        List<Group> freshdesk_groups = [SELECT Id, Name, DeveloperName FROM Group WHERE DeveloperName IN :freshdesk_queue_names];
        List<Group> ocx_groups = [SELECT Id, Name, DeveloperName FROM Group WHERE DeveloperName IN :ocx_queue_names];


        List<Case> test_cases = new List<Case>{
            new Case(
                Subject='Some Test Case',
                Description='This is a big test description.',
                LastModifiedById = UserInfo.getUserId(),
                Remote_Destination__c = 'FRESHDESK',
                Freshdesk_Id__c = 2,
                OwnerId = freshdesk_groups[0].Id,
                RecordTypeId = case_recordtype_developername_map.get('Support').getRecordTypeId()
            ),
            new Case(
                Subject='Some Test Case',
                Description='This is a big test description.',
                LastModifiedById = UserInfo.getUserId(),
                Remote_Destination__c = 'ORACLECX',
                OracleCX_Id__c = 3,
                OwnerId = ocx_groups[0].Id,
                RecordTypeId = case_recordtype_developername_map.get('Support').getRecordTypeId() // Gotta set this, or messages are not created. 
            )
        };

        insert new Dispatch_Setting__c(
            Name='CaseMessageDispatch',
            Dispatch_Query__c = 'SELECT Account_Number__c, Attachment_Id__c, Case_Comment_Id__c, Case_Message_Action__c, Case_Message_Destination__c, Case__c, CreatedDate, FirstName__c, Freshdesk_Id__c, Freshdesk_Queue__c, Freshdesk_Type__c, Id, LastName__c, Name, OracleCX_Id__c, OracleCX_Queue__c, Phone__c, User_Email__c, Case_Message_Status__c, User__c FROM Case_Message__c WHERE CreatedDate=today AND ',
            Remote_URL__c = 'https://localhost',
            Headers__c = '{"Content-Type": "application/xml"}',
            Order_By_Field_API_Name__c = 'CreatedDate',
            Order_Direction__c='DESC',
            Status_Field_API_Name__c='Case_Message_Status__c',
            Chain__c=false
        );
        
        TriggerHandler.bypass('CaseMessageTriggerHandler');
        insert test_cases;

        Test.setMock(HttpCalloutMock.class, new CaseMessageDispatchMock(500));
        Test.startTest();
    
        List<Case_Message__c> messages = [SELECT Id, Case_Message_Status__c FROM Case_Message__c];
        System.assert(messages.size() == 2, 'Messages did not get generated.');
        for (Case_Message__c msg: messages){
            System.assert(msg.Case_Message_Status__c == 'NEW');
        }

        System.enqueueJob(new CaseMessageDispatch());

        Test.stopTest();
        TriggerHandler.clearBypass('CaseMessageTriggerHandler');
        List<Case_Message__c> failed_messages = [SELECT Id, Case_Message_Status__c FROM Case_Message__c WHERE Case_Message_Status__c = 'FAILED'];
        List<Case_Message__c> new_messages = [SELECT Id, Case_Message_Status__c FROM Case_Message__c WHERE Case_Message_Status__c = 'NEW'];

        System.assert(failed_messages.size() == 1, 'Expected 1 record, Got ' + failed_messages);
        System.assert(new_messages.size() == 1, 'Expected 1 record, Got ' + new_messages);
    }
}