objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Medallia_Opted_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Medallia Opted Out</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Medallia_Feedback__c.object
<CustomObject>
    <description>Custom object to replicate in Salesforce feedback left by customers in Medallia.</description>
    <fields>
        <fullName>Contact_Email__c</fullName>
        <description>This field indicates what the customer&apos;s email is. Useful if the customer is not an existing contact in Salesforce.</description>
        <label>Contact - Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to link the feedback to an existing contact is Salesforce</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Medallia Feedbacks</relationshipLabel>
        <relationshipName>Medallia_Feedbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email_Update_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Email Update Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_Status__c</fullName>
        <description>This field shows where the record is in its lifecycle (e.g. invitation, survey completed, etc.)</description>
        <label>Record - Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Delivery Failed</fullName>
                </value>
                <value>
                    <fullName>Delivery bounced</fullName>
                </value>
                <value>
                    <fullName>Reminded</fullName>
                </value>
                <value>
                    <fullName>Opted Out</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Invited</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Medallia Feedback</label>
    <nameField>
        <label>Medallia Feedback</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medallia Feedback</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Medallia_Batch.cls
/*
* This batch job maintains the Email Update Status field on the Medallia Feedback object and
* the Medallia Opted Out field on the Contact object. It works with Medallia Feedback from
* the last 6 months and the associated Contacts.
*/
global class Medallia_Batch implements Database.Batchable<Sobject>, Schedulable {

    private string query;

    public Medallia_Batch() {
        query = 'SELECT Id, Record_Status__c, Email_Update_Status__c, Contact_Email__c, Contact_Id__c, Contact_Id__r.Email '
                + 'FROM Medallia_Feedback__c WHERE CreatedDate >= LAST_N_MONTHS:6';
    }

    global Medallia_Batch(String query) {
        this.query = query;
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, SObject[] scope) {
        List<Medallia_Feedback__c> feedbackList = scope;

        // Create a list of Ids of Contacts that have opted out and of Feedback objects that had 
        List<Id> optedOutContactIds = new List<Id>();
        List<Medallia_Feedback__c> feedbackWithUpdatedEmails = new List<Medallia_Feedback__c>();
        for(Medallia_Feedback__c feedback : feedbackList) {
            if(feedback.Record_Status__c == 'Opted Out' && feedback.Contact_Id__c != null) {
                optedOutContactIds.add(feedback.Contact_Id__c);
            // If the delivery was bounced and the Email has been updated (is different on the Contact).
            } else if(feedback.Record_Status__c == 'Delivery bounced (Hard bounce)' && feedback.Contact_Id__r.Email != feedback.Contact_Email__c) {
                feedbackWithUpdatedEmails.add(feedback);
            }
        }

        // If there are Contacts to be marked as opted out, mark them and update.
        if(optedOutContactIds.size() > 0) {
            List<Contact> optedOutContacts = [SELECT Id, Medallia_Opted_Out__c FROM Contact WHERE Id IN :optedOutContactIds];
            for(Contact c : optedOutContacts) {
                c.Medallia_Opted_Out__c = True;
            }
            update optedOutContacts;
        }

        // If there is Medallia Feedback that needs to be marked as having updated a bad email, mark it and update.
        if(feedbackWithUpdatedEmails.size() > 0) {
            for(Medallia_Feedback__c mf : feedbackWithUpdatedEmails) {
                mf.Email_Update_Status__c = True;
            }
            update feedbackWithUpdatedEmails;
        }
    }

    global void finish(Database.BatchableContext bc) {}

    global void execute(SchedulableContext sc) {
        Database.executeBatch(new Medallia_Batch(), 2000);
    }
}