objects/Contract_Pricing_Terms__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>Contract_Pricing_Terms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Department_Groups__c</fullName>
        <description>Logical grouping of Departments</description>
        <inlineHelpText>Select Department Groups for this Pricing Term</inlineHelpText>
        <label>Department Groups</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Select All</fullName>
                </value>
                <value>
                    <fullName>All Except Paper &amp; Toner</fullName>
                </value>
                <value>
                    <fullName>CBS</fullName>
                </value>
                <value>
                    <fullName>CPD</fullName>
                </value>
                <value>
                    <fullName>Furniture</fullName>
                </value>
                <value>
                    <fullName>Ink &amp; Toner</fullName>
                </value>
                <value>
                    <fullName>MPS</fullName>
                </value>
                <value>
                    <fullName>Office Supplies</fullName>
                </value>
                <value>
                    <fullName>Paper</fullName>
                </value>
                <value>
                    <fullName>School Supplies</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
                <value>
                    <fullName>Technology (Tech Depot)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Departments__c</fullName>
        <description>List of Departments</description>
        <inlineHelpText>List of Departments for Pricing Term</inlineHelpText>
        <label>Departments</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>01 - FURNITURE</fullName>
                </value>
                <value>
                    <fullName>03 - BINDERS</fullName>
                </value>
                <value>
                    <fullName>04 - DATED AND FORMS</fullName>
                </value>
                <value>
                    <fullName>05 - PAPER</fullName>
                </value>
                <value>
                    <fullName>06 - MAILROOM/SHIPPING</fullName>
                </value>
                <value>
                    <fullName>07 - SCHOOL SUPPLIES</fullName>
                </value>
                <value>
                    <fullName>08 - LIGHTING</fullName>
                </value>
                <value>
                    <fullName>09 - PC ACCESSORIES</fullName>
                </value>
                <value>
                    <fullName>10 - DESKTOP COMPUTERS</fullName>
                </value>
                <value>
                    <fullName>11 - WRITING</fullName>
                </value>
                <value>
                    <fullName>12 - SPECIALTY PAPER</fullName>
                </value>
                <value>
                    <fullName>13 - NOTETAKING</fullName>
                </value>
                <value>
                    <fullName>14 - INKJET CARTRIDGES</fullName>
                </value>
                <value>
                    <fullName>16 - PRINTERS</fullName>
                </value>
                <value>
                    <fullName>17 - BUSINESS COMMUNICATION</fullName>
                </value>
                <value>
                    <fullName>18 - SHRED/STORE SERVICES</fullName>
                </value>
                <value>
                    <fullName>19 - MOBILITY</fullName>
                </value>
                <value>
                    <fullName>20 - PERFORMANCE PP SRVC</fullName>
                </value>
                <value>
                    <fullName>21 - FLASH STORAGE</fullName>
                </value>
                <value>
                    <fullName>22 - MARKETING SERVICES</fullName>
                </value>
                <value>
                    <fullName>23 - SAFETY, SECURITY, AND MEDICAL</fullName>
                </value>
                <value>
                    <fullName>24 - OFFICE ACCESSORIES</fullName>
                </value>
                <value>
                    <fullName>25 - SEATING</fullName>
                </value>
                <value>
                    <fullName>26 - SEASONAL PRODUCTS</fullName>
                </value>
                <value>
                    <fullName>27 - SHREDDERS</fullName>
                </value>
                <value>
                    <fullName>28 - FILING</fullName>
                </value>
                <value>
                    <fullName>29 - CUSTOM OUTSOURC PRNT</fullName>
                </value>
                <value>
                    <fullName>30 - DELIVERY CHARGES</fullName>
                </value>
                <value>
                    <fullName>31 - K-12</fullName>
                </value>
                <value>
                    <fullName>32 - CUSTOM IN HOUSE PRNT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Private_Brand__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Private Brand</description>
        <label>Private Brand</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Relevant_Customer_Level__c</fullName>
        <label>Relevant Customer Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Grandparent</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>Standalone</fullName>
                </value>
                <value>
                    <fullName>GreatGrandParent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract Pricing Terms</label>
    <nameField>
        <label>Contract Pricing Terms Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Pricing Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Merch_Dept_Group__c.object
<CustomObject>
    <description>List of Merchandising Department mapping to Logical Groups</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <description>Department</description>
        <inlineHelpText>Select Department</inlineHelpText>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>01 - FURNITURE</fullName>
                </value>
                <value>
                    <fullName>03 - BINDERS</fullName>
                </value>
                <value>
                    <fullName>04 - DATED AND FORMS</fullName>
                </value>
                <value>
                    <fullName>05 - PAPER</fullName>
                </value>
                <value>
                    <fullName>06 - MAILROOM/SHIPPING</fullName>
                </value>
                <value>
                    <fullName>07 - SCHOOL SUPPLIES</fullName>
                </value>
                <value>
                    <fullName>08 - LIGHTING</fullName>
                </value>
                <value>
                    <fullName>09 - PC ACCESSORIES</fullName>
                </value>
                <value>
                    <fullName>10 - DESKTOP COMPUTERS</fullName>
                </value>
                <value>
                    <fullName>11 - WRITING</fullName>
                </value>
                <value>
                    <fullName>12 - SPECIALTY PAPER</fullName>
                </value>
                <value>
                    <fullName>13 - NOTETAKING</fullName>
                </value>
                <value>
                    <fullName>14 - INKJET CARTRIDGES</fullName>
                </value>
                <value>
                    <fullName>16 - PRINTERS</fullName>
                </value>
                <value>
                    <fullName>17 - BUSINESS COMMUNICATION</fullName>
                </value>
                <value>
                    <fullName>18 - SHRED/STORE SERVICES</fullName>
                </value>
                <value>
                    <fullName>19 - MOBILITY</fullName>
                </value>
                <value>
                    <fullName>20 - PERFORMANCE PP SRVC</fullName>
                </value>
                <value>
                    <fullName>21 - FLASH STORAGE</fullName>
                </value>
                <value>
                    <fullName>22 - MARKETING SERVICES</fullName>
                </value>
                <value>
                    <fullName>23 - SAFETY, SECURITY, AND MEDICAL</fullName>
                </value>
                <value>
                    <fullName>24 - OFFICE ACCESSORIES</fullName>
                </value>
                <value>
                    <fullName>25 - SEATING</fullName>
                </value>
                <value>
                    <fullName>26 - SEASONAL PRODUCTS</fullName>
                </value>
                <value>
                    <fullName>27 - SHREDDERS</fullName>
                </value>
                <value>
                    <fullName>28 - FILING</fullName>
                </value>
                <value>
                    <fullName>29 - CUSTOM OUTSOURC PRNT</fullName>
                </value>
                <value>
                    <fullName>30 - DELIVERY CHARGES</fullName>
                </value>
                <value>
                    <fullName>31 - K-12</fullName>
                </value>
                <value>
                    <fullName>32 - CUSTOM IN HOUSE PRNT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dept_Group_Name__c</fullName>
        <description>List of predefined Department Group Names</description>
        <inlineHelpText>Select Department Group Name</inlineHelpText>
        <label>Department Group Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Select All</fullName>
                </value>
                <value>
                    <fullName>All Except Paper &amp; Toner</fullName>
                </value>
                <value>
                    <fullName>CBS</fullName>
                </value>
                <value>
                    <fullName>CPD</fullName>
                </value>
                <value>
                    <fullName>Furniture</fullName>
                </value>
                <value>
                    <fullName>Ink &amp; Toner</fullName>
                </value>
                <value>
                    <fullName>MPS</fullName>
                </value>
                <value>
                    <fullName>Office Supplies</fullName>
                </value>
                <value>
                    <fullName>Paper</fullName>
                </value>
                <value>
                    <fullName>School Supplies</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
                <value>
                    <fullName>Technology (Tech Depot)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Merchandising Department Group</label>
    <nameField>
        <displayFormat>DG-{0000000000}</displayFormat>
        <label>Dept Group#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merchandising Department Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ContractPricingTermsClass.cls
Public class ContractPricingTermsClass {
  @AuraEnabled
    public static Map < String, List < String >> startInit(Id RecordId){
        system.debug('in apex---');
        string deptvalues ='';
        List<string> departVal= new List<string>();
        set<string> departmentVal= new set<string>();
        Map < String, List < String >> depPiklistMap = new Map < String, List < String >> ();
        List < String > CompletedepartmentList = new List < String > ();
        List<String> departmentList = new List<String>();
        List<Merch_Dept_Group__c> DepartmentsMapping = new List<Merch_Dept_Group__c>();
        set<string> departmentNameset  = new set<string>();
        
        string s = [select id,Departments__c from Contract_Pricing_Terms__c where id=:RecordId].Departments__c; 
        if(string.isNotEmpty(s)){
            departmentList.addall(s.split(';'));
        }
        system.debug('in apex--departmentList-'+departmentList);
        departmentList.sort();
        depPiklistMap.put('onloadDepList', departmentList);
        // strating disable
        Contract_Pricing_Terms__c CPT =  [select id,Relevant_Customer_Level__c,Private_Brand__c,Active__c,Contract__c,Departments__c 
                                          from Contract_Pricing_Terms__c 
                                          Where id =: RecordId];
        list<Contract_Pricing_Terms__c> duplicateRec = [select id,Relevant_Customer_Level__c,Private_Brand__c,Active__c,
                                                        Contract__c,Departments__c from Contract_Pricing_Terms__c where 
                                                        Relevant_Customer_Level__c=:CPT.Relevant_Customer_Level__c 
                                                        and Private_Brand__c=:CPT.Private_Brand__c 
                                                        and Contract__c =:CPT.Contract__c /* and Active__c=true */
                                                        and (NOT id =:CPT.id)];
        for(Contract_Pricing_Terms__c pricingTerm : duplicateRec){
            deptvalues+=pricingTerm.Departments__c+';';
        }
        
        if(deptvalues!=null){// && CPT.Active__c
            
            departVal = deptvalues.split(';');
            system.debug('departVal **'+departVal );
            for(string dep1 : departVal){
                departmentVal.add(dep1);
            }
        }
        system.debug('departmentVal**'+departmentVal);
        //ending disable
        
        string s2 =[select id,Department_Groups__c from Contract_Pricing_Terms__c where id=:RecordId].Department_Groups__c;
        List<string> depGroups = new List<string>();
        if(string.isNotEmpty(s2)){
            depGroups = s2.split(';');
        }
        //if(depGroups.contains('Select All')){
        DepartmentsMapping = [select Department__c from Merch_Dept_Group__c where Active__c=true]; 
        /* }
else{
DepartmentsMapping = [select Department__c from Merch_Dept_Group__c where Active__c=true and Dept_Group_Name__c IN :depGroups]; 
}*/
        for(Merch_Dept_Group__c deptName : DepartmentsMapping){
            departmentNameset.add(deptName.Department__c);
        }     
        for( string deplist : departmentNameset){
            if(!departmentVal.contains(deplist))
                CompletedepartmentList.add(deplist);
        }
        CompletedepartmentList.sort();
        system.debug('in apex--CompletedepartmentList-'+CompletedepartmentList);
        depPiklistMap.put('CompDepList', CompletedepartmentList);
        return depPiklistMap;
        
    }
    
    
    
    @AuraEnabled
    public static List<string> deparments1(string dep,id RecordId){
        string deptvalues ='';
        List<string> departVal= new List<string>();
        set<string> departmentVal= new set<string>();
        system.debug('in apex--2-');
        List<string> part = new List<string>();
        part = dep.split(';');
        system.debug('in apex--2-'+part);
        List<Merch_Dept_Group__c> DepartmentsMapping = new List<Merch_Dept_Group__c>();
        set<string> departmentNameset  = new set<string>();
        List<String> departmentList = new List<String>();
        // strating disable
        Contract_Pricing_Terms__c CPT =  [select id,Relevant_Customer_Level__c,Private_Brand__c,Active__c,Contract__c,Departments__c 
                                          from Contract_Pricing_Terms__c 
                                          Where id =: RecordId];
        list<Contract_Pricing_Terms__c> duplicateRec = [select id,Relevant_Customer_Level__c,Private_Brand__c,Active__c,
                                                        Contract__c,Departments__c from Contract_Pricing_Terms__c where 
                                                        Relevant_Customer_Level__c=:CPT.Relevant_Customer_Level__c 
                                                        and Private_Brand__c=:CPT.Private_Brand__c 
                                                        and Contract__c =:CPT.Contract__c /* and Active__c=true */
                                                        and (NOT id =:CPT.id)];
        for(Contract_Pricing_Terms__c pricingTerm : duplicateRec){
            deptvalues+=pricingTerm.Departments__c+';';
        }
        if(deptvalues!=null /* && CPT.Active__c */){//
            departVal = deptvalues.split(';');
            system.debug('departVal **'+departVal );
            for(string dep1 : departVal){
                departmentVal.add(dep1);
            }
        }
        system.debug('departmentVal**'+departmentVal);
        //ending disable
        if(part.contains('Select All')){
            DepartmentsMapping = [select Department__c from Merch_Dept_Group__c where Active__c=true]; 
        }
        else{
            DepartmentsMapping = [select Department__c from Merch_Dept_Group__c where Active__c=true and Dept_Group_Name__c IN :part]; 
        }
        for(Merch_Dept_Group__c deptName : DepartmentsMapping){
            departmentNameset.add(deptName.Department__c);
        }     
        for( string deplist : departmentNameset){
            if(!departmentVal.contains(deplist))
                departmentList.add(deplist);
        }
        departmentList.sort();
        system.debug('in apex--departmentList-'+departmentList);
        
        
        return departmentList;
        
    }
    
    @AuraEnabled
    public static Map < String, List < String >> deparments(string dep,id RecordId,string CustLevel,boolean PrivateBand,id Parentid){
        string deptvalues ='';
        Map < String, List < String >> depPiklistMap = new Map < String, List < String >> ();
        List<string> departVal= new List<string>();
        set<string> departmentVal= new set<string>();
        system.debug('in apex--2-');
        system.debug('in apex--RecordId-'+RecordId);
        List<string> part = new List<string>();
        if(string.isNotEmpty(dep))
            part = dep.split(';');
        system.debug('in apex--2-'+part);
        List<Merch_Dept_Group__c> DepartmentsMapping = new List<Merch_Dept_Group__c>();
        List<Merch_Dept_Group__c> CmpDepartmentsMapping = new List<Merch_Dept_Group__c>();
        set<string> departmentNameset  = new set<string>();
        set<string> departmentNameset2  = new set<string>();
        List<String> departmentList = new List<String>();
        List < String > CompletedepartmentList = new List < String > ();
		List < String > CmpdepartmentList = new List < String > ();
        list<Contract_Pricing_Terms__c> duplicateRec = new list<Contract_Pricing_Terms__c>();
        // strating disable
       /* Contract_Pricing_Terms__c CPT =  [select id,Relevant_Customer_Level__c,Private_Brand__c,Active__c,Contract__c,Departments__c 
                                          from Contract_Pricing_Terms__c 
                                          Where id =: RecordId];*/
        if(string.isNotEmpty(RecordId)){
            system.debug('==in if---147===');
        duplicateRec = [select id,Relevant_Customer_Level__c,Private_Brand__c,Active__c,
                                                        Contract__c,Departments__c from Contract_Pricing_Terms__c where 
                                                        Relevant_Customer_Level__c=:CustLevel 
                                                        and  Private_Brand__c=:PrivateBand 
                                                        and Contract__c =:Parentid /* and Active__c=true */
                                                        and (NOT id =:RecordId)];
        }
        else{
           duplicateRec = [select id,Relevant_Customer_Level__c,Private_Brand__c,Active__c,
                                                        Contract__c,Departments__c from Contract_Pricing_Terms__c where 
                                                     Relevant_Customer_Level__c=:CustLevel 
                                                        and   Private_Brand__c=:PrivateBand 
                                                        and Contract__c =:Parentid /* and Active__c=true */
                                                        ];
        }
        system.debug('duplicateRec **'+duplicateRec);
        for(Contract_Pricing_Terms__c pricingTerm : duplicateRec){
            deptvalues+=pricingTerm.Departments__c+';';
        }
        system.debug('deptvalues **'+deptvalues);
        if(deptvalues!=null)/*&& CPT.Active__c)*/{//
            departVal = deptvalues.split(';');
            system.debug('departVal **'+departVal );
            for(string dep1 : departVal){
                departmentVal.add(dep1);
            }
        }
        system.debug('departmentVal**'+departmentVal);
        //ending disable
        if(part.contains('Select All')){
            DepartmentsMapping = [select Department__c from Merch_Dept_Group__c where Active__c=true]; 
        }
        else{
            DepartmentsMapping = [select Department__c from Merch_Dept_Group__c where Active__c=true and Dept_Group_Name__c IN :part]; 
        }
        system.debug('DepartmentsMapping'+DepartmentsMapping);
        for(Merch_Dept_Group__c deptName : DepartmentsMapping){
            departmentNameset.add(deptName.Department__c);
        }     
        system.debug('departmentNameset'+departmentNameset);
        for( string deplist : departmentNameset){
            if(!departmentVal.contains(deplist))
                departmentList.add(deplist);
        }
        departmentList.sort();
        system.debug('in apex--departmentList-'+departmentList);
        CmpDepartmentsMapping = [select Department__c from Merch_Dept_Group__c where Active__c=true]; 
        for(Merch_Dept_Group__c deptName2 : CmpDepartmentsMapping){
            departmentNameset2.add(deptName2.Department__c);
        }
		system.debug('departmentNameset2'+departmentNameset2);
		for( string deplist : departmentNameset2){
            if(!departmentVal.contains(deplist))
                CompletedepartmentList.add(deplist);
        }
		CompletedepartmentList.sort();
        depPiklistMap.put('availableOptions', CompletedepartmentList);
        depPiklistMap.put('SelectedValues', departmentList);
        system.debug('availableOptions **'+CompletedepartmentList );
        system.debug('SelectedValues **'+departmentList );
        return depPiklistMap;
        
    }
    
    
    @AuraEnabled
    Public Static  Map<String, Object>  upsert_CPT(Contract_Pricing_Terms__c CPT)
    { 
        Map<String, Object> MyMap = new Map<String, Object>();
           try{
             Upsert CPT;
        }   catch(Exception e){
                MyMap.put('Status', e.getMessage());
                MyMap.put('StatusCode', -1);
                system.debug('ee****'+e.getStackTraceString());
                system.debug('ee**'+e.getMessage());
            }
            system.debug('ee**'+MyMap);
            return MyMap;
       
    }
    
    @AuraEnabled
    public static List < String > startInit_New(){
        List<String> departmentList = new List<String>();
        set<string> departmentNameset  = new set<string>();
        List<Merch_Dept_Group__c> DepartmentsMapping = [select Department__c from Merch_Dept_Group__c where Active__c=true];
        for(Merch_Dept_Group__c deptName : DepartmentsMapping){
            departmentNameset.add(deptName.Department__c);
        }     
        for( string deplist : departmentNameset){
            
                departmentList.add(deplist);
        }
        departmentList.sort();
        return departmentList;
    }
    
    @AuraEnabled
    public static List<string> custDepartment(Id RecordId){
        system.debug('======level======'+RecordId);
        string deptvalues ='';
        List<string> departVal= new List<string>();
        set<string> departmentVal= new set<string>();
        List<String> departmentList = new List<String>();
        //if(String.isNotBlank(RecordId)){
        Contract_Pricing_Terms__c CPT =  [select id,Relevant_Customer_Level__c,Private_Brand__c,Active__c,Contract__c,Departments__c 
                                          from Contract_Pricing_Terms__c 
                                          Where id =: RecordId];
        
        list<Contract_Pricing_Terms__c> duplicateRec = [select id,Relevant_Customer_Level__c,Private_Brand__c,Active__c,
                                                        Contract__c,Departments__c from Contract_Pricing_Terms__c where 
                                                       Relevant_Customer_Level__c=:CPT.Relevant_Customer_Level__c 
                                                        and Private_Brand__c=:CPT.Private_Brand__c 
                                                        and Contract__c =:CPT.Contract__c /* and Active__c=true */
                                                        and (NOT id =:CPT.id)];
        for(Contract_Pricing_Terms__c pricingTerm : duplicateRec){
            deptvalues+=pricingTerm.Departments__c+';';
        }
        if(deptvalues!=null /* && CPT.Active__c*/){//
            departVal = deptvalues.split(';');
            system.debug('departVal **'+departVal );
            for(string dep : departVal){
                departmentVal.add(dep);
            }
            
        }
        return departmentList;
        
    }
    
}