objects/Contract_Pricing_Terms__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CC_Prc_Chg_Notice_Reqd_days__c</fullName>
        <inlineHelpText>If contract silent, enter 0</inlineHelpText>
        <label>CC Price Change Notice Req&apos;d (in days)</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CC_Price_Incr_Cap_Pegd_To__c</fullName>
        <description>CC Price Increase Cap Pegged To</description>
        <inlineHelpText>CC Price Increase Cap Pegged To</inlineHelpText>
        <label>What is the price increase cap pegged to</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Static Amount</fullName>
                </value>
                <value>
                    <fullName>Consumer Price Index (CPI)</fullName>
                </value>
                <value>
                    <fullName>Producer Price Index (PPI)</fullName>
                </value>
                <value>
                    <fullName>Needs validation</fullName>
                    <default>true</default>
                    <label>Needs validation</label>
                </value>
                <value>
                    <fullName>Web price</fullName>
                </value>
                <value>
                    <fullName>Operating cost</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CC_Price_Incr_Capped__c</fullName>
        <description>Are CC Price Increases Capped?</description>
        <inlineHelpText>Are CC Price Increases Capped?</inlineHelpText>
        <label>Are price increases capped?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>Needs validation</fullName>
                    <default>true</default>
                    <label>Needs validation</label>
                </value>
                <value>
                    <fullName>Contract silent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Comm_Req_CC_Price_Chg__c</fullName>
        <inlineHelpText>If contract silent, enter 0</inlineHelpText>
        <label>Communication Req&apos;d For CC Price Change</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Notification only</fullName>
                </value>
                <value>
                    <fullName>Notification and customer approval</fullName>
                </value>
                <value>
                    <fullName>Needs validation</fullName>
                    <default>true</default>
                    <label>Needs validation</label>
                </value>
                <value>
                    <fullName>Contract silent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>Contract_Pricing_Terms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Departments__c</fullName>
        <description>List of Departments</description>
        <inlineHelpText>List of Departments for Pricing Term</inlineHelpText>
        <label>Departments</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>01 - FURNITURE</fullName>
                </value>
                <value>
                    <fullName>03 - BINDERS</fullName>
                </value>
                <value>
                    <fullName>04 - DATED AND FORMS</fullName>
                </value>
                <value>
                    <fullName>05 - PAPER</fullName>
                </value>
                <value>
                    <fullName>06 - MAILROOM/SHIPPING</fullName>
                </value>
                <value>
                    <fullName>07 - SCHOOL SUPPLIES</fullName>
                </value>
                <value>
                    <fullName>08 - LIGHTING</fullName>
                </value>
                <value>
                    <fullName>09 - PC ACCESSORIES</fullName>
                </value>
                <value>
                    <fullName>10 - DESKTOP COMPUTERS</fullName>
                </value>
                <value>
                    <fullName>11 - WRITING</fullName>
                </value>
                <value>
                    <fullName>12 - SPECIALTY PAPER</fullName>
                </value>
                <value>
                    <fullName>13 - NOTETAKING</fullName>
                </value>
                <value>
                    <fullName>14 - INKJET CARTRIDGES</fullName>
                </value>
                <value>
                    <fullName>16 - PRINTERS</fullName>
                </value>
                <value>
                    <fullName>17 - BUSINESS COMMUNICATION</fullName>
                </value>
                <value>
                    <fullName>18 - SHRED/STORE SERVICES</fullName>
                </value>
                <value>
                    <fullName>19 - MOBILITY</fullName>
                </value>
                <value>
                    <fullName>20 - PERFORMANCE PP SRVC</fullName>
                </value>
                <value>
                    <fullName>21 - FLASH STORAGE</fullName>
                </value>
                <value>
                    <fullName>22 - MARKETING SERVICES</fullName>
                </value>
                <value>
                    <fullName>23 - SAFETY, SECURITY, AND MEDICAL</fullName>
                </value>
                <value>
                    <fullName>24 - OFFICE ACCESSORIES</fullName>
                </value>
                <value>
                    <fullName>25 - SEATING</fullName>
                </value>
                <value>
                    <fullName>26 - SEASONAL PRODUCTS</fullName>
                </value>
                <value>
                    <fullName>27 - SHREDDERS</fullName>
                </value>
                <value>
                    <fullName>28 - FILING</fullName>
                </value>
                <value>
                    <fullName>29 - CUSTOM OUTSOURC PRNT</fullName>
                </value>
                <value>
                    <fullName>30 - DELIVERY CHARGES</fullName>
                </value>
                <value>
                    <fullName>31 - K-12</fullName>
                </value>
                <value>
                    <fullName>32 - CUSTOM IN HOUSE PRNT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Relevant_Customer_Level__c</fullName>
        <label>Relevant Customer Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Grandparent</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>Standalone</fullName>
                </value>
                <value>
                    <fullName>GreatGrandParent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Required_Timing_Of_CC_Updates__c</fullName>
        <inlineHelpText>If contract silent, enter None</inlineHelpText>
        <label>Required Timing Of CC Updates</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Awaiting Information</fullName>
                    <default>true</default>
                    <label>Awaiting Information</label>
                </value>
                <value>
                    <fullName>None/Contract Silent</fullName>
                </value>
                <value>
                    <fullName>Jan</fullName>
                </value>
                <value>
                    <fullName>Feb</fullName>
                </value>
                <value>
                    <fullName>Mar</fullName>
                </value>
                <value>
                    <fullName>Apr</fullName>
                </value>
                <value>
                    <fullName>May</fullName>
                </value>
                <value>
                    <fullName>Jun</fullName>
                </value>
                <value>
                    <fullName>Jul</fullName>
                </value>
                <value>
                    <fullName>Aug</fullName>
                </value>
                <value>
                    <fullName>Sep</fullName>
                </value>
                <value>
                    <fullName>Oct</fullName>
                </value>
                <value>
                    <fullName>Nov</fullName>
                </value>
                <value>
                    <fullName>Dec</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor_Letter_Required_For_CC_Increase__c</fullName>
        <label>Vendor Letter Required For CC Increase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>Needs validation</fullName>
                    <default>true</default>
                    <label>Needs validation</label>
                </value>
                <value>
                    <fullName>Yes - Upon request</fullName>
                </value>
                <value>
                    <fullName>Contract silent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract Pricing Terms</label>
    <nameField>
        <label>Contract Pricing Terms Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Pricing Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Merch_Dept_Group__c.object
<CustomObject>
    <description>List of Merchandising Department mapping to Logical Groups</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <description>Department</description>
        <inlineHelpText>Select Department</inlineHelpText>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>01 - FURNITURE</fullName>
                </value>
                <value>
                    <fullName>03 - BINDERS</fullName>
                </value>
                <value>
                    <fullName>04 - DATED AND FORMS</fullName>
                </value>
                <value>
                    <fullName>05 - PAPER</fullName>
                </value>
                <value>
                    <fullName>06 - MAILROOM/SHIPPING</fullName>
                </value>
                <value>
                    <fullName>07 - SCHOOL SUPPLIES</fullName>
                </value>
                <value>
                    <fullName>08 - LIGHTING</fullName>
                </value>
                <value>
                    <fullName>09 - PC ACCESSORIES</fullName>
                </value>
                <value>
                    <fullName>10 - DESKTOP COMPUTERS</fullName>
                </value>
                <value>
                    <fullName>11 - WRITING</fullName>
                </value>
                <value>
                    <fullName>12 - SPECIALTY PAPER</fullName>
                </value>
                <value>
                    <fullName>13 - NOTETAKING</fullName>
                </value>
                <value>
                    <fullName>14 - INKJET CARTRIDGES</fullName>
                </value>
                <value>
                    <fullName>16 - PRINTERS</fullName>
                </value>
                <value>
                    <fullName>17 - BUSINESS COMMUNICATION</fullName>
                </value>
                <value>
                    <fullName>18 - SHRED/STORE SERVICES</fullName>
                </value>
                <value>
                    <fullName>19 - MOBILITY</fullName>
                </value>
                <value>
                    <fullName>20 - PERFORMANCE PP SRVC</fullName>
                </value>
                <value>
                    <fullName>21 - FLASH STORAGE</fullName>
                </value>
                <value>
                    <fullName>22 - MARKETING SERVICES</fullName>
                </value>
                <value>
                    <fullName>23 - SAFETY, SECURITY, AND MEDICAL</fullName>
                </value>
                <value>
                    <fullName>24 - OFFICE ACCESSORIES</fullName>
                </value>
                <value>
                    <fullName>25 - SEATING</fullName>
                </value>
                <value>
                    <fullName>26 - SEASONAL PRODUCTS</fullName>
                </value>
                <value>
                    <fullName>27 - SHREDDERS</fullName>
                </value>
                <value>
                    <fullName>28 - FILING</fullName>
                </value>
                <value>
                    <fullName>29 - CUSTOM OUTSOURC PRNT</fullName>
                </value>
                <value>
                    <fullName>30 - DELIVERY CHARGES</fullName>
                </value>
                <value>
                    <fullName>31 - K-12</fullName>
                </value>
                <value>
                    <fullName>32 - CUSTOM IN HOUSE PRNT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Merchandising Department Group</label>
    <nameField>
        <displayFormat>DG-{0000000000}</displayFormat>
        <label>Dept Group#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merchandising Department Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>OD_Employee_ID__c</fullName>
        <externalId>true</externalId>
        <label>OD Employee ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Contract_Pricing_Terms_Extension_TC.cls
@isTest
private class Contract_Pricing_Terms_Extension_TC
{
      static testMethod  void Contract_Pricing_Terms_Extension_TC (){
       Profile p4 = [SELECT Id FROM profile WHERE name='System Administrator'];   
         User us1 = new User(alias = 'us_1', email='proxy@proxy1456.officedepot.com',OD_Employee_ID__c='113456',emailencodingkey='UTF-8', lastname='lastnam1',languagelocalekey='en_US',localesidkey='en_US', profileid = p4.Id,timezonesidkey='America/Los_Angeles',username='12proxy@proxy456.com');
         insert us1;
          system.runAs(us1){
      Account acc = new Account ();
        acc.name = 'Tehlaka2';
          insert acc;
          
    contract c = new contract ();
    c.Name='test1';
    c.AccountId = acc.Id;
    insert c;
 
    
    Contract_Pricing_Terms__c cp = new Contract_Pricing_Terms__c();
    cp.Relevant_Customer_Level__c= 'abc' ;
    cp.Contract__c = c.Id;
    cp.Departments__c= 'test';
    cp.Active__c=true;
    cp.Required_Timing_Of_CC_Updates__c = 'testing';
    cp.Vendor_Letter_Required_For_CC_Increase__c = 'trial';
    cp.Comm_Req_CC_Price_Chg__c = 'Notification and customer approval';
    cp.CC_Prc_Chg_Notice_Reqd_days__c = 3;
    cp.CC_Price_Incr_Cap_Pegd_To__c= 'Consumer Price Index (CPI)';
    cp.CC_Price_Incr_Capped__c = 'trial 5';
    insert cp;
    
    Merch_Dept_Group__c md = new Merch_Dept_Group__c();
    //md.Name= 'test2';
    md.Department__c = cp.Departments__c ;
    md.Dept_Group_Name__c = 'Select All';
    md.Active__c = true; 
    insert md;
  
    test.startTest();
     System.runAs(us1)
         {
    //List<string> pageUrl = ApexPages.currentPage().getUrl().split('\\?');        
    //Id id='';
    ApexPages.currentPage().getParameters().Put('id','\\?'+cp.Id);
    ApexPages.StandardController con = new ApexPages.StandardController(cp);    
    Contract_Pricing_Terms_Extension cpt = new Contract_Pricing_Terms_Extension(new ApexPages.StandardController(cp));
    

    cpt.PopulateCheckBox();
    cpt.disableDepartment();
      cpt.saveAndNew() ;
    cpt.backToContract();
    cpt.saveRecord();
    
     cpt.Populatevalue();

    cp.Required_Timing_Of_CC_Updates__c = null;
     update cp;
   


    cp.Vendor_Letter_Required_For_CC_Increase__c = null;
     update cp;
     

    cp.Comm_Req_CC_Price_Chg__c = null;
     update cp;
    

    cp.CC_Prc_Chg_Notice_Reqd_days__c = null;
     update cp;
     

    cp.CC_Price_Incr_Cap_Pegd_To__c= null;
     update cp;
    
    cp.CC_Price_Incr_Capped__c =null;
     update cp;
   

    cp.Relevant_Customer_Level__c = null;
    update cp;
    cpt.saveRecord();
        
    ApexPages.currentPage().getParameters().Put('clone','1');    
    cpt.saveRecord();
    cp.Department_Groups__c = 'Select All';
    update cp;
    
    cpt.PopulateCheckBox();
    
    
    cp.CC_Price_Incr_Cap_Pegd_To__c= 'Yes';
    update cp;
    cpt.Populatevalue();
    //Added by Lalit for S-399112 START
    cpt.conditionaldisplay();
    cpt.Deleterecord();
    List<Contract_Pricing_Terms__c> fetchedCP = new List<Contract_Pricing_Terms__c>();
    fetchedCP = [select id from Contract_Pricing_Terms__c where id = :cp.id];
    System.assert(fetchedCP.size() == 0);
    //Added by Lalit for S-399112 END
    }
    test.stopTest();
    }
      }

}