objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AOPS_Contact_Number__c</fullName>
        <externalId>true</externalId>
        <label>AOPS Contact Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact_Final_Staging__c.object
<CustomObject>
    <fields>
        <fullName>AOPS_Contact_Number__c</fullName>
        <label>AOPS Contact Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Sync_Message__c</fullName>
        <externalId>true</externalId>
        <label>Contact Sync Message</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_Of_Attempts__c</fullName>
        <label>Number Of Attempts</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sync_Failed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync_Failed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sync_Status_Message__c</fullName>
        <externalId>true</externalId>
        <label>Sync Status Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Contact Final Staging</label>
    <nameField>
        <label>Contact Final Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts Final Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SiteContacts_Final_Staging__c.object
<CustomObject>
    <fields>
        <fullName>AOPS_Contact_Number__c</fullName>
        <label>AOPS Contact Number</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Changed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Changed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_Of_Attempts__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Number Of Attempts</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sync_Failed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync Failed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sync_Message__c</fullName>
        <externalId>true</externalId>
        <label>Sync Message</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Site Contacts Final Staging</label>
    <nameField>
        <label>Site Contacts Final Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Contacts Final Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sync_batch_setting__mdt.object
<CustomObject>
    <fields>
        <fullName>batch_size__c</fullName>
        <label>batch size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>delay_next_job__c</fullName>
        <label>delay next job</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>sync batch setting</label>
    <pluralLabel>sync batch settings</pluralLabel>
</CustomObject>

classes/AOPSContactRetryProcessor.cls
public class AOPSContactRetryProcessor implements Queueable {

    private List<String> contactIdList;
    private static Integer WEBUSER_BATCH_SIZE = 50;
    private static Integer SITECONTACT_BATCH_SIZE = 50;
    private static Integer NO_OF_RETRIES = 1;

    public AOPSContactRetryProcessor(List<String> contactIdList) {
        this.contactIdList = contactIdList;
    }

    public void execute(QueueableContext context) {
        Savepoint sp = Database.setSavepoint();

        list<sync_batch_setting__mdt> sbs= [SELECT Id, batch_size__c, delay_next_job__c from sync_batch_setting__mdt where DeveloperName='number_of_retries' limit 1];
        if(sbs.size()>0) {
            NO_OF_RETRIES =sbs[0].batch_size__c.intValue();
        }
        try{        
            List<contact_final_staging__c> cntFinalStagingList = [SELECT Id, aops_contact_number__c, Sync_Failed__c, Number_Of_Attempts__c, Sync_Status_Message__c, Contact_Sync_Message__c FROM contact_final_staging__c 
            where Sync_Failed__c = true and (Number_Of_Attempts__c = null or Number_Of_Attempts__c <= :NO_OF_RETRIES) AND aops_contact_number__c IN :contactIdList];
            for (contact_final_staging__c cntFinalStaging : cntFinalStagingList) {
            cntFinalStaging.Sync_Failed__c = false;
            cntFinalStaging.Contact_Sync_Message__c = null;
            cntFinalStaging.Sync_Status_Message__c = null;
            if (cntFinalStaging.Number_Of_Attempts__c == null) 
                cntFinalStaging.Number_Of_Attempts__c = 1;
            else
                 cntFinalStaging.Number_Of_Attempts__c = cntFinalStaging.Number_Of_Attempts__c + 1;
            }
            update cntFinalStagingList;
        } catch(Exception ex) {
            System.debug('AOPSContactCronJob: Exception while retrying failed records for contact final staging records.'+ ex.getMessage());
        }

        try{
            List<SiteContacts_Final_Staging__c> siteContactList = [SELECT Id, aops_contact_number__c, Sync_Failed__c, Is_Changed__c, Number_Of_Attempts__c, Sync_Message__c FROM SiteContacts_Final_Staging__c 
            WHERE Sync_Failed__c = true and is_changed__c = true and Number_Of_Attempts__c <= :NO_OF_RETRIES AND aops_contact_number__c IN :contactIdList];
            for (SiteContacts_Final_Staging__c siteContact : siteContactList) {
                siteContact.Sync_Failed__c = false;
                siteContact.Sync_Message__c = null;
                if (siteContact.Number_Of_Attempts__c == null) 
                    siteContact.Number_Of_Attempts__c = 1;
                else
                    siteContact.Number_Of_Attempts__c = siteContact.Number_Of_Attempts__c + 1;
            }
            update siteContactList;
        } catch(Exception ex) {
            System.debug('AOPSContactCronJob: Exception while retrying failed records for sitecontact final staging records.'+ ex.getMessage());
        }
    }
}