objects/CPM__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CPMs</relationshipLabel>
        <relationshipName>CPM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Approval Recalled</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approved_for_Analyst_Assignment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved for Analyst Assignment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CPM_Required__c</fullName>
        <defaultValue>true</defaultValue>
        <label>CPM Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>District_Sales_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>District Sales Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CPM_Data16</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Finance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Finance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Next_ApproverId__c</fullName>
        <label>Next ApproverId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Analyst__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pricing Analyst</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CPM_DataihAw20</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scenario__c</fullName>
        <label>Scenario</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Send_Reminder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send_Reminder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Support_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Support Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>CPMs</relationshipLabel>
        <relationshipName>Case_CPM_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version #</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CPM</label>
    <nameField>
        <label>CPM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CPM_Test_Class.cls
//
// 8/10/2016 Jessica Schilling Case 175803 Fixed test class failures
//
@isTest
private class CPM_Test_Class {
  static testMethod void Test_Info(){
      Date d = Date.today();
      Id CaseRecordTypeID = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Work Request').getRecordTypeId();
     User CPMu = New USer(Username = 'Test_27@officedepot.com', 
                           LastName = 'Test_27', 
                           Email = 'Test_27@officedepot.com', 
                           Alias= 'Test_27', 
                           CommunityNickname = 'CPMTest_User_27', 
                           LocaleSidKey = 'en_US', 
                           LanguageLocaleKey = 'en_US',
                           ProfileId = '00eE0000000IALGIA4',
                           EmployeeNumber='000027');
      insert CPMu; 
      
    Account CPMa = new Account(Name='CPM_Test_27');
        insert CPMa;
      
    Case CPMc = New Case( Accountid = CPMa.id,
                                        Reason = 'WRF Request', 
                                        Priority = '3-Medium', 
                                        Status = 'Open',
                                        Approved_for_Analyst_Assignment__c = TRUE,
                                        RecordTypeId = CaseRecordTypeID,  //Work Request 
                                        WRF_Request_Type__c = 'Transition', 
                                        CPM_Required__c = TRUE, 
                                        WRF_Finance__c = FALSE, 
                                        WRF_Requestor__c = CPMa.OwnerId);
        //START JSCHILLING Case 175803 8/09/2016
        //Moved start and stop of test here to fix test class failure
        Test.StartTest();
        insert CPMc;
        Test.StopTest();
        //END JSCHILLING Case 175803 8/09/2016
      
    CPM__c CPM11 = New CPM__C(Name='CPM_4_CPM_Test_27_s1v1', 
                              Account_Name__C = CPMa.id,
                              Pricing_Analyst__c = CPMu.id,
                              Support_Number__c = CPMc.id, 
                              District_Sales_Manager__c = CPMu.id,
                              Finance__C = true,
                              Scenario__c = 1, 
                              Version__c = 1, 
                              Approval_status__c = 'Pending',
                              Next_ApproverId__c = CPMu.id );
        insert CPM11;

		/*if([select count() from ProcessInstance where targetobjectid=:CPMa.id] < 1)
        	{ 
        		Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();           
            	req1.setObjectId(CPM11.id);
        		Approval.ProcessResult result = Approval.process(req1);
            }*/
      
    //Modified the below line JSCHILLING Case 175803 8/10/2016 Moved start and stop of test to fix test class failure
    //Test.startTest();
    CPM__c CPM12 = New CPM__C(Name='CPM_4_CPM_Test_27_s1v2', 
                              Account_Name__C = CPMa.id, 
                              Finance__C = false, 
                              Support_Number__c = CPMc.id, 
                              Scenario__c = 1, 
                              Version__c = 2, 
                              Next_ApproverId__c = CPMu.id,
                              Pricing_Analyst__c = CPMu.id);
        insert CPM12;  
    CPM12.Send_Reminder__c = true;
      Update CPM12;
      
         //Modified the below line JSCHILLING Case 175803 8/10/2016 Moved start and stop of test to fix test class failure
         //Test.stopTest();

         
  } 
}