objects/DML_Relation__c.object
<CustomObject>
    <fields>
        <fullName>Effective_End_Date__c</fullName>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Start_Date__c</fullName>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <label>DML Relationship</label>
    <nameField>
        <displayFormat>DR-{0000}</displayFormat>
        <label>DML Relation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DML Relationship</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DML_Relation_History__c.object
<CustomObject>
    <fields>
        <fullName>DML_Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DML Relationship</label>
        <referenceTo>DML_Relation__c</referenceTo>
        <relationshipName>DML_Relation_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_End_Date__c</fullName>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Start_Date__c</fullName>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <label>Relation History</label>
    <nameField>
        <displayFormat>DH-{0000}</displayFormat>
        <label>DML Relation History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DML Relation History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DMLRelationHistoryClass.cls
public Class DMLRelationHistoryClass{

// update the start dates and end dates logic Method
  public static void updateDates( List <DML_Relation_History__c> recList){
  Set<Id>  DMLId= new Set<Id>();
  Map<Id, Date> mapRec=  new Map<Id, Date>();
  Map<Id, Date> mapRecEnd=  new Map<Id, Date>();

  List<DML_Relation_History__c> oldRecords = new List<DML_Relation_History__c>();

  // get all Relation records
     for( DML_Relation_History__c  rec :recList){
        if(rec.DML_Relationship__c!=null)
        DMLId.add(rec.DML_Relationship__c);
     }
     if(DMLId.size()>0){
     oldRecords=[select Id, Effective_Start_Date__c, Effective_end_Date__c,DML_Relationship__c  from DML_Relation_History__c
     where DML_Relationship__c in :DMLId];
     
     
     // get start dates
     List<DML_Relation__c> relationList=[select Id,Effective_Start_Date__c,Effective_end_Date__c from DML_Relation__c where
     Id in :DMLId];
        for( DML_Relation__c recNew:  relationList){
        mapRec.put(recNew.Id, recNew.Effective_Start_Date__c);
        mapRecEnd.put(recNew.Id, recNew.Effective_end_Date__c);

        }
        
     
       if(mapRec.size()>0){
       
                   //processing current Inserted record
                     for( DML_Relation_History__c  rec :recList){
                                if( rec.Effective_end_Date__c==null  &&  mapRecEnd.get(rec.DML_Relationship__c)==null)
                                rec.Effective_end_Date__c=System.today();
                                
                                if(rec.DML_Relationship__c!=null){
                                  if(rec.Effective_Start_Date__c  >  mapRec.get(rec.DML_Relationship__c)){
                                  rec.Effective_end_Date__c = rec.Effective_Start_Date__c ;
                                  }
                                  if( rec.Effective_end_Date__c>mapRec.get(rec.DML_Relationship__c)  && rec.Effective_Start_Date__c <mapRec.get(rec.DML_Relationship__c))
                                  rec.Effective_end_Date__c=mapRec.get(rec.DML_Relationship__c);
                                }

                      }

       
                   
                     //processing old Inserted record
                     for( DML_Relation_History__c  rec :oldRecords){
                                if(rec.DML_Relationship__c!=null){
                                  if(rec.Effective_Start_Date__c  >  mapRec.get(rec.DML_Relationship__c)){
                                  rec.Effective_end_Date__c = rec.Effective_Start_Date__c ;
                                  }
                                  if( rec.Effective_end_Date__c>mapRec.get(rec.DML_Relationship__c)  && rec.Effective_Start_Date__c <mapRec.get(rec.DML_Relationship__c))
                                  rec.Effective_end_Date__c=mapRec.get(rec.DML_Relationship__c);
                                }

                      }
                      if(oldRecords.size()>0)
                      update oldRecords;
       
       }
     }
  }
}