objects/GPO_Community_Setup__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used for GPO Communities</description>
    <fields>
        <fullName>Article_Guid__c</fullName>
        <label>Article Guid</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Article_URL__c</fullName>
        <label>Article URL</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Group_Name__c</fullName>
        <label>Default Group Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>GPO Community Setup</label>
</CustomObject>

objects/GPO_Group__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>GPO Group</relationshipLabel>
        <relationshipName>GPO_Group</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Activated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>NOTE: Once activated, the Community can NOT be deactivated.</description>
        <inlineHelpText>NOTE: Once activated, the Community can NOT be deactivated.</inlineHelpText>
        <label>Activated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Selected_Message__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Communities v2 - The Group&apos;s Selected Greeting Message that will display on the pre-login page.</description>
        <inlineHelpText>This is the Greeting Message that will display on the pre-login page.</inlineHelpText>
        <label>Selected Message</label>
        <referenceTo>GPO_Group_Detail__c</referenceTo>
        <relationshipLabel>GPO Group</relationshipLabel>
        <relationshipName>GPO_Group</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GPO Group</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>GPO Group</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GPO Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GPO_Group_Detail__c.object
<CustomObject>
    <fields>
        <fullName>GPO_Group__c</fullName>
        <label>GPO Group</label>
        <referenceTo>GPO_Group__c</referenceTo>
        <relationshipLabel>Group Group Details</relationshipLabel>
        <relationshipName>Group_Group_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <defaultValue>&apos;Greeting Message&apos;</defaultValue>
        <description>Communities v2 - Default Value is Greeting Message and should not be changed. News and NEWSCRED are no longer used. 
Can be: 
&apos;Greeting Message&apos; or &apos;News&apos; or &apos;NEWSCRED&apos;</description>
        <inlineHelpText>Should be: Greeting Message</inlineHelpText>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value1__c</fullName>
        <label>Value1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value2__c</fullName>
        <label>Value2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>GPO Group Detail</label>
    <nameField>
        <label>GPO  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Group Group Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GPO_GUID__c.object
<CustomObject>
    <fields>
        <fullName>Guid__c</fullName>
        <externalId>true</externalId>
        <label>Guid</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Modified_Date__c</fullName>
        <label>Modified Date</label>
        <type>DateTime</type>
    </fields>
    <label>GPO_GUID</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>GPO_GUIDS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GPO_GUIDS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GPO_Update_Guid_Batch.cls
/***
Description: This Batch is to Update Guids for newscred in community.
Created By: prasad Devar    
Created Date: 24-Apr-15
*/
Global class GPO_Update_Guid_Batch implements database.Batchable<Sobject>,Schedulable,Database.AllowsCallouts
{
    public String strQuery;
    public String accountid;
  
    private String DEFAULT_QUERY  = 'SELECT Id, Account__c, Activated__c,LastModifiedDate from GPO_Group__c limit 2';
    /* Default Constructor*/
    global GPO_Update_Guid_Batch ()
    {
        this.strQuery = DEFAULT_QUERY;
    }
   
    /* This method prepares the scope of the batch program based on the query result */
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
      System.debug('&&&&&&&&&&&&&&&&&&&&&&Inside strQuery '+strQuery );
    
        return Database.getQueryLocator(strQuery);
    }
    /* This method processes query result in batches */
    global void execute(Database.BatchableContext BC, SObject[] scope)
    {
     //String serviceEndpoint= 'http://awsnwssqpcmb01.elasticbeanstalk.com/newsservice/v1/categories/';
      GPO_Community_Setup__c commSetup = gpo_community_setup__c.getValues('default');    
      String serviceEndpoint= commSetup.Article_URL__c;
    String mainGuid = commSetup.Article_Guid__c;
              Map<String,String> mpval= new Map<String,String>();
   
    string dt ='';
    // Get the XML document from the external server
    Http http = new Http();
    HttpRequest req = new HttpRequest();
    req.setEndpoint(serviceEndpoint+mainGuid+'/articles/');
    JSONParser parser;
        
    if (!Test.isRunningTest()) {
    	req.setMethod('GET');
    	HttpResponse res = http.send(req);
        System.debug( 'res' + res.getBody());
  		parser = JSON.createParser(res.getBody());
    }	
    else {
    	parser = JSON.createParser('{"num_found": 22,"collection_item_set": [{"content": {"image_set": [{"guid": "dd38685f66d0717f173c4964d3aaceb3",'
			+ '"urls": {"large": "http://images4.newscred.com/Zz1kZDM4Njg1ZjY2ZDA3MTdmMTczYzQ5NjRkM2FhY2ViMw=="}}],"description": "<p>In todays fast-paced world",'
			+ '"title": "6 Ways To Beat Workplace Distractions","created_at": "2015-01-13 20:05:10","modified_at": "2015-01-13 20:54:22",'
			+ '"published_at": "2015-01-13 10:40:00","guid": "47118998fd1f4387c9eaf96297dcc032"}}]}');
    }
    
    String xx= '';
    String title='';
    String guid ='';
    String link ='';
    System.debug(' done exec ');
while (parser.nextToken() != null) 
 {
   if ((parser.getCurrentToken() == JSONToken.FIELD_NAME))
     {
        String fieldName = parser.getText();
        
        if(parser.getText()== 'content' )
        {
                  parser.nextToken();
                  
                  system.debug(parser.getText()+'   content');
                       
                    
                       if(parser.getCurrentToken() == JSONToken.START_OBJECT)
                        {
                        system.debug(parser.getText()+'  inside while content');

                            while(parser.nextToken() != null)
                                {
            
                                    if ((parser.getCurrentToken() == JSONToken.FIELD_NAME))
                                       {
                                        if(parser.getText()== 'image_set' )
                                        {
                                        system.debug(parser.getText()+'   image_set');
                                           parser.nextToken();
                                            system.debug(parser.getText()+'   image_set val');
                                             while(parser.getCurrentToken() != JSONToken.END_OBJECT)
                                             {
                                              parser.nextToken();
                                             
                                             }
                                             
                                             
                                             
                                          
                                            }
                                              if(parser.getText()== 'guid' )
                                            { 
                                              parser.nextToken();
                                              guid= parser.getText();
                                              system.debug(guid+'   guid');
                                              mpval.put(guid,dt);
                                             }
                                            if(parser.getText()== 'modified_at')   
                                            { 
                                              parser.nextToken();
                                              dt= parser.getText();
                                              system.debug(dt+'   modified_at');
                                             }       
                                         }

                                  
                                }
                                
                              
                                        }  
       
                         } 
                   }
        
        }
        
        List<GPO_GUID__c> cgnew = new List<GPO_GUID__c>();
      
          List<GPO_GUID__c> cgupdt = [select id, Guid__c,Modified_Date__c from  GPO_GUID__c where Guid__c=:mpval.keySet()];
     for (String id : mpval.keySet())
    {
      Datetime myDate = Datetime.valueOf( mpval.get(id));

      Boolean insertflag =true;
     for(GPO_GUID__c a: cgupdt ){
     if (a.Guid__c==  id )
        {
         insertflag = false;
         a.Modified_Date__c = myDate ;
         }
     }
    if(insertflag )
    {
    System.debug(id + ' val ' + mpval.get(id));
    GPO_GUID__c c = new GPO_GUID__c ();
    c.Guid__c= id ;
    c.Modified_Date__c = myDate;
    cgnew.add(c);
    }
    }
  insert cgnew;
  update cgupdt ;
  
  
  
  List<GPO_Group_Detail__c> updtgd =  [SELECT Id,  Value1__c, Value2__c from GPO_Group_Detail__c where GPO_Group__r.name like :commsetup.Default_Group_Name__c and type__c ='NEWSCRED' and isDeleted = false order by value2__c];
Integer i=1;
for (GPO_GUID__c  gpguid :  [select id, Guid__c,Modified_Date__c from  GPO_GUID__c  order by  Modified_Date__c desc])
{
    if(i>6)
    {
        break;
    }
    else
    {
     for(GPO_Group_Detail__c a: updtgd ){
     if (integer.valueof(a.Value2__c) ==  i)
        {
         a.Value1__c= gpguid.Guid__c;
         }
     }
    }
    i++;
}
  
 update updtgd;
  }
    
    /* This method is to execute to relase some resources if any*/
    global void finish(Database.BatchableContext BC)
    {
    
                        

    }
    /**
        This method must be there to implement Schedulable interface
    **/
    global void execute(SchedulableContext sc)
    {
       
        GPO_Update_Guid_Batch linkBatch = new GPO_Update_Guid_Batch ();
  
        database.executebatch(linkBatch , 5);
        
    } 
  
}