objects/GPOCounter__c.object
<CustomObject>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>GPOCounter</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>GPOCounter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GPOCounters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GPOComingSoonController.cls
public with sharing class GPOComingSoonController {
    public GPOComingSoonController(){
    }
    
    public void insertCounter(){
        GPOCounter__c c2 = new GPOCounter__c();
        if(ApexPages.currentPage().getParameters().get('source') != null || ApexPages.currentPage().getParameters().get('source') != '' ){
			c2.Source__c = ApexPages.currentPage().getParameters().get('source');
        }
        insert c2;
    }


    
  
}