objects/ILC_Metric_Quota__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Value__c</fullName>
        <label>Amount Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Appointments_Per_Month__c</fullName>
        <label>Appointments Per Month</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_Past_Training_Date__c</fullName>
        <label>Month Past Training Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quota_Period__c</fullName>
        <label>Quota Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fiscal Week</fullName>
                </value>
                <value>
                    <fullName>Fiscal Month</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quota_Value__c</fullName>
        <label>Quota Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Summary_Stage__c</fullName>
        <label>Summary Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1.Identify</fullName>
                </value>
                <value>
                    <fullName>2.Qualify</fullName>
                </value>
                <value>
                    <fullName>3.Introduce</fullName>
                </value>
                <value>
                    <fullName>4.Discovery Workshop</fullName>
                </value>
                <value>
                    <fullName>5.Present</fullName>
                </value>
                <value>
                    <fullName>6.Due Diligence</fullName>
                </value>
                <value>
                    <fullName>7.Negotiate</fullName>
                </value>
                <value>
                    <fullName>8.Finalize &amp; Implement</fullName>
                </value>
                <value>
                    <fullName>9.Support</fullName>
                </value>
                <value>
                    <fullName>10.End-of-Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Watson</fullName>
                </value>
                <value>
                    <fullName>Non-Watson</fullName>
                </value>
                <value>
                    <fullName>Appointment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ILC Metric Quota</label>
    <nameField>
        <displayFormat>ILC Quota - {0000}</displayFormat>
        <label>Instructional Lead Consultant Metric Quo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ILC Metric Quotas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ILC_Stage_Milestone_Adjustment__c.object
<CustomObject>
    <fields>
        <fullName>Adjustment_Period__c</fullName>
        <label>Adjustment Period Month Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Adjustment_ValueAmount__c</fullName>
        <label>Adjustment Value/Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ILC_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ILC Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ILC_Stage_Milestone_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MileStone__c</fullName>
        <label>MileStone</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>WatsonOpportunity</fullName>
                </value>
                <value>
                    <fullName>Appointment</fullName>
                </value>
                <value>
                    <fullName>Amount</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Summary_Stage__c</fullName>
        <label>Summary Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1.Identify</fullName>
                </value>
                <value>
                    <fullName>2.Qualify</fullName>
                </value>
                <value>
                    <fullName>3.Introduce</fullName>
                </value>
                <value>
                    <fullName>4.Discovery Workshop</fullName>
                </value>
                <value>
                    <fullName>5.Present</fullName>
                </value>
                <value>
                    <fullName>6.Due Diligence</fullName>
                </value>
                <value>
                    <fullName>7.Negotiate</fullName>
                </value>
                <value>
                    <fullName>8.Finalize &amp; Implement</fullName>
                </value>
                <value>
                    <fullName>9.Support</fullName>
                </value>
                <value>
                    <fullName>10.End-of-Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Watson_Non_Watson__c</fullName>
        <label>Watson/Non-Watson</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Watson</fullName>
                </value>
                <value>
                    <fullName>Non-Watson</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ILC Stage Milestone Adjustment</label>
    <nameField>
        <displayFormat>ILC Adjustment - {0000}</displayFormat>
        <label>ILC Stage Milestone Adjustment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ILC Stage Milestone Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Instructional_Lead_Consultant__c.object
<CustomObject>
    <fields>
        <fullName>Non_Watson_Training_Date__c</fullName>
        <label>Non-Watson Training Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>East</fullName>
                </value>
                <value>
                    <fullName>West</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Termination_Date__c</fullName>
        <label>Termination Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Instructional_Lead_Consultant</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Watson_Training_Date__c</fullName>
        <label>Watson Training Date</label>
        <type>Date</type>
    </fields>
    <label>Instructional Lead Consultant</label>
    <nameField>
        <displayFormat>ILC-{0000}</displayFormat>
        <label>Instructional Lead Consultant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Instructional Lead Consultants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/K12_Sales_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quota__c</fullName>
        <label>Quota</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>East</fullName>
                </value>
                <value>
                    <fullName>West</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Summary_Stage__c</fullName>
        <label>Summary Stage</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Training_Date__c</fullName>
        <label>Training Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Watson/Non-Watson</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Watson</fullName>
                </value>
                <value>
                    <fullName>Non-Watson</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>K12_Sales_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>K12 Sales Activity</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>K12 Sales Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>K12 Sales Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Fiscal_Month__c</fullName>
        <formula>CASE(MONTH(datevalue(CreatedDate) ),
1, &quot;January&quot;,
2, &quot;February&quot;,
3, &quot;March&quot;,
4, &quot;April&quot;,
5, &quot;May&quot;,
6, &quot;June&quot;,
7, &quot;July&quot;,
8, &quot;August&quot;,
9, &quot;September&quot;,
10, &quot;October&quot;,
11, &quot;November&quot;,
12, &quot;December&quot;,
&quot;None&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fiscal Month</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Summary_Stage__c</fullName>
        <formula>Stage_Summary_Stage__r.Summary_Stage_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Summary Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Watson__c</fullName>
        <formula>if( text( Product_Subtype__c )==&apos;Watson for Education&apos;  , true,false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Watson?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity_Team_Member_History__c.object
<CustomObject>
    <fields>
        <fullName>Fiscal_Month__c</fullName>
        <label>Fiscal Month</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Summary_Stage__c</fullName>
        <label>Summary Stage</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunity_Team_Member_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Team Member History</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Opportunity Team Member History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Team Member History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Tracking_History__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Fiscal_Month__c</fullName>
        <label>Fiscal Month</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunity_Tracking_HIstory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Summary_Stage__c</fullName>
        <label>Summary Stage</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>WatsonStageChange</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Watson__c</fullName>
        <formula>Opportunity__r.Watson__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Watson?</label>
        <type>Checkbox</type>
    </fields>
    <label>Opportunity Tracking History</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Opportunity Tracking History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Tracking HIstory</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PopulateK12SalesActivityNonWatson.cls
// This class is to Auto Launch the list of Records Loaded in the Transition Launch Object


Global class PopulateK12SalesActivityNonWatson implements database.Batchable<Sobject>,Database.Stateful,Schedulable
{
       global String strQuery; //this variable used to set query from test class or from shceduler if required
       public String DEFAULT_QUERY;

      
    /* Default Constructor*/
    global PopulateK12SalesActivityNonWatson ( )
    {  
           DEFAULT_QUERY ='Select Id,Region__c,User__c,Termination_Date__c,Watson_Training_Date__c,Non_Watson_Training_Date__c'
                                   +' FROM Instructional_Lead_Consultant__c order by Region__C';                                                   
        this.strQuery = DEFAULT_QUERY;
    }
    /* This method prepares the scope of the batch program based on the query result */
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        system.debug('strQuery@@@'+strQuery);
        return Database.getQueryLocator(strQuery);
    }
     /* This method processes query result in batches */
     
    global void execute(Database.BatchableContext BC, SObject[] scope)
    {
        List<Instructional_Lead_Consultant__c> newLst  = scope;
        //String currentYear=String.valueof(System.Today().Year()); 
        //Integer currentMonth=(System.Today().Month()) ;   
        
   // FiscalYearSettings fiscalYear = [SELECT Id FROM FiscalYearSettings WHERE name =: String.valueOf(System.Today().Year()) LIMIT 1];
    
    Period perMonth = [SELECT Id, Number,FiscalYearSettings.name FROM Period WHERE
    // FiscalYearSettingsId =: fiscalYear.Id AND 
    Type = 'Month' AND StartDate <=: System.Today() AND EndDate >=: System.Today() LIMIT 1];

      Integer currentMonth =perMonth.Number;
      String currentYear=string.valueof(perMonth.FiscalYearSettings.name);

 
        Set<Id> ilcSeT= new Set<Id> ();
        
           // get ILC users
              for(Instructional_Lead_Consultant__c rec:newLst  )
              ilcSeT.add(rec.user__C);
                 
                 
          //get Manual adjustments of ILC Rep
          Map<String, decimal> recILCMap = new Map<String, decimal>();
          List <ILC_Stage_Milestone_Adjustment__c > ManualList= new List <ILC_Stage_Milestone_Adjustment__c >();          
          ManualList=[select  ILC_Name__c,MileStone__c ,Watson_Non_Watson__c,Adjustment_ValueAmount__c,Adjustment_Period__c,
          Summary_Stage__c
          from ILC_Stage_Milestone_Adjustment__c  where ILC_Name__c in:ilcSeT and MileStone__c='Amount' and 
          Watson_Non_Watson__c='Non-Watson'];
          
          
         for(ILC_Stage_Milestone_Adjustment__c  recILC :ManualList){
         string key=recILC.ILC_Name__c+'-'+recILC.Adjustment_Period__c;
         recILCMap.put(key,recILC.Adjustment_ValueAmount__c);
         }
         
        // quota Data
        
        Map<String, ILC_Metric_Quota__c> nonPLSMap= new Map<String, ILC_Metric_Quota__c> ();
        Set<String > stageset= new Set<String >();

        // get Metric Quota Data
        List<ILC_Metric_Quota__c> quotaList= [ select Id,Amount_Value__c,Appointments_Per_Month__c,
        Month_Past_Training_Date__c,Quota_Period__c,
        Quota_Value__c,Summary_Stage__c,Type__c from ILC_Metric_Quota__c where Type__c ='Non-Watson'];
        
        for(ILC_Metric_Quota__c  recData :quotaList){
            nonPLSMap.put(string.valueof(recData.Month_Past_Training_Date__c),recData);
        }
        
        System.debug('&&&&nonPLSMap'+nonPLSMap);

        
        // get the opportunities for ILC Reps for Opportunities in same month
         List<AggregateResult> tasklist= [SELECT  Opportunity_Owner__c,Fiscal_Month__c, COUNT(id) tasks ,
         Sum(Amount__c) amtTask       
         from  Opportunity_Tracking_History__c  where Opportunity_Owner__c   in :ilcSeT and 
         IsClosed__c=false and
         Fiscal_Year__c=: currentYear  and type__c='Monthly'  and Watson__c=false and CreatedinCurrentFiscalMonth__c=true  
             
         GROUP BY Opportunity_Owner__c, Fiscal_Month__c  ORDER BY GROUPING(Opportunity_Owner__c), GROUPING(Fiscal_Month__c)];


        Map<String, integer> taskMap= new Map<String, integer>();  
        Map<String, Decimal> taskMapAmount= new Map<String, Decimal>();  
              
        for (AggregateResult ar : tasklist) {
                    String KepMaptask=(String)ar.get('Opportunity_Owner__c')+'-'+ (String)ar.get('Fiscal_Month__c');
                    taskMap.put(KepMaptask, ((decimal)ar.get('tasks')).intValue());
                    taskMapAmount.put(KepMaptask, ((decimal)ar.get('amtTask')));

        }
        
                // get the opportunities for ILC Reps for Opportunities in same month
         List<AggregateResult> tasklistMonth= [SELECT  Opportunity_Owner__c,Fiscal_Month__c, COUNT(id) tasks,
         Sum(Amount__c) amtTask              
         from  Opportunity_Tracking_History__c  where Opportunity_Owner__c   in :ilcSeT and 
         IsClosed__c=false and 
         Fiscal_Year__c=: currentYear  and type__c='Monthly'  and Watson__c=false and  CreatedinCurrentFiscalMonth__c=false      
         GROUP BY Opportunity_Owner__c, Fiscal_Month__c  ORDER BY GROUPING(Opportunity_Owner__c), GROUPING(Fiscal_Month__c)];

        Map<String, integer> taskMapMonth= new Map<String, integer>();        
        Map<String, Decimal> taskMapMonthAmount= new Map<String, Decimal>();        

        for (AggregateResult ar : tasklistMonth) {
                    String KepMaptask=(String)ar.get('Opportunity_Owner__c')+'-'+ (String)ar.get('Fiscal_Month__c');
                    taskMapMonth.put(KepMaptask, ((decimal)ar.get('tasks')).intValue());
                    taskMapMonthAmount.put(KepMaptask, ((decimal)ar.get('amtTask')));
        }
    
        
        // get the aggregate by Oppteam 
        
         // get the opportunities amounts where fiscalmonth is same as opportunity Created Month
         List<AggregateResult> teamlist= [SELECT  user__C, Fiscal_Month__c,COUNT(id) tasks ,
         Sum(Opportunity_Tracking_History__r.Amount__c) amtTask                     
         from  Opportunity_Team_Member_History__c where Opportunity_Tracking_History__r.Fiscal_Year__c=: currentYear
         and Opportunity_Tracking_History__r.IsClosed__c=false   
         and Opportunity_Tracking_History__r.type__C='Monthly'  and Opportunity_Tracking_History__r.Watson__c=false
         GROUP BY user__C, Fiscal_Month__c ORDER BY GROUPING(user__C), GROUPING(Fiscal_Month__c)];
         
         
        Map<String, integer> teamMap= new Map<String, integer>();   
        Map<String, Decimal> teamMapAmount= new Map<String, Decimal>();        
           
                for (AggregateResult ar : teamlist) {
                   String KepMaptask=(String)ar.get('user__C')+'-'+ (String)ar.get('Fiscal_Month__c');
                    teamMap.put(KepMaptask, ((decimal)ar.get('tasks')).intValue());
                    teamMapAmount.put(KepMaptask, ((decimal)ar.get('amtTask')));
        }
        
        


       // Clear Table
             List< K12_Sales_Activity__c> deletesalesList= new List< K12_Sales_Activity__c> ();
             Decimal eastquota=0,eastactual=0,eastnewactual=0,eastmanual=0;
             Decimal westquota=0,westactual=0,westnewactual=0,westmanual=0;
             Decimal eastAmountactual=0,eastnewAmountactual=0,westAmountactual=0,westnewAmountactual=0;
             
             Decimal eastteam=0,westteam=0;
             Decimal eastAmountteam=0,westAmountteam=0;
                          
                   
              try{
             deletesalesList =[select Id from K12_Sales_Activity__c where Activity_Type__C='Amount'  and 
             FiscalYear__c=:currentYear     and archive__c=false       ];
              if(deletesalesList.size()>0)
              delete deletesalesList;
              }
              catch(Exception e){}
       
        //List of Records to Insert       
       List< K12_Sales_Activity__c> salesList= new  List<K12_Sales_Activity__c >();
        
        // Process Over the Months from Jan till now
        
        
                // Process Over the Months from Jan till now
        
        for(integer i=1; i<=currentMonth;i++){
            // looping for NOn PLS functionality
            //looping over Reps
            //Current Month Date
             date myDate = date.newInstance(System.Today().Year() , i, 1);
             
             //Resetting variables
             eastquota=0;eastactual=0;eastnewactual=0;eastmanual=0;
             westquota=0;westactual=0;westnewactual=0;westmanual=0;
             eastAmountactual=0;eastnewAmountactual=0;westAmountactual=0;westnewAmountactual=0 ;          
             eastteam=0;westteam=0; 
             eastAmountteam=0;westAmountteam=0;              
             
              for(Instructional_Lead_Consultant__c rec:newLst  ){
                decimal Repquota=0;
              
              // Processing only if Rep is not terminated or termination is current Year
                  if(rec.Termination_Date__c==null  ||  (rec.Termination_Date__c.year()==System.Today().Year()   && i<=rec.Termination_Date__c.month()) ){
                                
                                // Non Watson Calculation
                                if( rec.Non_Watson_Training_Date__c !=null &&  rec.Non_Watson_Training_Date__c < =System.today() ){
                                        //get months between service date and current date
                                        
                                           System.debug('&&&&&&&&&&&  rec.Non_Watson_Training_Date__c'+rec.Non_Watson_Training_Date__c);                                    

                                           Integer monthsBetween = rec.Non_Watson_Training_Date__c.monthsBetween(myDate );   
                                           if( monthsBetween ==0|| monthsBetween ==-1){
                                              if(rec.Non_Watson_Training_Date__c.month()==i){
                                              monthsBetween =1;
                                              }
                                           }
                                           
                                           System.debug('&&&&&&&&&&&  monthsBetween '+monthsBetween );  
                                           
                             if( monthsBetween >0){                                               
                                           if(monthsBetween >12){
                                           Repquota= nonPLSMap.get('12').Amount_Value__c;        
                                           }
                                           else{
                                            Repquota= nonPLSMap.get(string.valueof(monthsBetween )).Amount_Value__c;
                                           }
        
                                K12_Sales_Activity__c salesRec= new K12_Sales_Activity__c();
                                salesRec.user__C=rec.user__C;
                                salesRec.FiscalYear__c=currentyear;
                                salesRec.Quota__c=Repquota;
                                salesRec.Type__c='Non-Watson';
                                salesRec.region__c=rec.region__C;
                                salesRec.FiscalMonth__c=string.valueof(i);
                                salesRec.No_Of_Months_From_Training_Date__c=monthsBetween ;
                                salesRec.Training_Date__c=rec.Non_Watson_Training_Date__c;
                                
                                String taskMapInput=rec.user__C+'-'+i;
                                salesREc.Count_New__c=taskMap.get(taskMapInput);
                                salesREc.Opp_Value_New__c=taskMapAmount.get(taskMapInput);
                                salesRec.Count_Existing__c=taskMapMonth.get(taskMapInput);
                                salesRec.Opp_Value_Existing__c=taskMapMonthAmount.get(taskMapInput);
                                salesRec.Count_Team__c=teamMap.get(taskMapInput);
                                salesRec.Opp_Value_Team__c=teamMapAmount.get(taskMapInput);                              
                                salesRec.Manual_Adj__c=recILCMap.get(taskMapInput);
                                salesRec.Activity_Type__C='Amount';
                                salesREc.Period__C='Monthly';

                                salesList.add(salesRec);   

                               System.debug('&&&&&&&&&&&  getting summary'); 
                               
                                     //get east summary
                                         if(rec.region__C=='East'){
                                         if(salesRec.Quota__c!=null)
                                         eastquota= eastquota+salesRec.Quota__c;
                                         
                                         if(salesRec.Count_New__c!=null)
                                         eastnewactual =eastnewactual +salesRec.Count_New__c;                                                                                                                          
                                         if(salesRec.Opp_Value_New__c!=null)
                                         eastnewAmountactual =eastnewAmountactual +salesRec.Opp_Value_New__c; 
                                         if(salesRec.Count_Existing__c!=null)
                                         eastactual=eastactual+salesRec.Count_Existing__c; 
                                         if(salesRec.Opp_Value_Existing__c!=null)
                                         eastAmountactual=eastAmountactual+salesRec.Opp_Value_Existing__c; 
                                         if(salesRec.Count_Team__c!=null)
                                         eastteam =eastteam +salesRec.Count_Team__c; 
                                         if(salesRec.Opp_Value_Team__c!=null)
                                         eastAmountteam=eastAmountteam+salesRec.Opp_Value_Team__c; 

                                         if(SalesRec.Manual_Adj__c  !=null)
                                         eastmanual=eastmanual+salesRec.Manual_Adj__c  ;                             
                                         }
                                          //get west summary
                                         if(rec.region__C== 'West'){
                                         if(salesRec.Quota__c!=null)
                                         westquota= westquota+salesRec.Quota__c;
                                         if(salesRec.Actual__c!=null)
                                         westactual=westactual+salesRec.Actual__c; 
                                         if(SalesRec.Manual_Adj__c  !=null)
                                         westmanual=westmanual+salesRec.Manual_Adj__c  ; 
                                         
                                         if(salesRec.Count_New__c!=null)
                                         westnewactual =westnewactual +salesRec.Count_New__c;                                                                                                                          
                                         if(salesRec.Opp_Value_New__c!=null)
                                         westnewAmountactual =westnewAmountactual +salesRec.Opp_Value_New__c; 
                                         if(salesRec.Count_Existing__c!=null)
                                         westactual=westactual+salesRec.Count_Existing__c; 
                                         if(salesRec.Opp_Value_Existing__c!=null)
                                         westAmountactual=westAmountactual+salesRec.Opp_Value_Existing__c; 
                                         if(salesRec.Count_Team__c!=null)
                                         westteam =westteam +salesRec.Count_Team__c; 
                                         if(salesRec.Opp_Value_Team__c!=null)
                                         westAmountteam=westAmountteam+salesRec.Opp_Value_Team__c; 
                            
                               
                                         }

                             }    // end of if monthbetween                         
                                }     
                  }    
              }// end of for
              
              // Summary for each Month Region Wise
              
                                K12_Sales_Activity__c salesRecEast= new K12_Sales_Activity__c();                               
                                salesRecEast.FiscalYear__c=currentyear;
                                salesRecEast.Quota__c=eastquota;
                                salesRecEast.Manual_Adj__c=eastmanual;
                                salesRecEast.Type__c='Non-Watson';
                                salesRecEast.region__c='East';
                                salesRecEast.FiscalMonth__c=string.valueof(i); 
                                
                                salesREcEast.Count_New__c=eastnewactual ;
                                salesREcEast.Opp_Value_New__c=eastnewAmountactual ;
                                salesREcEast.Count_Existing__c=eastactual;
                                salesREcEast.Opp_Value_Existing__c=eastAmountactual;
                                salesREcEast.Count_Team__c=eastteam ;
                                salesREcEast.Opp_Value_Team__c=eastAmountteam;                             
                                
                                                                                           
                                salesRecEast.Activity_Type__C='Amount';
                                salesRecEast.Period__C='Monthly';
                                salesRecEast.Summary__C=true;
                                salesList.add(salesRecEast); 
                                 K12_Sales_Activity__c salesRecWest= new K12_Sales_Activity__c();                               
                                salesRecWest.FiscalYear__c=currentyear;
                                salesRecWest.Quota__c=westquota;
                                salesRecWest.Manual_Adj__c=westmanual;
                                salesRecWest.Type__c='Non-Watson';
                                salesRecWest.region__c='West';
                                salesRecWest.FiscalMonth__c=string.valueof(i);  
                                salesREcWest.Count_New__c=Westnewactual ;
                                salesREcWest.Opp_Value_New__c=WestnewAmountactual ;
                                salesREcWest.Count_Existing__c=Westactual;
                                salesREcWest.Opp_Value_Existing__c=WestAmountactual;
                                salesREcWest.Count_Team__c=Westteam ;
                                salesREcWest.Opp_Value_Team__c=WestAmountteam;                                                                                       
                                salesRecWest.Activity_Type__C='Amount';
                                salesRecWest.Period__C='Monthly';
                                salesRecWest.Summary__C=true;
                                salesList.add(salesRecWest);   
  
              
        
        }  // end of outer for
        
              //Insert Records
              if(salesList.size()>0)
              insert salesList;
        }

                                                                                  
   
      /* This method is to execute to relase some resources if any*/
    global void finish(Database.BatchableContext BC)
    {   
    }     
    
    global void execute(SchedulableContext sc)
    {
        String strQuery = '';
        PopulateK12SalesActivityNonWatson PopulateOppNonWatson= new PopulateK12SalesActivityNonWatson( );
        database.executebatch(PopulateOppNonWatson, 9000);
        
    } 
          
}