objects/Jira_Case__c.object
<CustomObject>
    <fields>
        <fullName>Bug_Environment__c</fullName>
        <label>Bug Environment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>UAT</fullName>
                </value>
                <value>
                    <fullName>PROD</fullName>
                </value>
                <value>
                    <fullName>SIT</fullName>
                </value>
                <value>
                    <fullName>DEV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Stage__c</fullName>
        <defaultValue>(&quot;Development&quot;)</defaultValue>
        <label>Case Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Development</fullName>
                    <default>true</default>
                    <label>Development</label>
                </value>
                <value>
                    <fullName>UAT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Jira Cases</relationshipLabel>
        <relationshipName>Jira_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Components__c</fullName>
        <defaultValue>(&quot;Sales Enablement (Disrupters)&quot;)</defaultValue>
        <label>Components</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EpicLink__c</fullName>
        <defaultValue>(&quot;NAIT-120447&quot;)</defaultValue>
        <label>Epic Link</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Found_In__c</fullName>
        <label>Found In</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Issue_Type__c</fullName>
        <label>Issue Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Jira_ID__c</fullName>
        <externalId>true</externalId>
        <label>Jira ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Jira_Sync_Status__c</fullName>
        <label>Jira Sync Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Labels__c</fullName>
        <label>Labels</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>project1</fullName>
                </value>
                <value>
                    <fullName>project2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sprint_Name__c</fullName>
        <label>Sprint Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>assigne__c</fullName>
        <label>Assigne</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>priority__c</fullName>
        <label>priority</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>summary__c</fullName>
        <label>summary</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Jira Case</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Jira Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jira Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UpsertJiraCaseProcess.cls
global  class UpsertJiraCaseProcess {
    
   @InvocableMethod(label='Create or Update Jira Case' description='Create or Update Jira Case on IT Case insert or update')
   public static void UpsertJiraCase(List<Id> caseList)
      {
          Map<id,Jira_Case__c> devJiraMap =  new Map<id,Jira_Case__c> ();
          Map<id,Jira_Case__c> uatJiraMap =  new Map<id,Jira_Case__c> ();
         for(Jira_Case__c s : [SELECT Id,summary__c, Case__c,EpicLink__c,Components__c, Description__c,Case__r.CaseNumber, Jira_ID__c, assigne__c, priority__c,  Issue_Type__c, Found_In__c, Labels__c, Bug_Environment__c,Case_Stage__c,Jira_Sync_Status__c from Jira_Case__c WHERE Case__c = :caseList ])
         {
             
             if(s.Case_Stage__c == 'UAT')
             {
                 uatJiraMap.put(s.Case__c,s);
             }
             else if(s.Case_Stage__c == 'Development')
             {
                 devJiraMap.put(s.Case__c,s);
             }

         }  
         List<Jira_Case__c> jcupdateList = new List<Jira_Case__c>();
          List<Jira_Case__c> jccreateList = new List<Jira_Case__c>();
        for(Case c :[select id,RecordTypeId,Subject,Priority,Description,IT_Classification__c,IT_Environment__c,SPRINT_NAME__c,Jira_Component__C from case  where id=:caseList])
        {
            Jira_Case__c jc = new Jira_Case__c();
            
            jc.Case__c=c.id;
          //  jc.EpicLink__c
          
            
           // jc.priority__c
          //  jc.Issue_Type__c
            
            jc.Jira_Sync_Status__c='';
            //jc.Case_Stage__c 
            if(uatJiraMap.get(c.id)!=null)
            {
                jc.id =uatJiraMap.get(c.id).id;
                jcupdateList.add(jc);
            }
            else if(devJiraMap.get(c.id)!=null)
            {
                jc.id =devJiraMap.get(c.id).id;
                jcupdateList.add(jc);
            }
            else{
                jc.Case_Stage__c='Development';
                jc.summary__c = c.Subject;
                jc.Description__c =c.Description;
                jc.Found_In__c=c.IT_Environment__c;
                jc.Bug_Environment__c=c.IT_Environment__c;
                 jc.Components__c =c.Jira_Component__C;
                jccreateList.add(jc);
            }
        }
      if(jcupdateList.size()>0)
      {
        update jcupdateList;
      }
       if(jccreateList.size()>0)
      {
        insert jccreateList;
      }
   }
}