objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Address1__c</fullName>
        <inlineHelpText>This field is required in order to convert  (Unless lead is directly linked to an account)</inlineHelpText>
        <label>Address1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <inlineHelpText>This field is required in order to convert  (Unless lead is directly linked to an account)</inlineHelpText>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <inlineHelpText>This Field is required to convert to a prospect</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>USA</fullName>
                    <default>true</default>
                    <label>USA</label>
                </value>
                <value>
                    <fullName>CAN</fullName>
                </value>
                <value>
                    <fullName>MEX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Discovery_Notes__c</fullName>
        <label>Discovery Notes</label>
        <length>2500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <description>Employee ID of Office Depot Associate who sourced this deal. Used for SPIFF reporting.</description>
        <inlineHelpText>Employee ID of Office Depot Associate who sourced this deal.</inlineHelpText>
        <label>Referrer Employee ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee_Name__c</fullName>
        <description>Name of Office Depot Associate who sourced this deal. Used for SPIFF reporting.</description>
        <inlineHelpText>Name of Office Depot Associate who sourced this deal.</inlineHelpText>
        <label>Referrer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Used in PRM for deal registration</description>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Used in PRM for Deal Registration</description>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Web Lead</fullName>
                </value>
                <value>
                    <fullName>Store Lead</fullName>
                    <default>true</default>
                    <label>Store Lead</label>
                </value>
                <value>
                    <fullName>Customer Service</fullName>
                </value>
                <value>
                    <fullName>One Source</fullName>
                </value>
                <value>
                    <fullName>Business Pro</fullName>
                </value>
                <value>
                    <fullName>FOS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Referral_Client_Type__c</fullName>
        <label>Referral Client Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Referral_Lead_Source__c</fullName>
        <description>Represents the Lead Source value on the original Lead or Contact sent in a Referral.</description>
        <label>Referral Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>800#</fullName>
                </value>
                <value>
                    <fullName>Chat</fullName>
                </value>
                <value>
                    <fullName>ITaaS Lead</fullName>
                </value>
                <value>
                    <fullName>Office Depot</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Refer &amp; Earn</fullName>
                </value>
                <value>
                    <fullName>Web</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Referral_Origin__c</fullName>
        <label>Referral Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Referral_Organizations</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Referrer_Email__c</fullName>
        <inlineHelpText>Email of Office Depot Associate who sourced this deal.</inlineHelpText>
        <label>Referrer Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Referrer_Phone__c</fullName>
        <inlineHelpText>Phone number of Office Depot Associate who sourced this deal.</inlineHelpText>
        <label>Referrer Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <inlineHelpText>This field is required in order to convert  (Unless lead is directly linked to an account)</inlineHelpText>
        <label>State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>This field is only editable by System Admin or through uploading</description>
        <inlineHelpText>Editable by System Admin or through data upload</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sales Play</fullName>
                </value>
                <value>
                    <fullName>Marketing Interest</fullName>
                </value>
                <value>
                    <fullName>Sales Initiative</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WCW_Count__c</fullName>
        <inlineHelpText>This field is required in order to convert  (Unless lead is directly linked to an account)</inlineHelpText>
        <label>Number of Employees</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <inlineHelpText>This field is required in order to convert  (Unless lead is directly linked to an account)</inlineHelpText>
        <label>Zip/Postal Code</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Referral__c.object
<CustomObject>
    <description>Enables referral of Leads or Contacts between internal organization such as BSD and CompuCom, etc.</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Employees__c</fullName>
        <label>Employees</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>Contact First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Contact Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Source__c</fullName>
        <label>Lead Source</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referred_By__c</fullName>
        <label>Referred By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Referral_Organizations</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Referred_To__c</fullName>
        <label>Referred To</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Referral_Organizations</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Referrer_Comments__c</fullName>
        <label>Referrer Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Referrer_Email__c</fullName>
        <label>Referrer Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Referrer_Employee_ID__c</fullName>
        <label>Referrer Employee ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_Name__c</fullName>
        <label>Referrer Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_Phone__c</fullName>
        <label>Referrer Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State/Province</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Referral Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <label>New</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Referral_Organizations.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Tech-Zone</fullName>
    </customValue>
    <customValue>
        <fullName>BizBox</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>CompuCom</fullName>
    </customValue>
    <customValue>
        <fullName>Grand &amp; Toy</fullName>
    </customValue>
    <masterLabel>Referral Organizations</masterLabel>
</GlobalValueSet>

classes/ReferralDestinationHandler.cls
/*
 * Handler for ReferralDestinationTrigger.  
 * Runs destination side logic for Referral records going to a group in this org.  
 * Note input to handler is filtered down to only Referrals destined to a group in this org. 
 * Also updates Last Update Date on Referral object each time a destination owned field is changed on Referral object.
 *
 * @author: Andrew Smith (6/10/2018)
 */ 
 
public without sharing class ReferralDestinationHandler {
	
	public void createLeads(List<Referral__c>  destRecs){
		List<Referral__c> newSubmittedReferrals = new List<Referral__c>();
		List<Referral__c> updateReferrals = new List<Referral__c>();
		Map<Id, Lead> referralLeadMap = new Map<Id, Lead>();
		
		newSubmittedReferrals = ReferralUtility.getNewSubmittedReferrals(destRecs);
				
		for(Referral__c ref : newSubmittedReferrals){
			Lead ld = new Lead();
			
			ld.RecordTypeId = ReferralUtility.getLeadRecordTypeID(ref.Referred_To__c);
			ld.FirstName = ref.First_Name__c;
			ld.Company = ref.Company__c;
			ld.Title = ref.Title__c;
			ld.Phone = ref.Phone__c;
			ld.Email = ref.Email__c;
			ld.Employee_Name__c = ref.Referrer_Name__c;
			ld.Referrer_Phone__c = ref.Referrer_Phone__c;
			ld.Referrer_Email__c = ref.Referrer_Email__c;
			ld.Employee_ID__c = ref.Referrer_Employee_ID__c;
			ld.Referral_Client_Type__c = ref.Type__c;
			ld.Referral_Lead_Source__c = ref.Lead_Source__c;
			ld.Referral_Origin__c = ref.Referred_By__c;
			ld.NumberOfEmployees = Integer.valueOf(ref.Employees__c);
			ld.WCW_Count__c = ref.Employees__c;
			
			if(ref.Referred_To__c != 'Tech-Zone' && ref.Referred_By__c != 'CompuCom' && ref.Referred_By__c != 'Tech-Zone'){
 				if(ref.Street__c != NULL){
	 				if(ref.Street__c.length() > 30){
	 					ld.Address1__c = ref.Street__c.substring(0,30);
	 				}
	 				else{
	 					ld.Address1__c = ref.Street__c;
	 				}
 				}
 				
 				ld.City__c = ref.City__c;
 				ld.State__c = ref.State__c;
 				ld.Country__c = ref.Country__c;
 				
 				if(ref.Postal_Code__c != NULL){
	 				if(ref.Postal_Code__c.length() > 11){
	 					ld.Zip__c = ref.Postal_Code__c.substring(0,11);
	 				}
	 				else{
	 					ld.Zip__c = ref.Postal_Code__c;
	 				}
 				}
 			}
 			else if(ref.Referred_To__c != 'Tech-Zone'){
 				ld.City__c = ref.City__c;
 				if(ref.Postal_Code__c != NULL){
	 				if(ref.Postal_Code__c.length() > 11){
	 					ld.Zip__c = ref.Postal_Code__c.substring(0,11);
	 				}
	 				else{
	 					ld.Zip__c = ref.Postal_Code__c;
	 				}
 				}
 			}
 			else if(ref.Referred_To__c == 'Tech-Zone'){
 				ld.Street =	ref.Street__c;
 				ld.City = ref.City__c;
 				ld.State = ref.State__c;
 				ld.PostalCode = ref.Postal_Code__c;
 				ld.Country = ref.Country__c; 
 			}
			
			if(ref.Referred_To__c == 'Tech-Zone'){
				ld.Discovery_Notes__c = ref.Referrer_Comments__c;
			}
			else if(ref.Referred_To__c == 'BizBox'){
				ld.Comments__c = ref.Referrer_Comments__c;
			}
			else{
				ld.Notes__c = ref.Referrer_Comments__c;
			}
			
			if(ref.Last_Name__c == NULL){
				ld.LastName = '[not provided]';
			}
			else{
				ld.LastName = ref.Last_Name__c;
			}
			
			referralLeadMap.put(ref.Id, ld);
		}
		
		insert referralLeadMap.values();
		
		Map<Id, Id> referralToLeadIdMap = new Map<Id, Id>();
		
		for(Id refId : referralLeadMap.keySet()){
			referralToLeadIdMap.put(refId, referralLeadMap.get(refId).Id);
		}
				
		LeadReferralSourceHandler handler = new LeadReferralSourceHandler();	
		handler.setReferralLeadId(referralToLeadIdMap);
		
	}
	
	public void processChangedLeadOrOpp(Map<ID, Referral__c> oldRecMap, List<Referral__c> newRecs){
		List<Referral__c> submittedReferrals = new List<Referral__c>();
		Map<Id, Id> referralToLeadIdMap = new Map<Id, Id>();
		Map<Id, Id> referralToOppIdMap = new Map<Id, Id>();
		
		submittedReferrals = ReferralUtility.getAllSubmittedReferrals(newRecs);
		
		for(Referral__c newRef : submittedReferrals){
			if(newRef.Status__c != 'Submitted'){ 
				if(oldRecMap != NULL){
					if(oldRecMap.get(newRef.Id).Resulting_Opportunity__c != newRef.Resulting_Opportunity__c && newRef.Resulting_Opportunity__c != NULL){
						referralToOppIdMap.put(newRef.Id, newRef.Resulting_Opportunity__c);
					}
					else if(oldRecMap.get(newRef.Id).Resulting_Lead__c != newRef.Resulting_Lead__c && newRef.Resulting_Lead__c != NULL){ 
						referralToLeadIdMap.put(newRef.Id, newRef.Resulting_Lead__c);

					}
				}
				else{
					if(newRef.Resulting_Opportunity__c != NULL){
						referralToOppIdMap.put(newRef.Id, newRef.Resulting_Opportunity__c);

					}
					else if(newRef.Resulting_Lead__c != NULL){
						referralToLeadIdMap.put(newRef.Id, newRef.Resulting_Lead__c);
					}
				}
			}
		}
				
		LeadReferralSourceHandler handlerLead = new LeadReferralSourceHandler();	
		handlerLead.setReferralLeadValues(handlerLead.getLeadObjectsForReferralToLeadIdMap(referralToLeadIdMap));
		
		OppReferralSourceHandler handlerOpp = new OppReferralSourceHandler();	
		handlerOpp.setReferralOppValues(handlerOpp.getOppObjectsForReferralToOppIdMap(referralToOppIdMap));
	}
	
	public void updateTimestamps(Map<ID, Referral__c> oldRecMap, List<Referral__c> newRecs){
		List<Referral__c> changedReferrals = new List<Referral__c>();
		
		for(Referral__c ref : newRecs){
			Referral__c oldRec = oldRecMap.get(ref.Id);
			
			if( ref.Opportunity_Amount__c != oldRec.Opportunity_Amount__c || 
			    ref.Opportunity_Close_Date__c != oldRec.Opportunity_Close_Date__c ||
				ref.Opportunity_Stage__c != oldRec.Opportunity_Stage__c || 
				ref.Rep_Name__c != oldRec.Rep_Name__c || 
				ref.Status__c != oldRec.Status__c || 
				ref.Loss_No_Action_Reason__c != oldRec.Loss_No_Action_Reason__c){
				
				changedReferrals.add(ref);
			}
		}
		
		ReferralUtility.setLastUpdateDate(changedReferrals);
	}
}