objects/Log__c.object
<CustomObject>
    <description>Records for Logging integration errors and other debugging information from Apex Code.</description>
    <fields>
        <fullName>Full_Message__c</fullName>
        <description>Holds the full error message or stack trace.</description>
        <label>Full Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Service_Name__c</fullName>
        <description>The name of the web service method submitting the log record.</description>
        <inlineHelpText>The name of the web service method submitting the log record.</inlineHelpText>
        <label>Service Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <description>How important is the info in the log?</description>
        <label>Severity</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>INFO</fullName>
                    <default>true</default>
                    <label>INFO</label>
                </value>
                <value>
                    <fullName>WARNING</fullName>
                </value>
                <value>
                    <fullName>ERROR</fullName>
                </value>
                <value>
                    <fullName>CRITICAL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Timestamp__c</fullName>
        <description>Timestamp for when the log entry is created. The created date is not sufficient since this this object may be created in a future method with can be delayed.</description>
        <label>Timestamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The user related to this log entry.</description>
        <label>UserId</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Log</label>
    <nameField>
        <label>Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <recordTypes>
        <fullName>Apex</fullName>
        <active>true</active>
        <description>RecordType for Apex Logs</description>
        <label>Apex</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/LoggingEvent__e.object
<CustomObject>
    <description>This is used to emit logging events and depreciates the EventLog event.</description>
    <fields>
        <fullName>Full_Message__c</fullName>
        <description>The full message for the event goes here.</description>
        <label>Full Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Log_Level__c</fullName>
        <defaultValue>&quot;INFO&quot;</defaultValue>
        <description>How Important is the Message? INFO, WARNING, ERROR, CRITICAL</description>
        <label>Log Level</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordType__c</fullName>
        <defaultValue>&quot;apex&quot;</defaultValue>
        <description>The Record type for the event. The record type needs to correspond to a record type in the Log__c object.</description>
        <label>RecordType</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>The source of event.</description>
        <label>Source</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <defaultValue>$User.Id</defaultValue>
        <description>The Id of the user who kicked of this event.</description>
        <label>UserId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>LoggingEvent</label>
    <pluralLabel>LoggingEvents</pluralLabel>
</CustomObject>

classes/LoggingEventHandler.cls
/*******************************************************************************************************
 * @author Adam Albright, adam.albright@officedepot.com, 11 April 2019
 * @description Covered by MyUtils_Test
 */

public without sharing class LoggingEventHandler extends TriggerHandler {
    public override void afterInsert() {
        // If the event log is valid, creat an entry. If it is not,
        if (Test.isRunningTest()) {
            System.debug(LoggingLevel.INFO, 'Before Insert Testing.');
        }
        List<Log__c> myLogs = new List<Log__c>();
        Map<String, Schema.RecordTypeInfo> log_record_types = Schema.SObjectType.Log__c.getRecordTypeInfosByDeveloperName();
        for (LoggingEvent__e myEventLog: (List<LoggingEvent__e>) Trigger.New) {
            if (log_record_types.keySet().contains(myEventLog.RecordType__c)) {
                Log__c myLog = new Log__c(
                    Severity__c = myEventLog.Log_Level__c,
                    RecordTypeId = log_record_types.get(
                        myEventLog.RecordType__c
                    ).getRecordTypeId(),
                    Timestamp__c = myEventLog.CreatedDate,
                    Full_Message__c = myEventLog.Full_Message__c,
                    Service_Name__c = myEventLog.Source__c,
                    UserId__c = myEventLog.UserId__c
                );
                myLogs.add(myLog);
            } else {
                Log__c myLog = new Log__c(
                    Severity__c = 'ERROR',
                    RecordTypeId = log_record_types.get(
                        'Apex'
                    ).getRecordTypeId(),
                    Timestamp__c = System.now(),
                    Full_Message__c = JSON.serialize(myEventLog),
                    Service_Name__c = 'LoggingEventHandler',
                    UserId__c = UserInfo.getUserId()
                );
                myLogs.add(myLog);
            }
        }
        if (Test.isRunningTest()) {
            System.debug(LoggingLevel.INFO, 'Logs: ' + myLogs);
        }
        insert myLogs;
    }
}