objects/Potential_Band__c.object
<CustomObject>
    <description>Potential Bands used to find potential of a Industry given different properties related to the industry.</description>
    <fields>
        <fullName>Banding_Key__c</fullName>
        <description>The High Level Industry + Employee Count Band + Revenue Band for Matching Org Objects to Potential Bands Populated the Trigger.</description>
        <externalId>true</externalId>
        <inlineHelpText>The High Level Industry + Employee Count Band + Revenue Band for Matching Org Objects to Potential Bands.</inlineHelpText>
        <label>Banding Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Employee_Count_Band__c</fullName>
        <description>The employee count band key used to match industries based on their employee count.</description>
        <inlineHelpText>The employee count band key used to match industries based on their employee count.</inlineHelpText>
        <label>Employee Count Band</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>High_Level_Industry__c</fullName>
        <description>The High-Level Industry as defined by SBI.</description>
        <inlineHelpText>The High-Level Industry as defined by SBI.</inlineHelpText>
        <label>High-Level Industry</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>High_Level_Industry</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Revenue_Band__c</fullName>
        <description>The revenue band key used to match industries based on their revenue.</description>
        <inlineHelpText>The revenue band key used to match industries based on their revenue.</inlineHelpText>
        <label>Revenue Band</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <description>The Segment calculated according to the Alteryx Model.</description>
        <inlineHelpText>The Segment calculated according to the Alteryx Model.</inlineHelpText>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DML_Segments</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Industry_Potential__c</fullName>
        <description>The total industry potential given the high-level industry, employee count band, and revenue band.</description>
        <inlineHelpText>The total industry potential given the high-level industry, employee count band, and revenue band.</inlineHelpText>
        <label>Total Industry Potential</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Potential Band</label>
    <nameField>
        <displayFormat>PB-{00000000}</displayFormat>
        <label>Potential Band Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Potential Bands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/DML_Segments.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>No Segment Assigned</fullName>
        <default>true</default>
        <label>No Segment Assigned</label>
    </customValue>
    <customValue>
        <fullName>ISO Accounts</fullName>
    </customValue>
    <customValue>
        <fullName>Mailstream</fullName>
    </customValue>
    <customValue>
        <fullName>Strategic</fullName>
    </customValue>
    <customValue>
        <fullName>Key Accounts 2</fullName>
    </customValue>
    <customValue>
        <fullName>Key Accounts 1</fullName>
    </customValue>
    <customValue>
        <fullName>Federal</fullName>
    </customValue>
    <masterLabel>DML Segments</masterLabel>
</GlobalValueSet>

globalValueSets/High_Level_Industry.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accomodation and Food Services</fullName>
    </customValue>
    <customValue>
        <fullName>Administration and Support and Waste Management and Remediation Services</fullName>
    </customValue>
    <customValue>
        <fullName>Agriculture, Forestry, Fishing, and Hunting</fullName>
    </customValue>
    <customValue>
        <fullName>Arts, Entertainment, and Recreation</fullName>
    </customValue>
    <customValue>
        <fullName>Construction</fullName>
    </customValue>
    <customValue>
        <fullName>Educational Services</fullName>
    </customValue>
    <customValue>
        <fullName>Finance and Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Health Care and Social Assistance</fullName>
    </customValue>
    <customValue>
        <fullName>Information</fullName>
    </customValue>
    <customValue>
        <fullName>Management of Companies and Enterprises</fullName>
    </customValue>
    <customValue>
        <fullName>Manufacturing</fullName>
    </customValue>
    <customValue>
        <fullName>Mining</fullName>
    </customValue>
    <customValue>
        <fullName>Nonclassifiable Establishments</fullName>
    </customValue>
    <customValue>
        <fullName>Other Services (except Public Administration)</fullName>
    </customValue>
    <customValue>
        <fullName>Professional, Scientific, and Technical Services</fullName>
    </customValue>
    <customValue>
        <fullName>Public Administration</fullName>
    </customValue>
    <customValue>
        <fullName>Real Estate Rental and Leasing</fullName>
    </customValue>
    <customValue>
        <fullName>Retail Trade</fullName>
    </customValue>
    <customValue>
        <fullName>Transportation and Warehousing</fullName>
    </customValue>
    <customValue>
        <fullName>Utilities</fullName>
    </customValue>
    <customValue>
        <fullName>Wholesale Trade</fullName>
    </customValue>
    <description>SBI assigned high level industries based on lob data  from dnb usa.</description>
    <masterLabel>High-Level Industry</masterLabel>
</GlobalValueSet>

classes/PotentialBandManagment.cls
public without sharing class PotentialBandManagment {
    public static List<Potential_Band__c> getBandingKeys(List<Potential_Band__c> bands){
        for(Potential_Band__c band: bands){
            band.Banding_Key__c = getBandingKey(
                band.High_Level_Industry__c,
                Integer.valueOf(band.Employee_Count_Band__c.round(System.RoundingMode.FLOOR)),
                Integer.valueOf(band.Revenue_Band__c)
            );
        }
        return bands;
    }

    public static String getBandingKey(
        String high_level_industry,
        Integer employee_count_band,
        Integer revenue_band
    ){
        return (
            high_level_industry +
            String.valueOf(employee_count_band) +
            String.valueOf(revenue_band)
        ).replaceAll('[^a-zA-Z0-9]', '').toLowerCase();
    }

    public static Integer getEmployeeCountBand(Integer employee_count){
        if (employee_count == null)
            return 0;
        if(employee_count > 50000)
            return 5;
        if (employee_count > 10000)
            return 4;
        if (employee_count > 5000)
            return 3;
        if (employee_count > 200)
            return 2;
        if (employee_count > 0)
            return 1;
        else {
            return 0;
        }
    }

    public static Integer getRevenueBand(Integer revenue){

        if (revenue == null)
            return 0;
        if(revenue > 1000000000.0)
            return 5;
        if (revenue > 500000000.0)
            return 4;
        if (revenue > 50000000.0)
            return 3;
        if (revenue > 10000000.0)
            return 2;
        if (revenue > 0.0)
            return 1;
        else {
            return 0;
        }
    }

    public static String getSegment(Integer total_potential){

        if (total_potential == null)
            return 'No Segment Assigned';
        if(total_potential > 2000000)
            return 'Strategic';
        if (total_potential >= 500000)
            return 'Key Accounts 1';
        if (total_potential >= 50000)
            return 'Key Accounts 2';
        else {
            return 'ISO Accounts';
        }
    }

    public static List<Potential_Band__c> setSegment(List<Potential_Band__c> bands){
        for(Potential_Band__c band: bands){
            band.Segment__c = getSegment(Integer.valueOf(band.Total_Industry_Potential__c.round(System.RoundingMode.FLOOR)));
        }
        return bands;
    }


}