objects/Reassignment_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reassignment Queue</relationshipLabel>
        <relationshipName>Reassignment_Queue</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reassignment Queue</label>
    <nameField>
        <displayFormat>RQ-{0000}</displayFormat>
        <label>Reassignment Queue	 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reassignment Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/populateAcctLookup_TC.cls
/**
 * Created by Najma Ateeq - not to be deployed since populateAcctLookup does not exist on prod.
 */
@isTest
private class populateAcctLookup_TC {

    static testMethod void myUnitTest() {
        createTestData();
    }
    static void createTestData(){
    	Account acc = Test_Utils.CreateAccount();
    	Reassignment_Queue__c reQ = new Reassignment_Queue__c();
    	reQ.Account__c = acc.Id;
    	insert reQ;
    }
}