objects/Reassignment_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reassignment Queue</relationshipLabel>
        <relationshipName>Reassignment_Queue</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Autoapprove7thDay__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Autoapprove7thDay</label>
        <type>Checkbox</type>
    </fields>
    <label>Reassignment Queue</label>
    <nameField>
        <displayFormat>RQ-{0000}</displayFormat>
        <label>Reassignment Queue	 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reassignment Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/beforeTriggerReassignmentQueue_TC.cls
/**
 * Created by Najma Ateeq for Story #S-386202(OD Case Number - 00617674)
 */
@isTest
private class beforeTriggerReassignmentQueue_TC {

    static testMethod void myUnitTest() {
        createTestData();
    }
    static void createTestData(){
        Account acc = Test_Utils.createAccount();
        Reassignment_Queue__c reQ = new Reassignment_Queue__c();
        reQ.Autoapprove7thDay__c = true;
        reQ.Account__c = acc.Id;
        insert reQ;
        update reQ;
    }
}