objects/Sales_Person__c.object
<CustomObject>
    <fields>
        <fullName>ExtIDSalesPerson__c</fullName>
        <externalId>true</externalId>
        <label>ExtIDSalesPerson</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OMX_Emp_Id__c</fullName>
        <label>OMX Emp Id</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OMX_Rep_ID__c</fullName>
        <externalId>true</externalId>
        <label>OMX Rep ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role_Relate_Id__c</fullName>
        <externalId>true</externalId>
        <label>Role Relate Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Person_IDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Person ID</label>
    <nameField>
        <label>Sales Person ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Person IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UpdateOMXXRef_TC.cls
@isTest
public class UpdateOMXXRef_TC{
    
    static testMethod void UpdateOMXXRef_TC() 
     {
          Sales_Person__c s =  new Sales_Person__c();
           s.ExtIDSalesPerson__c ='XXXX';
           s.IsActive__c=true;
             s.Primary__c=true;
               s.Role_Relate_Id__c ='123';  
               s.User__c='005E0000000lNbVIAU';
               s.Name = 'XXXX';
              //  s.OMX_Emp_Id__c ='1233';
          //s.OMX_Rep_ID__c ='11233'; 
               insert s;
          String rlid = 'XXXX';
          Sales_Person__c c = [select id,OMX_Emp_Id__c,OMX_Rep_ID__c from Sales_Person__c where Name = :rlid limit 1];
          c.OMX_Emp_Id__c ='123';
          c.OMX_Rep_ID__c ='1123';  
         update c;
     }

}