objects/User.object
<CustomObject>
    <fields>
        <fullName>MB_Expiration_Date__c</fullName>
        <description>market Builder Exp date time for TOKEN</description>
        <label>MB Expiration Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OD_Employee_ID__c</fullName>
        <externalId>true</externalId>
        <label>OD Employee ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Token_Market_Builder__c</fullName>
        <description>The Token used for Market Builder App</description>
        <label>Token Market Builder</label>
        <length>100</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/User_Staging__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Manager_Employee_Number__c</fullName>
        <label>Manager Employee Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OD_Employee_Number__c</fullName>
        <externalId>true</externalId>
        <label>OD Employee Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Pending Manager</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Manager Error</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>User Staging</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/user_manager_update_batch_TC.cls
/**
 * Created by Najma Ateeq for Story #S-331356
 */
@isTest
private class user_manager_update_batch_TC {

    static testMethod void myUnitTest() {
       createTestData();
       	
        Test.startTest();
        user_manager_update_batch sb=new user_manager_update_batch();
        String sch = '0 0 23 * * ?';
        system.schedule('Test check', sch, sb);
        Test.stopTest();
    }
    static testMethod void myUnitTest1() {
       createTestData();
       	
        Test.startTest();
        user_manager_update_batch sb=new user_manager_update_batch();
        database.executeBatch(sb);
        Test.stopTest();
    }
    static void createTestData(){
    	User u2=[SELECT id,ProfileId,OD_Employee_ID__c,TimeZoneSidKey FROM User WHERE id =:UserInfo.getUserId()];
        
        User u = new user(Username='test_test1@acme.com',FirstName ='test123', LastName='xyz123', Alias='a', CommunityNickname='aa', LocaleSidKey='en_US', EmailEncodingKey='UTF-8', ProfileId=u2.ProfileId, LanguageLocaleKey='en_US');
        u.email='aaabc@officedepot.com';
        u.MB_Expiration_Date__c = System.now().addminutes(1);
        u.OD_Employee_ID__c ='622207';
       // u.Manager_Employee_Number__c = '12345';
        u.IsActive=true;
        u.TimeZoneSidKey=u2.TimeZoneSidKey;
        u.Token_Market_Builder__c ='abc';
        Insert u;
        
    	User_Staging__c usrStaging = new User_Staging__c(Email__c='abcd@officedepot.com',OD_Employee_Number__c='622207',Title__c='USSTO:000540:Sales Consultant-Print Serv',Manager_Employee_Number__c = '12345',status__c = 'Pending Manager');
    	insert usrStaging;
    }
}